### ISSUE TITLE
Only SystemUI fc-ing. Settings drawer works great. 

### ISSUE THREAD

**Issue by sapthesh** [wasdennnoch/AndroidN-ify#1000]
SystemUI force closing in Lollipop still. Settings drawer works fine. 

Catlog attached below. 
[2016-09-24-23-47-33nify-uifc.txt](https://github.com/wasdennnoch/AndroidN-ify/files/491585/2016-09-24-23-47-33nify-uifc.txt)

#695
[nify#6952016-09-28-00-52-57.txt](https://github.com/wasdennnoch/AndroidN-ify/files/499733/nify.6952016-09-28-00-52-57.txt)

**Comment by wasdennnoch** [comment]
Same crash as #1063
