### ISSUE TITLE
Settings Drawer not showing

### ISSUE THREAD

**Issue by DanTDMMcpe** [wasdennnoch/AndroidN-ify#1002]
Logs:

**Comment by DanTDMMcpe** [comment]
[xposed_error_20160929_152439.txt](https://github.com/wasdennnoch/AndroidN-ify/files/499993/xposed_error_20160929_152439.txt)

Or here

**Comment by wasdennnoch** [comment]
Did you enable the drawer in the experimental settings menu?

**Comment by wasdennnoch** [comment]
No response
