### ISSUE TITLE
systemui crash 

### ISSUE THREAD

**Issue by arunverma833** [wasdennnoch/AndroidN-ify#1003]
I have systemui crash with many builds except stable 0.2 but I want to use latest builds with awsm features but can't :-( 
Crash with latest build 696 using cm12.1 xperia s logs attached 
https://drive.google.com/file/d/0BwWvDiQ04VutUnJ0S0F3NDJMWjQ/view?usp=docslist_api

**Comment by arunverma833** [comment]
No reply so far?

**Comment by wasdennnoch** [comment]
I have a real life too.

**Comment by arunverma833** [comment]
The mod of urs sir is soo awsm that everyone wants to use that..... That's why everyone is excited and keen and expect some good things from u sir

**Comment by arunverma833** [comment]
Any update in this issue sir

**Comment by wasdennnoch** [comment]
Fixed with e07a4dea33ccb5bb170c59d8af90ee0e203e4315.

`E/AndroidRuntime( 2169): java.lang.IllegalArgumentException: method com.android.systemui.statusbar.SignalClusterView.setMobileDataIndicators [XposedOriginal] argument 9 has type int, got java.lang.Boolean`
