### ISSUE TITLE
Contextual headers

### ISSUE THREAD

**Issue by BlackScorpion3** [wasdennnoch/AndroidN-ify#1004]
App interfere with my contextual headers on any build newer than 634. Attached is my systemUI.
https://drive.google.com/file/d/0Byf8o5PcFIf4VF9rOW8xT2lVdG8/view?usp=drivesdk

**Comment by wasdennnoch** [comment]
Please post a more precise description and a screenshot.

**Comment by BlackScorpion3** [comment]
If I have the module enabled my contextual headers do not work. If I disable the 'style quick settings' and restart system UI the contextual headers work. It runs fine on 634 but none of the newer builds.

Thank you,
Don B.

Sent via the BlackBerry Hub for Android<http://play.google.com/store/apps/details?id=com.blackberry.hub>

**Comment by wasdennnoch** [comment]
Did you try the "Unaltered header background" option?

**Comment by wasdennnoch** [comment]
No response
