### ISSUE TITLE
Can you please provide 'app specific notification' feature as a separate app? 

### ISSUE THREAD

**Issue by tushar260** [wasdennnoch/AndroidN-ify#1006]
In a few days I'll probably be flashing CM14, I love this features and wish this to be on cm14 as well.

After the release of xposed for nougat, will n-ify work if I disable all other features and use only this one?

**Comment by wasdennnoch** [comment]
I have no idea. It's intended to work on L and M. I'm not planning support for N just for one feature.

**Comment by tushar260** [comment]
@paphonbth  what do you think of this? 😅
