### ISSUE TITLE
Settings Drawer and N style Settings not working on Motorola Stock Rom

### ISSUE THREAD

**Issue by rgshah3** [wasdennnoch/AndroidN-ify#1008]
Attached xposed log 
[xposed_error_20161001_011319.txt](https://github.com/wasdennnoch/AndroidN-ify/files/503703/xposed_error_20161001_011319.txt)

**Comment by wasdennnoch** [comment]
Did you enable them in the experimental settings?

**Comment by wasdennnoch** [comment]
Actually I guess it's #1060
