### ISSUE TITLE
cm 13, system ui take too much memory(screenshot,logfile)

### ISSUE THREAD

**Issue by moonheart** [wasdennnoch/AndroidN-ify#1009]
after several hours, system ui take up to 500mb memory.
I have to force stop it to get more memory .
here is the screenshot of the memory usage.the first one is system ui.
![screenshot_20161001-184900](https://cloud.githubusercontent.com/assets/15916990/19013346/f32a2878-8808-11e6-830b-57b98afc9e7f.png)

xposed log file:

[errorlog.zip](https://github.com/wasdennnoch/AndroidN-ify/files/504244/errorlog.zip)

**Comment by wasdennnoch** [comment]
Are you 100% sure it's caused by this module? The log mainly consists of the module "Prevent Running" that spams the log with the info that it stopped 3 services - about 100 lines every second. That's just a biiit much. See yourself: http://puu.sh/rU3YX/83cd6a8c20.png
Please test it it's this module by disabling N-ify.

**Comment by moonheart** [comment]
@wasdennnoch  If I disable N-ify, system ui will not take that much memory. I will test if there's any conflicts between prevent running and N-ify by disabling any one of them and attach the log.

**Comment by wasdennnoch** [comment]
You are on CM13, right?
There are no crashes or other issues I see in the log and it's working just fine on other CM13 devices so I have no clue why that's happening. My only assumption is a module conflict as you said.
And please have a look at the smamming module, I wouldn't wonder if stopping these services comsumes more battery than just letting them run.

**Comment by moonheart** [comment]
@wasdennnoch Yes, I'm on CM13.
Here is the [error.zip](https://github.com/wasdennnoch/AndroidN-ify/files/552118/error.zip) after I disabled Prevent Running.
In recent versions of N-fiy, System UI takes about 160M memory, and after I disabled Prevent Running, this didn't change.
I checked the log, found some hooking error of N-fiy, is this the reason?

**Comment by wasdennnoch** [comment]
The error is caused by the Settings, the connected bluetoothe devices couldn't be fetched, that isn't the reason. I really don't know what's causing this now.

**Comment by moonheart** [comment]
Since this problem was hard to reproduce and I flashed to Android N, I'll close this issue, thanks.
