### ISSUE TITLE
There are some bugs in Lock screen QS

### ISSUE THREAD

**Issue by Luisito3107** [wasdennnoch/AndroidN-ify#1012]
I have found some bugs on the lock screen QS in the build 696 of Android N-ify. No small tiles in QS when swiping on lock screen. Remaining space when hiding tiles on lock screen.

I attach an video of the bug and the Xposed log:
Video: https://docs.google.com/uc?id=0B0Yd9h_4Uo8QRjQyejlCVGZiTFU&export=download
Xposed Log: https://docs.google.com/uc?id=0B0Yd9h_4Uo8QYUNTWVkwNDRmQjg&export=download

I don't know if this is a big but also I can't find the "Full width volume panel" on the module settings.

**Comment by JaredTheWolf** [comment]
+1, Stock Moto ROM 6.0.1

**Comment by wasdennnoch** [comment]
Not a bug, see #816.
