### ISSUE TITLE
"Clear All" Recents button disappeared and non-functional in OOS 3.1.3

### ISSUE THREAD

**Issue by Matthius453** [wasdennnoch/AndroidN-ify#1014]
I realise it says there's a known issue on OOS3 with the recents button relating to a System UI crash, but I believe i've found something else not functioning correctly.
If it's not known already, i'd like to report that when trying to clear all the apps that are in your recents, the button isn't there anymore when N-Ify is activated. When pressing in the location it should be, the UI just backs out of recents and none of the apps are closed.

Attached is the Xposed log.
[Untitled.txt](https://github.com/wasdennnoch/AndroidN-ify/files/504964/Untitled.txt)

After further experimentation, only on occasion does the button not do anything and sometimes when you click in the place where the button should be, it does clear all. However, sometimes it does not do this - quite temperamental.

Information:
Device; Oneplus X
ROM: (Rooted) OOS 3.1.3 
Build?: Latest stable build of Android N-Ify via Xposed downloads.

**Comment by wasdennnoch** [comment]
Try the newest snapshot build, it should have a working clear button in the recents.
