### ISSUE TITLE
Quick Settings dissappear upon expansion

### ISSUE THREAD

**Issue by IsaiahvH** [wasdennnoch/AndroidN-ify#1018]
Hi,

First of all, thank you for this amazing app!
However, there is an issue with using jenkins-AndroidN-ify-696 (6) on OxygenOS 3.1.0, Android 6.0.1 on the OnePlus 2.
While the Quick Settings are correctly shown at first, upon expansion they all move to the left and nothing is left on the actual screen; see the screenshots below.

![screenshot_20161003-193309](https://cloud.githubusercontent.com/assets/1858814/19047203/1da75f00-89a1-11e6-860f-d5ee54dc6d8f.png)

![screenshot_20161003-193328](https://cloud.githubusercontent.com/assets/1858814/19047207/22cc74a2-89a1-11e6-9c7c-633756ad35a6.png)

![screenshot_20161003-193336](https://cloud.githubusercontent.com/assets/1858814/19047215/270bf15a-89a1-11e6-9bd1-95fa88dfff74.png)

It'd be great if this could be fixed.
If there's any more information I can provide, let me know!

Thank you :]

**Comment by wasdennnoch** [comment]
#912
