### ISSUE TITLE
No further updates? Nougat.1 features awaited 

### ISSUE THREAD

**Issue by tushar260** [wasdennnoch/AndroidN-ify#1021]

**Comment by wasdennnoch** [comment]
There arw these things called real life and motivation.

**Comment by tushar260** [comment]
I'm really sorry if you felt bad 🙈
I just asked if you were planning for android 7.1 features or just got bored of this module as google will be releasing many updates including visual as well as under the hood changes.

So, will you invest you precious time in implementing all of them? 😅

I'm noone to demotivate you, don't get me wrong. I truly appreciate the time you take out for the thing you're not paid for. ;)
