### ISSUE TITLE
Recent Apps Close Instantly

### ISSUE THREAD

**Issue by I3anter** [wasdennnoch/AndroidN-ify#1022]
Snapshot version. 
When I press the recent apps button, the menu comes up but as soon as i let go of the button, it disappears. If I hold on to the button and reach to swipe the apps away, the recent menu just closes. Happens 90% of the time and it's rare for it to actually work

Oppo Find 7a
OmniROM 6.0.1 August 30 nightly

**Comment by kulankit97** [comment]
Toggle the alternate double tap detection.

**Comment by I3anter** [comment]
Simple fix lol
