### ISSUE TITLE
When clicking does not change the quick toggles icon

### ISSUE THREAD

**Issue by FatihFIRINCI** [wasdennnoch/AndroidN-ify#1025]
When you clicked does not change toggles icon. Also I want rearrange button for quick toggles and battery shortcut. Please consider this. Thanks much. Maybe is not bug, so dont need to logcat :)

**Comment by wasdennnoch** [comment]
Are you clicking the header or panel tiles? Does the other tile get updated (update expanded when toggle from collapsed and vice-versa)? There is a QS editor and battery tile available in the snapshot builds, if you are on 0.2.0 try a snapshot, they are linked in the XDA thead and this repo's readme. Maybe they also fix your bug.

**Comment by FatihFIRINCI** [comment]
25 00:09:14.605 I/Xposed  (16299): [Android N-ify] [INFO] SummaryTweaks: Found 0 matches using findMethodsByExactParameters to find updateTileView
10-25 00:25:54.301 I/Xposed  (17239): [Android N-ify] [INFO] SummaryTweaks: Found 0 matches using findMethodsByExactParameters to find updateTileView

**Comment by FatihFIRINCI** [comment]
Hi, I click the WiFi icon, but it does not shine icon. 
I want to show a video. If you want watch it. Thanks for effort. 

http://www2.zippyshare.com/v/6lvaXsfL/file.html

**Comment by wasdennnoch** [comment]
Your ROM (more or less) heavily changed the layout; HTC stock UI is only partially supported and the Quick Settings part isn't at all officially. You can try to disable the N click behaviour, that might help fixing it. It look like you are rusing 0.2.0 and I can already say that the snapshots build with the QS editor and multiple QS pages won't work at all with the stock ROM.
