### ISSUE TITLE
Empty areas in QS 

### ISSUE THREAD

**Issue by korom42** [wasdennnoch/AndroidN-ify#1026]
Having this issue in latest build 696 ( Xperia Z5 E6653 Android 6.0.1 latest stock ROM) 
*The date vertical with time issue Started from build #680 (which fix date overlap on small screens)
**PS :** I hope if possilbe make date full in QS like (Sat, Oct 08) instead of 10/08/2016 to match it with android N one.
![sketch-1475930726831](https://cloud.githubusercontent.com/assets/18078699/19214879/1f46178c-8d86-11e6-890f-29a564a94039.png)

**Comment by wasdennnoch** [comment]
It all looKs like N, they changed the date position/behavior on smaller screens. The date format already has an open issue.
