### ISSUE TITLE
Bug in snapshot version

### ISSUE THREAD

**Issue by 1nikolas** [wasdennnoch/AndroidN-ify#1028]
Just downloaded the latest snapshot and on the status bar nothing is showing even in quick action. When I click edit I get a strange message. 

Screenshots:
http://i.imgur.com/gT6BSDnl.jpg
http://i.imgur.com/ch8v33Xl.jpg
http://i.imgur.com/ljDa9q8l.jpg

**Comment by wasdennnoch** [comment]
Please post your Xposed log

**Comment by 1nikolas** [comment]
10-09 12:37:19.485 I/Xposed  (  307): -----------------
10-09 12:37:19.485 I/Xposed  (  307): Starting Xposed version 85, compiled for SDK 23
10-09 12:37:19.485 I/Xposed  (  307): Device: X5 (DOOGEE), Android version 6.0 (SDK 23)
10-09 12:37:19.485 I/Xposed  (  307): ROM: DOOGEE-X5-Android6.0-20160624
10-09 12:37:19.485 I/Xposed  (  307): Build fingerprint: DOOGEE/full_hct6580_weg_c_m/hct6580_weg_c_m:6.0/MRA58K/1466761092:user/test-keys
10-09 12:37:19.485 I/Xposed  (  307): Platform: armeabi-v7a, 32-bit binary, system server: yes
10-09 12:37:19.485 I/Xposed  (  307): SELinux enabled: yes, enforcing: yes
10-09 12:37:19.508 I/Xposed  (  307): -----------------
10-09 12:37:19.509 I/Xposed  (  307): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
10-09 12:37:20.810 I/Xposed  (  307): Detected ART runtime
10-09 12:37:20.986 I/Xposed  (  307): Found Xposed class de/robv/android/xposed/XposedBridge, now initializing
10-09 12:37:21.916 I/Xposed  (  307): Loading modules from /data/app/com.ceco.marshmallow.gravitybox-1/base.apk
10-09 12:37:22.291 I/Xposed  (  307):   Loading class com.ceco.marshmallow.gravitybox.GravityBox
10-09 12:37:22.326 I/Xposed  (  307): GB:Hardware: mt6580
10-09 12:37:22.326 I/Xposed  (  307): GB:Product: DOOGEE
10-09 12:37:22.326 I/Xposed  (  307): GB:Device manufacturer: DOOGEE
10-09 12:37:22.326 I/Xposed  (  307): GB:Device brand: DOOGEE
10-09 12:37:22.326 I/Xposed  (  307): GB:Device model: X5
10-09 12:37:22.364 I/Xposed  (  307): GB:Device type: phone
10-09 12:37:22.365 I/Xposed  (  307): GB:Is MTK device: false
10-09 12:37:22.365 I/Xposed  (  307): GB:Is Xperia device: false
10-09 12:37:22.365 I/Xposed  (  307): GB:Is Moto XT device: false
10-09 12:37:22.365 I/Xposed  (  307): GB:Has Lenovo custom UI: false
10-09 12:37:22.372 I/Xposed  (  307): GB:Has telephony support: true
10-09 12:37:22.372 I/Xposed  (  307): GB:Has Gemini support: false
10-09 12:37:22.373 I/Xposed  (  307): GB:Android SDK: 23
10-09 12:37:22.373 I/Xposed  (  307): GB:Android Release: 6.0
10-09 12:37:22.373 I/Xposed  (  307): GB:ROM: DOOGEE-X5-Android6.0-20160624
10-09 12:37:22.532 I/Xposed  (  307): Loading modules from /data/app/tk.wasdennnoch.androidn_ify-1/base.apk
10-09 12:37:22.730 I/Xposed  (  307):   Loading class tk.wasdennnoch.androidn_ify.XposedHook
10-09 12:37:22.807 I/Xposed  (  307): [Android N-ify] [INFO] XposedHook: Version jenkins-AndroidN-ify-696 (6)
10-09 12:37:22.807 I/Xposed  (  307): [Android N-ify] [INFO] XposedHook: Automated Build; Version: 696
10-09 12:37:22.808 I/Xposed  (  307): [Android N-ify] [INFO] XposedHook: Build Time: 2016-09-27T19:53Z
10-09 12:37:22.808 I/Xposed  (  307): [Android N-ify] [INFO] XposedHook: Git SHA: f2b053aff35e8b8dc36cd4a2892e991d99d0a27c
10-09 12:37:22.810 I/Xposed  (  307): [Android N-ify] [INFO] XposedHook: ---- Device info ----
10-09 12:37:22.810 I/Xposed  (  307): [Android N-ify] [INFO] XposedHook: SDK Version: 23
10-09 12:37:22.810 I/Xposed  (  307): [Android N-ify] [INFO] XposedHook: Build ID: DOOGEE-X5-Android6.0-20160624
10-09 12:37:22.810 I/Xposed  (  307): [Android N-ify] [INFO] XposedHook: Manufacturer: DOOGEE
10-09 12:37:22.810 I/Xposed  (  307): [Android N-ify] [INFO] XposedHook: Brand: DOOGEE
10-09 12:37:22.810 I/Xposed  (  307): [Android N-ify] [INFO] XposedHook: Model: X5
10-09 12:37:22.810 I/Xposed  (  307): [Android N-ify] [WARNING] XposedHook: Can't read prefs file, default values will be applied in hooks!
10-09 12:37:22.811 I/Xposed  (  307): Loading modules from /system/priv-app/com.ua.danav.fixlang/base.apk
10-09 12:37:22.850 I/Xposed  (  307):   Loading class com.ua.danav.fixlang.MainActivity
10-09 12:37:26.810 I/Xposed  (  917): GB:Is AOSP forced: false
10-09 12:38:17.417 I/Xposed  ( 1020): [Android N-ify] [ERROR] QSTileHostHooks: Couldn't create tile with spec "default"
10-09 12:38:17.713 E/Xposed  ( 1020): de.robv.android.xposed.XposedHelpers$InvocationTargetError: java.lang.IllegalArgumentException: Bad tile spec: default
10-09 12:38:17.713 E/Xposed  ( 1020): 	at de.robv.android.xposed.XposedHelpers.callMethod(XposedHelpers.java:1227)
10-09 12:38:17.713 E/Xposed  ( 1020): 	at tk.wasdennnoch.androidn_ify.systemui.qs.tiles.AOSPTile.<init>(AOSPTile.java:22)
10-09 12:38:17.713 E/Xposed  ( 1020): 	at tk.wasdennnoch.androidn_ify.systemui.qs.TilesManager.createAospTile(TilesManager.java:111)
10-09 12:38:17.713 E/Xposed  ( 1020): 	at tk.wasdennnoch.androidn_ify.systemui.qs.QSTileHostHooks.createTile(QSTileHostHooks.java:256)
10-09 12:38:17.713 E/Xposed  ( 1020): 	at tk.wasdennnoch.androidn_ify.systemui.qs.QSTileHostHooks.access$500(QSTileHostHooks.java:33)
10-09 12:38:17.713 E/Xposed  ( 1020): 	at tk.wasdennnoch.androidn_ify.systemui.qs.QSTileHostHooks$1.beforeHookedMethod(QSTileHostHooks.java:119)
10-09 12:38:17.713 E/Xposed  ( 1020): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:720)
10-09 12:38:17.713 E/Xposed  ( 1020): 	at com.android.systemui.statusbar.phone.QSTileHost.onTuningChanged(<Xposed>)
10-09 12:38:17.713 E/Xposed  ( 1020): 	at com.android.systemui.tuner.TunerService.addTunable(TunerService.java:98)
10-09 12:38:17.713 E/Xposed  ( 1020): 	at com.android.systemui.tuner.TunerService.addTunable(TunerService.java:82)
10-09 12:38:17.713 E/Xposed  ( 1020): 	at com.android.systemui.statusbar.phone.QSTileHost.<init>(QSTileHost.java:150)
10-09 12:38:17.713 E/Xposed  ( 1020): 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
10-09 12:38:17.713 E/Xposed  ( 1020): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:740)
10-09 12:38:17.713 E/Xposed  ( 1020): 	at com.android.systemui.statusbar.phone.QSTileHost.<init>(<Xposed>)
10-09 12:38:17.713 E/Xposed  ( 1020): 	at com.android.systemui.statusbar.phone.PhoneStatusBar.makeStatusBarView(PhoneStatusBar.java:957)
10-09 12:38:17.713 E/Xposed  ( 1020): 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
10-09 12:38:17.713 E/Xposed  ( 1020): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:740)
10-09 12:38:17.713 E/Xposed  ( 1020): 	at com.android.systemui.statusbar.phone.PhoneStatusBar.makeStatusBarView(<Xposed>)
10-09 12:38:17.713 E/Xposed  ( 1020): 	at com.android.systemui.statusbar.phone.PhoneStatusBar.addStatusBarWindow(PhoneStatusBar.java:2929)
10-09 12:38:17.713 E/Xposed  ( 1020): 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
10-09 12:38:17.713 E/Xposed  ( 1020): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:740)
10-09 12:38:17.713 E/Xposed  ( 1020): 	at com.android.systemui.statusbar.phone.PhoneStatusBar.addStatusBarWindow(<Xposed>)
10-09 12:38:17.713 E/Xposed  ( 1020): 	at com.android.systemui.statusbar.phone.PhoneStatusBar.createAndAddWindows(PhoneStatusBar.java:2925)
10-09 12:38:17.713 E/Xposed  ( 1020): 	at com.android.systemui.statusbar.BaseStatusBar.start(BaseStatusBar.java:660)
10-09 12:38:17.713 E/Xposed  ( 1020): 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
10-09 12:38:17.713 E/Xposed  ( 1020): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:740)
10-09 12:38:17.713 E/Xposed  ( 1020): 	at com.android.systemui.statusbar.BaseStatusBar.start(<Xposed>)
10-09 12:38:17.713 E/Xposed  ( 1020): 	at com.android.systemui.statusbar.phone.PhoneStatusBar.start(PhoneStatusBar.java:640)
10-09 12:38:17.713 E/Xposed  ( 1020): 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
10-09 12:38:17.713 E/Xposed  ( 1020): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:740)
10-09 12:38:17.713 E/Xposed  ( 1020): 	at com.android.systemui.statusbar.phone.PhoneStatusBar.start(<Xposed>)
10-09 12:38:17.713 E/Xposed  ( 1020): 	at com.android.systemui.statusbar.SystemBars.createStatusBarFromConfig(SystemBars.java:106)
10-09 12:38:17.713 E/Xposed  ( 1020): 	at com.android.systemui.statusbar.SystemBars.onNoService(SystemBars.java:58)
10-09 12:38:17.713 E/Xposed  ( 1020): 	at com.android.systemui.statusbar.ServiceMonitor.startService(ServiceMonitor.java:230)
10-09 12:38:17.713 E/Xposed  ( 1020): 	at com.android.systemui.statusbar.ServiceMonitor.-wrap5(ServiceMonitor.java)
10-09 12:38:17.713 E/Xposed  ( 1020): 	at com.android.systemui.statusbar.ServiceMonitor$1.handleMessage(ServiceMonitor.java:73)
10-09 12:38:17.713 E/Xposed  ( 1020): 	at android.os.Handler.dispatchMessage(Handler.java:111)
10-09 12:38:17.713 E/Xposed  ( 1020): 	at android.os.Looper.loop(Looper.java:207)
10-09 12:38:17.713 E/Xposed  ( 1020): 	at android.app.ActivityThread.main(ActivityThread.java:5728)
10-09 12:38:17.713 E/Xposed  ( 1020): 	at java.lang.reflect.Method.invoke(Native Method)
10-09 12:38:17.713 E/Xposed  ( 1020): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
10-09 12:38:17.713 E/Xposed  ( 1020): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
10-09 12:38:17.713 E/Xposed  ( 1020): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
10-09 12:38:17.713 E/Xposed  ( 1020): Caused by: java.lang.IllegalArgumentException: Bad tile spec: default
10-09 12:38:17.713 E/Xposed  ( 1020): 	at com.android.systemui.statusbar.phone.QSTileHost.createTile(QSTileHost.java:344)
10-09 12:38:17.713 E/Xposed  ( 1020): 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
10-09 12:38:17.713 E/Xposed  ( 1020): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:740)
10-09 12:38:17.713 E/Xposed  ( 1020): 	at com.android.systemui.statusbar.phone.QSTileHost.createTile(<Xposed>)
10-09 12:38:17.713 E/Xposed  ( 1020): 	at java.lang.reflect.Method.invoke(Native Method)
10-09 12:38:17.713 E/Xposed  ( 1020): 	at de.robv.android.xposed.XposedHe
10-09 12:38:39.355 I/Xposed  ( 1020): [Android N-ify] [ERROR] NotificationPanelHooks: Couldn't open edit view; mRecords == null
10-09 12:39:02.951 I/Xposed  ( 2852): [Android N-ify] [ERROR] QSTileHostHooks: Couldn't create tile with spec "default"
10-09 12:39:02.961 E/Xposed  ( 2852): de.robv.android.xposed.XposedHelpers$InvocationTargetError: java.lang.IllegalArgumentException: Bad tile spec: default
10-09 12:39:02.961 E/Xposed  ( 2852): 	at de.robv.android.xposed.XposedHelpers.callMethod(XposedHelpers.java:1227)
10-09 12:39:02.961 E/Xposed  ( 2852): 	at tk.wasdennnoch.androidn_ify.systemui.qs.tiles.AOSPTile.<init>(AOSPTile.java:22)
10-09 12:39:02.961 E/Xposed  ( 2852): 	at tk.wasdennnoch.androidn_ify.systemui.qs.TilesManager.createAospTile(TilesManager.java:111)
10-09 12:39:02.961 E/Xposed  ( 2852): 	at tk.wasdennnoch.androidn_ify.systemui.qs.QSTileHostHooks.createTile(QSTileHostHooks.java:256)
10-09 12:39:02.961 E/Xposed  ( 2852): 	at tk.wasdennnoch.androidn_ify.systemui.qs.QSTileHostHooks.access$500(QSTileHostHooks.java:33)
10-09 12:39:02.961 E/Xposed  ( 2852): 	at tk.wasdennnoch.androidn_ify.systemui.qs.QSTileHostHooks$1.beforeHookedMethod(QSTileHostHooks.java:119)
10-09 12:39:02.961 E/Xposed  ( 2852): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:720)
10-09 12:39:02.961 E/Xposed  ( 2852): 	at com.android.systemui.statusbar.phone.QSTileHost.onTuningChanged(<Xposed>)
10-09 12:39:02.961 E/Xposed  ( 2852): 	at com.android.systemui.tuner.TunerService.addTunable(TunerService.java:98)
10-09 12:39:02.961 E/Xposed  ( 2852): 	at com.android.systemui.tuner.TunerService.addTunable(TunerService.java:82)
10-09 12:39:02.961 E/Xposed  ( 2852): 	at com.android.systemui.statusbar.phone.QSTileHost.<init>(QSTileHost.java:150)
10-09 12:39:02.961 E/Xposed  ( 2852): 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
10-09 12:39:02.961 E/Xposed  ( 2852): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:740)
10-09 12:39:02.961 E/Xposed  ( 2852): 	at com.android.systemui.statusbar.phone.QSTileHost.<init>(<Xposed>)
10-09 12:39:02.961 E/Xposed  ( 2852): 	at com.android.systemui.statusbar.phone.PhoneStatusBar.makeStatusBarView(PhoneStatusBar.java:957)
10-09 12:39:02.961 E/Xposed  ( 2852): 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
10-09 12:39:02.961 E/Xposed  ( 2852): 	at de.robv.android.xposed.XposedBridge.handl

**Comment by 1nikolas** [comment]
Still not fixed with build 697

**Comment by wasdennnoch** [comment]
Should be fixed with 579adab5fc041ea53550f113d0e0105901de84d2.
