### ISSUE TITLE
Google Assistant

### ISSUE THREAD

**Issue by Simi3000** [wasdennnoch/AndroidN-ify#1032]
It's cool this new feature, but I miss Google Now on Tap, and there is not option to re-enable.

**Comment by Maxr1998** [comment]
For now, you could just roll back to the previous AndroidN-ify version.
Next version will include a toggle and better error handling for unsupported versions.

**Comment by Jrdnkasparek** [comment]
You can still use now on tap with the new Google Assistant. You have to swipe up from the button after holding down for Assistant to trigger it

**Comment by Maxr1998** [comment]
Yeah, but I think he wanted the old UI, not just the screen search feature.. or am I wrong?

**Comment by Simi3000** [comment]
Its OK the new design but I want the text selection.

**Comment by Jrdnkasparek** [comment]
ohh okay, yeah idk how to do that with the new version, maybe just ask google assistant :D

**Comment by Maxr1998** [comment]
Text selection was removed by Google. You also can now disable the new Assistant in N-ify settings.
