### ISSUE TITLE
System UI crashes when Quick Settings "Style header" is disabled upon receiving a notification

### ISSUE THREAD

**Issue by kkuhle** [wasdennnoch/AndroidN-ify#1038]
I am using stock LG G5.  I understand that this module is designed for AOSP or pure stock roms, but I decided to try it anyway.  I was excited to find that most of it works really well.  The only problem I have is that when I disable quick settings "Style header" my system ui crashes on most notifications that come in.  

Here is my logcat.
https://dl.dropboxusercontent.com/u/28494298/2016-10-12-14-03-54.txt

Style Header enabled - https://dl.dropboxusercontent.com/u/28494298/Capture%2B_2016-10-11-18-23-05.png
Syle Header disabled - https://dl.dropboxusercontent.com/u/28494298/Capture%2B_2016-10-14-16-16-09.png

If anything can be done about this that would be awesome!  Please let me know if anything else is needed.  Thanks for your hard work on this module!

**Comment by kab89** [comment]
I would also love to see a workaround on this problem. Thanks

**Comment by mattszcz** [comment]
Also, disabling Quick Settings->Style Header does not restore the default quick settings.

**Comment by wasdennnoch** [comment]
Crash should be fixed with 874c40ad7c0ec5d0cf9526d6c87ecd437f426e83.
