### ISSUE TITLE
LG G3 system UI crash

### ISSUE THREAD

**Issue by edwardsuper** [wasdennnoch/AndroidN-ify#1039]
My LG G3 UI crashed whenever I press the "Reply" button or swipe away the notifications. My phone is running N&N rom v4.0 Marshmallow.

**Comment by edwardsuper** [comment]
[logcat.txt](https://github.com/wasdennnoch/AndroidN-ify/files/526293/logcat.txt)

Please help fix the problem with the attached log file.

**Comment by wasdennnoch** [comment]
Ther eis no crash in the logcat; Please post your Xposed log and another logcat captured while the SystemUI crashes.

**Comment by wasdennnoch** [comment]
Also, do you have header tweaks disabled? If so it's probably a duplicate of #1038.

**Comment by wasdennnoch** [comment]
Should be fixed with 874c40ad7c0ec5d0cf9526d6c87ecd437f426e83.
