### ISSUE TITLE
How can I use google assistant on my Redmi Note 4G (CM14), I've tried both the methods (changing build.prop and flashing those 2 zip files) but none of them worked for me.

### ISSUE THREAD

**Issue by tushar260** [wasdennnoch/AndroidN-ify#1040]

**Comment by wasdennnoch** [comment]
This is completely irrelevant to the module. I don't know exactly what has to be changed. Maybe it also depends on the Google app version so you migjt have to install the latest beta version.

**Comment by tushar260** [comment]
I am on the lastest beta. I thought you might know so I asked. 😅
