### ISSUE TITLE
SystemUI Crash on Alcatel Flash Plus Running Remix F2 AOSP 5.0.2 rom.

### ISSUE THREAD

**Issue by Takumi87** [wasdennnoch/AndroidN-ify#1042]
I always get systemui crash no matter what snapshot build i use. The stable build 0.2.0 was working fine tho. Please tell me how i can submit the logcat.

**Comment by Takumi87** [comment]
10-13 12:38:36.655 D/Environment(11568):     mPrimary=true mRemovable=false mEmulated=true mMtpReserveSpace=10 
10-13 12:38:36.655 D/Environment(11568):     mAllowMassStorage=false mMaxFileSize=0 mOwner=UserHandle{0} mUuid=null 
10-13 12:38:36.655 D/Environment(11568):     mUserLabel=null mState=mounted 
10-13 12:38:36.655 D/Environment(11568): getStorageVolume,  volume:StorageVolume:
10-13 12:38:36.655 D/Environment(11568):     mStorageId=131073 mPath=/storage/sdcard1 mDescriptionId=17040783 
10-13 12:38:36.655 D/Environment(11568):     mPrimary=false mRemovable=true mEmulated=false mMtpReserveSpace=0 
10-13 12:38:36.655 D/Environment(11568):     mAllowMassStorage=true mMaxFileSize=0 mOwner=null mUuid=3EE8-15F9 
10-13 12:38:36.655 D/Environment(11568):     mUserLabel=ICHIGO mState=mounted 
10-13 12:38:36.656 D/Environment(11568): getStorageVolume,  volume:StorageVolume:
10-13 12:38:36.656 D/Environment(11568):     mStorageId=196609 mPath=/storage/usbotg mDescriptionId=17040786 
10-13 12:38:36.656 D/Environment(11568):     mPrimary=false mRemovable=true mEmulated=false mMtpReserveSpace=0 
10-13 12:38:36.656 D/Environment(11568):     mAllowMassStorage=false mMaxFileSize=0 mOwner=null mUuid=null 
10-13 12:38:36.656 D/Environment(11568):     mUserLabel=null mState=removed 
10-13 12:38:36.656 D/ColorDrawable(11591): setColor color = -10066330, ColorDrawable = android.graphics.drawable.ColorDrawable@2538927d
10-13 12:38:36.657 D/SQLiteDatabase(1289): beginTransaction()
10-13 12:38:36.658 D/SQLiteDatabase(1289): endTransaction()
10-13 12:38:36.661 D/Mms/Provider/Sms(1527): query begin, uri = content://sms/2654, selection = null
10-13 12:38:36.663 D/ActivityManager(842): getContentProviderImpl: from caller=android.app.ApplicationThreadProxy@e5174ba (pid=11568, userId=0) to get content provider media cpr=ContentProviderRecord{12c28b43 u0 com.android.providers.media/.MediaProvider}
10-13 12:38:36.664 V/SettingsInterface(1527):  from settings cache , name = multi_sim_common , value = 2
10-13 12:38:36.666 D/ListView(11591): mSelectorRect.setEmpty in layoutChildren this=com.nolanlawson.logcat.widget.ExceptionCatchingListView{3cb3b6d0 VFED..CL ......ID 0,102-720,1230 #102000a android:id/list}
10-13 12:38:36.667 D/ColorDrawable(11591): Color = -16777216, canvas = android.view.GLES20RecordingCanvas@a3ff260, mTintMode = SRC_IN, mTint = null, ColorDrawable = android.graphics.drawable.ColorDrawable@18fc06e2
10-13 12:38:36.667 D/NativeCrypto(1097): ssl=0x7f6b4a0280 sslRead buf=0x7f6d40f000 len=2048,timeo=60000
10-13 12:38:36.668 D/ColorDrawable(11591): Color = -16750900, canvas = android.view.GLES20RecordingCanvas@2c21d48c, mTintMode = SRC_IN, mTint = null, ColorDrawable = android.graphics.drawable.ColorDrawable@6bf4a5
10-13 12:38:36.668 D/ColorDrawable(11591): Color = -16750900, canvas = android.view.GLES20RecordingCanvas@2c21d48c, mTintMode = SRC_IN, mTint = null, ColorDrawable = android.graphics.drawable.ColorDrawable@3bdf3eb1
10-13 12:38:36.669 D/ActivityThread(11568): hoder:android.app.IActivityManager$ContentProviderHolder@3d3bca4f,provider,holder.Provider:android.content.ContentProviderProxy@123365dc
10-13 12:38:36.669 D/ColorDrawable(11591): Color = -10066330, canvas = android.view.GLES20RecordingCanvas@2c21d48c, mTintMode = SRC_IN, mTint = null, ColorDrawable = android.graphics.drawable.ColorDrawable@2538927d
10-13 12:38:36.670 D/ColorDrawable(11591): Color = -16750900, canvas = android.view.GLES20RecordingCanvas@2c21d48c, mTintMode = SRC_IN, mTint = null, ColorDrawable = android.graphics.drawable.ColorDrawable@165dc09
10-13 12:38:36.671 D/ColorDrawable(11591): Color = -16750900, canvas = android.view.GLES20RecordingCanvas@2c21d48c, mTintMode = SRC_IN, mTint = null, ColorDrawable = android.graphics.drawable.ColorDrawable@2b84c755
10-13 12:38:36.671 D/ColorDrawable(11591): Color = -16750900, canvas = android.view.GLES20RecordingCanvas@2c21d48c, mTintMode = SRC_IN, mTint = null, ColorDrawable = android.graphics.drawable.ColorDrawable@11aec061
10-13 12:38:36.672 D/ColorDrawable(11591): Color = -16750900, canvas = android.view.GLES20RecordingCanvas@2c21d48c, mTintMode = SRC_IN, mTint = null, ColorDrawable = android.graphics.drawable.ColorDrawable@3784f32d
10-13 12:38:36.673 D/ColorDrawable(11591): Color = -16750900, canvas = android.view.GLES20RecordingCanvas@2c21d48c, mTintMode = SRC_IN, mTint = null, ColorDrawable = android.graphics.drawable.ColorDrawable@2a7c4bb9
10-13 12:38:36.673 D/SQLiteDatabase(1289): beginTransaction()
10-13 12:38:36.673 D/ColorDrawable(11591): Color = -10066330, canvas = android.view.GLES20RecordingCanvas@2c21d48c, mTintMode = SRC_IN, mTint = null, ColorDrawable = android.graphics.drawable.ColorDrawable@13e97605
10-13 12:38:36.674 D/SQLiteDatabase(1289): endTransaction()
10-13 12:38:36.674 D/ColorDrawable(11591): Color = -16750900, canvas = android.view.GLES20RecordingCanvas@2c21d48c, mTintMode = SRC_IN, mTint = null, ColorDrawable = android.graphics.drawable.ColorDrawable@14ccde11
10-13 12:38:36.675 D/ColorDrawable(11591): Color = -16750900, canvas = android.view.GLES20RecordingCanvas@2c21d48c, mTintMode = SRC_IN, mTint = null, ColorDrawable = android.graphics.drawable.ColorDrawable@175eafdd
10-13 12:38:36.676 D/ColorDrawable(11591): Color = -16750900, canvas = android.view.GLES20RecordingCanvas@2c21d48c, mTintMode = SRC_IN, mTint = null, ColorDrawable = android.graphics.drawable.ColorDrawable@25ad769
10-13 12:38:36.676 D/ColorDrawable(11591): Color = -256, canvas = android.view.GLES20RecordingCanvas@2c21d48c, mTintMode = SRC_IN, mTint = null, ColorDrawable = android.graphics.drawable.ColorDrawable@30026ea7
10-13 12:38:36.677 D/ColorDrawable(11591): Color = -16750900, canvas = android.view.GLES20RecordingCanvas@2c21d48c, mTintMode = SRC_IN, mTint = null, ColorDrawable = android.graphics.drawable.ColorDrawable@1ce52a53
10-13 12:38:36.677 D/ColorDrawable(11591): Color = -16750900, canvas = android.view.GLES20RecordingCanvas@2c21d48c, mTintMode = SRC_IN, mTint = null, ColorDrawable = android.graphics.drawable.ColorDrawable@2bb41bf
10-13 12:38:36.678 D/ColorDrawable(11591): Color = -16750900, canvas = android.view.GLES20RecordingCanvas@2c21d48c, mTintMode = SRC_IN, mTint = null, ColorDrawable = android.graphics.drawable.ColorDrawable@321540eb
10-13 12:38:36.679 D/ColorDrawable(11591): Color = -16750900, canvas = android.view.GLES20RecordingCanvas@2c21d48c, mTintMode = SRC_IN, mTint = null, ColorDrawable = android.graphics.drawable.ColorDrawable@2ed573d7
10-13 12:38:36.680 D/ActivityThread(12169): SVC-Destroying service: com.htc.BiLogClient.BiLogUploadService@12d129e9
10-13 12:38:36.680 D/ColorDrawable(11591): Color = -16750900, canvas = android.view.GLES20RecordingCanvas@2c21d48c, mTintMode = SRC_IN, mTint = null, ColorDrawable = android.graphics.drawable.ColorDrawable@24855922
10-13 12:38:36.680 D/ColorDrawable(11591): Color = -16750900, canvas = android.view.GLES20RecordingCanvas@2c21d48c, mTintMode = SRC_IN, mTint = null, ColorDrawable = android.graphics.drawable.ColorDrawable@30c755e
10-13 12:38:36.681 D/ColorDrawable(11591): Color = -10066330, canvas = android.view.GLES20RecordingCanvas@2c21d48c, mTintMode = SRC_IN, mTint = null, ColorDrawable = android.graphics.drawable.ColorDrawable@b233dba
10-13 12:38:36.682 D/ColorDrawable(11591): Color = -16750900, canvas = android.view.GLES20RecordingCanvas@2c21d48c, mTintMode = SRC_IN, mTint = null, ColorDrawable = android.graphics.drawable.ColorDrawable@3a1330d6
10-13 12:38:36.683 D/ColorDrawable(11591): Color = -16750900, canvas = android.view.GLES20RecordingCanvas@2c21d48c, mTintMode = SRC_IN, mTint = null, ColorDrawable = android.graphics.drawable.ColorDrawable@257d0ab2
10-13 12:38:36.683 I/ActivityManager(842): Killing 11311:com.android.gallery3d/u0a38 (adj 15): empty #17
10-13 12:38:36.684 D/ColorDrawable(11591): Color = -16750900, canvas = android.view.GLES20RecordingCanvas@2c21d48c, mTintMode = SRC_IN, mTint = null, ColorDrawable = android.graphics.drawable.ColorDrawable@1afa474e
10-13 12:38:36.684 D/NativeCrypto(1097): ssl=0x7f6b4a0280 sslRead buf=0x7f6d40f000 len=2048,timeo=60000
10-13 12:38:36.684 D/ColorDrawable(11591): Color = -16750900, canvas = android.view.GLES20RecordingCanvas@2c21d48c, mTintMode = SRC_IN, mTint = null, ColorDrawable = android.graphics.drawable.ColorDrawable@13600f51
10-13 12:38:36.685 D/ColorDrawable(11591): Color = -16750900, canvas = android.view.GLES20RecordingCanvas@2c21d48c, mTintMode = SRC_IN, mTint = null, ColorDrawable = android.graphics.drawable.ColorDrawable@1ebbe51d
10-13 12:38:36.686 D/ColorDrawable(11591): Color = -16750900, canvas = android.view.GLES20RecordingCanvas@2c21d48c, mTintMode = SRC_IN, mTint = null, ColorDrawable = android.graphics.drawable.ColorDrawable@3f4550a9
10-13 12:38:36.686 D/ColorDrawable(11591): Color = -16750900, canvas = android.view.GLES20RecordingCanvas@2c21d48c, mTintMode = SRC_IN, mTint = null, ColorDrawable = android.graphics.drawable.ColorDrawable@39ebfdf5
10-13 12:38:36.687 D/ColorDrawable(11591): Color = -16750900, canvas = android.view.GLES20RecordingCanvas@2c21d48c, mTintMode = SRC_IN, mTint = null, ColorDrawable = android.graphics.drawable.ColorDrawable@313b5901
10-13 12:38:36.688 D/ColorDrawable(11591): Color = -16750900, canvas = android.view.GLES20RecordingCanvas@2c21d48c, mTintMode = SRC_IN, mTint = null, ColorDrawable = android.graphics.drawable.ColorDrawable@9e68dcd
10-13 12:38:36.688 D/ColorDrawable(11591): Color = -16750900, canvas = android.view.GLES20RecordingCanvas@2c21d48c, mTintMode = SRC_IN, mTint = null, ColorDrawable = android.graphics.drawable.ColorDrawable@21148859
10-13 12:38:36.689 D/ActivityThread(12169): SVC-STOP_SERVICE handled : 0 / android.os.BinderProxy@11d71270
10-13 12:38:36.691 D/PerfServiceManager(842): [PerfService] notifyFrameUpdate - bDuringTouchBoost:false 
10-13 12:38:36.692 D/NativeCrypto(1097): ssl=0x7f6b4a0280 sslRead buf=0x7f6d40f000 len=2048,timeo=60000
10-13 12:38:36.692 D/NativeCrypto(1097): ssl=0x7f6b4a0280 sslRead buf=0x7f6d40f000 len=2048,timeo=60000
10-13 12:38:36.692 D/NativeCrypto(1097): ssl=0x7f6b4a0280 sslRead buf=0x7f6d40f000 len=2048,timeo=60000
10-13 12:38:36.694 D/CSLegacyTypeTracker(842): getNetworkForType type 1
10-13 12:38:36.695 D/CSLegacyTypeTracker(842): getNetworkForType type 1
10-13 12:38:36.695 D/CSLegacyTypeTracker(842): getNetworkForType type 1
10-13 12:38:36.695 D/ConnectivityService(842): getActiveNetworkInfo:[type: WIFI[], state: CONNECTED/CONNECTED, reason: (unspecified), extra: "PLDTHOMEDSLtin2dgreat", roaming: false, failover: false, isAvailable: true, isConnectedToProvisioningNetwork: false]/10008
10-13 12:38:36.703 D/Mms/Provider/Sms(1527): query end
10-13 12:38:36.709 V/MediaProvider(1097): update for uri=content://media/external/file/273611, initValues=mime_type=null date_modified=1475332570 _size=795340 title=2012_bmw_1m_a is_drm=false
10-13 12:38:36.716 I/SurfaceFlinger(241): [Built-in Screen (type:0)] fps:5.543879,dur:1082.27,max:216.72,min:149.24
10-13 12:38:36.726 D/SQLiteDatabase(1289): beginTransaction()
10-13 12:38:36.729 D/SQLiteDatabase(2809): beginTransaction()
10-13 12:38:36.730 D/SQLiteDatabase(2809): beginTransaction()
10-13 12:38:36.731 D/SQLiteDatabase(2809): endTransaction()
10-13 12:38:36.731 D/SQLiteDatabase(2809): endTransaction()
10-13 12:38:36.741 I/art     (12242): Background sticky concurrent mark sweep GC freed 7036(675KB) AllocSpace objects, 0(0B) LOS objects, 31% free, 1313KB/1926KB, paused 8.033ms total 72.657ms
10-13 12:38:36.744 W/ADB_SERVICES(6073): terminating JDWP 11311 connection: Success
10-13 12:38:36.744 D/ADB_SERVICES(6073): remove pid 11311 to jdwp process list
10-13 12:38:36.744 D/DisplayManagerService(842): Display listener for pid 11311 died.
10-13 12:38:36.744 D/SQLiteDatabase(1289): endTransaction()
10-13 12:38:36.755 D/ColorDrawable(11591): setColor color = -16750900, ColorDrawable = android.graphics.drawable.ColorDrawable@b233dba
10-13 12:38:36.761 D/MWB_LOGS(4997): Folder monitored: /storage/sdcard1/Link2SD/bind/data/com.ea.games.r3_row/files/.depot/Tracks/Hockenheim/national/high
10-13 12:38:36.763 V/MediaProvider(1097): update for uri=content://media/external/file/273612, initValues=mime_type=null date_modified=1475332570 _size=41359 title=2012_bmw_1m_cab.etc.dds is_drm=false
10-13 12:38:36.766

**Comment by wasdennnoch** [comment]
You have to post a full unfiltered logcat recorded during the crashes as an attachment. *Do not post it directly as text in a reply*, it really clutters the page.

**Comment by Takumi87** [comment]
Ok. I was supposed to just attach the .txt here but i duno how. I just signed up today and im new to github. 😁
