### ISSUE TITLE
Google assistant doesn't remember voice

### ISSUE THREAD

**Issue by dave07747** [wasdennnoch/AndroidN-ify#1044]
Every time I say okay Google it asks to train the voice again

**Comment by kulankit97** [comment]
Same happens with me everytime.. plz.. need a fix..

**Comment by stagefright5** [comment]
@dave , please provide the logs

**Comment by dave07747** [comment]
10-14 07:15:00.123 I/Xposed  (  225): -----------------
10-14 07:15:00.123 I/Xposed  (  225): Starting Xposed version 86, compiled for SDK 23
10-14 07:15:00.123 I/Xposed  (  225): Device: Nexus 5 (LGE), Android version 6.0.1 (SDK 23)
10-14 07:15:00.123 I/Xposed  (  225): ROM: MOB30M
10-14 07:15:00.123 I/Xposed  (  225): Build fingerprint: google/hammerhead/hammerhead:6.0.1/MOB30M/2862625:user/release-keys
10-14 07:15:00.123 I/Xposed  (  225): Platform: armeabi-v7a, 32-bit binary, system server: yes
10-14 07:15:00.123 I/Xposed  (  225): SELinux enabled: yes, enforcing: yes
10-14 07:15:01.170 I/Xposed  (  225): -----------------
10-14 07:15:01.173 I/Xposed  (  225): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
10-14 07:15:02.047 I/Xposed  (  225): Detected ART runtime
10-14 07:15:02.086 I/Xposed  (  225): Found Xposed class 'de/robv/android/xposed/XposedBridge', now initializing
10-14 07:15:02.735 I/Xposed  (  225): Loading modules from /data/app/com.ceco.marshmallow.gravitybox-2/base.apk
10-14 07:15:03.344 I/Xposed  (  225):   Loading class com.ceco.marshmallow.gravitybox.GravityBox
10-14 07:15:03.374 I/Xposed  (  225): GB:Hardware: hammerhead
10-14 07:15:03.374 I/Xposed  (  225): GB:Product: hammerhead
10-14 07:15:03.374 I/Xposed  (  225): GB:Device manufacturer: LGE
10-14 07:15:03.374 I/Xposed  (  225): GB:Device brand: google
10-14 07:15:03.374 I/Xposed  (  225): GB:Device model: Nexus 5
10-14 07:15:03.383 I/Xposed  (  225): GB:Device type: phone
10-14 07:15:03.383 I/Xposed  (  225): GB:Is MTK device: false
10-14 07:15:03.384 I/Xposed  (  225): GB:Is Xperia device: false
10-14 07:15:03.384 I/Xposed  (  225): GB:Is Moto XT device: false
10-14 07:15:03.384 I/Xposed  (  225): GB:Has Lenovo custom UI: false
10-14 07:15:03.384 I/Xposed  (  225): GB:Has telephony support: true
10-14 07:15:03.384 I/Xposed  (  225): GB:Has Gemini support: false
10-14 07:15:03.384 I/Xposed  (  225): GB:Android SDK: 23
10-14 07:15:03.384 I/Xposed  (  225): GB:Android Release: 6.0.1
10-14 07:15:03.384 I/Xposed  (  225): GB:ROM: MOB30M
10-14 07:15:03.430 I/Xposed  (  225): Loading modules from /data/app/com.smartmadsoft.xposed.nolockhome2-1/base.apk
10-14 07:15:03.533 I/Xposed  (  225):   Loading class com.smartmadsoft.xposed.nolockhome2.Locksmith
10-14 07:15:03.566 I/Xposed  (  225): Loading modules from /data/app/de.defim.apk.bootmanager-2/base.apk
10-14 07:15:03.634 I/Xposed  (  225):   Loading class de.defim.apk.bootmanager.Xposed
10-14 07:15:03.644 I/Xposed  (  225):     [BootManager] initialized
10-14 07:15:03.644 I/Xposed  (  225):   Loading class de.defim.apk.bootmanager.Xcheck
10-14 07:15:03.645 I/Xposed  (  225): Loading modules from /data/app/ma.wanam.youtubeadaway-1/base.apk
10-14 07:15:03.685 I/Xposed  (  225):   Loading class ma.wanam.youtubeadaway.Xposed
10-14 07:15:03.688 I/Xposed  (  225): Loading modules from /data/app/com.pyler.youtubebackgroundplayback-1/base.apk
10-14 07:15:03.720 I/Xposed  (  225):   Loading class com.pyler.youtubebackgroundplayback.YouTubeBackgroundPlayback
10-14 07:15:03.724 I/Xposed  (  225): Loading modules from /data/app/tk.wasdennnoch.androidn_ify-1/base.apk
10-14 07:15:03.855 I/Xposed  (  225):   Loading class tk.wasdennnoch.androidn_ify.XposedHook
10-14 07:15:03.926 I/Xposed  (  225): [Android N-ify] [INFO] XposedHook: Version jenkins-AndroidN-ify-697 (6)
10-14 07:15:03.926 I/Xposed  (  225): [Android N-ify] [INFO] XposedHook: Automated Build; Version: 697
10-14 07:15:03.926 I/Xposed  (  225): [Android N-ify] [INFO] XposedHook: Build Time: 2016-10-11T19:59Z
10-14 07:15:03.927 I/Xposed  (  225): [Android N-ify] [INFO] XposedHook: Git SHA: 4f14cce7602c5910949786b1dd3f8088433930a8
10-14 07:15:03.937 I/Xposed  (  225): [Android N-ify] [INFO] XposedHook: ---- Device info ----
10-14 07:15:03.937 I/Xposed  (  225): [Android N-ify] [INFO] XposedHook: SDK Version: 23
10-14 07:15:03.937 I/Xposed  (  225): [Android N-ify] [INFO] XposedHook: Build ID: MOB30M
10-14 07:15:03.937 I/Xposed  (  225): [Android N-ify] [INFO] XposedHook: Manufacturer: LGE
10-14 07:15:03.937 I/Xposed  (  225): [Android N-ify] [INFO] XposedHook: Brand: google
10-14 07:15:03.937 I/Xposed  (  225): [Android N-ify] [INFO] XposedHook: Model: Nexus 5
10-14 07:15:03.937 I/Xposed  (  225): Loading modules from /data/app/com.android.vending.billing.InAppBillingService.LOCK-2/base.apk
10-14 07:15:04.130 I/Xposed  (  225):   Loading class com.chelpus.XSupport
10-14 07:15:04.182 I/Xposed  (  225): Loading modules from /data/app/com.czbix.xposed.wifipassword-2/base.apk
10-14 07:15:04.224 I/Xposed  (  225):   Loading class com.czbix.xposed.wifipassword.Patch
10-14 07:15:06.818 I/Xposed  (  889): GB:Is AOSP forced: false
10-14 07:15:26.893 I/Xposed  ( 1184): Hook M constructor success
10-14 07:15:34.835 I/Xposed  ( 2301): YouTube: com.google.android.youtube 11.39.56 loaded!
10-14 07:15:34.835 I/Xposed  ( 2301): YouTube AdAway 3.4.0: Trying brute force way...
10-14 07:15:40.305 I/Xposed  ( 2301): YouTube AdAway: Successfully hooked ocg constructor!
10-14 07:15:40.307 I/Xposed  ( 2301): YouTube AdAway: Successfully hooked sequence: class =ocg methods a-b, param=mjs
10-14 07:15:58.072 E/Xposed  ( 3912): java.lang.NoSuchMethodError: bbw#a(boolean)#exact
10-14 07:15:58.072 E/Xposed  ( 3912): 	at de.robv.android.xposed.XposedHelpers.findMethodExact(XposedHelpers.java:337)
10-14 07:15:58.072 E/Xposed  ( 3912): 	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:178)
10-14 07:15:58.072 E/Xposed  ( 3912): 	at com.ceco.marshmallow.gravitybox.ModDialer24.init(ModDialer24.java:216)
10-14 07:15:58.072 E/Xposed  ( 3912): 	at com.ceco.marshmallow.gravitybox.GravityBox.handleLoadPackage(GravityBox.java:149)
10-14 07:15:58.072 E/Xposed  ( 3912): 	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:34)
10-14 07:15:58.072 E/Xposed  ( 3912): 	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:61)
10-14 07:15:58.072 E/Xposed  ( 3912): 	at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:106)
10-14 07:15:58.072 E/Xposed  ( 3912): 	at de.robv.android.xposed.XposedInit$1.beforeHookedMethod(XposedInit.java:93)
10-14 07:15:58.072 E/Xposed  ( 3912): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:314)
10-14 07:15:58.072 E/Xposed  ( 3912): 	at android.app.ActivityThread.handleBindApplication(<Xposed>)
10-14 07:15:58.072 E/Xposed  ( 3912): 	at android.app.ActivityThread.-wrap1(ActivityThread.java)
10-14 07:15:58.072 E/Xposed  ( 3912): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
10-14 07:15:58.072 E/Xposed  ( 3912): 	at android.os.Handler.dispatchMessage(Handler.java:102)
10-14 07:15:58.072 E/Xposed  ( 3912): 	at android.os.Looper.loop(Looper.java:148)
10-14 07:15:58.072 E/Xposed  ( 3912): 	at android.app.ActivityThread.main(ActivityThread.java:5417)
10-14 07:15:58.072 E/Xposed  ( 3912): 	at java.lang.reflect.Method.invoke(Native Method)
10-14 07:15:58.072 E/Xposed  ( 3912): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
10-14 07:15:58.072 E/Xposed  ( 3912): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
10-14 07:15:58.072 E/Xposed  ( 3912): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
10-14 07:16:01.434 I/Xposed  ( 4132): YouTube: com.google.android.youtube 11.39.56 loaded!
10-14 07:16:01.434 I/Xposed  ( 4132): YouTube AdAway 3.4.0: Trying brute force way...
10-14 07:16:09.152 I/Xposed  ( 4132): YouTube AdAway: Successfully hooked ocg constructor!
10-14 07:16:09.154 I/Xposed  ( 4132): YouTube AdAway: Successfully hooked sequence: class =ocg methods a-b, param=mjs
10-14 07:16:51.041 E/Xposed  ( 6350): java.lang.NoSuchMethodError: bbw#a(boolean)#exact
10-14 07:16:51.041 E/Xposed  ( 6350): 	at de.robv.android.xposed.XposedHelpers.findMethodExact(XposedHelpers.java:337)
10-14 07:16:51.041 E/Xposed  ( 6350): 	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:178)
10-14 07:16:51.041 E/Xposed  ( 6350): 	at com.ceco.marshmallow.gravitybox.ModDialer24.init(ModDialer24.java:216)
10-14 07:16:51.041 E/Xposed  ( 6350): 	at com.ceco.marshmallow.gravitybox.GravityBox.handleLoadPackage(GravityBox.java:149)
10-14 07:16:51.041 E/Xposed  ( 6350): 	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:34)
10-14 07:16:51.041 E/Xposed  ( 6350): 	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:61)
10-14 07:16:51.041 E/Xposed  ( 6350): 	at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:106)
10-14 07:16:51.041 E/Xposed  ( 6350): 	at de.robv.android.xposed.XposedInit$1.beforeHookedMethod(XposedInit.java:93)
10-14 07:16:51.041 E/Xposed  ( 6350): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:314)
10-14 07:16:51.041 E/Xposed  ( 6350): 	at android.app.ActivityThread.handleBindApplication(<Xposed>)
10-14 07:16:51.041 E/Xposed  ( 6350): 	at android.app.ActivityThread.-wrap1(ActivityThread.java)
10-14 07:16:51.041 E/Xposed  ( 6350): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
10-14 07:16:51.041 E/Xposed  ( 6350): 	at android.os.Handler.dispatchMessage(Handler.java:102)
10-14 07:16:51.041 E/Xposed  ( 6350): 	at android.os.Looper.loop(Looper.java:148)
10-14 07:16:51.041 E/Xposed  ( 6350): 	at android.app.ActivityThread.main(ActivityThread.java:5417)
10-14 07:16:51.041 E/Xposed  ( 6350): 	at java.lang.reflect.Method.invoke(Native Method)
10-14 07:16:51.041 E/Xposed  ( 6350): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
10-14 07:16:51.041 E/Xposed  ( 6350): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
10-14 07:16:51.041 E/Xposed  ( 6350): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
10-14 07:42:42.242 I/XposedInstaller(20619): Downloaded http://dl.xposed.info/repo/partial/10409.xml.gz with status 0 (error: null), size 14324 bytes
10-14 07:42:42.492 I/XposedInstaller(20619): Updated repository http://dl.xposed.info/repo/full.xml.gz to version 10431 (13 new / 0 removed modules)
10-14 07:43:02.535 I/Xposed  (20915): Hook M constructor success

**Comment by Maxr1998** [comment]
@dave07747 this issue is known and also happens with the build.prop edit. Only Google can fix it.
Logs don't help me, as this issue isn't logged.
