### ISSUE TITLE
Google Assistant crashes on "Ok Google" settings screen

### ISSUE THREAD

**Issue by ElectronicWizard** [wasdennnoch/AndroidN-ify#1046]
I initially dismissed the Google Assistant's query to train the voice model.

When I later went back into settings to train it, the Google App crashes whenever I go to the setting area.
Specifically:
Google App -> Hamburger menu -> Settings -> Voice -> "OK Google" Detection [Crashes]

Logcat is [here](http://pastebin.com/raw/dkmfC0bx).

**Comment by Maxr1998** [comment]
Known, also happens with the build.prop edit. Google has to fix this.

**Comment by Jhackler** [comment]
It is happening to me on brand new phone after update it chrashes till reboot. I can use ok google once and for as long as I don't then so something else. As soon as I do I cant use it till restart
