### ISSUE TITLE
Settings App

### ISSUE THREAD

**Issue by Simi3000** [wasdennnoch/AndroidN-ify#1049]
Android N-ify crash when I try to open the main app.

**Comment by Maxr1998** [comment]
Provide logs please.

**Comment by Simi3000** [comment]
I new in this 😬 how can I get the log?

**Comment by Maxr1998** [comment]
Search for "how to take a logcat" on Google. There are millions of guides.

**Comment by Simi3000** [comment]
https://mega.nz/#!WlIzgDqJ!oHROQt942DeUy4qrJdcVdXKj5Lq-RmgBgSJqTxF8ePU

**Comment by Simi3000** [comment]
https://mega.nz/#!TlQCVQ6Q!7CTUhw0UtsSWMvJTmqzEcQX4SqI6Rpl84xGFl1-FGyc

**Comment by Simi3000** [comment]
https://mega.nz/#!755ElQrA!4XR8vgFq2HvagFyDSEZQGdiYkt_RJ87YREURq7SNHao

**Comment by Simi3000** [comment]
Is this what you want?

**Comment by Simi3000** [comment]
Fixed, I just Update.

**Comment by Maxr1998** [comment]
Ok, great :)
