### ISSUE TITLE
[Bug] Expand notification panel icon is misaligned

### ISSUE THREAD

**Issue by vemacs** [wasdennnoch/AndroidN-ify#105]
Android N-ify (button is too far up):

![](https://i.imgur.com/hcKgKfE.png)

Android N (button is vertically centered):

![](https://i.imgur.com/E7MHhUF.png)

**Comment by wasdennnoch** [comment]
I even mentioned it in the thread when releasing the snapshot ;)

**Comment by wasdennnoch** [comment]
And not the expand indicator but the QS itself are positioned too low.

**Comment by vemacs** [comment]
Ah, sorry, didn't see that.

**Comment by vemacs** [comment]
https://github.com/wasdennnoch/AndroidN-ify/commit/b2b93ea03bf213cbe4400a024632016268c144a3 fixed it.
