### ISSUE TITLE
How to enable Google Assistant?

### ISSUE THREAD

**Issue by JDWaghela** [wasdennnoch/AndroidN-ify#1050]
How to enable Google assistant ? Where is the option of toggle it ? After last update I m not able to view nougat Google assistant ? Which is right version ? And version of what ? System os or Google app version?

**Comment by Maxr1998** [comment]
I will enable Google Assistant by default again for next build.

**Comment by JDWaghela** [comment]
Yes I updated 702 . But not coming assistant yet .

**Comment by Maxr1998** [comment]
Then look at my latest post on XDA and read how to enable it.

**Comment by jahirfiquitiva** [comment]
Hey @Maxr1998 

I have the Google Assistant. I mean, it shows when I long press home button, but for some reason it doesn't remember my voice. And when I try to enter Google app Voice settings, the app crashes.

I even tried disabling the module, reconfiguring Google Voice recognition, and the re-enabling the module without success.

The only thing I haven't done is changing the build.prop lines ... Is that really needed? I mean, the Assistant still appears :/

Thanks

**Comment by JDWaghela** [comment]
Hey dude from where I can enable Google assistant. I can't find that in forum.xda. plz tell me here.

**Comment by JDWaghela** [comment]
Okay i found the feature. But it don't remember voice setting. Any help with that ?

**Comment by Maxr1998** [comment]
Read the FAQ [here](http://forum.xda-developers.com/showpost.php?p=69133065&postcount=11443).

**Comment by JDWaghela** [comment]
Thanks
