### ISSUE TITLE
System UI crashes on startup!

### ISSUE THREAD

**Issue by flyer13** [wasdennnoch/AndroidN-ify#1056]
First of all, thank you all folks for this beautiful Module 
second, I am using Galaxy Note 5 I tried #697,#698, #700 I got SystemUI popup message at the beginning.
I also tried to disabled "change No recent Image" but still crashing!!!
version 0.2.0 working well without any issues 
Here is my log
[logcat.txt](https://github.com/wasdennnoch/AndroidN-ify/files/530487/logcat.txt)

**Comment by prabhat00** [comment]
it occurs when switching from portrait to landscape, it can be fixed by disabling "Enlarge first row" setting in Quick Settings
[xposed_error_20161015_031458.txt](https://github.com/wasdennnoch/AndroidN-ify/files/530527/xposed_error_20161015_031458.txt)

**Comment by flyer13** [comment]
thanks Prabhatt00 for your help:)
I am sorry where can I find this "Enlarge first row" setting ?
So you mean after I disable this  option my problem "systemUI crash"  will be fixed? "
right now  I am using version 0.2.0.

**Comment by flyer13** [comment]
Ok I found the "Enlarge first row" setting :)
I'll try the latest version Now and back to you:)
thanks

**Comment by flyer13** [comment]
I just tried the #703 version with no luck again still crash!!!
![1](https://cloud.githubusercontent.com/assets/22845509/19404843/4308f06e-923f-11e6-8e1a-22a442e81e6f.jpg)

**Comment by wasdennnoch** [comment]
Nobody said it's fixed lol, you'll have to wait until the chagelog or any collaborator says that it's fixed ;)

**Comment by flyer13** [comment]
LoooooL, So do you recommend back to version 0.2.0 temporary?

**Comment by Maxr1998** [comment]
@flyer13 yes, roll back to a stable version for now.

**Comment by flyer13** [comment]
yes, I did back to version 0.2.0 now.
I really appreciate your support guys!
I hope my problem will be fixed soon:)

**Comment by wasdennnoch** [comment]
FYI you posted your Xposed log and not a logcat, there is a big difference. Your ROM seems to be stock Samsung based which means I don't officially support it. There is literally an error in every hook because Samsung made very big changes to the layouts and code and I won't be able to fix most of it. You can however ty to install GoodLock, a new SystemUI by Samsung which is closer to AOSP if it's working on your device.
