### ISSUE TITLE
System UI crash when switching from portrait to landscape with "Enlarge first row" enabled

### ISSUE THREAD

**Issue by prabhat00** [wasdennnoch/AndroidN-ify#1057]
this problem is solved when disabling "Enlarge first row" setting in Quick Settings.
the log file is attached.
[xposed_error_20161015_031458.txt](https://github.com/wasdennnoch/AndroidN-ify/files/530532/xposed_error_20161015_031458.txt)

**Comment by AidanRB** [comment]
I can confirm this, except it doesn't always FC.  It's kind of random.

**Comment by Maxr1998** [comment]
Thanks for the logs, they will be very helpful.

**Comment by cbdreinulldrei** [comment]
Can confirm this bug....

**Comment by Maxr1998** [comment]
Identified and fixed the issue: `[labelView()](https://android.googlesource.com/platform/frameworks/base/+/marshmallow-release/packages/SystemUI/src/com/android/systemui/qs/QSTileView.java#236)` in QSTileView was null, as `[recreateLabel()](https://android.googlesource.com/platform/frameworks/base/+/marshmallow-release/packages/SystemUI/src/com/android/systemui/qs/QSTileView.java#124)` only got called in `[setDual()](https://android.googlesource.com/platform/frameworks/base/+/marshmallow-release/packages/SystemUI/src/com/android/systemui/qs/QSTileView.java#180)` when changed was `true`.
