### ISSUE TITLE
No QS in lockscreen 

### ISSUE THREAD

**Issue by Mikeyangeleo** [wasdennnoch/AndroidN-ify#1059]
There are no QS tiles in the lock screen but if you pill again  you'll see the rest I'm using resurrection remix version 5.7.3 marshmallow thanks for future replies

**Comment by Maxr1998** [comment]
Disable the QS Editor in AndroidN-ify. If that doesn't help, disable the header styling. Custom ROMs are extremely difficult to support.

**Comment by Mikeyangeleo** [comment]
Please just look into it your solution helped but the animations and stuff look awful 😢😢🙏🙏

**Comment by wasdennnoch** [comment]
It's normal that there are no QuickQS on Lockscreen, enabling them would break the option to hide tiles on lockscreen.

**Comment by Mikeyangeleo** [comment]
OK thanks man for the advice
