### ISSUE TITLE
First row icon in Quick Settings getting stuck behind when full Quick Settings bar if expanded

### ISSUE THREAD

**Issue by soder82** [wasdennnoch/AndroidN-ify#1061]
Sometimes when I pull my status bar down to show all the settings in Quick Settings, the first row is getting stucked behind the expanded menu. A reboot fix this, until it happens again.

OnePlus One running COS 13.1.2 and build 704 of AndroidN-ify.

![http- 2f 2fuploads tapatalk-cdn com 2f20161015 2f120f60ee31574fbb960ab2c16bf04bc1](https://cloud.githubusercontent.com/assets/1496070/19410694/fedb7196-92f2-11e6-9f32-8ee8a9380232.jpg)
![http- 2f 2fuploads tapatalk-cdn com 2f20161015 2f219b57017a156fbcde3e4b2a5110347b](https://cloud.githubusercontent.com/assets/1496070/19410695/fedebce8-92f2-11e6-93da-e9798e693d75.jpg)

**Comment by wasdennnoch** [comment]
This happens when changing themes; did you change your theme before that happened (if possible on the ROM (what is COS?))?

**Comment by soder82** [comment]
Yeah, it's possible I did that. Trying to get that Nougat look. Someone
said the same on xda.

COS, CyanogenOS, running on OnePlus One.

/Söder

On Sat, Oct 15, 2016, 19:52 MrWasdennnoch <notifications@github.com> wrote:

This happens when changing themes; did you change your theme before that
happened (if possible on the ROM (what is COS?))?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/wasdennnoch/AndroidN-ify/issues/1061#issuecomment-253999737>,
or mute the thread

**Comment by wasdennnoch** [comment]
There's the problem, restart the SystemUI after a theme change. It's recommended to reboot after any theme change anyways.
