### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by JDWaghela** [wasdennnoch/AndroidN-ify#1062]
Why don't you use Gson and AsycHttpClient library .. it will reduce your code. ?

**Comment by wasdennnoch** [comment]
Add a huge library with many dependencies for one little HTTP request and three small JSON parsers? Way too overkill, it would bloat the apk unnecessarily.

**Comment by wasdennnoch** [comment]
It would reduce the code by maybe 40 lines on the cost of an apk being 1mb bigger.

**Comment by JDWaghela** [comment]
Ok nice logic.
