### ISSUE TITLE
Latest auto build no camera

### ISSUE THREAD

**Issue by ccxex29** [wasdennnoch/AndroidN-ify#1066]
Tried on Sony Stock MM ROM with Camera stock and Camera FV-5
blank. anybody also experience this issue? 2.0 works just fine with camera..
whats goin on?

**Comment by pwrusr** [comment]
Try disabling xposed or uninstal nify and check.. If problem persists.. Then something wrong with ur rom... As per my knowledge.. Nify won't mess with camera when u r on stock (:

**Comment by ccxex29** [comment]
I downgraded the N-ify to version 2.0 and the camera works as it should but not with latest jenkins build.. I'm gonna try stuffs a bit more to find out the reason

**Comment by pwrusr** [comment]
Update ur framework (:

**Comment by ccxex29** [comment]
I think restart strangely fixed the camera.. And probably the reason was the restart systemui.. Perhaps it's just not that perfect for sony roms afterall.
Thank you very much for the help.

**Comment by wasdennnoch** [comment]
Sometimes the Mediaserver crashes which causes the camera to be inaccessible, it's not related to Xposed.
