### ISSUE TITLE
-----SystemUI crash loop after boot LOGCAT ADDED! ----

### ISSUE THREAD

**Issue by JustAbasicForker** [wasdennnoch/AndroidN-ify#1067]
System UI fails to load up I'm presented with a black screen and my wallapaping fading in and out at times but can't get it to open up, I have to uninstall Xposed to get rid of it. im also running a stock Android rom. This is on the latest snapshot (works fine on the stable 2.0 version )  Thank you :)

**Comment by wasdennnoch** [comment]
You can get a logcat via your computer/adb. Google is your friend.

**Comment by JustAbasicForker** [comment]
Hi @wasdennnoch I got the log cat! but its way too big 
(about 25MB )! I will upload it on google drive so you can have look at it (its a lot of text! sorry for giving you such pain!) [https://drive.google.com/file/d/0B3DxmgQi3Qm-Y2o5TWNDbU5Xc0k/view?usp=sharing](url)
Thank you for your time! you are doing great!

**Comment by JustAbasicForker** [comment]
nobody?
