### ISSUE TITLE
not work 

### ISSUE THREAD

**Issue by flyinbed** [wasdennnoch/AndroidN-ify#1068]
Phone MI4 install ROM CM-13.0-20161015-NIGHTLY version , it start no work . and start AndroidN-ify ( version 705) application is force stop . .

**Comment by Maxr1998** [comment]
Install build 710 and try again. If it still gives issues, send me a log.

**Comment by wasdennnoch** [comment]
No response

**Comment by flyinbed** [comment]
sorry , long time not login github , i install last version 769 , is working  


Thinks you works :)

**Comment by Maxr1998** [comment]
Ok, thanks for reporting back.
