### ISSUE TITLE
Serious issue about Mobile data quick toggle

### ISSUE THREAD

**Issue by kulankit97** [wasdennnoch/AndroidN-ify#1069]
First of all this is my xposed log:-
https://drive.google.com/file/d/0B5UsJA5haW5oSlZRd2ozYU5QazQ/view?usp=drivesdk

When I click on 1st Sim icon on notification drawer, the second Sim icon gets expanded.. it should show data usage on 1st Sim in general use but it shows 2nd Sim data usage. Please fix this as soon as possible..

The problem still persists in build #704..

**Comment by wasdennnoch** [comment]
#657
