### ISSUE TITLE
状态栏第2层

### ISSUE THREAD

**Issue by Fly-World** [wasdennnoch/AndroidN-ify#1070]
作者您好，状态栏第2层WiFi蓝牙无法打开 ROM是CM12.1

**Comment by poxxz** [comment]
那啥，我不是作者

2016-10-17 19:50 GMT+08:00 Fly-World <notifications@github.com>:

**Comment by poxxz** [comment]
还有，作者不是中国人，反馈请用英语

2016-10-18 12:33 GMT+08:00 Capricornss Wu <wzj820109299@gmail.com>:

**Comment by Fly-World** [comment]
那能麻烦您帮我转告一下原作者吗？

**Comment by wasdennnoch** [comment]
I am the OP. And please use English when possible and explain your issue more detailed. If English is an issue you can also continue with Chinese if you really need to.

**Comment by poxxz** [comment]
我已经很久没用过插件了

2016年10月18日 13:32，"Fly-World" <notifications@github.com>写道：
