### ISSUE TITLE
Quick Setting icons move down when being retracted

### ISSUE THREAD

**Issue by pgmann** [wasdennnoch/AndroidN-ify#1072]
This happens when I retract the quick settings panel. I have a Moto G2 (titan) with CM13 installed. On a very rare occasion this **doesn't** happen, but not very often.

https://cloud.githubusercontent.com/assets/5852501/19438949/170b05d8-9474-11e6-8e9f-7104e34b60a5.png

**Comment by wasdennnoch** [comment]
It's because at first the notifications get moved upwards until one notification is fully readable before the QS get retracted. Without any notification it would work properly.

**Comment by pgmann** [comment]
An update - tested with build 733. It's now even more broken!

![screenshot_20161027-082317](https://cloud.githubusercontent.com/assets/5852501/19758190/e1ab575a-9c1e-11e6-84dd-6e06f101d7ba.png)

**Comment by pgmann** [comment]
@wasdennnoch Managed to get a screenshot without any notifications. This disproves your theory about why this happens.

![screenshot_20161101-154254](https://cloud.githubusercontent.com/assets/5852501/19895816/1e4e291a-a04a-11e6-81a6-0c7b0db438fd.png)

**Comment by wasdennnoch** [comment]
Still merge it into #995
