### ISSUE TITLE
Google assistant no longer works

### ISSUE THREAD

**Issue by dave07747** [wasdennnoch/AndroidN-ify#1075]
It's back to being Google now and that image recognition thing on long press home button. There's nothing notable in the xposed logs so I'll save your time and not post them. I think it's just a Google apps update that caused this, so could you look into getting around it again?

**Comment by Maxr1998** [comment]
It should be already fixed with build 709.

**Comment by dave07747** [comment]
Ah, just got the update, thank you for all the hard work!
