### ISSUE TITLE
Quick Reply

### ISSUE THREAD

**Issue by Simi3000** [wasdennnoch/AndroidN-ify#1076]
It's possible to force whatsapp to use Android N app version features? Like on Google Now, that Android N-ify enable Google Assistant.
'Cause this option (I think) would improve Quick Reply Function.

*I know you are going to close this Issue, (because is not an Issue)

**Comment by Maxr1998** [comment]
Not really. The WhatsApp code is heavily obfuscated, and one obfuscated app is really enough for me..

**Comment by Simi3000** [comment]
What about replace Whatsapp Notifications with other ones that are shown individually?
I know one app that does it...
