### ISSUE TITLE
Ya no modifica nada 

### ISSUE THREAD

**Issue by belcebu666** [wasdennnoch/AndroidN-ify#1078]
Desde la versión 620 el módulo no funciona en Lollipop lg g3 Stylus no modifica pero desde la 602 si modifica ,podria arreglarlo

**Comment by Maxr1998** [comment]
Nobody of the devs speaks Spanish, try to translate your issue. Please also provide more information and logs.

**Comment by belcebu666** [comment]
In the news updates it produces a closing Sistem ui resulting brick a
solution that happens from versión 620 forward and toggles are removed from
the build in 0.2.0 works

**Comment by wasdennnoch** [comment]
We need a logcat recorded during the SystemUI crash to fix it and more info about your device.

**Comment by belcebu666** [comment]
as I can send a logcat truth Nose lot of that where active? and is a g3 lg
stylus with ROM AOSP 5.0.2 Android pure was checking and the reply does not
work the status bar either and new updates as 602 per there are quick
toggles no longer appear only when I put it on automatic rotation but now
they appear no longer hide use of version 0.2.0 the most stable will send
screen shots the first two are currently using that says System ui does not
work is the 703

**Comment by wasdennnoch** [comment]
Still need a logcat.
