### ISSUE TITLE
Bug when turning off mobile data

### ISSUE THREAD

**Issue by el70** [wasdennnoch/AndroidN-ify#1079]
Running Fulmics 6.5 Rom on LG G3. With latest version of N-ify (709) and Google app (6.7.13.21 arm) I get the Google Assistant working and everything is good.  However, if I turn mobile data off, the phone crashes and the message: "System.UI has stopped working" appears over and over. I need to go back to TWRP recovery, wipe everything and restore from a previous backup to get the phone working again.

**Comment by Mewtaseem** [comment]
I also receive this issue. My device is the BLU R1 HD running the stock rom (build v12).

**Comment by kb3wmh** [comment]
Also have this issue on the R1 HD. However, you don't need to wipe the phone, N-ify can be uninstalled from TWRP

**Comment by Maxr1998** [comment]
Please supply logs. This could be a duplicate of #1063, but I don't know.

**Comment by wasdennnoch** [comment]
No response
