### ISSUE TITLE
Voice Search icon disappeared

### ISSUE THREAD

**Issue by Eva850** [wasdennnoch/AndroidN-ify#1081]
Each time I reboot my device the Voice Search icon disappears. I have to restore it with proper pm enable command. If it is intentional, can you make possible to have Voice Search and Google Assistant enabled at one time?

**Comment by Maxr1998** [comment]
Do you mean the voice search icon in Pixel Launcher? How did you enable it?

**Comment by Eva850** [comment]
My device is Xperia Z5 with stock launcher. I have to execute pm enable 'com.google.android.googlequicksearchbox/com.google.android.googlequicksearchbox.VoiceSearchActivity' each time I reboot my device

**Comment by Eva850** [comment]
On build #754 and newer issue seems to be fixed.
