### ISSUE TITLE
None of the Experimental features working plus Lock Screen is Unusable

### ISSUE THREAD

**Issue by anjneyM** [wasdennnoch/AndroidN-ify#1082]
The Experimental features are not working.The SELINUX is set to Permissive and other "Customizations"
work.
The lock screen has become SUPER LAGGY, It is unusable.

**Comment by anjneyM** [comment]
[Logcat.txt](https://github.com/wasdennnoch/AndroidN-ify/files/545621/Logcat.txt)

**Comment by wasdennnoch** [comment]
Please post your Xposed log. Do you have said experimental features activated? Are ou on a snapshot build?

**Comment by anjneyM** [comment]
[error.log.zip](https://github.com/wasdennnoch/AndroidN-ify/files/561265/error.log.zip)

**Comment by anjneyM** [comment]
Yes 
I have activated everything
I'm on a CM Nightly (was that your question?)

**Comment by anjneyM** [comment]
Sorry for late reply though...

**Comment by anjneyM** [comment]
Before you ask,
I'm using version 6.6.21.21.arm of the google app 
Official CM 13 Nightly

**Comment by wasdennnoch** [comment]
Preferences are unreadable, this has already been reported.

**Comment by anjneyM** [comment]
I've changed SELinux to permissive
