### ISSUE TITLE
WiFi tile isn't working and misaligned with 712 build 

### ISSUE THREAD

**Issue by pwrusr** [wasdennnoch/AndroidN-ify#1086]

**Comment by solirf** [comment]
Same here with xperia Z5 mm

**Comment by solirf** [comment]
Also when i apply any theme brightness bar gose hidden 

Same with 713

**Comment by pwrusr** [comment]
Brightness bar * It's been there frm 0.2 
# Sys ui restart needed whenever u apply a new theme... Though it's annoying (:

**Comment by Maxr1998** [comment]
Should be fixed now.

**Comment by pwrusr** [comment]
No expand arrow? As u said in xda

**Comment by Maxr1998** [comment]
Yes.

**Comment by pwrusr** [comment]
Okay...Thanq  (:
