### ISSUE TITLE
Build 717, edit tiles got totally disappeared or empty 

### ISSUE THREAD

**Issue by pwrusr** [wasdennnoch/AndroidN-ify#1089]
On Android L.

**Comment by pwrusr** [comment]
Android L

**Comment by pwrusr** [comment]
[xposed_error_20161024_004122.txt](https://github.com/wasdennnoch/AndroidN-ify/files/546568/xposed_error_20161024_004122.txt)
 I mean.. Every tile in edit page

**Comment by Simi3000** [comment]
Tap the Eddit button in landscape

**Comment by paphonbth** [comment]
Fixed with #1098
