### ISSUE TITLE
Hangouts Direct Reply doesn't work without Android Auto

### ISSUE THREAD

**Issue by I3anter** [wasdennnoch/AndroidN-ify#1090]
Hangouts direct reply doesn't exist at all. There's only one reply button that takes to the default MM reply popup. I don't know what to really send other than a screenshot so tell me if you that one...

**Comment by Maxr1998** [comment]
It works fine for me. Try to install the Android Auto app.

**Comment by I3anter** [comment]
Yep, it's working with Android Auto, but do I need to keep it on my phone to have it work?

**Comment by Maxr1998** [comment]
Yes, I think so. AndroidN-ify extracts the RemoteInput from the Android Auto parts of the notification, which only seem to get passed when the app is installed.

**Comment by Maxr1998** [comment]
I'll keep this issue as reminder, but as labelled, this is a wontfix. I can't use another way to enable direct reply in Hangouts.
