### ISSUE TITLE
Play music picture problem

### ISSUE THREAD

**Issue by DDCOON** [wasdennnoch/AndroidN-ify#1092]
When I'm using this module,
 song picture is very small. Mentioned, that this bug is only in Play Music, in others players it working perfectly.

![screenshot_20161024-020739](https://cloud.githubusercontent.com/assets/16988740/19630649/c57f8aca-998e-11e6-9bc6-4333b52760b7.png)

**Comment by Simi3000** [comment]
Go to the notification settings in N-ify, tap the 'app blacklist' and add(toggle) the Google music app.

**Comment by Maxr1998** [comment]
Like @Simi3000 said. Blacklisting the app will make the notification look fine.

**Comment by DECHTECH** [comment]
I'd just like to add this also happens with the Cyanogenmod Music app (Eleven), but only in the lock screen (For me anyway, running Google Style v1 rom for Sony Xperia Z3 and Android N-ify snapshot 721).
![screenshot_20161024-202711 1](https://cloud.githubusercontent.com/assets/23028669/19641766/c2a04470-9a29-11e6-9854-5fc2302ab5fd.png)

**Comment by wasdennnoch** [comment]
#744
