### ISSUE TITLE
 Opening battery settings from Quick Settings (using GB) crashes the settings app.

### ISSUE THREAD

**Issue by Adrianrff** [wasdennnoch/AndroidN-ify#1093]
This happens in build 721, updated a few minutes ago and the previous build as well. 

If I open the battery settings using quick settings, the settings app will crash. The first time it happened I though it may have something to do with experimental features, so I disabled them (don't use them anyway) and rebooted. Then I tried accessing battery settings from the settings app (homescreen shortcut rather) and it worked. But trying from the quick tiles caused the settings app to crash again. Every subsequent attempt to access the battery settings, regardless of where I'm accessing from, has the same result. 

It only happens with the battery settings app, every other section in settings seems ok. 

[xposed_error_20161023_204351.txt](https://github.com/wasdennnoch/AndroidN-ify/files/546770/xposed_error_20161023_204351.txt)

**Comment by Adrianrff** [comment]
UPDATE:
I just connected the charger and disconnected it while later and the problem dissappeared. No idea what went on, probably not related to N-ify. 

I will update if I find anything relevant.

**Comment by Adrianrff** [comment]
Update 2:

It's back at it again. Issue persists.

**Comment by wasdennnoch** [comment]
I need a logcat for the crash.

**Comment by iChronos** [comment]
I think is the same that the one I sent you yesterday, my full settings crashed everytime I tried to see battery usage

**Comment by Adrianrff** [comment]
Here you go

[2016-10-24-13-03-09.txt](https://github.com/wasdennnoch/AndroidN-ify/files/548514/2016-10-24-13-03-09.txt)

**Comment by wasdennnoch** [comment]
It's the same cash as the second one in #1103, so I'll close this.

```
10-24 13:02:37.945 E/AndroidRuntime(26860): java.lang.IllegalArgumentException: text cannot be null
10-24 13:02:37.945 E/AndroidRuntime(26860): 	at android.graphics.Paint.measureText(Paint.java:1545)
10-24 13:02:37.945 E/AndroidRuntime(26860): 	at com.android.settings.fuelgauge.BatteryHistoryChart.onMeasure(BatteryHistoryChart.java:634)
10-24 13:02:37.945 E/AndroidRuntime(26860): 	at android.view.View.measure(View.java:18794)
```
