### ISSUE TITLE
Dual sim issues

### ISSUE THREAD

**Issue by kulankit97** [wasdennnoch/AndroidN-ify#1094]
First of all this is my xposed log:-
https://drive.google.com/file/d/0B5UsJA5haW5oSlZRd2ozYU5QazQ/view?usp=drivesdk

When I click on 1st Sim icon on notification drawer, the second Sim icon gets expanded.. it should show data usage on 1st Sim in general use but it shows 2nd Sim data usage. Please fix this as soon as possible..

The problem still persists in build #721..

**Comment by wasdennnoch** [comment]
You posted it twice, #1029 is the one with more info though.
