### ISSUE TITLE
Bugs in 7.1 style headers

### ISSUE THREAD

**Issue by sargijeh** [wasdennnoch/AndroidN-ify#1097]
there are some misalignments here :)
xposed log attached down below :)
![screenshot_2016-10-24-15-26-06](https://cloud.githubusercontent.com/assets/22320438/19644818/bfbef236-99fe-11e6-8026-c25ad86c8c3d.png)
[xposed_error_20161024_152321.txt](https://github.com/wasdennnoch/AndroidN-ify/files/547675/xposed_error_20161024_152321.txt)

**Comment by rockmacaca** [comment]
I'll also add that there is too much empty space the the expanded view above the brightness slider, it seems like the space where the collapsed QS toggles are doesn't collapse.

Also, QS tiles in the header are missing in the expanded lock screen notifications view.

**Comment by sargijeh** [comment]
@rockmacaca I don't have lockscreen issue and also I think above brightness slider it should be that much empty space because it will seem weird :-S

**Comment by rockmacaca** [comment]
ok. Here's a screenshot of the issue I'm talking about:
![Screenshot](https://lh3.googleusercontent.com/XRf5zxDopQLSRKdzgbNrWe5n_9gx2geBdOE7o5ZRJkfJ6VY2cXtjpO1UoaeqWF6HDayB-_A5wHhveQ=w548-h974-no)

The QS panel expands fine with everything in place (minus the animation)

**Comment by wasdennnoch** [comment]
Built 723 should already have fixed this.

**Comment by sargijeh** [comment]
@wasdennnoch I don't have disappearing bug, but others which I posted about are not fixed

**Comment by rockmacaca** [comment]
Sorry, I should have provided more info.

Moto X Pure on 6.0 (Moto's stock rom)
N-ify #723

**Comment by wasdennnoch** [comment]
The disappearing tile on lock screen are no bug, it's a security measurement. See #816. I'll remove the related posts to keep it clean.

**Comment by kurtextrem** [comment]
on my device the date has disappeard - oneplus one.

**Comment by wasdennnoch** [comment]
On screens smaller than a specific size the date gets put below the clock, only visible when you expand the panel.

**Comment by kurtextrem** [comment]
Oh okay. I guess this comes from Google? 
At least I am annoyed by it, as there is enough space next to it...

**Comment by kurtextrem** [comment]
Oh okay. I guess this comes from Google?
At least I am annoyed by it, as there is enough space next to it...

**Comment by wasdennnoch** [comment]
Do you have the QS editor enabled? If not everything should be fixed now.

**Comment by sargijeh** [comment]
@wasdennnoch I tried everything, still it clip he date from buttom and it can be seen on "AUG" :( I'm on  build 755

**Comment by DavidMKD** [comment]
@wasdennnoch I did have it enabled previously, right now it's disabled and the bug is gone but the gap is still there above brightness slider and the provider name and clock are too high placed

**Comment by wasdennnoch** [comment]
The clock is placed perfectly, but the provider name hould be higher now. Please send a screenshot of the issue.

**Comment by DavidMKD** [comment]
It's kinda like the clock is higher than the date and on the second screenshot, should there be a date next to the clock? 

@wasdennnoch 
![screenshot_2016-11-05-22-55-32](https://cloud.githubusercontent.com/assets/13114412/20033856/283c724c-a3ab-11e6-948e-93c337da7b86.png)


![screenshot_2016-11-05-22-58-05](https://cloud.githubusercontent.com/assets/13114412/20033864/65fa95c8-a3ab-11e6-946a-02d43c77acc1.png)

**Comment by wasdennnoch** [comment]
Nope. On smaller screens the date gets put below the clock. There is an option to force the old behaviour though.

**Comment by sargijeh** [comment]
Why dis you closw this? My screen is 6.44", but date ia clipped on months like august it can be seen!

**Comment by DavidMKD** [comment]
Here, now, at last everything is good but I kinda wish the clock had a bigger font/size

**Comment by wasdennnoch** [comment]
You didn't mention any clipped date. But that's also open in another issue.

**Comment by kurtextrem** [comment]
@wasdennnoch Thank you so much for implementing the option. :)
