### ISSUE TITLE
question

### ISSUE THREAD

**Issue by baibaibai666** [wasdennnoch/AndroidN-ify#1099]
i can't use the button of the wifi select on the information plat in the newest vertion722

**Comment by Maxr1998** [comment]
You mean the WiFi quick settings tile? Could you elaborate?

**Comment by rockmacaca** [comment]
I may have had this issue once a couple days ago, I managed to fix it by clearing cache and/or updating to one of the newer builds.

**Comment by wasdennnoch** [comment]
No response
