### ISSUE TITLE
Tiles Disappeared #723 ; RR 5.5.9 (5.1.1)

### ISSUE THREAD

**Issue by jerryshaw12** [wasdennnoch/AndroidN-ify#1100]
But if I disabled edit tiles option, the stock tiles shown up and edit button accessible???

Here's logcat, Xposed log and screenshot
https://drive.google.com/folderview?id=0B3TzmNRa2nE6ZGJVbGdwWWJxMkE

**Comment by wasdennnoch** [comment]
I fixed the crash in the log, does it work with the newest build?

**Comment by ch3mn3y** [comment]
725 still crashes

**Comment by wasdennnoch** [comment]
@ch3mn3y A SystemUI crash is different from disappearing tiles, opdn a new issue if you have SystemUI crashes. Don't forget a logcat then.

**Comment by jerryshaw12** [comment]
It's still disappeared, do I need to upload framework and system UI?

**Comment by jerryshaw12** [comment]
The new logs uploaded in same link

**Comment by hrsong99** [comment]
This happens for me as well. I have a OnePlus x running the latest Paranoid Android (6.0.2) and no QS tiles and normal tiles show up for me.
