### ISSUE TITLE
lp crash build 720 logs attached

### ISSUE THREAD

**Issue by arunverma833** [wasdennnoch/AndroidN-ify#1104]
Tried build 720 but got crash sir 
Logs here
https://drive.google.com/file/d/0BwWvDiQ04VutWVBiY2I3VFdQclk/view?usp=docslist_api
Missing this mod sir
Ty

**Comment by wasdennnoch** [comment]
We surely love this issue because it's always a bit different on every ROM ;)
Are you on LP mor MM? Also which ROM / Phone?
```
E/AndroidRuntime( 5280): Process: com.android.systemui, PID: 5280
E/AndroidRuntime( 5280): java.lang.IllegalArgumentException: method com.android.systemui.statusbar.SignalClusterView.setMobileDataIndicators [XposedOriginal] argument 9 has type int, got java.lang.Boolean
E/AndroidRuntime( 5280):        at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
E/AndroidRuntime( 5280):        at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:334)
E/AndroidRuntime( 5280):        at com.android.systemui.statusbar.SignalClusterView.setMobileDataIndicators(<Xposed>)
```

**Comment by arunverma833** [comment]
Sir I  am on cm 12.1 device xperia s 
Thx for ur reply sir

**Comment by wasdennnoch** [comment]
Are you sure you used 720? Can you please try the latest build again? (but be prepared if it still loops)

**Comment by arunverma833** [comment]
Yes sir tried the latest build sir but got no luck :-(

**Comment by arunverma833** [comment]
Any update sir

**Comment by wasdennnoch** [comment]
Do you have the prefs not readable warning? Because it really should work guessing from the code.

**Comment by arunverma833** [comment]
Sorry didn't understand sir 
What u expect from me sir logs ? I can provide from latest build 😜😋😛

**Comment by wasdennnoch** [comment]
I don't expect any logs, I just asked if you get the prefernce warning.

**Comment by arunverma833** [comment]
No sir I just having system ui stopped during boot 
Need help

**Comment by arunverma833** [comment]
Sir u r insane u fixed lp crash with latest build 
Thanks sir 
Keep up
