### ISSUE TITLE
Glitch/lag in QS animation on LP

### ISSUE THREAD

**Issue by Freewander10** [wasdennnoch/AndroidN-ify#1105]
There's an annoying glitch in QS animation when expanding QS tiles. The animation isn't as smooth as it should be. 
Xposed logs:

[xposed_error_20161024_120154.txt](https://github.com/wasdennnoch/AndroidN-ify/files/548499/xposed_error_20161024_120154.txt)

Logcat:
[Log_2016-10-24_11-58-58.txt](https://github.com/wasdennnoch/AndroidN-ify/files/548511/Log_2016-10-24_11-58-58.txt)

**Comment by wasdennnoch** [comment]
There are no errors in the log. Describe "smooth", does it stutter when expanding? Are you on Exodus?

**Comment by Freewander10** [comment]
Maybe it's the frame rate. I'm going to try and make a video.
Yes, it stutters a bit. 
And another yes, I'm still on Exodus.

**Comment by wasdennnoch** [comment]
A bit of stuttering is normal as Xposed isn't very efficient. But as long as it doesn't drop below 15fps it should be ok.
