### ISSUE TITLE
Please look into cmte roms 

### ISSUE THREAD

**Issue by Mikeyangeleo** [wasdennnoch/AndroidN-ify#1107]
Bro please can you just look into cyanogenmod theme engine roms it has a lot of bugs the edit icon is super small, no QS tiles in the lock screen, system ui crash on boot, please bro 🙏🙏all the cmte engine users would really appreciate it I'm using rr 5.7.3 marshmallow

**Comment by Mikeyangeleo** [comment]
This is my system please take a look at it thanks 

https://drive.google.com/file/d/0B2aRWo5suZT8X2tDUGptRkhwc0k/view?usp=drivesdk

**Comment by wasdennnoch** [comment]
I'm on RR 5.7.4 without any issues. Weird. No tiles on lock screen are intended, I need a logcat captured during the crash to fix it.

**Comment by Mikeyangeleo** [comment]
I've found a way to manage it and the size of the edit icon increased, don't know why and as for the system ui crash I managed it with screen rotation thanks bro all that remains is the space above the QS header thanks man
