### ISSUE TITLE
Fancy Animation Gets Cut Off

### ISSUE THREAD

**Issue by I3anter** [wasdennnoch/AndroidN-ify#1108]
If I leave Fancy quick settings animation on, the little tiles get obstructed by something during the animation, only when styling notifications is off. I use a CM Android Nougat theme since I like the look of notifications better on that, and just got introduced to this bug as soon as I reboot from unchecking that option. 

Log: https://drive.google.com/file/d/0B0alOOiqE1ZkNmxJNHpQQ3hhaVU/view?usp=sharing
Video: https://goo.gl/photos/WdYMtWoxMwhoC3Gt6

**Comment by wasdennnoch** [comment]
The expand button also doesn't work, right?

**Comment by wasdennnoch** [comment]
Fixed with 8f6d7dd0ed3a77ec8c026df44d7ceda65d6c1136
