### ISSUE TITLE
Android N-ify Module Is Not Activated

### ISSUE THREAD

**Issue by Lebogang95** [wasdennnoch/AndroidN-ify#1113]
So, Basically !
I Have The
HUAWEI MT7-L09 
Android Version : 6.0 (EMUI 4.0)
Super Su Systemless Flashed
Xposed Systemless Installed
Latest Version Of Android N-ify Module Is Installed
The Problem ?
Well It Says Module Is Not Activated... Really Frustrating Because It Seems Like Huawei Phones Are Just Useless In Terms Of These Things Or Did I Do Something Wrong ?
Oh And No Logs Are Available From Xposed As Well, I Have Restarted A Million Times And Stuff.

**Comment by wasdennnoch** [comment]
Looks like Xposed isn't activated properly. Do other modules work? Also make sure to wait a bit after installing and before rebooting. Make sure the module is activated in the installer. Apart from that I can't help you, if these things don't work you have ask in the official Xposed XDA thread.

**Comment by Lebogang95** [comment]
I Believe So Too
I Have Other Modules Installed Which Don't Really Work. I Figured It Was Because Of The Fact That I Don't Have (Pure) Stock Android And Instead A "Heavily Modified" Version Of It. 
But Now With This Not Activated Issue I'm Starting To Believe That Xposed Is Not Activated Properly
But Thanks !

**Comment by wasdennnoch** [comment]
That's probably the case if other modules don't work either.

**Comment by Lebogang95** [comment]
![screenshot_2016-10-25-22-24-00](https://cloud.githubusercontent.com/assets/23060221/19703028/775c09a2-9b02-11e6-9a08-0aba7656108a.png)

Weird Because This Is The Case

**Comment by RouNNdeL** [comment]
I see that you are using a Systemless Xposed version, have you installed flashed Magisk (it is required when using a systemless xposed)?

**Comment by Lebogang95** [comment]
![screenshot_2016-10-26-05-15-07](https://cloud.githubusercontent.com/assets/23060221/19712106/3fd39dea-9b3b-11e6-8d43-aa191cf7e24c.png)
Yup!

**Comment by RouNNdeL** [comment]
Weird, I don't know what else could cause that issue then

**Comment by Lebogang95** [comment]
Solved.
Turns Out, As I Figured That Huawei Phones, Of Any Phones Actually Running EMUI 3.1 & 4.0 Require A Little Bit More Than Just Flashing Xposed. 
So Here Is What I Did
First You Need To Disable Resource Hooks If It Is Enabled On Xposed
Then Proceed To Modifying : local.prop For EMUI 4.0 I'm Not So Sure On EMUI 3.1
You Can Find The Local.prop By Following This
System/emui/base/prop/local.prop
Edit The Local Prop As Follows 
ro.config.hwtheme=0
Then After That Flash Xposed Systemless
Then Flash Xposed Official
I'm Not Sure On What Flashing The Systemless Does But I Figured It Would Contribute To Keeping My Phone Out Of A Bootloop
To Edit The Local.prop You Need Root Browser
Cheers
