### ISSUE TITLE
Notification,breaks down qs animation with latest builds

### ISSUE THREAD

**Issue by pwrusr** [wasdennnoch/AndroidN-ify#1115]
Qs animation breaks down with the arrival of notifications

**Comment by wasdennnoch** [comment]
I totally know what the issue is now...

**Comment by pwrusr** [comment]
Qs animation lags for a moment or scattered while expanding or collapsing qs pannel.. Example... If I get any msg or notification like some apps update or watsap msg or even while playing music... Expanding the qs pannel appears to be glitchy

**Comment by wasdennnoch** [comment]
That's normal as the SystemUI has to recreate the notification layout and then it gets hooked with Xposed which isn't very efficient performance-wise.
