### ISSUE TITLE
Suggestion to include the Android Neko easter egg

### ISSUE THREAD

**Issue by kushalchauhan98** [wasdennnoch/AndroidN-ify#1118]
Could you please include the new cat-collecting easter egg (Android Neko) ?
[http://www.androidauthority.com/android-7-0-nougat-dev-preview-5-easter-egg-703847/](url)

**Comment by Embraser01** [comment]
👍 I had the same idea so I made a version compatible LP+ (tested only on MM). 

It's not complete, I had to move the Tile to a persistent Notification (realy ugly)... I'm hoping to use a Tile from AndroidN-ify or GravityBox one day.
If you want to take a look : 
[https://github.com/Embraser01/Android-NekoLand](https://github.com/Embraser01/Android-NekoLand)

**Comment by kushalchauhan98** [comment]
The feature is included in the latest build now. Thumbs up to the devs! I am closing the issue now.
