### ISSUE TITLE
Package parse error

### ISSUE THREAD

**Issue by GeoZac** [wasdennnoch/AndroidN-ify#1119]
The build 739 shows a parse error on installation on RR 6.0.1,verified with multiple downloaders and networks 
MD5 26d9ca66e61ab5ce2041295a55e28f7a

SHA
d454884d7b96a98590e4dac93ed1113b4c129b00

**Comment by pwrusr** [comment]
Uninstal all previous versions > reboot > Install snapshot >reboot... No luck?  OK then let's try this... install 0.2 > reboot >Install snapshot on it > reboot (:

**Comment by GeoZac** [comment]
How would me uninstalling an app fix the corrupted apk build on a remote server.if possible report back md5 checksum of latest build(739)

**Comment by GeoZac** [comment]
Some unrelated issue on device
