### ISSUE TITLE
SystemUI Crash on Sony Xperia Z5 Stock MM 6.0.1

### ISSUE THREAD

**Issue by korom42** [wasdennnoch/AndroidN-ify#1121]
This started from build #724 and still in latest #739. It happens right when unlocking the device after a boot. I found that it can be temporay fixed by closing all notifications from lockscreen then unlocking, but when any notification comes SystemUI crashes again.
PS: Note that  most xperia devices have a notification on boot when "Mobile Data" are disabled

[xposed_error_20161026_120422.log.txt](https://github.com/wasdennnoch/AndroidN-ify/files/553049/xposed_error_20161026_120422.log.txt)

**Comment by Eva850** [comment]
I have the same issue, it happens when there is a notification or when app displays toast message. I am also on 6.0.1 Xperia Z5

**Comment by Eva850** [comment]
http://pastebin.com/GDqVNru9
Logcat of crash

**Comment by ohayoubaka** [comment]
I also experience the same issue on my Xperia XZ on stock MM 6.0.1, since build #731. When a notification appears, SystemUI repeatedly crashes until the notification is cleared.

**Comment by ohayoubaka** [comment]
Here's a logcat
[logcat.txt](https://github.com/wasdennnoch/AndroidN-ify/files/560006/logcat.txt)

**Comment by francescosabia** [comment]
me have the same issue too..i use moonwalker rom

**Comment by thesmart1** [comment]
Same issue on Xperia X 6.0.1

**Comment by wasdennnoch** [comment]
#1147
