### ISSUE TITLE
system ui crash Blu studio c 5+5 

### ISSUE THREAD

**Issue by Jamadz15** [wasdennnoch/AndroidN-ify#1123]
the system ui of my phone crashes and the screen is on black since latest builds, i was able to get this xposed log, hope it can help, my phone is lollipop mediatek 6582, here i attached logs 

[error.log.old.txt](https://github.com/wasdennnoch/AndroidN-ify/files/554640/error.log.old.txt)
[error.log.txt](https://github.com/wasdennnoch/AndroidN-ify/files/554641/error.log.txt)

**Comment by wasdennnoch** [comment]
I need a logcat for crashes.

**Comment by Jamadz15** [comment]
sorry for the delaying, here is the logcat with 771 build 
[logcat.txt](https://github.com/wasdennnoch/AndroidN-ify/files/587493/logcat.txt)

**Comment by wasdennnoch** [comment]
There is no SystemUI crash in the log.

**Comment by Jamadz15** [comment]
I tried to read The logcat and i didn't see the crash neither but once I installed n-fy and reboot the screen is black all the time so I can't access to anything

**Comment by Jamadz15** [comment]
So I don't understand what happens, what else could I to make?

**Comment by wasdennnoch** [comment]
Well, you can still connect your phone to a computer and take a logcat via adb I guess,

**Comment by Jamadz15** [comment]
Well I've tried but I haven't been able to make it work but I'm gonna try to see if I can get it this time
