### ISSUE TITLE
Weird fancy animation

### ISSUE THREAD

**Issue by sujyoth99** [wasdennnoch/AndroidN-ify#1124]
The fancy transition animation always animates weirdly on my phone. I have even tried using the default theme and rebooting but the issue persists since the introduction of these animations. Is there a fix?

**This is the video of the animation (Theme - Flux):**
https://youtu.be/X0mma5iq9nY

**This is the video of the animation (Theme - Default):**
https://youtu.be/6YNn0T9ks70

I am using CM13 on a Moto X Play

**Logs:**

10-26 22:55:22.047 I/Xposed (12709): -----------------
10-26 22:55:22.047 I/Xposed (12709): Starting Xposed version 86, compiled for SDK 23
10-26 22:55:22.047 I/Xposed (12709): Device: XT1562 (Motorola), Android version 6.0.1 (SDK 23)
10-26 22:55:22.047 I/Xposed (12709): ROM: cm_lux-userdebug 6.0.1 M4B30X a4a0bb533e test-keys
10-26 22:55:22.047 I/Xposed (12709): Build fingerprint: motorola/lux_retasia_ds/lux_uds:5.1.1/LPD23.118-10/14:user/release-keys
10-26 22:55:22.047 I/Xposed (12709): Platform: armeabi-v7a, 32-bit binary, system server: yes
10-26 22:55:22.047 I/Xposed (12709): SELinux enabled: yes, enforcing: yes
10-26 22:55:22.074 I/Xposed (12709): -----------------
10-26 22:55:22.074 I/Xposed (12709): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
10-26 22:55:22.232 I/Xposed (12709): Detected ART runtime
10-26 22:55:22.240 I/Xposed (12709): Found Xposed class 'de/robv/android/xposed/XposedBridge', now initializing
10-26 22:55:22.803 I/Xposed (12709): Loading modules from /data/app/tk.wasdennnoch.androidn_ify-1/base.apk
10-26 22:55:22.876 I/Xposed (12709): Loading class tk.wasdennnoch.androidn_ify.XposedHook
10-26 22:55:22.900 I/Xposed (12709): [Android N-ify] [INFO] XposedHook: Version jenkins-AndroidN-ify-739 (6)
10-26 22:55:22.900 I/Xposed (12709): [Android N-ify] [INFO] XposedHook: Automated Build; Version: 739
10-26 22:55:22.900 I/Xposed (12709): [Android N-ify] [INFO] XposedHook: Build Time: 2016-10-26T05:11Z
10-26 22:55:22.900 I/Xposed (12709): [Android N-ify] [INFO] XposedHook: Git SHA: e8ffa8e346002fab9f21e694f5b9de1646c66f82
10-26 22:55:22.908 I/Xposed (12709): [Android N-ify] [INFO] XposedHook: Experimental features enabled
10-26 22:55:22.908 I/Xposed (12709): [Android N-ify] [INFO] XposedHook: ---- Device info ----
10-26 22:55:22.908 I/Xposed (12709): [Android N-ify] [INFO] XposedHook: SDK Version: 23
10-26 22:55:22.908 I/Xposed (12709): [Android N-ify] [INFO] XposedHook: Build ID: cm_lux-userdebug 6.0.1 M4B30X a4a0bb533e test-keys
10-26 22:55:22.909 I/Xposed (12709): [Android N-ify] [INFO] XposedHook: Manufacturer: Motorola
10-26 22:55:22.909 I/Xposed (12709): [Android N-ify] [INFO] XposedHook: Brand: Motorola
10-26 22:55:22.909 I/Xposed (12709): [Android N-ify] [INFO] XposedHook: Model: XT1562

**Comment by jackbuehner** [comment]
Have you tried using six quick settings tiles instead of five? The updated layout uses the layout from the Pixel phones, which use six quick settings tiles.

Change it in Android N-ify>Quick Settings>QS tiles to show.

**Comment by sujyoth99** [comment]
I did just that but the issue persists. I guess it's got something to do with my ROM.

**Comment by wasdennnoch** [comment]
#995
