### ISSUE TITLE
Battery QS  tile does not stay expanded

### ISSUE THREAD

**Issue by Freewander10** [wasdennnoch/AndroidN-ify#1125]
When clicking on the battery tile in the QS screen, it expands for a fraction of a second, then collapses. 
Xposed Logs:
[xposed_error_20161027_203226.txt](https://github.com/wasdennnoch/AndroidN-ify/files/557420/xposed_error_20161027_203226.txt)
Catlog:

[Log_2016-10-27_20-30-39.txt](https://github.com/wasdennnoch/AndroidN-ify/files/557423/Log_2016-10-27_20-30-39.txt)

**Comment by Freewander10** [comment]
Also, the Battery quick toggle tile in the notifications header animates from the wrong direction/place when being expanded. 
Xposed Logs:
[xposed_error_20161027_204433.txt](https://github.com/wasdennnoch/AndroidN-ify/files/557427/xposed_error_20161027_204433.txt)
Catlog:
[Log_2016-10-27_20-45-36.txt](https://github.com/wasdennnoch/AndroidN-ify/files/557429/Log_2016-10-27_20-45-36.txt)

**Comment by wasdennnoch** [comment]
#418
