### ISSUE TITLE
The unknown space

### ISSUE THREAD

**Issue by Mikeyangeleo** [wasdennnoch/AndroidN-ify#1126]
You should look into the space above the brightness slider when QS is expanded find a way to remove it and the WhatsApp quick reply stuff is somehow I know bbm does not support quick response tho and you can't reply from lock screen because of the unlock icon and sometimes settings crashes but its not a problem to me using resurrection remix version 5.7.3 😊😊😊😊

**Comment by Rodav10** [comment]
Paphonb has stated in the original commit,
'Known bug:
The huge space above brightness slider is a known issue. I can't find a way to solve it yet."

**Comment by Mikeyangeleo** [comment]
OK take your time
