### ISSUE TITLE
Notification Header battery icon missing

### ISSUE THREAD

**Issue by sulaiman20** [wasdennnoch/AndroidN-ify#1127]
Hi Sir, the battery icon on notification header is missing. Pls assist.

**Comment by wasdennnoch** [comment]
Have you ever seen screenshots of N?!

**Comment by sulaiman20** [comment]
There is battery icon right in android CM14 upon pulling down notification panel.

**Comment by wasdennnoch** [comment]
There is a battery tile but no "real" battery icon.

**Comment by sulaiman20** [comment]
Ok Sir, maybe I have overlooked. Apologies and thanks for your reply.
