### ISSUE TITLE
System UI crash with new notification, also enlarge first two items in qs stops working

### ISSUE THREAD

**Issue by eng3** [wasdennnoch/AndroidN-ify#1130]
System UI will force close with every new notification.  Also, the enlarge first two items on qs stops working after installing nify even enabling option. Without nify it works, after installing it does not. Stable version it works even without selecting the option

**Comment by eng3** [comment]
[Log_2016-10-30_08-17-33.txt](https://github.com/wasdennnoch/AndroidN-ify/files/560663/Log_2016-10-30_08-17-33.txt)

**Comment by wasdennnoch** [comment]
Crash already got fixed.
