### ISSUE TITLE
When i reicive a notification system ui crashes

### ISSUE THREAD

**Issue by francescosabia** [wasdennnoch/AndroidN-ify#1138]
[2016-10-31-19-22-44.txt](https://github.com/wasdennnoch/AndroidN-ify/files/562549/2016-10-31-19-22-44.txt)

**Comment by DDCOON** [comment]
Had same on my marshmallow, go to settings - display - turn off ambient display.

**Comment by francescosabia** [comment]
My ambient display is already turned off :(

Il 03 nov 2016 4:10 AM, "K-K-Kramer here." <notifications@github.com> ha
scritto:

**Comment by paphonbth** [comment]
No error info found in logs.

**Comment by francescosabia** [comment]
What can i do?😞

Il 03 nov 2016 11:59 AM, "paphonbth" <notifications@github.com> ha scritto:

**Comment by paphonbth** [comment]
Make sure the crash happens while you're capturing logcat.

**Comment by francescosabia** [comment]
Yes it was..but i ll try again

Il 03 nov 2016 12:01 PM, "paphonbth" <notifications@github.com> ha scritto:

**Comment by numeprenume** [comment]
This is the same issue as #1121 and #1117 .

**Comment by francescosabia** [comment]
Yes i know but there is no fix

Il 03 nov 2016 2:35 PM, "Victor" <notifications@github.com> ha scritto:

**Comment by francescosabia** [comment]
ok here it is another logcat. i hope there will be a fix
[2016-11-03-16-38-36.txt](https://github.com/wasdennnoch/AndroidN-ify/files/569409/2016-11-03-16-38-36.txt)

**Comment by wasdennnoch** [comment]
Merge into #1138, same crash.
