### ISSUE TITLE
Header bugs since #739

### ISSUE THREAD

**Issue by Buarzej** [wasdennnoch/AndroidN-ify#1139]
Tile editor is always on even if i turn it off (and it doesn't work by the way, my tiles are not saved when i exit from it).
Plus time and date on the header is covering the network provider name (look at the screenshot)

![_20161101_082220](https://cloud.githubusercontent.com/assets/23185058/19882256/8aae314c-a00c-11e6-81fb-5f503248816b.JPG)

[2016-10-31-19-22-44.txt](https://github.com/wasdennnoch/AndroidN-ify/files/563548/2016-10-31-19-22-44.txt)

**Comment by wasdennnoch** [comment]
Edit icon will be fixed soon, overlap is #1097
