### ISSUE TITLE
Googlee Assistentt not Working

### ISSUE THREAD

**Issue by EstoyMejor** [wasdennnoch/AndroidN-ify#1142]
At first, I'm so sorry if this question is dump in anyway but, I installed The modul on my HTC One M8 with the newest cyanogenmod. And still I cant use the new assistant, I can't even find it anywhere in the settings. Do I have a false version or somehting?

Thanks 
Marvin R.

**Comment by wasdennnoch** [comment]
Please search in the XDA thread.
