### ISSUE TITLE
Problem on EMUI

### ISSUE THREAD

**Issue by RisingFireStar** [wasdennnoch/AndroidN-ify#1144]
I have EMUI 3.1 android 5.1 and it doesn't work on my device (Huawei Y5 II)

Plz fix it.

**Comment by wasdennnoch** [comment]
Define "doesn't work" and attach your Xposed log or a logcat in case of crashes.

**Comment by RisingFireStar** [comment]
I have no crashes, it just don't works, it not changes my quick settings, settings, notifications, pretty mush everything, the only one thing that works, it's doble tap on "recents" button.

**Comment by wasdennnoch** [comment]
Most probably because MIUI changed the hell out of the layout, it doesn't look like AOSP at all. There's no way to put the new look on top of it.

**Comment by RisingFireStar** [comment]
EMUI not MIUI, and I seen some videos on YT, that on some of Huawei devices works your project.

**Comment by wasdennnoch** [comment]
But it almost liiks like MIUI. Ever seen some screenshots of vanilla Android?

**Comment by RisingFireStar** [comment]
Seen, and I used it, and I hate EMUI ui, and that's why I was trying to use your project. 
There is really you can't do something to make it work on EMUI?

**Comment by wasdennnoch** [comment]
Nope, it's even worse than TouchWiz, it has no similarity to vanilla Andorid at all.

**Comment by RisingFireStar** [comment]
Ugh... Alright tnx.
