### ISSUE TITLE
*----NO SYSTEM UI ON BOOT----*

### ISSUE THREAD

**Issue by JustAbasicForker** [wasdennnoch/AndroidN-ify#1146]
Opened a new issue after nobody replying to the old one. :/
Here's the logcat  https://drive.google.com/open?id=0B3DxmgQi3Qm-Y2o5TWNDbU5Xc0k 
Issue is: after the boot animation is done I get a black screen and nothing happens, I only get my wallpaper fading in and out at times. I get no system UI crashed error message, only the black screen.

ONLY HAPPNES ON SNAPSHOT BUILDS.
PS. if the logcat doesn't show what you need please tell me. I don't know what time to start the logcat (I did it as soon as I saw the boot animation)

Thank you

**Comment by wasdennnoch** [comment]
You don't have to open new ones, it doesn't change that I'm currently not actively developing :p

**Comment by JustAbasicForker** [comment]
Ah okay.

**Comment by wasdennnoch** [comment]
Ah yes, we love that issue as every ROM changes something. Which Android version and ROM are you using?
```
java.lang.IllegalArgumentException: method com.android.systemui.statusbar.policy.CallbackHandler.setMobileDataIndicators [XposedOriginal] argument 13 has type int, got java.lang.Boolean
	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:334)
	at com.android.systemui.statusbar.policy.CallbackHandler.setMobileDataIndicators(<Xposed>)
```

**Comment by JustAbasicForker** [comment]
Android 6.0 and a generic vanilla Android rom

**Comment by wasdennnoch** [comment]
Because I totally know what's ment with "a generic vanilla Android rom"

**Comment by JustAbasicForker** [comment]
It's just a AOSP 6.0 MM rom

**Comment by JustAbasicForker** [comment]
No one gain? 😐

**Comment by wasdennnoch** [comment]
It can't be AOSP because the AOSP method only has 10 arguments while the crash talks of the 13th one.

**Comment by JustAbasicForker** [comment]
@wasdennnoch It is a an (MTK) AOSP rom, it looks like stock android there are no skins over the UI. Maybe it the dual sims thing is messing it up? the problem is with the data indicator right? the data indicator is always on (4G icon is always on regardless if the data is on or off) on my launcher the data indicator and Wi-Fi icon doesn't change to grey when I pull my app drawer up. (pixel launcher) maybe there something wrong with that.
