### ISSUE TITLE
GB produces empty QS pages (CLOSED)

### ISSUE THREAD

**Issue by FreakyEnderman** [wasdennnoch/AndroidN-ify#1148]
Gravity box tiles (when they are disabled) still looks like they are capturing places up in quick settings.

**Comment by wasdennnoch** [comment]
Planning to add better GB support soon™.

**Comment by FreakyEnderman** [comment]
Good to hear that. Your job is hard man the big update feels like it is never going to be out. There is still a lot to improve. If I had money I'd definitely donate but unfortunately I don't even have a credit card. I hope we will see nice things soon. (Like expanding notifications just like in nougat.)

**Comment by FreakyEnderman** [comment]
Since GB support update the problem has been solved.
