### ISSUE TITLE
Missing "Clear all" text in the recent.

### ISSUE THREAD

**Issue by bebolint98** [wasdennnoch/AndroidN-ify#1150]
I use the latest build 747 build but the "Clear all" text is missing. I can able to clear the recent but there is no text. It started from about 2-3 build. Xiaomi Redmi Note 3 Pro CM13
![screenshot_20161105-163544](https://cloud.githubusercontent.com/assets/10884664/20031400/25561cb0-a377-11e6-9b0d-ab5c9eb9050d.png)

**Comment by FreakyEnderman** [comment]
Same with my Xperia (in xperia you won't be able to access the button because of the "small apps" bar)

**Comment by bebolint98** [comment]
@wasdennnoch So I try to find out which is the latest build where the "clear all" text not missing and that this build is **718**. It possible to make something with this, bring it back? And the last two build the 775 and 776 the clock is missing from the lockscreen, and when I pull down the noticication panel there are no tiles everything is missing from. I hope also this bugs is fixed. Thanks in advanced!

**Comment by wasdennnoch** [comment]
Fixed with 136b394b3e7671390bdd8cbc47e66f29a53b22d8
