### ISSUE TITLE
Few icon and date misplacement

### ISSUE THREAD

**Issue by DavidMKD** [wasdennnoch/AndroidN-ify#1156]
I have a problem with the latest build on Xperia M2 running 5.1.1 LP on build 754. The screenshot shows it all. I've also attached a log

EDIT: The provider name is fixed in 755, The pencil icon and the empty space between the brightness slider is there

Xposed Log:
http://www34.zippyshare.com/v/AKrmRlrQ/file.html

Screenshot:

 ![screenshot_2016-11-05-22-19-13](https://cloud.githubusercontent.com/assets/13114412/20033673/802a38cc-a3a6-11e6-82de-a806cebe08d2.png)

**Comment by wasdennnoch** [comment]
#1097
