### ISSUE TITLE
One Plus 3 recents Lockscreen.

### ISSUE THREAD

**Issue by SensehacK** [wasdennnoch/AndroidN-ify#1157]
**Description**
I have a Problem with it.. Every time i click on my recent apps button my Oneplus 3 turns black for a second and then sends me to lockscreen. 

So I have temporarily found a fix which is disable "Large Recent apps" , so after that One plus 3 doesn't crash with recents button or double tap to lockscreen asking for pin.
Oxygen OS 3.2.6

**Module version (build version)**

**Xposed log / logcat**

**Comment by wasdennnoch** [comment]
#680
