### ISSUE TITLE
Wrong shadow in app screenshot in recents

### ISSUE THREAD

**Issue by BlackGhost12** [wasdennnoch/AndroidN-ify#116]
![screenshot_2016-05-09-11-23-17](https://cloud.githubusercontent.com/assets/19236621/15107487/b0742738-15d8-11e6-9225-1b1435b44ac9.png)

**Comment by BlackGhost12** [comment]
![screenshot_2016-05-09-11-21-34](https://cloud.githubusercontent.com/assets/19236621/15107535/eadc6c3c-15d8-11e6-9ba1-90001a01dad9.png)
![screenshot_2016-05-09-11-21-34](https://cloud.githubusercontent.com/assets/19236621/15107544/f939d530-15d8-11e6-923d-2bd14ea47412.png)

**Comment by BlackGhost12** [comment]
[xposed_error_20160509_112938.zip](https://github.com/wasdennnoch/AndroidN-ify/files/254552/xposed_error_20160509_112938.zip)

**Comment by wasdennnoch** [comment]
Sooo... where's the exact problem? First one is the not full width volume panel.

**Comment by BlackGhost12** [comment]
The problem does not seem to be 1 second after you open a new tab and yes volume panel is not full.

**Comment by wasdennnoch** [comment]
You mean the horizontal lines on the google tab screenshot?

**Comment by BlackGhost12** [comment]
Yes, they have a new tab, but recent applications seem like they're getting better after a few seconds ago when I went to the screen. Or is it a problem right?

**Comment by BlackGhost12** [comment]
Sorry Google Translate 😀

**Comment by wasdennnoch** [comment]
I think I know what you mean ;)

**Comment by BlackGhost12** [comment]
Thanks 😊

**Comment by wasdennnoch** [comment]
Do you still get these lines in the recents? It looks like nobody else gets them.

**Comment by BlackGhost12** [comment]
![sketch-1463295159414](https://cloud.githubusercontent.com/assets/19236621/15272482/d64b5b26-1a82-11e6-983d-41a56a013164.png)

**Comment by BlackGhost12** [comment]
Unfortunately still it is going on. Perhaps my device or are due to be Android 5.1. Another who did not see such a problem isn 't it? I hope in the meantime can not be understood using google translation turn the most happening thing I can agree.

**Comment by BlackGhost12** [comment]
[Video_20160515103352061_by_videoshow.zip](https://github.com/wasdennnoch/AndroidN-ify/files/264870/Video_20160515103352061_by_videoshow.zip)

**Comment by BlackGhost12** [comment]
Maybe it's because of this problem Lollipop. Or can I use the Custom Rom. Installed also be sourced from another module.

**Comment by BlackGhost12** [comment]
Developers do not have it in closing I'll raise a root application or version probably because I use Rom.

**Comment by BlackGhost12** [comment]
@wasdennnoch

**Comment by BlackGhost12** [comment]
Marsmallow fixed.
