### ISSUE TITLE
Editing toggles in Full Notification Panel on Oxygen OS not possible.

### ISSUE THREAD

**Issue by SensehacK** [wasdennnoch/AndroidN-ify#1160]
**Description**
" ^ " This icon gets drawn over the " Edit " icon
We can't edit the toggles or re-arrange them in any order.
Screen shot  : https://goo.gl/photos/Fa997Lqd7T5S7G2j9
Oxygen OS.3.2.6 Android M.
One Plus 3.
**Module version (build version)**

**Xposed log / logcat**

**Comment by wasdennnoch** [comment]
I like how nobody has filled in th information in the prefilled form yet.
But it's obvious that you are using the modue version 0.2.0, the header layout already got improved in snapshot builds. There's also the new QS editor, but it seems to fail on OOS so you don't see any toggles at all. We're on it as soon as we get a deodexed SystemUI (you can try to deodex yours too, to would help everyone on OOS). So the issue you're describing is already fixed.

**Comment by SensehacK** [comment]
Thanks for such a quick reply. I'm also excited to run Google Assistant soon. :) keep up the good work.
