### ISSUE TITLE
"Apps with usage access" crashes Settings app

### ISSUE THREAD

**Issue by neurosutras** [wasdennnoch/AndroidN-ify#1161]
**Description**
Rooted CM13 with xPosed 86. "Settings - Security - Apps with usage access" yields "Unfortunately, settings has stopped". Disabling N-ify restores the function. 
**Module version (build version)**
756
**Xposed log / logcat**
--------- beginning of main
[ 11-06 07:14:48.686  7833: 7833 W/System   ]
ClassLoader referenced unknown path: /data/app/org.jtb.alogcat-1/lib/arm
[ 11-06 07:15:41.561  7833: 7833 W/InputEventReceiver ]
Attempted to finish an input event but the input event receiver has already been disposed.

**Comment by alexandrumarcel** [comment]
Do you have Drawer enabled in Experimental Features? If yes is the same with my issue https://github.com/wasdennnoch/AndroidN-ify/issues/1159

**Comment by wasdennnoch** [comment]
Please attach the whole log as a file.

**Comment by neurosutras** [comment]
He's right. Problem resolves when I disable the Settings drawer experimental feature.
