### ISSUE TITLE
Notification pull down not showing toggles

### ISSUE THREAD

**Issue by licaon-kter** [wasdennnoch/AndroidN-ify#1163]
Xperia 5.1.1

Starting with build 743 (this commit: https://github.com/wasdennnoch/AndroidN-ify/commit/db3f78e20a21f234e4d09e7027e71b76445e5aa3 ) pull down on the notification area does not make the second level Quick Toggles appear. I can even pull it down until the icons appear in place but once I raise the finger they go back up right away.

Pulling down on the top part (the one with the date/clock/cog/arrow) works as expected.

Also, after recording it started working as intended, on a reboot it will behave badly again.

I need "fancy animations" because of #1165

Video: 
https://mega.nz/#!QYZGWbwK!ziT3C3pYYPuZvsgsqxex8Luo6DfAhfSgNt8Ynvk6J30

Logcat: https://gist.github.com/licaon-kter/a98a88140272e7c1966b8e7842abff83

/PS: Any timeframe for some proper detailed debug info in logs?

**Comment by wasdennnoch** [comment]
That'a bug (?) in Andorid itself not caused by the module. You can't drag down the panel when you drag it by the "no notifications" text (The "hitbox" of the text is larger, it fills the whole width).

**Comment by licaon-kter** [comment]
So it's an Android bug that appeared after a certain n-ify commit? Umm strange.

I pull it like that all the time, and now, after that commit, it takes a while and it will recover to that behaviour.

**Comment by wasdennnoch** [comment]
On stock M the text is smaller (well, the "hitbox" because it has less top padding) so you might not have noticed it that much. But I already had this issue before I created this module and friends on stock devices without any modifications too.
