### ISSUE TITLE
Question: What to do when Xposed doesn't read N-Ify settings?

### ISSUE THREAD

**Issue by jahirfiquitiva** [wasdennnoch/AndroidN-ify#1167]
**Description**

I would like to know what else can one do to make Xposed read this module settings. I already tried rebooting, reinstalling the app, deleting cache/data, and I made sure SELinux was set to `Permissive`. The problem still persists.

What I can't understand is how other modules can work without this "restriction".

Also, I would like to know what else can one do to make this work properly, besides those things. I mean, there must be something one could do, or not?

Please help me. Thanks in advance.

**Module version (build version)**
Build 757

**Comment by Freewander10** [comment]
I made a post [here](http://forum.xda-developers.com/xposed/modules/xposed-android-n-ify-features-t3345091/post69311723) about the order of installation. Seems to have helped a few persons. You can check it out and see if it works for you too.

**Comment by licaon-kter** [comment]
I'm seeing a lot off boot loops when upgrading N-ify...

But on point, what I do:
* install/activate
* setup
* use a root aware file manager (eg. Total Commander), navigate to `/data/data/tk.wasdennnoch.androidn_ify/shared_files` and for that XML I change permissions from 660 (RW-RW----) to 666 (RW-RW-RW-)
* reboot

**Comment by Freewander10** [comment]
No. Those aren't the correct permission. Change them to 664 or 777.

**Comment by licaon-kter** [comment]
Why would you give eXecutable rights!?

**Comment by jahirfiquitiva** [comment]
@Freewander10 
Thanks it worked. Followed the installation steps and changed permissions to 777. After some reboots and trial-error, I had it working.

Btw, I still think developers should do something about this, because other modules work fine.

**Comment by Freewander10** [comment]
@licaon-kter because it probably won't work if you don't. I can't specifically say why it requires it though. 
But if you want to get it working without changing permissions. Check out the link I posted earlier to the post on xda. And follow those instructions. 

@jahirfiquitiva no problem bro. 
And MrWasdennnoch is already working on that.

**Comment by wasdennnoch** [comment]
The snapshots should already set the permissions to 0664, but apparently that doesn't work right yet.
