### ISSUE TITLE
Quick setting tiles invisible on Oxygen OS 3.2.x

### ISSUE THREAD

**Issue by Chronus-23** [wasdennnoch/AndroidN-ify#1168]
Device: Oneplus 3 A3003,  
OS: Oxygen OS 3.2.7 STABLE
**Description**: Quick settings on notification shade are missing. They are visible when in edit mode, but any amount of editing does not work to make them show up. 
**EDIT**: With QS Fancy animations enabled, the collapsed QS bar icons are visible, With Fancy animations disabled, the collapsed bar also goes missing. <-- This is issue #1165

**Module version (build version)**: Currently on Build 758, but issue is prevalent since Build 632 onwards. 

**Xposed log**: https://mega.nz/#!x1RhXARZ!wF14WsuDaRpvG1AVVWmZ2jiwRi9hU_DrOLP5qDZeLlI
**Video**: https://mega.nz/#!B8ZhnTSC!MSFr78O94jCnNuErhg2KfvRQdVU6vczmoe4lI3rd7ME

**Comment by licaon-kter** [comment]
2 thoughts:
* when you get link from Mega, get "link+key"
* does it get fixed if you enable "fancy animations"?

**Comment by Chronus-23** [comment]
Thankyou, OT, but what's the difference between link and link+key?

Fancy animation are already enabled. I disabled them and rebooted, and this hasn't fixed the issue. The error logs say something about not being able to find the icons where it should.

**Comment by licaon-kter** [comment]
We need they

**Comment by Chronus-23** [comment]
@licaon-kter Thanks. That was pretty idiotic of me. I have updated the links. Maybe this provides more information to anyone working on it. I saw on the other issue that logs weren't available.

**Comment by wasdennnoch** [comment]
#912
