### ISSUE TITLE
Partial Screenshot Not Working

### ISSUE THREAD

**Issue by alexandrumarcel** [wasdennnoch/AndroidN-ify#1170]
I'm using Beanstalk ROM [Based on CM13] and I when I'm doing a screenshot I don't get any option to select what I want to use in my screenshot. I have the Partial Screenshot enabled in Experimental Features.

Here is my Xposed Log.

[xposed_error_20161108_153337.txt](https://github.com/wasdennnoch/AndroidN-ify/files/578308/xposed_error_20161108_153337.txt)
 
And this is what I get inside that log file:

> 11-08 15:33:25.521 E/Xposed  (30527): Caused by: java.lang.ClassNotFoundException: com.android.systemui.screenshot.TakeScreenshotService$1
11-08 15:33:25.521 E/Xposed  (30527): 	at java.lang.Class.classForName(Native Method)
11-08 15:33:25.521 E/Xposed  (30527): 	at java.lang.Class.forName(Class.java:324)
11-08 15:33:25.521 E/Xposed  (30527): 	at external.org.apache.commons.lang3.ClassUtils.getClass(ClassUtils.java:823)
11-08 15:33:25.521 E/Xposed  (30527): 	at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:62)
11-08 15:33:25.521 E/Xposed  (30527): 	... 18 more
11-08 15:33:25.521 E/Xposed  (30527): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.android.systemui.screenshot.TakeScreenshotService$1" on path: DexPathList[[zip file "/system/priv-app/SystemUI/SystemUI.apk"],nativeLibraryDirectories=[/system/priv-app/SystemUI/lib/arm64, /vendor/lib64, /system/lib64]]
11-08 15:33:25.521 E/Xposed  (30527): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
11-08 15:33:25.521 E/Xposed  (30527): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
11-08 15:33:25.521 E/Xposed  (30527): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
11-08 15:33:25.521 E/Xposed  (30527): 	... 22 more
11-08 15:33:25.521 E/Xposed  (30527): 	Suppressed: java.lang.ClassNotFoundException: Didn't find class "com.android.systemui.screenshot.TakeScreenshotService$1" on path: DexPathList[[dex file "/data/dalvik-cache/xposed_XResourcesSuperClass.dex"],nativeLibraryDirectories=[/vendor/lib64, /system/lib64]]
11-08 15:33:25.521 E/Xposed  (30527): 		at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
11-08 15:33:25.521 E/Xposed  (30527): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
11-08 15:33:25.521 E/Xposed  (30527): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
11-08 15:33:25.521 E/Xposed  (30527): 		... 23 more
11-08 15:33:25.521 E/Xposed  (30527): 		Suppressed: java.lang.ClassNotFoundException: com.android.systemui.screenshot.TakeScreenshotService$1
11-08 15:33:25.521 E/Xposed  (30527): 			at java.lang.Class.classForName(Native Method)
11-08 15:33:25.521 E/Xposed  (30527): 			at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
11-08 15:33:25.521 E/Xposed  (30527): 			at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
11-08 15:33:25.521 E/Xposed  (30527): 			at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
11-08 15:33:25.521 E/Xposed  (30527): 			... 24 more
11-08 15:33:25.521 E/Xposed  (30527): 		Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
11-08 15:33:25.926 W/Xposed  (30527): Package name for /data/app/tk.wasdennnoch.androidn_ify-1/base.apk had to be retrieved via parser
11-08 15:33:28.246 W/Xposed  (18995): Package name for /data/app/tk.wasdennnoch.androidn_ify-1/base.apk had to be retrieved via parser
11-08 15:33:28.248 W/Xposed  (18974): Package name for /data/app/tk.wasdennnoch.androidn_ify-1/base.apk had to be retrieved via parser

**Comment by Maxr1998** [comment]
Thanks, Beanstalk uses an extra class `ScreenshotHandler` for the handler. Will fix.

**Comment by wasdennnoch** [comment]
Fixed with 7fbab02eebc129826ea037f893f3ea2f70fae072 :P
