### ISSUE TITLE
Question: is that normal?

### ISSUE THREAD

**Issue by ranielcsar** [wasdennnoch/AndroidN-ify#1175]
I'm using CM13 but with stock theme, not dark."device default" theme is dark on n-ify.
![screenshot_20161108-165242](https://cloud.githubusercontent.com/assets/20558676/20116127/37dc7e34-a5e2-11e6-8105-9b6ae795b51e.png)

**Comment by wasdennnoch** [comment]
The device default theme uses the `android:Theme.DeviceDefault` theme without modifications. This theme changes with themes and can be themed by the ROM itself. So yes, this theme appears to be normal. Theme.

Ok seriouly, it uses what the ROM gives it.
