### ISSUE TITLE
Probable SystemUI crash on updating to build 764 on near vanilla LP.

### ISSUE THREAD

**Issue by sayak-brm** [wasdennnoch/AndroidN-ify#1176]
### Probable SystemUI crash on updating to build 764 on near vanilla LP.

_Build 764 (6) from Jenkins_

The Wallpaper keeps appearing and disappearing. No statusbar, lockscreen, navbar, etc.
Only the power menu appears. Problem disappears after disabling xposed, disabling module and then re enabling Xposed.

**Problem doesn't exist on build 763.**

Screenshots: 
![screenshot_2016-11-09-09-51-18](https://cloud.githubusercontent.com/assets/5992716/20127820/e617abf0-a668-11e6-909a-8f4205f0187e.png)
![screenshot_2016-11-09-09-54-11](https://cloud.githubusercontent.com/assets/5992716/20127821/e6238240-a668-11e6-804a-3a9d326710f0.png)
![screenshot_2016-11-09-09-51-13](https://cloud.githubusercontent.com/assets/5992716/20127822/e62b356c-a668-11e6-959a-ec76d88b3d0f.png)

Xposed Logs:
[log.zip](https://github.com/wasdennnoch/AndroidN-ify/files/579986/log.zip)

**Comment by chakflying** [comment]
Nothing displays except the power menu after boot up on build 764.
Oneplus 3 OOS, android 6.0.1

**Comment by wasdennnoch** [comment]
A logcat is required for crashes.

**Comment by licaon-kter** [comment]
Seeing this on Xperia 5.1.1 too.

Strange that on the first try (no other module active) it started fine, baring #1181 I guess, that might be a clue.
So after that successful boot I enabled QS EDITING and rebooted, to a black screen apparently (yes I had no wallpaper). I can use the Power Menu though.

**Comment by mranzy** [comment]
The system ui keeps happening when enabling QS Editor on cm12

**Comment by KyleMHB** [comment]
I have this too with a Samsung Galaxy S6 Edge+ (Wanam Xposed isntalled) with Audax 12.0 Rom (6.0.1)

**Comment by LosTigeros** [comment]
Log: https://drive.google.com/file/d/0B5IKSY3sCuE9WGZabnlrZnhfT1E/view?usp=drivesdk

**Comment by wasdennnoch** [comment]
As I said, a logcat is requird... captured during the crash...

**Comment by mranzy** [comment]
Here's the logcat:
[logcatonboot.txt](https://github.com/wasdennnoch/AndroidN-ify/files/587275/logcatonboot.txt)

**Comment by sayak-brm** [comment]
To @wasdennnoch : @mranzy has uploaded the logcat. Probably the right time to remove the `LOG PLS`
 tag.

**Comment by wasdennnoch** [comment]
@mranzy's log seems to be from MM. Which ROM are you using? I still need a LP log.
