### ISSUE TITLE
Nothing changed after instalation

### ISSUE THREAD

**Issue by dfire86** [wasdennnoch/AndroidN-ify#1180]
Hi im using galaxy note 4 N910G
after installing the module it didnt change the look at all
Settings drawer is the same
Notification icons the same (but with fancy alignment ) 
No crashes or error msgs

Pls help me with this.

**Comment by wasdennnoch** [comment]
Version?

**Comment by dfire86** [comment]
N ify ver. 0.2.0 on Android 6.0.1

**Comment by wasdennnoch** [comment]
There's your problem. You have to install a snapshot build.

**Comment by dfire86** [comment]
You mean cynogenmod rom???

**Comment by alexandrumarcel** [comment]
@dfire86 he means this: https://ci.paphonb.xyz/jenkins/job/AndroidN-ify/

Uninstall the old module and install this. To use all the features pres the "I" icon from the top left and then keep pressing the "N" logo util you enable experimental features tab :)

**Comment by dfire86** [comment]
Thanks i installed the stable version as u mentioned . But it gave me a system ui error .
Anyway thanks alot
