### ISSUE TITLE
Volume panel tile doesn't show up in QS

### ISSUE THREAD

**Issue by Freewander10** [wasdennnoch/AndroidN-ify#1182]
The volume panel tile does not show up in the QS panel after its added and the system ui is restarted. There's only a blank space left where it is supposed to be. 
[xposed_error_20161109_133136.txt](https://github.com/wasdennnoch/AndroidN-ify/files/581675/xposed_error_20161109_133136.txt)
![screenshot_2016-11-09-13-30-17](https://cloud.githubusercontent.com/assets/21367316/20151873/e77e36dc-a689-11e6-8c66-f958c33274b0.png)

![screenshot_2016-11-09-13-30-55](https://cloud.githubusercontent.com/assets/21367316/20151939/2a0f9130-a68a-11e6-9d14-ef87771d4f8b.png)

1st Screenshot: when it is initially added in the editor screen. 
2nd screenshot: after the editor is closed and a reboot is done or the system ui is restarted.

**Comment by wasdennnoch** [comment]
Is the tile available without N-ify? If it's available in the editor it doesn't mean your ROM actually natively supports it which leads to this behavior.

**Comment by Freewander10** [comment]
It's available in the stock QS editor so the ROM supports it. 
![screenshot_2016-11-10-11-38-00](https://cloud.githubusercontent.com/assets/21367316/20185585/a30f5a74-a73a-11e6-8b6c-6c9ba76a2f49.png)

**Comment by Freewander10** [comment]
On a different ROM
Issue no longer exists
