### ISSUE TITLE
Screen turning on and off after activating N-ify..

### ISSUE THREAD

**Issue by d3nni** [wasdennnoch/AndroidN-ify#1183]
Using the latest Snapshot build. On my S6 with the Noble A8 Stock Port including GraceUX.

**Module version (build version)**
- 764 (6)

**Xposed log / logcat**
- https://drive.google.com/file/d/0B2ookYerp0lFLUhvZEZXRnlDbUk/view?usp=drivesdk

I'm  not sure if you can help me to get it running but maybe worth a try. :)

Thanks!

**Comment by wasdennnoch** [comment]
I need a logcat. Note that (Close-)Stock Samsung isn't supported, I'll take a look at the log but I'll decide whether I'll do something with it.

**Comment by Abhi1245** [comment]
Same problem plz help me
