### ISSUE TITLE
System UI crash on recent 

### ISSUE THREAD

**Issue by vitogor** [wasdennnoch/AndroidN-ify#1184]
**Description**
OnePlus x running running Android 6.0.1 Xposed v 86.
When click resent. It crashes and says system UI crash.

**Module version (build version)**

**Xposed log / logcat**

**Comment by vitogor** [comment]
OnePlus x running running Android 6.0.1 Xposed v 86.
When click resent. It crashes and says system UI crash.

Love how it looks in notification. Good job.

**Comment by wasdennnoch** [comment]
Did you even read the template or the issue guidelines?
