### ISSUE TITLE
Brightness slider height, setting icon

### ISSUE THREAD

**Issue by niaboc79** [wasdennnoch/AndroidN-ify#1186]
Hi, 

Here's a few issues on all latest builds. 

The brightness slider should be higher. Also the animation when the notification panel is closed is not correct. On android 7.1 the brightness slider is fading out only, he doesn't move up.

The setting icon should be smaller.

**Comment by paphonbth** [comment]
Yep. There are some bugs about the new QS panel.
The huge space isn't going to get fixed soon because of some layout differences between M and N. But I'll try.

**Comment by paphonbth** [comment]
Fixed with 447e7c9.
