### ISSUE TITLE
System ui crash on Alcatel Fierce XL 

### ISSUE THREAD

**Issue by 0verrid3** [wasdennnoch/AndroidN-ify#1188]
I installed the latest version of N-Ify that I found on here and the system ui wouldn't work

Android version 5.1.1, Xposed v86.1

[<!--](url
[alogcat.2016-11-10-09-20-14-0500.txt](https://github.com/wasdennnoch/AndroidN-ify/files/583625/alogcat.2016-11-10-09-20-14-0500.txt)
)

**Comment by wasdennnoch** [comment]
That logcat is wayyy too small and doesn't contain any useful information. Did you capture it while the SystemUI crashed and without filters?
