### ISSUE TITLE
Not working in cm13?

### ISSUE THREAD

**Issue by DonnyMrizky** [wasdennnoch/AndroidN-ify#119]

**Comment by vlw** [comment]
Working

**Comment by DonnyMrizky** [comment]
Look, What you can fix it? Please help bro, i like your module
Pada tanggal 9 Mei 2016 19.15, "vlw" <notifications@github.com> menulis:

**Comment by vlw** [comment]
![screenshot_20160509-163420](https://cloud.githubusercontent.com/assets/6003820/15114727/fb9d88dc-1603-11e6-82ae-de9214070cb2.png)

All working on CM13

**Comment by wasdennnoch** [comment]
Latest commits should have fixed the problems on CM13.

**Comment by DonnyMrizky** [comment]
Ok thanks bro
Pada tanggal 9 Mei 2016 21.02, "MrWasdennnoch" <notifications@github.com>
menulis:
