### ISSUE TITLE
Setting drawer not working

### ISSUE THREAD

**Issue by Naman256** [wasdennnoch/AndroidN-ify#1190]
I'm using moto g 3rd gen stock marshmallow 6.0.1 I enabled setting drawer in module but not showing up in Setting 
[Logs.txt](https://github.com/wasdennnoch/AndroidN-ify/files/585229/Logs.txt)

**Comment by Naman256** [comment]
Logs 

https://drive.google.com/file/d/0B6VF5z74_GSHLUtaMEJqQkNqa00/view?usp=drivesdk

**Comment by Naman256** [comment]
Idk how to I can upload logs in better way. I'm Noob 😥

**Comment by wasdennnoch** [comment]
I don't know what kind of log this is but it surely doesn't contain anything useful. I need your Xposed log.

**Comment by Naman256** [comment]
Here are my Xposed logs 

[xposed_error_20161111_124742.zip](https://github.com/wasdennnoch/AndroidN-ify/files/586081/xposed_error_20161111_124742.zip)

Sorry I'm Noob 😥 I share Xposed framework logs before

**Comment by wasdennnoch** [comment]
No crashes, so I guess it's the same problem as in #1060.
