### ISSUE TITLE
Google Assistant voice training

### ISSUE THREAD

**Issue by RouNNdeL** [wasdennnoch/AndroidN-ify#1192]
**Description**
Google Assistant asks for voice training every time you trigger it with "Ok Google", even after the voice has been trained already. [Video](http://vid.me/utBA)

**Module version (build version)**
jenkins-AndroidN-ify-764 (6)

**Device & ROM**
Device: Oneplus One A0001
Android version: 6.0.1
CyanogenMod Version: cm-13.0-20160819-SNAPSHOT-ZNH5YAO0IN-bacon
Xposed Version: Systemless v86.5
Magisk version: 6
Google app version: 6.8.19.21.arm

**Xposed log / logcat**
[xposed_error_20161111_160018.log.txt](https://github.com/wasdennnoch/AndroidN-ify/files/586053/xposed_error_20161111_160018.log.txt)

**Comment by wasdennnoch** [comment]
Known issue on Googles side: http://forum.xda-developers.com/showpost.php?p=69133065&postcount=11443

**Comment by RouNNdeL** [comment]
Is there a chance it happens on the Pixels, if it does they might fix it?

**Comment by wasdennnoch** [comment]
I on't know, but I guess it works there. Assistant is intended as a pixel-exclusive feature and they surely didn't intend it to run on any other phone.
