### ISSUE TITLE
Latest 768 build crashes ui whenever we do restart Sys ui  and location toggle isnt working after 763 build

### ISSUE THREAD

**Issue by pwrusr** [wasdennnoch/AndroidN-ify#1194]
I'm aware that Sys ui crashes with qs editor enabled from 764... Soo I gave it a try by disabling qs editor and updated to 768... The oddest thing is.. Sys ui gets crashed whenever I do restart Sys ui in nify...

Logs 
[xposed_error_20161112_104618.txt](https://github.com/wasdennnoch/AndroidN-ify/files/587077/xposed_error_20161112_104618.txt)

**Comment by pwrusr** [comment]
[xposed_error_20161112_104618.txt](https://github.com/wasdennnoch/AndroidN-ify/files/587075/xposed_error_20161112_104618.txt)

**Comment by pwrusr** [comment]
Update # I enabled fix in experimental features... Reboot > total ui crash.. Hope this wil get fixed (:

**Comment by paphonbth** [comment]
Yet another crash without useful logs.

**Comment by pwrusr** [comment]
[xposed_error_20161112_184257.txt](https://github.com/wasdennnoch/AndroidN-ify/files/587211/xposed_error_20161112_184257.txt)
Hope This might be useful (:

**Comment by wasdennnoch** [comment]
LOGCAT

**Comment by pwrusr** [comment]
[logcatonboot.txt](https://github.com/wasdennnoch/AndroidN-ify/files/587342/logcatonboot.txt)


There's no luck with 771 though.. Hope it wil be fixed with this logcat (: great work on working around on our issues.. Cheers (:

**Comment by pwrusr** [comment]
@paphonbth..sys  ui crash fixed with 776.. Thanks for ur work and commitment (: but stil nify tiles aren't saving. Hope they wil get fixed too (:
