### ISSUE TITLE
[Bug] Sometimes there are two overlapping ripples for the expand panel button

### ISSUE THREAD

**Issue by vemacs** [wasdennnoch/AndroidN-ify#120]
I can't reproduce this consistently, but here's a screenshot of the issue:

![](http://i.imgur.com/y3pezxP.jpg)

Running latest revision on stock 6.0.1.

**Comment by vlw** [comment]
![screenshot_20160501-121421](https://cloud.githubusercontent.com/assets/6003820/15112801/35ebe30e-15f9-11e6-9ae7-83d18667aeb3.png)

Same with CM13 (screenshot from 1th May)

**Comment by haseoxth** [comment]
Which version you are using now? Seems I can't  reproduce this issue with the build today.

**Comment by vemacs** [comment]
The absolute latest experimental build, and the build after the header fix. It's very inconsistently reproducible and goes away with a restart, but it always comes back eventually.

**Comment by wasdennnoch** [comment]
So it randomly appears without you doing anything? And does it go away when editing the tiles?

**Comment by vemacs** [comment]
Yes, it randomly appears (at least for me), and I have no idea how to edit the tiles :P

Do you mean via the system UI tuner in stock?

**Comment by wasdennnoch** [comment]
Yep, the SystemUI tuner, or whereever (is that a word? ^^) your ROM moved it to.

**Comment by vemacs** [comment]
@wasdennnoch I managed to reproduce it 100%. Tap "do not disturb" in the small QS tiles (panel not expanded), and then deactivate the switch in the upper right corner. That causes the double ripple, 100% of the time.

**Comment by paphonbth** [comment]
Can confirm that it happens on my phone too. But I can't fix it because my UI Automator is broken. It won't capture XML layout.

**Comment by vlw** [comment]
@wasdennnoch , delete label pls
![screenshot_6](https://cloud.githubusercontent.com/assets/6003820/15188133/ef556a04-17ac-11e6-840b-b417ebe2d21e.jpg)

**Comment by vemacs** [comment]
@paphonbth @wasdennnoch I managed to obtain the layout name via UI automator

![](https://i.imgur.com/G4acJBa.png)

**Comment by vemacs** [comment]
Recreating mExpandIndicator and readding it to the layout seems to remove the double ripple, but the behavior is incorrect because I apparently did it wrong.

**Comment by wasdennnoch** [comment]
Fixed with 8a7f5a4f37ff3339154289de977a1c5b5119aa1e
