### ISSUE TITLE
Quick Settings not hiding on Lockscreen

### ISSUE THREAD

**Issue by V-Droid** [wasdennnoch/AndroidN-ify#1200]
I've selected 3 quick settings to be hidden on the Lock screen however they are still visible. I'm not sure what logs are needed. I'm running CM13 on a Moto E 2nd Gen.@paphonbth @wasdennnoch.<br /><br />![Screenshot_20161112-094717.png](http://i.imgur.com/nGp5IGN.png)<br /><br />![Screenshot_20161112-094659.png](http://i.imgur.com/ykoKdMi.png)<br />

**Comment by wasdennnoch** [comment]
I'd need your Xposed log with debug mode enabled aftre playing around with that setting.
