### ISSUE TITLE
With multiple QS pages the notifications get dragged instead of the ViewPager when touched once

### ISSUE THREAD

**Issue by numeprenume** [wasdennnoch/AndroidN-ify#1206]
Strted happening with 813df359 and 447c7e9.
Here's a video: https://drive.google.com/file/d/0B7NA3219RnozVG1IdHZvMTE2VFU/view?usp=drivesdk

Besides the scrolling issue, you can see that the animation for expanding a tile starts one tile above where it was supposed to start, regardless of the position. The QS header also overlaps the notifications on lockscreen: http://i.imgur.com/Esmme4m.jpg

**Comment by wasdennnoch** [comment]
I don't have the wrong animation but can confirm the scrolling issue.

**Comment by numeprenume** [comment]
Well the wrong animation only happens sometimes, I'm not sure what triggers it.

**Comment by wasdennnoch** [comment]
Just had this happen too with the profiles tile.
