### ISSUE TITLE
No QS when I activate remove huge space 

### ISSUE THREAD

**Issue by Mikeyangeleo** [wasdennnoch/AndroidN-ify#1208]
When I activate remove huge space in QS the QS dissappear
I'm using aicp 11 6.0.1

**Comment by wasdennnoch** [comment]
Why do so many people don't fill in anything at all?

**Comment by Mikeyangeleo** [comment]
Sorry
When I activate remove huge space in QS the QS dissappear
I'm using aicp 11 6.0.1

**Comment by Mikeyangeleo** [comment]
Please help

**Comment by Mikeyangeleo** [comment]
How do I get the log anyone help

**Comment by Mikeyangeleo** [comment]
https://docs.google.com/uc?id=0B2aRWo5suZT8eWxhS0Z5c2U1Yk0&export=download

**Comment by Mikeyangeleo** [comment]
I've given you the xposed log what else do you need boss

**Comment by Mikeyangeleo** [comment]
https://docs.google.com/uc?id=0B2aRWo5suZT8ZVNVXzgtT2U4OEU&export=download  log from  version 781 please help

**Comment by Mikeyangeleo** [comment]
My real problem is that there is no status bar or quick setting or lock screen I'm using aicp 11 Android version 6.0.1 marshmallow

**Comment by Mikeyangeleo** [comment]
Once I enable fix huge space in status bar
