### ISSUE TITLE
Tiny album art bug in music player from builds 530+ 

### ISSUE THREAD

**Issue by pwrusr** [wasdennnoch/AndroidN-ify#1212]
Can it be fixed with upcoming builds...!!!

**Comment by pwrusr** [comment]
Probably notification hooks need an update (: @paphonb

**Comment by pwrusr** [comment]
Suggested workaround @notification hooks.java (:

**Comment by pwrusr** [comment]
Suggested workaround @notification hooks.java (:

**Comment by Freewander10** [comment]
This seems to be a duplicate of #744

**Comment by pwrusr** [comment]
then its my bad ...i hasnt noticed this issue ...it was tagged # can be reproduced !!!!!!!!!!!!!means it wil keep showing up ....waiting to close this issue on devs response (:
