### ISSUE TITLE
clicking on location tile restarts system UI

### ISSUE THREAD

**Issue by Madkita** [wasdennnoch/AndroidN-ify#1213]
build#776 clicking on location time restarts system UI
I have only attached n-ify logcat is your need full log tell me

**Comment by Madkita** [comment]
here is the log

**Comment by Madkita** [comment]
---- Nov 15, 2016 13:06:17 ----

11-15 12:17:26.956  1321  1321 I ActivityManager: Start proc 13250:tk.wasdennnoch.androidn_ify/u0a84 for service tk.wasdennnoch.androidn_ify/com.android.egg.neko.NekoService

11-15 12:17:30.743  1321  2458 I ActivityManager: START u0 {act=android.intent.action.MAIN flg=0x10000000 cmp=tk.wasdennnoch.androidn_ify/com.android.egg.neko.NekoLand} from uid 10084 on display 0

11-15 12:17:40.479  1321  2458 I ActivityManager: START u0 {act=android.intent.action.MAIN flg=0x14000000 cmp=tk.wasdennnoch.androidn_ify/com.android.egg.neko.NekoLockedActivity} from uid 10028 on display 0

11-15 12:17:47.819  1321  2802 I ActivityManager: Killing 13250:tk.wasdennnoch.androidn_ify/u0a84 (adj 9): remove task

11-15 12:17:47.858  1321  2794 I WindowState: WIN DEATH: Window{5b530b2 u0 tk.wasdennnoch.androidn_ify/com.android.egg.neko.NekoLand}

11-15 12:18:15.193  1321  2794 I ActivityManager: START u0 {act=android.intent.action.MAIN flg=0x14000000 cmp=tk.wasdennnoch.androidn_ify/.ui.SettingsActivity} from uid 10028 on display 0

11-15 12:18:15.262  1321  2548 I ActivityManager: Start proc 13572:tk.wasdennnoch.androidn_ify/u0a84 for activity tk.wasdennnoch.androidn_ify/.ui.SettingsActivity

11-15 12:18:16.766  1321  1332 I ActivityManager: START u0 {cmp=tk.wasdennnoch.androidn_ify/.ui.AboutActivity} from uid 10084 on display 0

11-15 12:18:23.139  1321  2533 I ActivityManager: Killing 13572:tk.wasdennnoch.androidn_ify/u0a84 (adj 9): remove task

11-15 12:18:23.153  1321  1495 I WindowState: WIN DEATH: Window{f6c91bc u0 tk.wasdennnoch.androidn_ify/tk.wasdennnoch.androidn_ify.ui.SettingsActivity}

11-15 12:18:23.155  1321  2792 I WindowState: WIN DEATH: Window{cfd42f0 u0 tk.wasdennnoch.androidn_ify/tk.wasdennnoch.androidn_ify.ui.AboutActivity}

11-15 12:18:32.445  1419  1419 E AndroidRuntime: 	at tk.wasdennnoch.androidn_ify.extracted.systemui.qs.QSDetail.handleShowingDetail(QSDetail.java:188)

11-15 12:18:32.445  1419  1419 E AndroidRuntime: 	at tk.wasdennnoch.androidn_ify.systemui.qs.QuickSettingsHooks$6.replaceHookedMethod(QuickSettingsHooks.java:143)

11-15 12:28:14.125 13795 13795 E AndroidRuntime: 	at tk.wasdennnoch.androidn_ify.extracted.systemui.qs.QSDetail.handleShowingDetail(QSDetail.java:188)

11-15 12:28:14.125 13795 13795 E AndroidRuntime: 	at tk.wasdennnoch.androidn_ify.systemui.qs.QuickSettingsHooks$6.replaceHookedMethod(QuickSettingsHooks.java:143)

11-15 12:28:32.144 15847 15847 E AndroidRuntime: 	at tk.wasdennnoch.androidn_ify.extracted.systemui.qs.QSDetail.handleShowingDetail(QSDetail.java:188)

11-15 12:28:32.144 15847 15847 E AndroidRuntime: 	at tk.wasdennnoch.androidn_ify.systemui.qs.QuickSettingsHooks$6.replaceHookedMethod(QuickSettingsHooks.java:143)

11-15 12:29:13.972 16103 16103 E AndroidRuntime: 	at tk.wasdennnoch.androidn_ify.extracted.systemui.qs.QSDetail.handleShowingDetail(QSDetail.java:188)

11-15 12:29:13.972 16103 16103 E AndroidRuntime: 	at tk.wasdennnoch.androidn_ify.systemui.qs.QuickSettingsHooks$6.replaceHookedMethod(QuickSettingsHooks.java:143)

11-15 12:48:25.598  1321  2790 I ActivityManager: START u0 {act=android.intent.action.MAIN flg=0x14000000 cmp=tk.wasdennnoch.androidn_ify/com.android.egg.neko.NekoLockedActivity} from uid 10028 on display 0

11-15 12:48:25.682  1321  2794 I ActivityManager: Start proc 19861:tk.wasdennnoch.androidn_ify/u0a84 for activity tk.wasdennnoch.androidn_ify/com.android.egg.neko.NekoLockedActivity

11-15 12:48:29.666  1321  2547 I ActivityManager: START u0 {act=android.intent.action.MAIN flg=0x14000000 cmp=tk.wasdennnoch.androidn_ify/com.android.egg.neko.NekoLockedActivity} from uid 10028 on display 0

11-15 12:49:12.659  1321  2458 I ActivityManager: Killing 19861:tk.wasdennnoch.androidn_ify/u0a84 (adj 15): empty #3

11-15 13:05:01.020 23574 23574 W XSharedPreferen: type=1400 audit(0.0:4884): avc: denied { open } for name="tk.wasdennnoch.androidn_ify_preferences.xml" dev="mmcblk0p7" ino=82621 scontext=u:r:system_app:s0 tcontext=u:object_r:app_data_file:s0:c512,c768 tclass=file

11-15 13:05:51.731 16199 16199 E AndroidRuntime: 	at tk.wasdennnoch.androidn_ify.extracted.systemui.qs.QSDetail.handleShowingDetail(QSDetail.java:188)

11-15 13:05:51.731 16199 16199 E AndroidRuntime: 	at tk.wasdennnoch.androidn_ify.systemui.qs.QuickSettingsHooks$6.replaceHookedMethod(QuickSettingsHooks.java:143)

11-15 13:05:57.585 23778 23778 W View    : requestLayout() improperly called by tk.wasdennnoch.androidn_ify.extracted.systemui.ExpandableIndicator{815784 VFED..C.. ......ID 171,0-228,57 #7f100019} during layout: running second layout pass

---- Nov 15, 2016 13:06:17 ----

**Comment by Freewander10** [comment]
I'm having a similar issue. But with the profiles tile instead #1207

**Comment by wasdennnoch** [comment]
Already fixed.
