### ISSUE TITLE
Replacing dismiss button with CLEAR ALL doesn't work

### ISSUE THREAD

**Issue by dil3mm4** [wasdennnoch/AndroidN-ify#1222]
As stated in the title, clear all replacement doesn't clear notifications.

**Module version (build version)**
0.2.0 (5)
**OS version**
5.0.2
**xPosed version**
86

**Comment by pwrusr** [comment]
toggle (off) change dismiss button >restart Sys ui or do a reboot 
(: 

If ur issue got solved... Please close it (:

**Comment by dil3mm4** [comment]
I understand, but I'd like it to work with the replacement LoL
Toggling off the dismiss button, just rollbacks to the standard lollipop
icon (that works).

**Comment by pwrusr** [comment]
Then provide ur xposed logs #
Use stock one as...  temporary fix for u (;

**Comment by dil3mm4** [comment]
logcat or xposed one?


2016-11-17 15:44 GMT+01:00 pwrusr <notifications@github.com>:

**Comment by pwrusr** [comment]
If Sys ui crash > logcat 
No Sys ui crash and facing minor issues > xposed logs (:

**Comment by dil3mm4** [comment]
Good then, providing logs in 10 mins.

2016-11-17 16:01 GMT+01:00 pwrusr <notifications@github.com>:

**Comment by dil3mm4** [comment]
​
 xposed_error_20161117_162232.log
<https://drive.google.com/file/d/0B_oTazq9BMw8X3ljSlZZX252YjA/view?usp=drive_web>
​

2016-11-17 16:02 GMT+01:00 Francesco M. <francoismanzo@gmail.com>:

**Comment by wasdennnoch** [comment]
A long known issue and should be fixed in snapshot builds.
