### ISSUE TITLE
Notification background is wrong since the last release

### ISSUE THREAD

**Issue by Thaodan** [wasdennnoch/AndroidN-ify#1223]
Since the latest snapshot the background of notifications is wrong. 
I'm using the glassified thems with cm theme engine as status bar theme. 
With the latest snapshot the background is no longer transparent as intended. 
**Module version (build version)**
697

**Comment by Thaodan** [comment]
Correction:
Version with the issue 779 
Version without the issue 697

**Comment by wasdennnoch** [comment]
In N notifications have a white background underneath that you can disable in the settings.

**Comment by Thaodan** [comment]
Thanks for the fast reply. The option fixed It for me. Is their a reason that the in notification reply only works sometimes?

**Comment by wasdennnoch** [comment]
It depends on the app to add one.

**Comment by Thaodan** [comment]
this is true but didn't you extract the action from android wear/auto?

**Comment by wasdennnoch** [comment]
Yes. That still doesn't mean there is one.
