### ISSUE TITLE
Quick Replies not appearing for certain apps

### ISSUE THREAD

**Issue by TheSnowyBear** [wasdennnoch/AndroidN-ify#1226]
**Description**
The quick reply option doesn't appear at all for Telegram and Inbox by Google, while it appears for WhatsApp (single message) and Google Messenger on my device. Quick reply actually appeared for Telegram once, but it was an isolated episode. I've been using the module for around 10 days now. My device is an Xperia Z3 D6603 running the latest version of Sony's Concept for Marshmallow. If you need further information I'm here.

**Module version (build version)**
Snapshot 783

**Xposed log / logcat**
11-18 12:58:40.848 I/Xposed  (  653): -----------------
11-18 12:58:40.848 I/Xposed  (  653): Starting Xposed version 86, compiled for SDK 23
11-18 12:58:40.848 I/Xposed  (  653): Device: D6603 (Sony), Android version 6.0.1 (SDK 23)
11-18 12:58:40.848 I/Xposed  (  653): ROM: MOB31E.Z1.3657-somc
11-18 12:58:40.848 I/Xposed  (  653): Build fingerprint: Sony/leo/leo:6.0.1/MOB31E.Z1/3657-somc:user/release-keys
11-18 12:58:40.848 I/Xposed  (  653): Platform: armeabi-v7a, 32-bit binary, system server: yes
11-18 12:58:40.848 I/Xposed  (  653): SELinux enabled: yes, enforcing: yes
11-18 12:58:41.857 I/Xposed  (  653): -----------------
11-18 12:58:41.857 I/Xposed  (  653): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
11-18 12:58:42.118 I/Xposed  (  653): Detected ART runtime
11-18 12:58:42.131 I/Xposed  (  653): Found Xposed class 'de/robv/android/xposed/XposedBridge', now initializing
11-18 12:58:42.367 I/Xposed  (  653): Loading modules from /data/app/tk.wasdennnoch.androidn_ify-1/base.apk
11-18 12:58:42.547 I/Xposed  (  653):   Loading class tk.wasdennnoch.androidn_ify.XposedHook
11-18 12:58:42.570 I/Xposed  (  653): [Android N-ify] [INFO] XposedHook: Version jenkins-AndroidN-ify-783 (6)
11-18 12:58:42.570 I/Xposed  (  653): [Android N-ify] [INFO] XposedHook: Automated Build; Version: 783
11-18 12:58:42.571 I/Xposed  (  653): [Android N-ify] [INFO] XposedHook: Build Time: 2016-11-17T18:54Z
11-18 12:58:42.571 I/Xposed  (  653): [Android N-ify] [INFO] XposedHook: Git SHA: 15155f71c3b73b21d63e036ee5d07d34b8b1560b
11-18 12:58:42.575 I/Xposed  (  653): [Android N-ify] [INFO] XposedHook: ---- Device info ----
11-18 12:58:42.576 I/Xposed  (  653): [Android N-ify] [INFO] XposedHook: SDK Version: 23
11-18 12:58:42.576 I/Xposed  (  653): [Android N-ify] [INFO] XposedHook: Build ID: MOB31E.Z1.3657-somc
11-18 12:58:42.576 I/Xposed  (  653): [Android N-ify] [INFO] XposedHook: Manufacturer: Sony
11-18 12:58:42.576 I/Xposed  (  653): [Android N-ify] [INFO] XposedHook: Brand: Sony
11-18 12:58:42.576 I/Xposed  (  653): [Android N-ify] [INFO] XposedHook: Model: D6603
11-18 12:58:42.576 I/Xposed  (  653): Loading modules from /data/app/com.sabik.assistantenabler-2/base.apk
11-18 12:58:42.639 I/Xposed  (  653):   Loading class com.sabik.assistantenabler.AssistantEnabler
11-18 12:58:42.654 I/Xposed  (  653): Loading modules from /data/app/com.achep.acdisplay-1/base.apk
11-18 12:58:42.745 I/Xposed  (  653):   Loading class com.achep.acdisplay.plugins.xposed.ImmersiveModeDontPanic
11-18 12:58:42.767 E/Xposed  (  653):     Failed to load class com.achep.acdisplay.plugins.xposed.ImmersiveModeDontPanic
11-18 12:58:42.767 E/Xposed  (  653): de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.android.internal.policy.impl.ImmersiveModeConfirmation
11-18 12:58:42.767 E/Xposed  (  653): 	at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:64)
11-18 12:58:42.767 E/Xposed  (  653): 	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:253)
11-18 12:58:42.767 E/Xposed  (  653): 	at com.achep.acdisplay.plugins.xposed.ImmersiveModeDontPanic.initZygote(ImmersiveModeDontPanic.java:58)
11-18 12:58:42.767 E/Xposed  (  653): 	at de.robv.android.xposed.XposedInit.loadModule(XposedInit.java:436)
11-18 12:58:42.767 E/Xposed  (  653): 	at de.robv.android.xposed.XposedInit.loadModules(XposedInit.java:361)
11-18 12:58:42.767 E/Xposed  (  653): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:91)
11-18 12:58:42.767 E/Xposed  (  653): Caused by: java.lang.ClassNotFoundException: com.android.internal.policy.impl.ImmersiveModeConfirmation
11-18 12:58:42.767 E/Xposed  (  653): 	at java.lang.Class.classForName(Native Method)
11-18 12:58:42.767 E/Xposed  (  653): 	at java.lang.Class.forName(Class.java:324)
11-18 12:58:42.767 E/Xposed  (  653): 	at external.org.apache.commons.lang3.ClassUtils.getClass(ClassUtils.java:823)
11-18 12:58:42.767 E/Xposed  (  653): 	at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:62)
11-18 12:58:42.767 E/Xposed  (  653): 	... 5 more
11-18 12:58:42.767 E/Xposed  (  653): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.android.internal.policy.impl.ImmersiveModeConfirmation" on path: DexPathList[[zip file "/system/framework/XposedBridge.jar"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
11-18 12:58:42.767 E/Xposed  (  653): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
11-18 12:58:42.767 E/Xposed  (  653): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
11-18 12:58:42.767 E/Xposed  (  653): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
11-18 12:58:42.767 E/Xposed  (  653): 	... 9 more
11-18 12:58:42.767 E/Xposed  (  653): 	Suppressed: java.lang.ClassNotFoundException: Didn't find class "com.android.internal.policy.impl.ImmersiveModeConfirmation" on path: DexPathList[[dex file "/data/dalvik-cache/xposed_XResourcesSuperClass.dex"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
11-18 12:58:42.767 E/Xposed  (  653): 		at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
11-18 12:58:42.767 E/Xposed  (  653): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
11-18 12:58:42.767 E/Xposed  (  653): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
11-18 12:58:42.767 E/Xposed  (  653): 		... 10 more
11-18 12:58:42.767 E/Xposed  (  653): 		Suppressed: java.lang.ClassNotFoundException: com.android.internal.policy.impl.ImmersiveModeConfirmation
11-18 12:58:42.767 E/Xposed  (  653): 			at java.lang.Class.classForName(Native Method)
11-18 12:58:42.767 E/Xposed  (  653): 			at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
11-18 12:58:42.767 E/Xposed  (  653): 			at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
11-18 12:58:42.767 E/Xposed  (  653): 			at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
11-18 12:58:42.767 E/Xposed  (  653): 			... 11 more
11-18 12:58:42.767 E/Xposed  (  653): 		Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
11-18 12:58:42.767 I/Xposed  (  653):   Loading class com.achep.acdisplay.plugins.xposed.OverrideHomeButton
11-18 12:58:42.772 E/Xposed  (  653):     Failed to load class com.achep.acdisplay.plugins.xposed.OverrideHomeButton
11-18 12:58:42.772 E/Xposed  (  653): de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.android.internal.policy.impl.PhoneWindowManager
11-18 12:58:42.772 E/Xposed  (  653): 	at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:64)
11-18 12:58:42.772 E/Xposed  (  653): 	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:253)
11-18 12:58:42.772 E/Xposed  (  653): 	at com.achep.acdisplay.plugins.xposed.OverrideHomeButton.initZygote(OverrideHomeButton.java:45)
11-18 12:58:42.772 E/Xposed  (  653): 	at de.robv.android.xposed.XposedInit.loadModule(XposedInit.java:436)
11-18 12:58:42.772 E/Xposed  (  653): 	at de.robv.android.xposed.XposedInit.loadModules(XposedInit.java:361)
11-18 12:58:42.772 E/Xposed  (  653): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:91)
11-18 12:58:42.772 E/Xposed  (  653): Caused by: java.lang.ClassNotFoundException: com.android.internal.policy.impl.PhoneWindowManager
11-18 12:58:42.772 E/Xposed  (  653): 	at java.lang.Class.classForName(Native Method)
11-18 12:58:42.772 E/Xposed  (  653): 	at java.lang.Class.forName(Class.java:324)
11-18 12:58:42.772 E/Xposed  (  653): 	at external.org.apache.commons.lang3.ClassUtils.getClass(ClassUtils.java:823)
11-18 12:58:42.772 E/Xposed  (  653): 	at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:62)
11-18 12:58:42.772 E/Xposed  (  653): 	... 5 more
11-18 12:58:42.772 E/Xposed  (  653): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.android.internal.policy.impl.PhoneWindowManager" on path: DexPathList[[zip file "/system/framework/XposedBridge.jar"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
11-18 12:58:42.772 E/Xposed  (  653): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
11-18 12:58:42.772 E/Xposed  (  653): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
11-18 12:58:42.772 E/Xposed  (  653): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
11-18 12:58:42.772 E/Xposed  (  653): 	... 9 more
11-18 12:58:42.772 E/Xposed  (  653): 	Suppressed: java.lang.ClassNotFoundException: Didn't find class "com.android.internal.policy.impl.PhoneWindowManager" on path: DexPathList[[dex file "/data/dalvik-cache/xposed_XResourcesSuperClass.dex"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
11-18 12:58:42.772 E/Xposed  (  653): 		at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
11-18 12:58:42.772 E/Xposed  (  653): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
11-18 12:58:42.772 E/Xposed  (  653): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
11-18 12:58:42.772 E/Xposed  (  653): 		... 10 more
11-18 12:58:42.772 E/Xposed  (  653): 		Suppressed: java.lang.ClassNotFoundException: com.android.internal.policy.impl.PhoneWindowManager
11-18 12:58:42.772 E/Xposed  (  653): 			at java.lang.Class.classForName(Native Method)
11-18 12:58:42.772 E/Xposed  (  653): 			at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
11-18 12:58:42.772 E/Xposed  (  653): 			at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
11-18 12:58:42.772 E/Xposed  (  653): 			at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
11-18 12:58:42.772 E/Xposed  (  653): 			... 11 more
11-18 12:58:42.772 E/Xposed  (  653): 		Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available

**Comment by paphonbth** [comment]
It's up to the app to include quick reply.

**Comment by TheSnowyBear** [comment]
The apps mentioned include it, that's why I opened the issue
