### ISSUE TITLE
Android Neko (easter egg) keeps crashing

### ISSUE THREAD

**Issue by byytelope** [wasdennnoch/AndroidN-ify#1227]
When I press on the empty dish tile in QS and select a food, N-ify crashes and the weird thing is there's nothing in the Xposed logs. And I also found that if you lock the phone after pressing the empty dish, the pop-up shows up instead of the lockscreen. It goes away and the lockscreen shows up when I press any thing and crashes N-ify in the process.
I'm on near stock LP and module 783.

**Comment by byytelope** [comment]
[xposed_error_20161120_085611.zip](https://github.com/wasdennnoch/AndroidN-ify/files/601856/xposed_error_20161120_085611.zip)

**Comment by wasdennnoch** [comment]
As you said, the Xposed log doesn't help. We need a logcat.

**Comment by byytelope** [comment]
Sorry about that. Here: [logcat.txt](https://github.com/wasdennnoch/AndroidN-ify/files/601962/logcat.txt)

**Comment by paphonbth** [comment]
Still no useful information in the log. Make sure the crash happens when you're capturing logs and please post full logs, not a trimmed one.

**Comment by byytelope** [comment]
Pretty sure this one will have something useful. [logcat.txt](https://github.com/wasdennnoch/AndroidN-ify/files/602159/logcat.txt)

**Comment by paphonbth** [comment]
Found the cause. Will fix it as soon as I have access to my pc.

**Comment by byytelope** [comment]
Ah, thank you.

**Comment by paphonbth** [comment]
Should be fixed with 9fc189f.

**Comment by byytelope** [comment]
Yeah that's fixed but found another bug. When I longpress on the Neko tile, it opens N-ify and crashes instantly. Here's the logcat: [logcat.txt](https://github.com/wasdennnoch/AndroidN-ify/files/604461/logcat.txt)
