### ISSUE TITLE
Overlapping carrier label and edit tiles button

### ISSUE THREAD

**Issue by 873960774** [wasdennnoch/AndroidN-ify#123]
http://image.coolapk.com/feed/2016/0509/478941_1462802354_0194.jpg.s.jpg

**Comment by 873960774** [comment]
http://image.coolapk.com/feed/2016/0509/478941_1462802354_0194.jpg.m.jpg

**Comment by wasdennnoch** [comment]
Coming straight from coolakp? ^^
I see the edit button, what is the overlapping text from?

**Comment by 873960774** [comment]
yeah :D

they are edit button, time and telecom operators.

thanks.

http://m.imgur.com/Gnf8nOy

**Comment by haseoxth** [comment]
It looks like you have a special layout with status bar, by the way @wasdennnoch I know you are from Germany and even that you also know this Chinese app store coolapk ? That surprised me.

**Comment by wasdennnoch** [comment]
@haseoxth I'm from germany, yes. I know coolapk because I once googled the name of my other module (LockMod) out of curiosity and a coolapk entry came up. A quick google translation revealed that it seemed to be a chinese app market ^^

**Comment by haseoxth** [comment]
Yeah it's the most professional android app store in China, users there are mostly android enthusiasts so this module is very popular. 
We all deeply grateful for all the works you have done.

**Comment by maz-1** [comment]
I am having the same issue with xperia z1 compact with stock lollipop :-(
![screenshot_6](https://cloud.githubusercontent.com/assets/5277060/15131553/94417f06-1683-11e6-88f3-e00928a8fd0a.png)

**Comment by wasdennnoch** [comment]
Should be fixed with 42343a9972f756eb6a044c9e6fd3b7a35681141c
