### ISSUE TITLE
Lockscreen text & notification drawer issue (logcat attached)

### ISSUE THREAD

**Issue by yzyboost** [wasdennnoch/AndroidN-ify#1231]
**Description**
No lockscreen text & notification drawer ( logcat attached)
**Module version (build version)**
Build 774 - build 783
**Xposed log / logcat**
[2016-11-20-18-32-52.txt](https://github.com/wasdennnoch/AndroidN-ify/files/601960/2016-11-20-18-32-52.txt)

**Comment by pwrusr** [comment]
Duplicate #1221
Wait until devs fix it

**Comment by yzyboost** [comment]
I attached the logcat.

**Comment by paphonbth** [comment]
What's the point of posting the same issue three times?
All discussion about this issue goes into #1221.
