### ISSUE TITLE
Double Quick answer

### ISSUE THREAD

**Issue by Leoxur** [wasdennnoch/AndroidN-ify#1232]
**Description**
In some app notification like Gmail, WhatsApp there are two answer button (One of the app and the other by n-ify) it's not a good and confortable view
**Module version (build version)**
783

**Comment by Robotit** [comment]
Same on version 791, and true not comfortable to see plus it's confusing to see it duplicated.

**Comment by Maxr1998** [comment]
Duplicate of #862, and invalid.
