### ISSUE TITLE
cant play coc (clash of clan) glitches nd strange lag 

### ISSUE THREAD

**Issue by arunverma833** [wasdennnoch/AndroidN-ify#1240]
Sir ur mod is awsm as u fixed my systemui crash earlier thanks for that sir 
Sir I have strange issue that is I cant play coc as it gives lags and glitches and can't open keyboard too 
Sir can u plz help me in this 
Thx for help sir

**Comment by arunverma833** [comment]
Using latest build sir

**Comment by wasdennnoch** [comment]
I have the very strong feeling that it isn't related to the module at all and more of a ROM / kernel issue.

**Comment by arunverma833** [comment]
Sir right now I have uninstalled this mod and now working fine sir no lags 
So I think mod is giving that issue

**Comment by wasdennnoch** [comment]
Still the module can't affect a random game. Did you install a nee kernel recently? That gave me issues some time ago. Are you sure it wasn't just the reboot that fixed it?

**Comment by arunverma833** [comment]
Sure sir I have just uninstalled this mod and everything goes smooth in the game sir 
And I have not installed any new kernel sir

**Comment by wasdennnoch** [comment]
I still can't think of a way how the game should be influenced.

**Comment by arunverma833** [comment]
I think i takes huge ram 
Btw i have 1 gb 
Sir u need any logs?
