### ISSUE TITLE
can't access cats

### ISSUE THREAD

**Issue by Madkita** [wasdennnoch/AndroidN-ify#1243]
when I long press on the dish it immediately takes me to home screen 
I can put food and also when there is a cat the notification appears
here is a log:
---- Nov 25, 2016 20:05:26 ----

11-25 11:09:52.423 11054 11054 E AndroidRuntime: Process: tk.wasdennnoch.androidn_ify, PID: 11054

11-25 11:09:58.230 11276 11276 E AndroidRuntime: Process: tk.wasdennnoch.androidn_ify, PID: 11276

11-25 13:13:06.226 22326 22326 E AndroidRuntime: Process: tk.wasdennnoch.androidn_ify, PID: 22326

11-25 14:03:25.005 28308 28308 E AndroidRuntime: Process: tk.wasdennnoch.androidn_ify, PID: 28308

11-25 15:05:58.963  9510  9510 E AndroidRuntime: Process: tk.wasdennnoch.androidn_ify, PID: 9510

11-25 16:39:00.400 13802 13802 E AndroidRuntime: Process: tk.wasdennnoch.androidn_ify, PID: 13802

11-25 18:56:45.208 23974 23974 E AndroidRuntime: Process: tk.wasdennnoch.androidn_ify, PID: 23974

11-25 19:12:35.113  1420  2564 I ActivityManager: START u0 {act=android.intent.action.MAIN flg=0x14000000 cmp=tk.wasdennnoch.androidn_ify/com.android.egg.neko.NekoLockedActivity} from uid 10027 on display 0

11-25 19:12:35.176  1420  2171 I ActivityManager: Start proc 29229:tk.wasdennnoch.androidn_ify/u0a83 for activity tk.wasdennnoch.androidn_ify/com.android.egg.neko.NekoLockedActivity

11-25 19:13:40.455  1420  1439 I ActivityManager: Killing 29229:tk.wasdennnoch.androidn_ify/u0a83 (adj 13): empty #3

11-25 19:34:50.970  1420  1431 I ActivityManager: Force stopping tk.wasdennnoch.androidn_ify appid=10083 user=0: from pid 11480

11-25 20:03:12.417  1420  1420 I ActivityManager: Start proc 5367:tk.wasdennnoch.androidn_ify/u0a83 for service tk.wasdennnoch.androidn_ify/com.android.egg.neko.NekoService

11-25 20:03:12.756  5367  5367 W System  : ClassLoader referenced unknown path: /data/app/tk.wasdennnoch.androidn_ify-2/lib/arm

11-25 20:03:16.920  1420  1599 I ActivityManager: START u0 {act=android.intent.action.MAIN flg=0x10000000 cmp=tk.wasdennnoch.androidn_ify/com.android.egg.neko.NekoLand} from uid 10083 on display 0

11-25 20:03:17.203  5367  5367 E AndroidRuntime: Process: tk.wasdennnoch.androidn_ify, PID: 5367

11-25 20:03:17.207  1420  2591 W ActivityManager:   Force finishing activity tk.wasdennnoch.androidn_ify/com.android.egg.neko.NekoLand

11-25 20:03:17.509  1420  2591 I WindowManager: Screenshot max retries 4 of Token{35a3a12 ActivityRecord{561159d u0 tk.wasdennnoch.androidn_ify/com.android.egg.neko.NekoLand t112 f}} appWin=Window{7eaae5b u0 Starting tk.wasdennnoch.androidn_ify} drawState=4

11-25 20:03:17.510  1420  1440 W ActivityManager: Skipping crash dialog of ProcessRecord{dd7a00d 5367:tk.wasdennnoch.androidn_ify/u0a83}: disabled

11-25 20:03:17.539  1420  2487 I WindowState: WIN DEATH: Window{1dabaa4 u0 tk.wasdennnoch.androidn_ify/com.android.egg.neko.NekoLand}

11-25 20:03:17.587  1420  4187 I ActivityManager: Process tk.wasdennnoch.androidn_ify (pid 5367) has died

11-25 20:03:22.614  1420  2564 I ActivityManager: START u0 {act=android.intent.action.MAIN flg=0x14000000 cmp=tk.wasdennnoch.androidn_ify/com.android.egg.neko.NekoLockedActivity} from uid 10027 on display 0

11-25 20:03:22.656  1420  1431 I ActivityManager: Start proc 5466:tk.wasdennnoch.androidn_ify/u0a83 for activity tk.wasdennnoch.androidn_ify/com.android.egg.neko.NekoLockedActivity

11-25 20:03:22.743  5466  5466 W System  : ClassLoader referenced unknown path: /data/app/tk.wasdennnoch.androidn_ify-2/lib/arm

11-25 20:03:23.124  5466  5489 E         : appName=tk.wasdennnoch.androidn_ify, acAppName=/system/bin/surfaceflinger

11-25 20:03:29.443  1420  2487 I ActivityManager: Killing 5466:tk.wasdennnoch.androidn_ify/u0a83 (adj 13): empty #3

11-25 20:03:30.141  1420  1432 I ActivityManager: START u0 {act=android.intent.action.MAIN flg=0x14000000 cmp=tk.wasdennnoch.androidn_ify/.ui.SettingsActivity} from uid 10027 on display 0

11-25 20:03:30.188  1420  2487 I ActivityManager: Start proc 5684:tk.wasdennnoch.androidn_ify/u0a83 for activity tk.wasdennnoch.androidn_ify/.ui.SettingsActivity

11-25 20:03:30.328  5684  5684 W System  : ClassLoader referenced unknown path: /data/app/tk.wasdennnoch.androidn_ify-2/lib/arm

11-25 20:03:30.469  5684  5684 I art     : Rejecting re-init on previously-failed class java.lang.Class<tk.wasdennnoch.androidn_ify.XposedHook>

11-25 20:03:30.469  5684  5684 I art     : Rejecting re-init on previously-failed class java.lang.Class<tk.wasdennnoch.androidn_ify.XposedHook>

11-25 20:03:30.672  5684  5706 E         : appName=tk.wasdennnoch.androidn_ify, acAppName=/system/bin/surfaceflinger

11-25 20:03:31.604  1420  1599 I ActivityManager: START u0 {cmp=tk.wasdennnoch.androidn_ify/.ui.AboutActivity} from uid 10083 on display 0

11-25 20:04:45.833  1420  2565 I ActivityManager: START u0 {act=android.intent.action.MAIN flg=0x14000000 cmp=tk.wasdennnoch.androidn_ify/com.android.egg.neko.NekoLand} from uid 10027 on display 0

11-25 20:04:46.052  5684  5684 E AndroidRuntime: Process: tk.wasdennnoch.androidn_ify, PID: 5684

11-25 20:04:46.054  1420  2688 W ActivityManager:   Force finishing activity tk.wasdennnoch.androidn_ify/com.android.egg.neko.NekoLand

11-25 20:04:46.081  1420  1440 W ActivityManager: Skipping crash dialog of ProcessRecord{cad7285 5684:tk.wasdennnoch.androidn_ify/u0a83}: disabled

11-25 20:04:46.121  1420  1432 I WindowState: WIN DEATH: Window{d22ebfc u0 tk.wasdennnoch.androidn_ify/com.android.egg.neko.NekoLand}

11-25 20:04:46.123  1420  2468 I WindowState: WIN DEATH: Window{8c23f1 u0 tk.wasdennnoch.androidn_ify/tk.wasdennnoch.androidn_ify.ui.AboutActivity}

11-25 20:04:46.123  1420  1491 W InputDispatcher: channel '4d5b080 tk.wasdennnoch.androidn_ify/tk.wasdennnoch.androidn_ify.ui.SettingsActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9

11-25 20:04:46.123  1420  1491 E InputDispatcher: channel '4d5b080 tk.wasdennnoch.androidn_ify/tk.wasdennnoch.androidn_ify.ui.SettingsActivity (server)' ~ Channel is unrecoverably broken and will be disposed!

11-25 20:04:46.126  1420  4188 I WindowState: WIN DEATH: Window{4d5b080 u0 tk.wasdennnoch.androidn_ify/tk.wasdennnoch.androidn_ify.ui.SettingsActivity}

11-25 20:04:46.126  1420  4188 W InputDispatcher: Attempted to unregister already unregistered input channel '4d5b080 tk.wasdennnoch.androidn_ify/tk.wasdennnoch.androidn_ify.ui.SettingsActivity (server)'

11-25 20:04:46.177  1420  4189 I ActivityManager: Process tk.wasdennnoch.androidn_ify (pid 5684) has died

11-25 20:04:46.201  1420  4189 I ActivityManager: Start proc 6612:tk.wasdennnoch.androidn_ify/u0a83 for activity tk.wasdennnoch.androidn_ify/.ui.AboutActivity

11-25 20:04:46.293  6612  6612 W System  : ClassLoader referenced unknown path: /data/app/tk.wasdennnoch.androidn_ify-2/lib/arm

11-25 20:04:46.467  6612  6612 I art     : Rejecting re-init on previously-failed class java.lang.Class<tk.wasdennnoch.androidn_ify.XposedHook>

11-25 20:04:46.467  6612  6612 I art     : Rejecting re-init on previously-failed class java.lang.Class<tk.wasdennnoch.androidn_ify.XposedHook>

11-25 20:04:46.608  6612  6632 E         : appName=tk.wasdennnoch.androidn_ify, acAppName=/system/bin/surfaceflinger

11-25 20:04:46.672  1420  1444 I ActivityManager: Displayed tk.wasdennnoch.androidn_ify/.ui.AboutActivity: +494ms (total +798ms)

11-25 20:05:11.107  1420  2688 I ActivityManager: START u0 {act=android.intent.action.MAIN flg=0x14000000 cmp=tk.wasdennnoch.androidn_ify/com.android.egg.neko.NekoLand} from uid 10027 on display 0

11-25 20:05:11.248  6612  6612 E AndroidRuntime: Process: tk.wasdennnoch.androidn_ify, PID: 6612

11-25 20:05:11.255  1420  2564 W ActivityManager:   Force finishing activity tk.wasdennnoch.androidn_ify/com.android.egg.neko.NekoLand

11-25 20:05:11.264  1420  1440 W ActivityManager: Skipping crash dialog of ProcessRecord{7dbac45 6612:tk.wasdennnoch.androidn_ify/u0a83}: disabled

11-25 20:05:11.341  1420  4188 I WindowState: WIN DEATH: Window{122f4bc u0 tk.wasdennnoch.androidn_ify/com.android.egg.neko.NekoLand}

11-25 20:05:11.344  1420  1432 I WindowState: WIN DEATH: Window{e05e48 u0 tk.wasdennnoch.androidn_ify/tk.wasdennnoch.androidn_ify.ui.AboutActivity}

11-25 20:05:11.417  1420  2171 I ActivityManager: Process

**Comment by wasdennnoch** [comment]
Please attach a full unfiltered  logcat as a file, not inline.

**Comment by byytelope** [comment]
I have the same issue on #1227

**Comment by Madkita** [comment]
here is a full log

**Comment by Madkita** [comment]
Here
