### ISSUE TITLE
System UI FC on ARM/mediatek/android 5.1/micromax canvas e352

### ISSUE THREAD

**Issue by d1sc0nn3ct3d** [wasdennnoch/AndroidN-ify#1244]
will be attaching logcats later.. systemUI fc on arm devices that uses vanilla android. everything crashes. unable to logcat via phone since systemUI is FC.

**Comment by wasdennnoch** [comment]
You can capture logcats via adb (computer).

**Comment by d1sc0nn3ct3d** [comment]
/MPlugin ( 2501): Unsupported class: com.mediatek.systemui.ext.IQuickSettingsPlugin

E/Xposed  ( 2501): de.robv.android.xposed.XposedHelpers$InvocationTargetError: java.lang.IllegalArgumentException: Bad tile spec: dnd

E/Xposed  ( 2501): 	at de.robv.android.xposed.XposedHelpers.callMethod(XposedHelpers.java:1225)

E/Xposed  ( 2501): 	at tk.wasdennnoch.androidn_ify.systemui.qs.tiles.AOSPTile.<init>(AOSPTile.java:21)

E/Xposed  ( 2501): 	at tk.wasdennnoch.androidn_ify.systemui.qs.TilesManager.createAospTile(TilesManager.java:134)

E/Xposed  ( 2501): 	at tk.wasdennnoch.androidn_ify.systemui.qs.QSTileHostHooks.createTile(QSTileHostHooks.java:304)

E/Xposed  ( 2501): 	at tk.wasdennnoch.androidn_ify.systemui.qs.QSTileHostHooks.access$400(QSTileHostHooks.java:34)

E/Xposed  ( 2501): 	at tk.wasdennnoch.androidn_ify.systemui.qs.QSTileHostHooks$3.afterHookedMethod(QSTileHostHooks.java:227)

E/Xposed  ( 2501): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:348)

E/Xposed  ( 2501): 	at com.android.systemui.statusbar.phone.QSTileHost.recreateTiles(<Xposed>)

E/Xposed  ( 2501): 	at com.android.systemui.statusbar.phone.QSTileHost.<init>(QSTileHost.java:179)

E/Xposed  ( 2501): 	at com.android.systemui.statusbar.phone.PhoneStatusBar.makeStatusBarView(PhoneStatusBar.java:1099)

E/Xposed  ( 2501): 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)

E/Xposed  ( 2501): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:334)

E/Xposed  ( 2501): 	at com.android.systemui.statusbar.phone.PhoneStatusBar.makeStatusBarView(<Xposed>)

E/Xposed  ( 2501): 	at com.android.systemui.statusbar.phone.PhoneStatusBar.addStatusBarWindow(PhoneStatusBar.java:3541)

E/Xposed  ( 2501): 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)

E/Xposed  ( 2501): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:334)

E/Xposed  ( 2501): 	at com.android.systemui.statusbar.phone.PhoneStatusBar.addStatusBarWindow(<Xposed>)

E/Xposed  ( 2501): 	at com.android.systemui.statusbar.phone.PhoneStatusBar.createAndAddWindows(PhoneStatusBar.java:3537)

E/Xposed  ( 2501): 	at com.android.systemui.statusbar.BaseStatusBar.start(BaseStatusBar.java:596)

E/Xposed  ( 2501): 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)

E/Xposed  ( 2501): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:334)

E/Xposed  ( 2501): 	at com.android.systemui.statusbar.BaseStatusBar.start(<Xposed>)

E/Xposed  ( 2501): 	at com.android.systemui.statusbar.phone.PhoneStatusBar.start(PhoneStatusBar.java:666)

E/Xposed  ( 2501): 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)

E/Xposed  ( 2501): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:334)

E/Xposed  ( 2501): 	at com.android.systemui.statusbar.phone.PhoneStatusBar.start(<Xposed>)

E/Xposed  ( 2501): 	at com.android.systemui.statusbar.SystemBars.createStatusBarFromConfig(SystemBars.java:106)

E/Xposed  ( 2501): 	at com.android.systemui.statusbar.SystemBars.onNoService(SystemBars.java:58)

E/Xposed  ( 2501): 	at com.android.systemui.statusbar.ServiceMonitor.startService(ServiceMonitor.java:228)

E/Xposed  ( 2501): 	at com.android.systemui.statusbar.ServiceMonitor.access$000(ServiceMonitor.java:49)

E/Xposed  ( 2501): 	at com.android.systemui.statusbar.ServiceMonitor$1.handleMessage(ServiceMonitor.java:73)

E/Xposed  ( 2501): 	at android.os.Handler.dispatchMessage(Handler.java:111)

E/Xposed  ( 2501): 	at android.os.Looper.loop(Looper.java:194)

E/Xposed  ( 2501): 	at android.app.ActivityThread.main(ActivityThread.java:5637)

E/Xposed  ( 2501): 	at java.lang.reflect.Method.invoke(Native Method)

E/Xposed  ( 2501): 	at java.lang.reflect.Method.invoke(Method.java:372)

E/Xposed  ( 2501): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)

E/Xposed  ( 2501): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

E/Xposed  ( 2501): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)

E/Xposed  ( 2501): Caused by: java.lang.IllegalArgumentException: Bad tile spec: dnd

E/Xposed  ( 2501): 	at com.android.systemui.statusbar.phone.QSTileHost.createTile(QSTileHost.java:377)

E/Xposed  ( 2501): 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)

E/Xposed  ( 2501): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:334)

E/Xposed  ( 2501): 	at com.android.systemui.statusbar.phone.QSTileHost.createTile(<Xposed>)

E/Xposed  ( 2501): 	at java.lang.reflect.Method.invoke(Native Method)

E/Xposed  ( 2501): 	at java.lang.reflect.Method.invoke(Method.java:372)

E/Xposed  ( 2501): 	at de.robv.android.xposed.XposedHelpers.callMethod(XposedHelpers.java:1217)

E/Xposed  ( 2501): 	... 38 more

E/AndroidRuntime( 2501): FATAL EXCEPTION: main

E/AndroidRuntime( 2501): Process: com.android.systemui, PID: 2501

E/AndroidRuntime( 2501): java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.ViewPropertyAnimator android.view.View.animate()' on a null object reference

E/AndroidRuntime( 2501): 	at tk.wasdennnoch.androidn_ify.systemui.statusbar.StatusBarHooks$1.replaceHookedMethod(StatusBarHooks.java:91)

E/AndroidRuntime( 2501): 	at de.robv.android.xposed.XC_MethodReplacement.beforeHookedMethod(XC_MethodReplacement.java:29)

E/AndroidRuntime( 2501): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:314)

E/AndroidRuntime( 2501): 	at com.android.systemui.statusbar.phone.NavigationBarTransitions.applyLightsOut(<Xposed>)

E/AndroidRuntime( 2501): 	at com.android.systemui.statusbar.phone.NavigationBarTransitions.applyMode(NavigationBarTransitions.java:91)

E/AndroidRuntime( 2501): 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)

E/AndroidRuntime( 2501): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:334)

E/AndroidRuntime( 2501): 	at com.android.systemui.statusbar.phone.NavigationBarTransitions.applyMode(<Xposed>)

E/AndroidRuntime( 2501): 	at com.android.systemui.statusbar.phone.NavigationBarTransitions.init(NavigationBarTransitions.java:52)

E/AndroidRuntime( 2501): 	at com.android.systemui.statusbar.phone.NavigationBarView.reorient(NavigationBarView.java:673)

E/AndroidRuntime( 2501): 	at com.android.systemui.statusbar.phone.PhoneStatusBar.prepareNavigationBarView(PhoneStatusBar.java:1519)

E/AndroidRuntime( 2501): 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)

E/AndroidRuntime( 2501): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:334)

E/AndroidRuntime( 2501): 	at com.android.systemui.statusbar.phone.PhoneStatusBar.prepareNavigationBarView(<Xposed>)

E/AndroidRuntime( 2501): 	at com.android.systemui.statusbar.phone.PhoneStatusBar.addNavigationBar(PhoneStatusBar.java:1556)

E/AndroidRuntime( 2501): 	at com.android.systemui.statusbar.phone.PhoneStatusBar.start(PhoneStatusBar.java:673)

E/AndroidRuntime( 2501): 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)

E/AndroidRuntime( 2501): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:334)

E/AndroidRuntime( 2501): 	at com.android.systemui.statusbar.phone.PhoneStatusBar.start(<Xposed>)

E/AndroidRuntime( 2501): 	at com.android.systemui.statusbar.SystemBars.createStatusBarFromConfig(SystemBars.java:106)

E/AndroidRuntime( 2501): 	at com.android.systemui.statusbar.SystemBars.onNoService(SystemBars.java:58)

E/AndroidRuntime( 2501): 	at com.android.systemui.statusbar.ServiceMonitor.startService(ServiceMonitor.java:228)

E/AndroidRuntime( 2501): 	at com.android.systemui.statusbar.ServiceMonitor.access$000(ServiceMonitor.java:49)

E/AndroidRuntime( 2501): 	at com.android.systemui.statusbar.ServiceMonitor$1.handleMessage(ServiceMonitor.java:73)

E/AndroidRuntime( 2501): 	at android.os.Handler.dispatchMessage(Handler.java:111)

E/AndroidRuntime( 2501): 	at android.os.Looper.loop(Looper.java:194)

E/AndroidRuntime( 2501): 	at android.app.ActivityThread.main(ActivityThread.java:5637)

E/AndroidRuntime( 2501): 	at java.lang.reflect.Method.invoke(Native Method)

E/AndroidRuntime( 2501): 	at java.lang.reflect.Method.invoke(Method.java:372)

E/AndroidRuntime( 2501): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)

E/AndroidRuntime( 2501): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

E/AndroidRuntime( 2501): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)

**Comment by d1sc0nn3ct3d** [comment]
Bro its the log.. Hope it helps. SystemUi FC. Thank you very much!
