### ISSUE TITLE
QS Pages automatically change tiles count per row

### ISSUE THREAD

**Issue by prakashait09** [wasdennnoch/AndroidN-ify#1247]
**Description**
I use gravitybox and had set 4 tiles per row, and i am using N-ify build 783.
Sometimes it shows 3 tiles per row, sometimes 4. I don't know how and when it changes automatically.

**Module version (build version)**
783

**Xposed log / logcat**

**Comment by pwrusr** [comment]
No one will be having any idea By providing description only... 

_Check for duplicates 
_attach your logs 

This is the best way to explain ur issue... LOGS they say or convey betterthan anyone (:

**Comment by prakashait09** [comment]
Hi,
I updated to build 785 yesterday and haven't faced this issue since then. But if you want, i will attach logs.
Do you want it ?

**Comment by pwrusr** [comment]
If ur issue got solved then close it

**Comment by prakashait09** [comment]
Could not reproduce the issue since build 785, so closing it.
