### ISSUE TITLE
OOS3.1.4 crash on open recents

### ISSUE THREAD

**Issue by nickimola** [wasdennnoch/AndroidN-ify#1250]
Hi, 

I posted the same issue here: http://forum.xda-developers.com/showpost.php?p=69859846&postcount=14085

Basically, even after disabling the "new image" on recent, systemUI still crashes every time i try to open it.

I'm attaching the catlog if it is useful.

Thanks
[test.txt](https://github.com/wasdennnoch/AndroidN-ify/files/622036/test.txt)

**Comment by lightpencil** [comment]
**Confirmed**
Same crash happens on oos3.1.4 on oneplus 3

**Comment by wasdennnoch** [comment]
#680
