### ISSUE TITLE
[Suggestion] Option to remove round icon from notifications that contain a upper-case letter

### ISSUE THREAD

**Issue by TheHaso** [wasdennnoch/AndroidN-ify#1253]
Hi there,

I wanted to suggest for a option to remove the round icon that contains a upper-case of the first letter in the header. As seen on the attached image, the gmail notification contains a gmail icon, app name, then mail header, small mail context and my mail. The purple icon is kinda bloating the notification, and is kinda unnecessary.

Also can see that on my notification from FINN app, its very clean and nice.

A option to remove those would be amazing.

![screenshot_20161205-114152](https://cloud.githubusercontent.com/assets/11940704/20884899/3903e894-baee-11e6-842b-5cb973459058.png)

**Comment by wasdennnoch** [comment]
As I already said in the XDA thread (http://forum.xda-developers.com/showpost.php?p=69939144&postcount=14185), it's a Gmail thing and not module-related.
