### ISSUE TITLE
Data indicator in Media style notification and app name text cant be readable 

### ISSUE THREAD

**Issue by pwrusr** [wasdennnoch/AndroidN-ify#1258]
@paphonb 
![sketch-1481390058034](https://cloud.githubusercontent.com/assets/22295050/21074913/376dbf6e-bf2b-11e6-9114-08a14e40209a.png)
Lower (second line) Text on Media style notification is cropped and there's data icon instead of music icon 

Music notification text accent (color) is too dim which makes it unreadable... White text would be gud (: 
And there's no change in compact style 

Thanks for the fix... U devs r awesome 

Build 787
LP 
![sketch-1481390883999](https://cloud.githubusercontent.com/assets/22295050/21074972/dcc81a26-bf2c-11e6-8cc0-597470d47bb3.png)

**Comment by wasdennnoch** [comment]
#630
