### ISSUE TITLE
PIN not providing

### ISSUE THREAD

**Issue by LosTigeros** [wasdennnoch/AndroidN-ify#1259]
**Description**
When AndroidN-ify is enabled. I can't provide PIN for SIM Card.
When I click on number, its not writing to textbox.

**Module version (build version)**
Latest

**Xposed log / logcat**
There is nothing in xposed log and logcat.

**Comment by Maxr1998** [comment]
Device name/Android version? ROM name/source?

**Comment by LosTigeros** [comment]
MyPhone Infinity IIS (MT6753), Android 5.1

**Comment by AlexD97** [comment]
Same issue here. I have a OnePlus One with Android 6.0.1 (darkobas) .
