### ISSUE TITLE
Huge space in notification bar between the clock and brightnes bar

### ISSUE THREAD

**Issue by ziadshawki1** [wasdennnoch/AndroidN-ify#1262]
![screenshot_20161211-145811](https://cloud.githubusercontent.com/assets/24506841/21080282/da1ff6f4-bfb3-11e6-8d02-ae935c653e64.png)
Theres a huge space between the clock and the brightnes bar
Plz fix
This is xposed log
[error.zip](https://github.com/wasdennnoch/AndroidN-ify/files/644456/error.zip)

My device is lenovo k3 note
Thank you for your efford

**Comment by pwrusr** [comment]
Enable gap fix in experimental settings (:

**Comment by ziadshawki1** [comment]
How i dont understand wheres gap fix

**Comment by pwrusr** [comment]
Open nify > tap on top right 'i' (info) > keep tapping on N logo until it says experimental features enabled > go back and enable gap fix > reboot 

Close this issue if ur issue got solved (:

**Comment by ziadshawki1** [comment]
When I made what u said and enable it 
I get system ui has stopped a lot of times and bootloop
😑

**Comment by pwrusr** [comment]
Well... Get ur logcat and post it here 

And what I said is correct for that gap fix... There has been some issues while enabling that gap fix which was fixed already (:

**Comment by ziadshawki1** [comment]
this is the logcat plz try to fix the bug
[logcat.txt](https://github.com/wasdennnoch/AndroidN-ify/files/647433/logcat.txt)

**Comment by PradyunS** [comment]
For me if you enable the 'fix huge space' theres no quick settings/notifications or lockscreen text

**Comment by lDarkusl** [comment]
Same un here. But how to get my logcat file?

**Comment by PradyunS** [comment]
@IdarkusI
Go to the xposed app, go to logs, and hit the save icon
