### ISSUE TITLE
Music Player notification issue

### ISSUE THREAD

**Issue by alexandrumarcel** [wasdennnoch/AndroidN-ify#1268]
I can't see the singer's name nor the album name because an white bar is overlapping the text. I tried to use another media player but I get the same thing and this happens only on the lockscreen
![screenshot_20161213-133702](https://cloud.githubusercontent.com/assets/6230856/21156783/c6b8b11e-c17f-11e6-818a-28a976f99f65.png)

**Comment by LosTigeros** [comment]
I have too problem with music player, and I dont want to duplicate issues so:
![Picture of Spotify notification](http://vpx.pl/i/2016/12/23/IMG_20161223_100627_417.jpg)

**Comment by Jesterjke** [comment]
![img_20170103_213801](https://cloud.githubusercontent.com/assets/22295967/21618665/b87c80be-d1f4-11e6-82d3-b2946b144593.jpg)
I have the same issue. 
Also dark text on dark background as mentioned before. 
Same in play music and sound cloud(and Spotify, obviously)

**Comment by LosTigeros** [comment]
Now it looks that:
![Picture of Spotify notification](https://lh3.googleusercontent.com/Z3h_LIy3k4aKziXE3VrzAIz7xP9eX6vh6B9lJbLaRGGyNDpSu1dRK-lGmlbuTM2B1zrbjz1dbnrMsew=w1960-h3042-rw)

**Comment by DarkKowalski** [comment]
I have a similar problem.
