### ISSUE TITLE
Translation needs to be update

### ISSUE THREAD

**Issue by 641cgust** [wasdennnoch/AndroidN-ify#1271]
**Description**
The translation of Chinese Traditional has been update yesterday,could you build a new update for this.
**Module version (build version)**
#792
**Xposed log / logcat**

**Comment by 641cgust** [comment]
The latest translation of AndroidN-ify zh-rTW
links below.
http://pastebin.com/J0d8Kb3C

**Comment by wasdennnoch** [comment]
Please update translations on Crowdin. I just pushed updated ones.
