### ISSUE TITLE
Calling screen crashes when try to make call

### ISSUE THREAD

**Issue by pradeepct** [wasdennnoch/AndroidN-ify#1278]
Calling screen crash and reboot screen appears when I try to call and also when I receive calls....

My model Asus Zenfone 5

**Comment by pwrusr** [comment]
Use third party dialer and add it to Nify blacklist... This may fix ur issue (:

**Comment by byytelope** [comment]
If the issue is still not fixed, try setting your dialer as the default phone app. Go to settings, press the cog in the top right, go to default apps, press phone and set it.

**Comment by pradeepct** [comment]
Thank you 😃
