### ISSUE TITLE
Gap on-top

### ISSUE THREAD

**Issue by dil3mm4** [wasdennnoch/AndroidN-ify#1284]
**tl;dr I know that it's no longer developed, but if someone has some spare-time would be nice to have a fix.**
**Description**
Gap on-top. 
Between clock and on-top edge.
**Module version (build version)**
801 build
**OS**
5.0.2 - LG Stock
**xPosed version**
84
**Infos**
If there's something else needed just ask.
**Screenshot**
![screenshot 09 2fgen 2f2017 17-29-58](https://cloud.githubusercontent.com/assets/21145257/21774730/b3a81b54-d693-11e6-84ef-7d04f342535f.png)
@paphonbth @Maxr1998

**Comment by pwrusr** [comment]
Turn on force date next to time option in nify....
If still ur problem persists... it may be dpi issue...try changing dpi of ur screen (: 
Don't ask me how.. Pls Google it (:

**Comment by dil3mm4** [comment]
Already done, both solutions, combined and non combined. 
Always same result.

**Comment by paphonbth** [comment]
From XDA thread

> Might not work on ROMs that heavily modify code I'm touching with this module (I'm looking at you, TouchWiz, LG, and partially HTC).

**Comment by dil3mm4** [comment]
I know, but it's a small fix. It's just a gap, nothing more, I was just asking because it's not a major issue :)
