### ISSUE TITLE
Not working.

### ISSUE THREAD

**Issue by nadeemkkd** [wasdennnoch/AndroidN-ify#1293]
**Description**

**Module version (build version)**

**Xposed log / logcat**

**Comment by nadeemkkd** [comment]
Error module not activated. Wat to do.am using oneplus x,marshmallow.

**Comment by Maxr1998** [comment]
Logs, maybe?

**Comment by nadeemkkd** [comment]
Sorry...wat u mean by "logs.may be?"


I can't understand.any solution to solve dis problems.?
Do u need any information about my fon?

Plz help me.
Software Name :- Android N-ify 
Fon Model :- Oneplus X (ONE E1003)

**Comment by Visandi** [comment]
Make sure the module has been checked in xposed and reboot your device
