### ISSUE TITLE
AOSP non-LG rom SYSTEMUI Crash

### ISSUE THREAD

**Issue by Dil3mm4** [wasdennnoch/AndroidN-ify#1308]
**Description**
SystemUI crashes
**Module version (build version)**
811
**Xposed log / logcat**
[logcat.txt](https://github.com/wasdennnoch/AndroidN-ify/files/751896/logcat.txt)
[logcat2.txt](https://github.com/wasdennnoch/AndroidN-ify/files/751897/logcat2.txt)

[xposed.txt](https://github.com/wasdennnoch/AndroidN-ify/files/751898/xposed.txt)

**Comment by paphonbth** [comment]
What is your ROM? It is definitely not something close to AOSP.

**Comment by dil3mm4** [comment]
5.0.2 MTK AOSP.

**Comment by AkashSharma19** [comment]
I having the same problem in micromax e455  .  5.0.2.   On snapdragon 415. System ui crashed after booting

**Comment by AkashSharma19** [comment]
And when i yried the older 10 to 15 versions.  They worked but not showing qs

**Comment by Dil3mm4** [comment]
So what's the solution?
