### ISSUE TITLE
Padding of notification header and content

### ISSUE THREAD

**Issue by sargijeh** [wasdennnoch/AndroidN-ify#1325]
**Description**
In build 821, the padding of notification title and content is removed and everything is starting from far left :(

**Module version (build version)**
Build 821, Xperia 5.1.1

**Comment by RouNNdeL** [comment]
I can confirm the same issue appeared on my Oneplus One CM13 6.0.1 build 821

**Comment by patrickliao2007** [comment]
In both build 821 and 822, this issue appeared
 on my Nexus 6p, Android 6.0.1.

**Comment by Innacor29** [comment]
Same issue on my Ulefone Power running Marshmallow 6.0 on the build 822

**Comment by hcker19998** [comment]
I am also facing the same problem in my sprout8 running Android 6.0.1

**Comment by RouNNdeL** [comment]
Seems like it got fixed in 823, at least on my device

**Comment by Innacor29** [comment]
Yes, it has been fixed
