### ISSUE TITLE
App not activated

### ISSUE THREAD

**Issue by Sindhusaurrav1998** [wasdennnoch/AndroidN-ify#1337]
It says activate module...Pls help

**Comment by Sindhusaurrav1998** [comment]
It says activate module...Pls help

**Comment by PradyunS** [comment]
well then activate it! go  to the xposed installer app, go to modules, click the checkbox next to the name, and then reboot your phone

**Comment by Maxr1998** [comment]
Do what @PradyunS said, that'll "fix" it.
