### ISSUE TITLE
Not working on Lineage OS 13/6.0.1

### ISSUE THREAD

**Issue by yzyboost** [wasdennnoch/AndroidN-ify#1339]
**Description**
Hey guys! I've flashed xposed framework on twrp, installed xposed installer and the module. After enable the module and reboot also, my phone isn't boot on the home/lock screen. Thanks in advance. Hope you will help me.
**Module version (build version)**
from v 0.2.0 to latest.
**Xposed log / logcat**
Can't attach a log, because its bootloop.

**Comment by Maxr1998** [comment]
@yzyboost could you create a logcat with the computer? That also works without the system having booted up.

**Comment by yzyboost** [comment]
Okay, how?? What is the compatible xposed version for marshmallow 6.0.1? I tried v84 and v85 sdk 23, yeah its installed but after activating the module and reboot, it stuck on bootanimation.

**Comment by PradyunS** [comment]
@yzyboost
On adb: adb logcat -v long > bootloopingandroidnify.txt

**Comment by yzyboost** [comment]
What software should I use?

On May 23, 2017 7:55 AM, "PradyunS" <notifications@github.com> wrote:

@yzyboost <https://github.com/yzyboost>
On adb: adb logcat -v long > bootloopingandroidnify.txt

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/wasdennnoch/AndroidN-ify/issues/1339#issuecomment-303251405>,
or mute the thread

**Comment by yzyboost** [comment]
It's okay now! The xposed framework should be updated. Lol.
