### ISSUE TITLE
App Icon and Text missing from notification header

### ISSUE THREAD

**Issue by Freewander10** [wasdennnoch/AndroidN-ify#1342]
In the latest build (830) the notification header is blank. 

[xposed_error_20170523_103448.txt](https://github.com/wasdennnoch/AndroidN-ify/files/1022766/xposed_error_20170523_103448.txt)

![img_20170523_103724](https://cloud.githubusercontent.com/assets/21367316/26362693/6dffb1dc-3fa4-11e7-967f-7261ef56c184.jpg)

**Comment by numeprenume** [comment]
Try this: [https://drive.google.com/open?id=0B7NA3219RnozVVpBUmludU5Qa1U](url)

**Comment by Freewander10** [comment]
Yea. It's fixed now. Thanks!
