### ISSUE TITLE
Fancy QS Transition Error

### ISSUE THREAD

**Issue by 00Sumit7** [wasdennnoch/AndroidN-ify#1344]
**Swiping up from expanded quick settings the brightness slider also moves up untill it touches date and then goes down with a lag**

**Module version (830)**

**
[xposed_error_20170523_231538.log.txt](https://github.com/wasdennnoch/AndroidN-ify/files/1023167/xposed_error_20170523_231538.log.txt)

![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/23012970/26368332/ef1b453c-400e-11e7-93e3-154fceb9db76.gif)
**

**Comment by numeprenume** [comment]
Hmm, this shouldn't have anything to do with my changes. Did it happen before? Decrease your phone's DPI to fix this.

**Comment by 00Sumit7** [comment]
It was happening few time in previous builds but after restarting
systemui it fixes.

But it is not fixing in latest build.

And lowering​ dpi gives no change.

**Comment by numeprenume** [comment]
Lower it more then. At some point it will stop doing that.

**Comment by 00Sumit7** [comment]
Let me try.
I will inform you.

**Comment by 00Sumit7** [comment]
It stops at 160dpi.
The lowest in settings.

But i can't​ use ky phone like this.

**Comment by 00Sumit7** [comment]
Lowering dpi is only way?

**Comment by numeprenume** [comment]
Hopefully not, I'll see what I can do about it.

**Comment by 00Sumit7** [comment]
Thank you.

**Comment by numeprenume** [comment]
Can you try [this](https://drive.google.com/open?id=0B7NA3219RnozOE9TLVhScGFJOVE) and tell me if it fixes it and if you find any other new problems?

**Comment by 00Sumit7** [comment]
Let me try .

**Comment by 00Sumit7** [comment]
Thanks bro.
Problem fixed.
Everything working for me..
👍👍
Thanks again.

**Comment by 00Sumit7** [comment]
When version 0.3.0 is going to be official.

**Comment by 00Sumit7** [comment]
I have a small question.
Should i install build 833.
Or
Stick to 3.0.3 debug.

**Comment by numeprenume** [comment]
Yeah you can install the latest build.
