### ISSUE TITLE
Can't write lock screen PIN

### ISSUE THREAD

**Issue by licaon-kter** [wasdennnoch/AndroidN-ify#1349]
Xperia 5.1.1

**Description**
Install/update module, restart, swipe to enter PIN, pressing any number does not actually write the number in the box, although you can see the animation on touch.

**Module version (build version)**
Started in build 828 (I guess), present in 829 and 833 (did not bother to test in between).
Build 827 works ok.

**Xposed log / logcat**
https://gist.github.com/licaon-kter/115e85d9a6e144d33d9784f6dbe76fea

I guess one of these fixes broke it: https://github.com/wasdennnoch/AndroidN-ify/commit/6f79766b05770f8313f63ddf69b4eb43ec1c58e8 (why weren't these added one by one ?)

@numeprenume Any ideas?

**Comment by numeprenume** [comment]
Which experimental features have you enabled? Can you record a video and send me your SystemUI.apk? (deodexed if it's possible)

**Comment by licaon-kter** [comment]
Experimental: Fix huge space under qs header and Experimental N notifications behavior

**Comment by numeprenume** [comment]
Okay, try disabling Experimental N notifications behavior and see if it fixes it.

**Comment by licaon-kter** [comment]
Nope, and neither does cleaning up the app settings (using default settings only).
Unfortunately this is not my system to mess with all the time so if you have ideas/commits I will test them but not super fast (ex. unable to unlock I need to: uninstall Xposed, re-optimize all apps, uninstall N-ify, reinstall xposed, re-optimize all apps; these take a while)

**Comment by numeprenume** [comment]
You don't have to mess with Xposed. You can just delete the apk in /data/app/tk.wasdennnoch/androidn_ify in recovery and then reboot. Anyway, I still need your SystemUI apk to see what might cause it.

**Comment by licaon-kter** [comment]
There is no access to encrypted /data from TWRP on Xperia 5.1.1, it's a known issue on their side. :(

**Comment by PradyunS** [comment]
This might sound crazy but i recently watched POTC so everyrhing i say sounds crazy: try entering your normal pin and clicking enter and see if it works

**Comment by numeprenume** [comment]
If you have debugging enabled you can run 
`adb shell`
`su`
`touch /data/data/de.robv.android.xposed.installer/conf/disabled`
and it will disable Xposed, or just run 
`rm /data/app/tk.wasdennnoch.androidn_ify` after the first 2 commands

**Comment by licaon-kter** [comment]
@PradyunS There is no ENTER key (not sure if by default of the making of anotherapp, I'll getback to you on this:))

**Comment by wasdennnoch** [comment]
That's why you enable usb debugging and grant it su permissions before you install Xposed ;)

And adb is accessible before you unlock the device.

**Comment by licaon-kter** [comment]
Did not know about that. Thanks

**Comment by licaon-kter** [comment]
Stock [SystemUI.apk](
https://mega.nz/#!hNo0TYoS!3lJSw31t6pcVv2L6glGKVSlEJesRO8ctaSQ_tdQr-Cw
)/[.odex](
https://mega.nz/#!hdgi3Lrb!ie25uGWQ1pEFMBVeudI3FXvUsuq2C5GhiPejwEH8ggk
)
I've read about de-odexing but did not manage to do it. Are these enough or you need some framework apks too?

**Comment by numeprenume** [comment]
Yeah, I'll need the framework folder too (can't remember exactly which specific files are needed)

**Comment by licaon-kter** [comment]
Hope these are it: [framework-res](
https://mega.nz/#!sB52yT7K!iAG8bLCjsGwQmqaMHIINI9mdV1zH5u1qGCtfVX_EHjo
) and [SemcGenericUxpRes](
https://mega.nz/#!sQY2DZIT!Q6rXTvaEclsr_3kHjmSiF3x6dywuiZ93cTrRdprO1VY
)

**Comment by numeprenume** [comment]
I meant the whole folder, but more specifically /framework/arm and /framework/oat

**Comment by licaon-kter** [comment]
This is [/framework](
https://mega.nz/#!8UJnzIBa!FaxGUjGkrQJjLNQAXy4kQYtFHk8ShiDnbxmtFYyzaws
)

**Comment by numeprenume** [comment]
Okay, try [this](https://drive.google.com/file/d/0B7NA3219RnozV3RMb1gxdllZVGs/view?usp=sharing) and see if it works. Make sure you test with different options selected (fix space under qs header, experimental N notifications behavior).

**Comment by thesims2customs** [comment]
It happened to me too... I should re-flash my ROM and restore data. 
Well, this time I turn off emergency info on lockscreen and it works.
Only that option relates to lockscreen beside "reply on lockscreen".

**Comment by licaon-kter** [comment]
(I did not get a chance to test the new build yet)

FYI, I had "emergency info" OFF too, but it did not help.

**Comment by licaon-kter** [comment]
Updated to build 838 and it's fixed (no settings changed). Thanks.
