### ISSUE TITLE
Slippery NavBar is not working

### ISSUE THREAD

**Issue by yzyboost** [wasdennnoch/AndroidN-ify#1355]
**Description**
I enabled the slippery navbar option in the module but as you can see on the screenshot, yeah its working but the interface has no changes.
**Module version (build version)**
Latest build
![screenshot_20170605-003828](https://cloud.githubusercontent.com/assets/23522663/26763595/e3212d46-4987-11e7-87f9-6ec1f79c76b1.png)

**Xposed log / logcat**

**Comment by yzyboost** [comment]
I reboot my phone twice but nothing changes.

**Comment by yzyboost** [comment]
@paphonbth

**Comment by paphonbth** [comment]
There is no appearance change. But when you touch the navbar and slide out of it, the touch event will slip into the window underneath.

Watch the video if you don't understand.
https://drive.google.com/file/d/0B0KEA8vnuJucQ29jaHJMSUI0S0U/view?usp=drivesdk
