### ISSUE TITLE
Nougat

### ISSUE THREAD

**Issue by maxsoso10** [wasdennnoch/AndroidN-ify#1395]
**Description**

**Module version (build version)**

**Xposed log / logcat**

**Comment by maxsoso10** [comment]
:)

**Comment by suphon-t** [comment]
What do you mean?

**Comment by maxsoso10** [comment]
Roms for Root my device
ECHO_STUDIO
Android 7.0 Nougat

**Comment by suphon-t** [comment]
This module is only for Lollipop and Marshnallow.

**Comment by maxsoso10** [comment]
Oh okay
