### ISSUE TITLE
[Feature request] Ability to hide the "wrench" when system UI tuner is enabled

### ISSUE THREAD

**Issue by vemacs** [wasdennnoch/AndroidN-ify#141]
Specifically, this thing:

![](https://i.imgur.com/RLawNRe.png)

The only way to customize tiles on stock is via the system UI tuner, and the wrench is an eyesore. It would be cool if there was a setting to hide it.

**Comment by wasdennnoch** [comment]
Added with 7f36f6340ee7ca2ffee0cb75be0088b55ba1af47
