### ISSUE TITLE
Wrong height in custom notifications

### ISSUE THREAD

**Issue by TioaTyan** [wasdennnoch/AndroidN-ify#142]
NeteaseCouldMusic's lockscreen notification has a color area.
APP:com.netease.couldmisic
https://drive.google.com/file/d/0B1Zi_xM0omB8bHF2aGVOMXNaS2M/view?usp=docslist_api
https://drive.google.com/file/d/0B1Zi_xM0omB8UUJmMFVRNDhQRzg/view?usp=drivesdk

**Comment by TioaTyan** [comment]
look at here:https://drive.google.com/file/d/0B1Zi_xM0omB8bHF2aGVOMXNaS2M/view?usp=docslist_api

**Comment by TioaTyan** [comment]
https://drive.google.com/file/d/0B1Zi_xM0omB8ckViX2xhZ3d0LWM/view?usp=drivesdk

another song

**Comment by TioaTyan** [comment]
poweramp also has this problem:https://drive.google.com/file/d/0B1Zi_xM0omB8UUJmMFVRNDhQRzg/view?usp=drivesdk

**Comment by wasdennnoch** [comment]
This is a problem with custom notifications in general; every notification gets the new height, but most don't support it. Still an issue thas has to be fixed.

**Comment by TioaTyan** [comment]
😝

**Comment by paphonbth** [comment]
Not possible. It is due to how custom notification works and I can't change it.
![Notification.Builder.setContent](http://puu.sh/oMJJB/3d61d18d17.png)

**Comment by wasdennnoch** [comment]
@paphonbth https://github.com/android/platform_frameworks_base/blob/e71ecb2c4df15f727f51a0e1b65459f071853e35/packages/SystemUI/src/com/android/systemui/statusbar/ExpandableNotificationRow.java#L305
