### ISSUE TITLE
[Bug] Heads up full width

### ISSUE THREAD

**Issue by BlackGhost12** [wasdennnoch/AndroidN-ify#157]
Notifications can not be at full size when you first arrive.
![screenshot_2016-05-10-21-10-24](https://cloud.githubusercontent.com/assets/19236621/15157390/1022b17e-16f4-11e6-9302-bae8e4b1b1e4.png)

**Comment by BlackGhost12** [comment]
[xposed_error_20160510_211247.zip](https://github.com/wasdennnoch/AndroidN-ify/files/257828/xposed_error_20160510_211247.zip)

**Comment by BlackGhost12** [comment]
Still no improvement. 😢😞

**Comment by wasdennnoch** [comment]
I currently don't know what is causing it, for some users the volume panel isn't full width and heads up notifications sometimes aren't too. I couldn't find any hint in the source code of the ROMs.

**Comment by BlackGhost12** [comment]
Okey 👌 I was already using eXistenZ Lollipop. Now I will upgrade to version Marshmallow eXistenZ. Custom Rom I think the problem is originating from.

**Comment by BlackGhost12** [comment]
@wasdennnoch

**Comment by PwnicornDev** [comment]
I have the same problem on CM12.1

**Comment by BlackGhost12** [comment]
@PwnicornDev  I open again then.

**Comment by BlackGhost12** [comment]
Fixed Existenz Marsmallow. It does not work in Lollipop. Sourced from a problem Rom.
