### ISSUE TITLE
[Bug] Space

### ISSUE THREAD

**Issue by BlackGhost12** [wasdennnoch/AndroidN-ify#160]
Although he does not know. I have plenty of space to stay with my line I show?
![sketch-1462909682359](https://cloud.githubusercontent.com/assets/19236621/15160282/9450c4e2-1701-11e6-908f-4244178cc7ee.png)

**Comment by wasdennnoch** [comment]
This is the default implementation of Android, we didn't change that yet. I first have to look how it looks on N.

**Comment by BlackGhost12** [comment]
Okey Thanks 😊
