### ISSUE TITLE
VK app without name :(

### ISSUE THREAD

**Issue by vlw** [wasdennnoch/AndroidN-ify#172]
![screenshot_20160511-164127](https://cloud.githubusercontent.com/assets/6003820/15184551/49f27876-179e-11e6-891f-0d7b11390f18.png)
![screenshot_20160511-164133](https://cloud.githubusercontent.com/assets/6003820/15184556/4d1c5058-179e-11e6-9c8f-61c65285bae4.png)

**Comment by wasdennnoch** [comment]
Have you tried the alternative way of getting the app name in the settings?

**Comment by vlw** [comment]
Yep, tried.. No showing and with alternative way, and without alternative way

**Comment by vlw** [comment]
Maybe you will change way to gey app name? Need to put app name from this 
![image](https://cloud.githubusercontent.com/assets/6003820/15188396/37f46e44-17ae-11e6-910d-a02770334e95.png)

**Comment by vlw** [comment]
"Hook" this "window" and get this text

**Comment by wasdennnoch** [comment]
Just wondering if this is fixed with the latest build? Paphonb modified the name fetching a bit.

**Comment by vlw** [comment]
Yep, it was fixed. Thx
