### ISSUE TITLE
White pixel while opening QS-bar

### ISSUE THREAD

**Issue by vlw** [wasdennnoch/AndroidN-ify#173]
![screenshot_20160511-163706](https://cloud.githubusercontent.com/assets/6003820/15184665/d1594dda-179e-11e6-99b4-254d857ff0ad.png)
![screenshot_20160511-163814](https://cloud.githubusercontent.com/assets/6003820/15184667/d40c9884-179e-11e6-9b85-a4ccb1fe7729.png)
![screenshot_20160511-163841](https://cloud.githubusercontent.com/assets/6003820/15184669/d5d1b550-179e-11e6-9982-c4633fd28c7b.png)

**Comment by wasdennnoch** [comment]
I've noticed that too, you can barely see it. The QS panel background still has rounded corners.

**Comment by wasdennnoch** [comment]
Fixed with d1b86e8d71a61035dd58beb7644d28834719719e

**Comment by vemacs** [comment]
This is a stupidly tiny issue, but if you trigger the issue and then hold (not tap) the indicator, the double ripple is still there (for that one time). Fix would be to set rendering mode at the end of handleShowingDetail or via an onTouchListener.

**Comment by wasdennnoch** [comment]
That means something iss constantly setting the layer type. Which ROM do you use? Or everybody else having this issue?

**Comment by vemacs** [comment]
Oh, sorry about posting on the wrong issue. But it's a Nexus factory ROM, and I don't think it's constant (again, it's only immediately after I flip the switch in the header and hold the indicator).

**Comment by wasdennnoch** [comment]
I'll add that too.
