### ISSUE TITLE
Wrong QuickQS ripple position, no icon animation

### ISSUE THREAD

**Issue by vlw** [wasdennnoch/AndroidN-ify#177]
![screenshot_20160511-191157](https://cloud.githubusercontent.com/assets/6003820/15188609/469ba268-17af-11e6-91fd-4d355c83ddff.png)

**Comment by wasdennnoch** [comment]
Implemented with 41c954d67332b7718da9eb19017f46ba5f6e0b68 and 3779c5aff3bf829d26b61586b9ba15cc3fbb7a30
