### ISSUE TITLE
[BUG] Screenshot

### ISSUE THREAD

**Issue by PyROMStaff** [wasdennnoch/AndroidN-ify#182]
Hi, 
I think that the two buttons for share and delete a Screenshot are not in the correct place. 
http://uploads.tapatalk-cdn.com/20160510/d3892758ddffbe30235b51ec413f8eac.jpg

**Comment by paphonbth** [comment]
Which build are you using? This has been fixed in e647b5c

**Comment by PyROMStaff** [comment]
I've just updated and now it is working, thanks for help
