### ISSUE TITLE
[Feature request] Sliding Quick Setting

### ISSUE THREAD

**Issue by pirasalbe** [wasdennnoch/AndroidN-ify#183]
Hi, 
Just as asked on xda could you add sliding qs such as LG??? 
https://mega.nz/#!0oIyQCDD!9KfobMgWPlata3odquIQZkdpeOvWK7qwzI6jcm-vMEA

**Comment by wasdennnoch** [comment]
I'm actually not that sure if I'll do that. The main problem would be the animation of the tiles. Secondly, that's not how it's implemented in N. Third, there is a panel to hold all QS. Adding all QS to the row would make the panel redundant and vice-versa.
