### ISSUE TITLE
The vpn text isn't got a correct color

### ISSUE THREAD

**Issue by LKc1949** [wasdennnoch/AndroidN-ify#186]
![screenshot_20160512-135414](https://cloud.githubusercontent.com/assets/17155723/15205369/4258463e-17dc-11e6-894c-d44c235def76.png)
The vpn warn text in quick settings isn't got a correct color,it should be bright but it's dark.

**Comment by vlw** [comment]
Are you using a black notification theme? On white notification theme all good
![screenshot_20160512-085942](https://cloud.githubusercontent.com/assets/6003820/15205474/3baaf9dc-1820-11e6-80ac-60c34e8dbc29.png)

**Comment by LKc1949** [comment]
Oh , but i didn't applied any theme yet, probably it's a rom issue

**Comment by vlw** [comment]
CM13
![screenshot_20160512-090440](https://cloud.githubusercontent.com/assets/6003820/15205512/aaa158f4-1820-11e6-959f-735ae9356166.png)

**Comment by vlw** [comment]
Oh, lol.. Theme of notifications setting in status-bar header settings
![screenshot_20160512-090657](https://cloud.githubusercontent.com/assets/6003820/15205568/0ab50f4c-1821-11e6-9c01-283b2374d139.png)

**Comment by vlw** [comment]
Oh, it really your ROM issue, but need to fix. Pls, open a issue
