### ISSUE TITLE
Header size is different to QS tile

### ISSUE THREAD

**Issue by wyneg** [wasdennnoch/AndroidN-ify#193]
Hi!

This issue occured in a moto g XT1040, using lollipop 5.1, xposed v84 and android N-ify v76, but in v 95 still occur.

Thanks!

![screenshot_2016-05-11-05-58-06](https://cloud.githubusercontent.com/assets/18633176/15221153/a9047830-1840-11e6-8501-9af5081e460f.png)

[xposed_error_20160511_055843.docx](https://github.com/wasdennnoch/AndroidN-ify/files/261738/xposed_error_20160511_055843.docx)

**Comment by wasdennnoch** [comment]
Build 76? There's already buikd 99 which should fix some notification errors. The header issue seems to affect pretty much all motorola ROMs. And the header still has elevation, which means that the layout modified seems not to be found although there's no such error in the log. Can you plese post your (preferably deodexed) SystemUI.apk here?

**Comment by wyneg** [comment]
v76 was first installed in that device (girlfriend's moto g 4g), now she's using v95.
I'm using (in my moto g 4g) Stock ported marshmallow by lost101 and I don't have that issue.
In fact, I haven't faced issues since gap was fixed.
I will upload SystemUI.apk when I return home, thanks for response ;)

**Comment by wasdennnoch** [comment]
Should be fixed with 01dc35c35c279fbd84641e588ff518e099b9bdfd, a new build will be available soon

**Comment by wyneg** [comment]
I saw it, thanks!
