### ISSUE TITLE
Hope to reduce the date of the show, not only to reduce the time.（<string name="smaller_header_clock">）

### ISSUE THREAD

**Issue by douzicao** [wasdennnoch/AndroidN-ify#202]
![image](https://cloud.githubusercontent.com/assets/18158418/15235549/ff8f9140-18ee-11e6-8a6c-c4a9da1e1b32.png)

**Comment by poxxz** [comment]
什么ROM
2016年5月13日 上午9:44，"douzicao" <notifications@github.com>写道：

**Comment by douzicao** [comment]
new moto x xt1092 安卓6.0

**Comment by wasdennnoch** [comment]
As this got requested repeatedly, I'll add an option to provide your own date format.
