### ISSUE TITLE
Текст уведомлений, быстрые настройки | Text notifications , quick settings

### ISSUE THREAD

**Issue by BlackW030** [wasdennnoch/AndroidN-ify#233]
Модуль отличный, почти все функции работают на ура, кроме:
•В шапке уведомлений нет иконок быстрых настроек.
•На название уведомления лезет текст самого уведомления.

The module is excellent, almost all functions work with enthusiasm , except for :
• The cap is not the notification icon Quick Settings .
• The name of the text of the notification climbs notice.

Android 5.0.2 Stock, Xposed Framework v84, DPI 213, Display 4,5" 854*480.

**Comment by wasdennnoch** [comment]
Can you please provide your Xposed log?

**Comment by BlackW030** [comment]
If the logs are in Xposed Installer, they are not

**Comment by wasdennnoch** [comment]
If the log is empty please post the logcat: `adb logcat -v time > logcat.txt`

**Comment by vlw** [comment]
Какая прошивка? Версия андроид? Модель телефона?
И приложите скриншоты
