### ISSUE TITLE
QS tile not showing in my Qs header and clear all button not working

### ISSUE THREAD

**Issue by Androdiver** [wasdennnoch/AndroidN-ify#245]
Here is Screenshot
![1463393051464](https://cloud.githubusercontent.com/assets/19375581/15286635/bc9d3ff6-1b7b-11e6-9594-baa0e8f0c7f2.jpg)

**Comment by wasdennnoch** [comment]
If the log is empty, can you please post your logcat here? `adb logcat -v time > logcat.txt`

**Comment by Androdiver** [comment]
Ok sure wait

**Comment by Androdiver** [comment]
[N-ify.txt](https://github.com/wasdennnoch/AndroidN-ify/files/265165/N-ify.txt)

**Comment by wasdennnoch** [comment]
That's a short log (you need to wait some minutes after issuing this command), but there's already an error in it xD
What device are you using? Can you please post your deodexed SystemUI if available?

**Comment by Androdiver** [comment]
_

**Comment by Androdiver** [comment]
I only manage to get my stock system ui.apk



[SystemUI.pdf](https://github.com/wasdennnoch/AndroidN-ify/files/265178/SystemUI.pdf)
Please change its extension into apk before use i rename it in pdf because apk and zip getting failed to upload
Sorry

**Comment by wasdennnoch** [comment]
Hm, it's a odexed apk, as expected. Any chance you can grab a deodexed version? And which device are you using? And get a new logcat, but this time a longer one? ^^

**Comment by Androdiver** [comment]
I am using Xolo prime
Model:prime
Os version:lollipop 5.0.2
ARM version:arm7
Prossesor:mtk6582 quardcore
Ram:1 GB
Log file
[N.txt](https://github.com/wasdennnoch/AndroidN-ify/files/265186/N.txt)

And about deodexed systemUI.apk i m still trying to find

**Comment by Androdiver** [comment]
My Xposed log is now show
here is my xposed log file
[xposed_error_20160516_141642.log.txt](https://github.com/wasdennnoch/AndroidN-ify/files/265838/xposed_error_20160516_141642.log.txt)

**Comment by wasdennnoch** [comment]
Looks like a layout ID isn't found. Can you please upload your framework-res.apk here?

**Comment by Androdiver** [comment]
Here is link of my framework-res.apk
https://www.mediafire.com/download/cobq0q42zl62vqr

**Comment by wasdennnoch** [comment]
Thanks, your ROM indeed completely removed that ID. I'll have to use another way to get that view.

**Comment by Androdiver** [comment]
Please i know you can🙏

**Comment by Androdiver** [comment]
Thank you so much bro in update 153build is working

![Uploading Screenshot_2016-05-16-20-24-47.png…]()

**Comment by Androdiver** [comment]
What about clear all button it's still not working

**Comment by wasdennnoch** [comment]
Are you sure? With the latest build?

**Comment by Androdiver** [comment]
Yes i'm sure its latest build 156 and still not working

**Comment by Androdiver** [comment]
I'm so desperate😟 now in your latest build 185 status bar header icon vanish again no no no😭

**Comment by wasdennnoch** [comment]
Next log pls :P

**Comment by Androdiver** [comment]
Here is log
[logs.txt](https://github.com/wasdennnoch/AndroidN-ify/files/276280/logs.txt)

**Comment by tony8077616** [comment]
I have the same problem

**Comment by Androdiver** [comment]
If your xposed log is showing then please upload it here because my log is not showing
It can be helpful for both of us.

**Comment by wasdennnoch** [comment]
Fixed with the latest version? 412acdeef907c32e24a94ca1076aceb94d8d6761

**Comment by Androdiver** [comment]
Its not in Xposed repo from where I can get latest version or it take time to uploaded or already uploaded

**Comment by wasdennnoch** [comment]
The last builds failed; I'll post the link to the next successful one

**Comment by Androdiver** [comment]
Thanks for you effort👍👏

**Comment by wasdennnoch** [comment]
https://ci.paphonb.xyz/job/AndroidN-ify/189/

**Comment by vpeace** [comment]
same issue with the one plus 2 running Oxydium bases on Oxygen Os 3.0 beta

**Comment by Androdiver** [comment]
Why you don't try with latest build the problem is solve for me everything is fine except clear all button its still no working #wasdennnoch

**Comment by vpeace** [comment]
I am on the latest build the clear all button works just fine but there are some problems with twilight notification and the status bar

**Comment by wasdennnoch** [comment]
If there are any other issues, please open a new issue to keep it organized.
