### ISSUE TITLE
Xperia z5 dual

### ISSUE THREAD

**Issue by solirf** [wasdennnoch/AndroidN-ify#249]
Completely broke statusbar headers on #144
Layout error on log

**Comment by wasdennnoch** [comment]
Well... where  is the log?

**Comment by solirf** [comment]
Here my log
https://drive.google.com/file/d/0B6qIFeOWWC5kQ2xXOUptb2Zhbkk/view?usp=drivesdk

**Comment by wasdennnoch** [comment]
Fixed with 60d8e97ed2ac568e1d0cf0a6cae54c3dd9d0e513

**Comment by solirf** [comment]
Ton of error

**Comment by wasdennnoch** [comment]
Well, next log please

**Comment by solirf** [comment]
Version #157

**Comment by wasdennnoch** [comment]
The Xposed log. I can see the version in the log.

**Comment by solirf** [comment]
And this one

**Comment by solirf** [comment]
https://drive.google.com/file/d/0B6qIFeOWWC5kTVpjUEFFMkt6aXc/view?usp=drivesdk

**Comment by solirf** [comment]
Still ERROR 

https://drive.google.com/file/d/0B6qIFeOWWC5kUDd6dlRWVE9fSDg/view?usp=drivesdk

**Comment by solirf** [comment]
https://drive.google.com/file/d/0B6qIFeOWWC5kSHlHclhiZWJRNGM/view?usp=drivesdk

**Comment by solirf** [comment]
i have to restart twice systemui  for any change 


https://drive.google.com/file/d/0B6qIFeOWWC5kTHV2Q0RDVTJZNlE/view?usp=drivesdk

**Comment by wasdennnoch** [comment]
Can you please post your SystemUI here? The error is thrown because the LayoutParams of a view seem to be null which usually shouldn't be the case.

**Comment by solirf** [comment]
Sure mate 

Here Odex SystemUI : 
https://drive.google.com/open?id=0B6qIFeOWWC5kY3BfcHMwcVA1dGs

And Deodexed :
https://drive.google.com/open?id=0B6qIFeOWWC5kVDFzWUtXR3RWaVE

**Comment by wasdennnoch** [comment]
The issue should be fixed since several builds.
