### ISSUE TITLE
Icon 'no recents' hiding too slowly

### ISSUE THREAD

**Issue by vlw** [wasdennnoch/AndroidN-ify#250]
![screenshot_20160516-110911](https://cloud.githubusercontent.com/assets/6003820/15283947/e230b4e8-1b56-11e6-95b4-d01d444a7ece.png)
![screenshot_20160516-110842](https://cloud.githubusercontent.com/assets/6003820/15283949/eb6d0fd4-1b56-11e6-97b7-1f5534b87c53.png)
![screenshot_20160516-110858](https://cloud.githubusercontent.com/assets/6003820/15283952/f387b228-1b56-11e6-8dab-ce6a0d5cb48c.png)

**Comment by wasdennnoch** [comment]
How long does it take to disappear? On my device it's only like 0.1 second. Also the module only replaces the layout, it doesn't modify any code responsible for managing this image.

**Comment by vlw** [comment]
Yeah, it take very few time (about 0.1s), but it's a bug, and need to be fixed.

**Comment by vlw** [comment]
Screenshot taken with the 50th attempt, lol

**Comment by wasdennnoch** [comment]
Not sure if this is a bug, I get the same behaviour with that tweak disabled.

**Comment by vlw** [comment]
Oh really.. But without this option works blackout , but with it - no

**Comment by wasdennnoch** [comment]
I just had a look at the code and all it's doing is to replace the layout, it does nothing else. And I still get the same delay when completely disabling the module, so it's definitely how it's supposed to be.
