### ISSUE TITLE
Blacklist

### ISSUE THREAD

**Issue by tiagolinik** [wasdennnoch/AndroidN-ify#257]
Blacklist not working on cm13...

**Comment by wasdennnoch** [comment]
The blacklist needs a reboot to take effect. Also note that the height will still be changed no matter if the app is blacklisted.

**Comment by tiagolinik** [comment]
I put on the black list and is the same and the notification is the same thing , still great !

**Comment by wasdennnoch** [comment]
Still an issue? If so, send some logs first and maybe some screenshots.
