### ISSUE TITLE
[Feature Request] Add Battery Icon to expanded StatusBar

### ISSUE THREAD

**Issue by tazzkiller** [wasdennnoch/AndroidN-ify#259]
it's possible to add battery icon on the expanded  StatusBar ?

**Comment by wasdennnoch** [comment]
There's already another request for that ( #181 )

**Comment by tazzkiller** [comment]
i think it's not the same, i didn't talk about the tile but the statusbar icon of battery

**Comment by wasdennnoch** [comment]
Won't add that as there's no battery icon in N, it got replaced by the battery tile which will be implemented in the future.
