### ISSUE TITLE
Cellular network strength appears empty the expanded QS view

### ISSUE THREAD

**Issue by prasab** [wasdennnoch/AndroidN-ify#261]
The signal strength of cellular network is actually full. but when i expanded the quick settings it appears empty.

attaching a screen grab and also some logs.

Build: #159 
Device Affected: Moto G 2015 stock 6.0.1

![screenshot_20160519-210918](https://cloud.githubusercontent.com/assets/19474293/15399686/46e62a7e-1e06-11e6-88c4-a6775247e8ca.png)
[logcat_and_device_info.zip](https://github.com/wasdennnoch/AndroidN-ify/files/272906/logcat_and_device_info.zip)

**Comment by wasdennnoch** [comment]
I'm not modifying the tile in the panel, I'm only fetching their new states to update the QS in the header. Dies this happen frequently?

**Comment by prasab** [comment]
It used to happen all the time. I just updated from 159 to the latest #182 don't seem to witness it.

**Comment by prasab** [comment]
![screenshot_20160522-112019](https://cloud.githubusercontent.com/assets/19474293/15452522/567441b4-200f-11e6-84a0-f6446b70daf7.png)

**Comment by prasab** [comment]
H on the data QS getting truncated. Build 185

**Comment by wasdennnoch** [comment]
3f561d90217332cee735e265f54713e4304b570a added an option to use the old positioning method.
