### ISSUE TITLE
Setting does not show additional information 

### ISSUE THREAD

**Issue by Animeshkr13** [wasdennnoch/AndroidN-ify#281]
In setting it does not show any addition information.. M on xperia z1...and thnks for fixing recent and header overlapping...

**Comment by wasdennnoch** [comment]
I think Xperia changed the settings layout so that the summary views don't really exist anymore, but you can still send me a log and your Settings.apk please.

**Comment by Animeshkr13** [comment]
Hv u got my email

**Comment by wasdennnoch** [comment]
Which mail?

**Comment by Animeshkr13** [comment]
[Settings.apk.zip](https://github.com/wasdennnoch/AndroidN-ify/files/275333/Settings.apk.zip)
[error.zip](https://github.com/wasdennnoch/AndroidN-ify/files/275335/error.zip)

**Comment by Animeshkr13** [comment]
Change error zip into error.log..... I just can send it in that way... N tnk u

**Comment by wasdennnoch** [comment]
Ok, there is no summary view at all. I'll update the settings code after releasing the next official version and add an option to restore the views.

**Comment by Animeshkr13** [comment]
Thnk u...n ur work is really grt..

**Comment by Animeshkr13** [comment]
Setting is still lyk bfr..no change..

**Comment by wasdennnoch** [comment]
I haven't changed anything yet

**Comment by Animeshkr13** [comment]
Hv u pln for it...??

**Comment by lukss12** [comment]
Look at the "keep in mind" tag I think he will work on this later when some bigger problems got solved :)

**Comment by Animeshkr13** [comment]
I just flashed cm 13(unofficial) on my xperia z1.At first it just updates lyk normal but thn after frm build no. 492 i can't update it...after installing it just say it can't be installed....

**Comment by wasdennnoch** [comment]
Uninstall the previous version.

**Comment by Animeshkr13** [comment]
![screenshot_20160802-231500](https://cloud.githubusercontent.com/assets/19388615/17338903/132c8aa2-5907-11e6-8791-658c838504a6.png)

**Comment by lukss12** [comment]
Just uninstall and install

**Comment by Animeshkr13** [comment]
It works..
Thnk u...
