### ISSUE TITLE
Tapatalk doesn't get a correct tile

### ISSUE THREAD

**Issue by LKc1949** [wasdennnoch/AndroidN-ify#297]
![1463898110750](https://cloud.githubusercontent.com/assets/17155723/15452623/e3950942-1fbb-11e6-9a0c-126963db924e.png)
All apps are got correct tiles except Tapatalk.(it shows a package name instead)

Here's the log file:
[xposed_error_20160522_141733.log.txt](https://github.com/wasdennnoch/AndroidN-ify/files/276205/xposed_error_20160522_141733.log.txt)

**Comment by haseoxth** [comment]
Enable alternative app name loading method in module's settings.
It won't have much negative impact as the description said.
