### ISSUE TITLE
N-style expand animation

### ISSUE THREAD

**Issue by vemacs** [wasdennnoch/AndroidN-ify#303]
https://youtu.be/dxbL37IFVRo?t=1m56s

* Ripple is not clipped when expand animation is occurring

* Tiles animate their position

**Comment by vlw** [comment]
It fixed with 5d26502be8a2219269b311de6e7b66b1af454365

**Comment by vemacs** [comment]
The latest builds have failed, but I tried the experimental builds and the animation does not work properly on stock 6.0.1.

**Comment by vemacs** [comment]
Build #250 does not work with stock 6.0.1 (latest Nexus factory image). The tile positions fail to animate at all:

![](http://i.imgur.com/MatELoe.png)

I am guessing it was only developed for CyanogenMod. 

After pressing "Edit tiles" and exiting, the tiles do animate but move to an incorrect position (upper-left corner): 

![](http://i.imgur.com/j8QmIK4.png)

@paphonbth, can you please look into it? There are no exceptions in my Xposed log.
