### ISSUE TITLE
Oxygen os in Oneplus two

### ISSUE THREAD

**Issue by Glitte** [wasdennnoch/AndroidN-ify#309]
Hello，thank you for your contribution ，I really like your n module,but the n can't work in oxygen os.Can you help us？thankyou .the Status bar header not work ,If you have time, please look at it, after all, oxygen and AOSP are very close to,thanks

**Comment by superhupeng** [comment]
So does my oneplus2  dont work, too.

**Comment by wasdennnoch** [comment]
There are already two other OOS issues open, please use them.
