### ISSUE TITLE
Quick Quick Settings Tiles Not Aligned Correctly

### ISSUE THREAD

**Issue by tbremer19** [wasdennnoch/AndroidN-ify#314]
Hi! I'm using a OnePlus 2 running the latest CM13 nightlies. Since the last few builds of the module the "quick as tiles" are not aligned correctly (see screenshot). I think they are supposed to align with the clock.
![screenshot_20160524-192200](https://cloud.githubusercontent.com/assets/5941636/15513568/7364aff2-21e5-11e6-9796-233cef5cd339.png)

**Comment by tbremer19** [comment]
@wasdennoch do you need a log for that issue?

**Comment by wasdennnoch** [comment]
I'm having the same issue too for some reason, there ia space as the first item although there shouldn't be.

**Comment by wasdennnoch** [comment]
Fixed with f67961cd8781a359eb36e9c8d965d7b673b4bb20
