### ISSUE TITLE
QS tiles not showing in status bar

### ISSUE THREAD

**Issue by Danielcaz** [wasdennnoch/AndroidN-ify#316]
Hi the QS tiles are not showing in my status bar it's just blank i am using a ZTE V6 with android 5.0.2

**Comment by Danielcaz** [comment]
![screenshot_2016-05-24-14-00-53](https://cloud.githubusercontent.com/assets/19558375/15516509/a81a56de-21b8-11e6-8818-4bc958f417af.png)

**Comment by wasdennnoch** [comment]
Well, without a log I don't know what's wrong.

**Comment by Danielcaz** [comment]
Oh how do i send yo the log?

**Comment by Danielcaz** [comment]
[alogcat.2016-05-24-15-24-33-0500.txt](https://github.com/wasdennnoch/AndroidN-ify/files/280456/alogcat.2016-05-24-15-24-33-0500.txt)

Is it that?

**Comment by wasdennnoch** [comment]
The Xposed log should be enough, there's nothing in that short logcat

**Comment by Danielcaz** [comment]
[xposed_error_20160524_163033.zip](https://github.com/wasdennnoch/AndroidN-ify/files/280564/xposed_error_20160524_163033.zip)

Change it from .zip to .log i couldn't upload it in .log

**Comment by wasdennnoch** [comment]
"Android version N (SDK 21)" I see :P

Is your ROM deodexed? If so, please send me your SystemUI. If not, we'll have to experiment.

[Blade V6 (ZTE); no QSTile.getState()]

**Comment by Danielcaz** [comment]
Haha I did it so I would go with the N Easter egg xD


[SystemUI.zip](https://github.com/wasdennnoch/AndroidN-ify/files/282737/SystemUI.zip)

In that zip is the apk and odex file
Is it what you need?

**Comment by wasdennnoch** [comment]
I actually can't do anything with a odex, I need a dex to decompile it, and only you could deodex the apk, but that would take too much time, so I'll just build a test version that checks for right methods.

**Comment by wasdennnoch** [comment]
Please install this version and post the logs: http://www.mediafire.com/download/labtx20nirxo60p/Android_N-ify_getstate_search.apk

**Comment by Danielcaz** [comment]
![screenshot_2016-05-25-15-15-20](https://cloud.githubusercontent.com/assets/19558375/15554845/956984b4-228b-11e6-9b36-0fb89b11cbc1.png)
 I couldn't install it

**Comment by Danielcaz** [comment]
I downloaded it from a another browser and could install it

**Comment by Danielcaz** [comment]
[xposed_error_20160524_163131.txt](https://github.com/wasdennnoch/AndroidN-ify/files/282906/xposed_error_20160524_163131.txt)

**Comment by wasdennnoch** [comment]
Are you sure that you used this version and rebooted? The log doesn't contain the information I added to the build.

**Comment by Danielcaz** [comment]
Yes let me try doing it again

**Comment by Danielcaz** [comment]
[xposed_error_20160525_160941.txt](https://github.com/wasdennnoch/AndroidN-ify/files/283001/xposed_error_20160525_160941.txt)

I installed then rebooted

**Comment by wasdennnoch** [comment]
Thanks, looks like I have to add some more tests (or your ROM completely removed that method and I have to directly get the field, we'll see).

**Comment by wasdennnoch** [comment]
Any change in build 223?

**Comment by Danielcaz** [comment]
Yes i just installed it and the QS tiles are there you are awesome!

**Comment by Danielcaz** [comment]
The QS tiles disappeared again and when I touch the edit tiles button the systemUI restarts 
[xposed_error_20160605_094631.txt](https://github.com/wasdennnoch/AndroidN-ify/files/299377/xposed_error_20160605_094631.txt)

**Comment by wasdennnoch** [comment]
That's only a part of the log, but it looks like you are running a LP ROM. The animations aren't supported on LP yet.

**Comment by wasdennnoch** [comment]
Disable the fancy QS transition to fix it for now.

**Comment by Danielcaz** [comment]
I disabled it and they are back thank you
