### ISSUE TITLE
Not working on moto x play

### ISSUE THREAD

**Issue by amitmittal117** [wasdennnoch/AndroidN-ify#335]
The application is not working on moto x play

**Comment by amitmittal117** [comment]
The Action Bar displays Module not activated after refreshing several times. I also have restarted my device several times but there is no change in the application

**Comment by wasdennnoch** [comment]
Have you tried reinstalling the app and are you sure that you activated it in the Xposed installer?

**Comment by amitmittal117** [comment]
I flashed my device by clockwood recovery mode.So installing xposed install give me errors regarding framework.

**Comment by wasdennnoch** [comment]
If Xposed itself isn't working it has nothing to do with the module.
