### ISSUE TITLE
Battery in QS row

### ISSUE THREAD

**Issue by ja-som** [wasdennnoch/AndroidN-ify#339]
Hi, battery icon in QS row does not look good on my Nexus 7 II with stock Android 6.0.1 and Android N-ify build 237.
Icon is narrow and there is too much space on the right side.

If you need more info, please let me know ;-)

![img_20160531_224605](https://cloud.githubusercontent.com/assets/5942380/15690059/09887bca-2782-11e6-9ebb-c28db85bae16.jpg)

**Comment by Leo3418** [comment]
Are you using GravityBox v6.1.2?
I faced this issue also on my Galaxy S4.

**Comment by ja-som** [comment]
Yes, I do.

**Comment by paphonbth** [comment]
There's a workaround for this.
See ba574a6

**Comment by ja-som** [comment]
For me, this is solved, now I can disable QS editor, which also disable this battery icon in QS row, or maybe icon and position is also improved, unrelated to QS editor. Thank you :) 👍
