### ISSUE TITLE
Crash and notification

### ISSUE THREAD

**Issue by Animeshkr13** [wasdennnoch/AndroidN-ify#344]
Aftr the last update there r many bugs like in quick qs the battery tile didnt show and also the down button is upside down...the edit button didnt work and system crashes aftr clicking it...and as a reminder..setting didnt show summary as befr..

**Comment by Animeshkr13** [comment]
[error.zip](https://github.com/wasdennnoch/AndroidN-ify/files/294242/error.zip)
Change this into .log

**Comment by Animeshkr13** [comment]
![screenshot_2016-06-02-02-12-07](https://cloud.githubusercontent.com/assets/19388615/15725030/7ddd0ed8-2867-11e6-9fac-a4e08239487e.png)
See the last tile ...

**Comment by Animeshkr13** [comment]
![_20160602_022358](https://cloud.githubusercontent.com/assets/19388615/15725359/261e629e-2869-11e6-84d3-f8d010a3de6a.JPG)

Slow Expanding animation cause this

**Comment by wasdennnoch** [comment]
The QS animation isn't compatible with Android Lollipop yet.
