### ISSUE TITLE
Tile positions do not animate properly (or at all) on stock 6.0.1 ROM

### ISSUE THREAD

**Issue by vemacs** [wasdennnoch/AndroidN-ify#355]
(repost of https://github.com/wasdennnoch/AndroidN-ify/issues/303#issuecomment-223105103)

Build #250 does not work with stock 6.0.1 (latest Nexus factory image). The tile positions fail to animate at all:

![](http://i.imgur.com/MatELoe.png)

After pressing "Edit tiles" and exiting, the tiles do animate but move to an incorrect position (upper-left corner): 

![](http://i.imgur.com/j8QmIK4.png)

@paphonbth, can you please look into it? There are no exceptions in my Xposed log.

**Comment by vlw** [comment]
Was have same on CM13, but after editing tiles i lose this issue :)

**Comment by Raikem** [comment]
Same problem here, sometimes quick qs row doesnt appear, log here forum.xda-developers.com/attachment.php?attachmentid=3770360&d=1464885586

**Comment by xpduyson** [comment]
animation not working on CM12.1 too

**Comment by wasdennnoch** [comment]
It won't work on Lollipop for now. I'm having the same animation issues btw, that makes it a bit easier to fix.

**Comment by Raikem** [comment]
If you press edit and then block the screen animations kind of work.

**Comment by iamanubhavnaidu** [comment]
I'm using Nexus 5 stock.. But the same problem running on 6.0.1 and the latest build. Help me out

**Comment by andresxd98** [comment]
I have exactly the same problem 6.0.1 AOSP ROM.

**Comment by vemacs** [comment]
The problem is with this method call in QuickQSPanel:

            getRelativePosition(ai1, qsTileView, StatusBarHeaderHooks.mQsPanel);

**Comment by vemacs** [comment]
Suspicions about layout inflation confirmed.

**Comment by iamanubhavnaidu** [comment]
How should we change those commands?

**Comment by wasdennnoch** [comment]
I should have time to fix this today. I already thought that it has something to do with layout inflation, a `OnGlobalLayoutListener` should fix it.

**Comment by iamanubhavnaidu** [comment]
Thank you.. Please fix it ASAP :)

**Comment by iamanubhavnaidu** [comment]
By when will this issue be fixed?

**Comment by wasdennnoch** [comment]
Good question. The layout listener didn't work and the attempt posted earlier did neither (or I forgot to revert something else when trying it). I'm a bit busy currently, so it will take some more time.

**Comment by iamanubhavnaidu** [comment]
It is worth waiting. :) Thanks for the effort. :)

**Comment by vemacs** [comment]
Here's a ghetto idea: expand the settings without the animation, with all views at 0.0 opacity, on the first button press. Then, do the relative position measurements, close the settings, restore the opacity, and then animate.

**Comment by justinkruit** [comment]
As far as I notice, the bug started appearing after this commit: https://github.com/wasdennnoch/AndroidN-ify/commit/fb2e3d8fa0c824296d5ee1b99a1fd13603db1669
I'm using a version before that (Jenkins build 237) which doesn't have any problems.

**Comment by wasdennnoch** [comment]
This commit doesn't change anything of the original animation

**Comment by justinkruit** [comment]
Got the feeling I pasted the wrong commit. I've looked, and I'm pretty sure that in this commit it all broke: https://github.com/wasdennnoch/AndroidN-ify/commit/5d26502be8a2219269b311de6e7b66b1af454365 
Quite a large commit, but I'm pretty if started here

**Comment by wasdennnoch** [comment]
Yes, that commit added the whole animation, it wan't there before lol

**Comment by justinkruit** [comment]
Only problem, is that quite some people don't actually have any animations. Just jumping

**Comment by vemacs** [comment]
See the original post. If you edit tiles and close, the broken animation starts.

**Comment by iamanubhavnaidu** [comment]
Does the latest build solve this problem? 
I switched to cm13 just for this module😁😁

**Comment by paphonbth** [comment]
@iamanubhavnaidu It's always been working on CM13

**Comment by iamanubhavnaidu** [comment]
@paphonbth I used stock before and there I had this problem... So I switched to cm13 because it was good on it. That's what I meant to say..😉

**Comment by vemacs** [comment]
Any way to do this with math based on known dimensions, if reading off the layouts isn't working? Or finding a way to invisibly expand the quick settings on first launch?

**Comment by wasdennnoch** [comment]
Wait, how did I manage to close this from the PR? Whatever, this should be working now except for a little jump at the end, can anybody confirm?

**Comment by vemacs** [comment]
Yeah, exactly what you said.

**Comment by Raikem** [comment]
This is fixed now, and the little jump too, but when restarting system UI (even if you dont change the defaul settings) the animation doesnt work correctly, the quickQS tiles go to the left when pulling down.
