### ISSUE TITLE
Status bar tweaks don't work well with bright themes

### ISSUE THREAD

**Issue by chenasraf** [wasdennnoch/AndroidN-ify#356]
Here's an example: http://imgur.com/gallery/n8rFW

**Comment by wasdennnoch** [comment]
Any change beginning with build 290?

**Comment by chenasraf** [comment]
How can I get it? It's not listed in Xposed Installer. Do I have to use source?

**Comment by wasdennnoch** [comment]
It's a snapshot version, there is a link in the second post in the XDA thread where you can find them.
