### ISSUE TITLE
Baterry tile only with "!"

### ISSUE THREAD

**Issue by vlw** [wasdennnoch/AndroidN-ify#357]
CM13
![screenshot_20160601-233544](https://cloud.githubusercontent.com/assets/6003820/15724870/c11a2f20-2851-11e6-9ba7-477623acd7d2.png)

**Comment by vlw** [comment]
![screenshot_20160602-073222](https://cloud.githubusercontent.com/assets/6003820/15734108/a8fb4f3a-2894-11e6-8269-2d18747ac983.png)

In 100%

**Comment by TheDorkKnightRises** [comment]
Confirmed on COS 13 (OnePlus One) too.
Permanent "!" on custom Battery tile.

**Comment by wasdennnoch** [comment]
This should be fixed with the latest snapshots. Anybody can confirm?

**Comment by TheDorkKnightRises** [comment]
Can confirm. Fixed on COS 13, OnePlus One.

![screenshot_20160615-013321-01](https://cloud.githubusercontent.com/assets/7022352/16057948/d7f1564a-3299-11e6-9b83-a37b51a8f1f5.jpeg)
![screenshot_20160615-013325](https://cloud.githubusercontent.com/assets/7022352/16057966/e5184658-3299-11e6-93cf-f26ea590e8d3.png)
![screenshot_20160615-013331](https://cloud.githubusercontent.com/assets/7022352/16057971/eba3536e-3299-11e6-90f5-46a700ed4894.png)
