### ISSUE TITLE
Overlapping QuickQS isons in animation

### ISSUE THREAD

**Issue by vlw** [wasdennnoch/AndroidN-ify#359]
![screenshot_20160601-234629](https://cloud.githubusercontent.com/assets/6003820/15725156/3444dd6e-2853-11e6-9aec-2c3779f36c15.png)

**Comment by wasdennnoch** [comment]
Could you please post a video that shows the bug? Does the tile just appear or should it be in the heder?

**Comment by vlw** [comment]
[Screencast_2016-06-03-08-06-08.mp4.zip](https://github.com/wasdennnoch/AndroidN-ify/files/296948/Screencast_2016-06-03-08-06-08.mp4.zip)

**Comment by wasdennnoch** [comment]
So you only mean the overlapping tiles. This is unavoidable with the current animation style. There is a different animation in the second preview that may have fixed it, but that's more complex to implement.
