### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Animeshkr13** [wasdennnoch/AndroidN-ify#374]
Aftr clicking the edit tile..the system ui crashes alwys..and also battery tile didnt show at all ...plz also see the setting summary

**Comment by Animeshkr13** [comment]
[error.zip](https://github.com/wasdennnoch/AndroidN-ify/files/296008/error.zip)
Log

**Comment by wasdennnoch** [comment]
I already told you in your last issue: The tile editor isn't compatible with Android Lillipop yet! It won't work yet!
