### ISSUE TITLE
QS is not visible

### ISSUE THREAD

**Issue by BlackW030** [wasdennnoch/AndroidN-ify#383]
https://drive.google.com/file/d/0B4vZTMAK1A24b2lDOWx4RXdjSlE/view?usp=docslist_api

**Comment by BlackW030** [comment]
https://drive.google.com/file/d/0B4vZTMAK1A24VlY4X0lGN0FuU2c/view?usp=drivesdk

**Comment by wasdennnoch** [comment]
The log file is empty...

**Comment by BlackW030** [comment]
If you could , tell which way logs are N-ify?
The whole system is searched

**Comment by wasdennnoch** [comment]
Normally the Xposed log should be enough. Open he installer > logs > overflow menu > Save / Send and post it here

**Comment by BlackW030** [comment]
6 июня 2016 г. 21:17 пользователь "MrWasdennnoch" <notifications@github.com>
написал:

**Comment by BlackW030** [comment]
I close the issue , as if # 288 disable animation , the QS is functioning normally .
