### ISSUE TITLE
wifi tile and pulldown  tile is not working sometime

### ISSUE THREAD

**Issue by Androdiver** [wasdennnoch/AndroidN-ify#398]
Sometime when i press wifi tile in qs header it redirect me to wifi menu instead of trigger wifi on and also pulldown tile button not working correctly
Please take a look at image and log below
![2016_06_05_23_19_38_23_32_52](https://cloud.githubusercontent.com/assets/19375581/15807341/250337e6-2b79-11e6-8368-b251718a1cc8.gif)
[2016-06-05-23-07-49.txt](https://github.com/wasdennnoch/AndroidN-ify/files/299463/2016-06-05-23-07-49.txt)

**Comment by wasdennnoch** [comment]
There's nothing in the log, maybe the Xposed log can help out. It looks like the wifi options menu gets opened always, not sometimes. Your ROM probably changed  the secondary click behaviour, I don't know if I can change that that easy. The expand indocator recognizes the click, it has a ripple that you can see sticking out at the bottom, but the blue background seems to overlap it. Are you using a module that modifies the header is is a theme (although a theme shouldn't block the button).

**Comment by Androdiver** [comment]
No its not a theme i just set a custom image with the help of a xposed module name xqs background and i using it from long time ago your old version work properly with it.but in latest version its creating problem.
For now i disable android N click behavior and its workin fine and when i on Android n click behaviour the problem get started again i think that Android N click behavior creating some type of issue as i know Android N click behavior  should only work in inner tile but it also effecting header tile.

**Comment by wasdennnoch** [comment]
The N tile click behavior shouldn't modify any layouts, only - as the name says - the click behavior. Are you sure this isnt' happening because of the SystemUI restarts?

**Comment by Androdiver** [comment]
That why i say someTime because even when n click behavior is on after restarting system ui it problem get started and sometime later when i restart system ui problem get sovled again restard problem comes back 😖

**Comment by wasdennnoch** [comment]
lol the website of the developer of that module got suspended

**Comment by Androdiver** [comment]
Yeah its sad but that module is really good only that module can change qs bacgrbackground image at present.

**Comment by wasdennnoch** [comment]
I had a look at the XQS Background source; I fear I can't change the way it works, but you can use Zeus Contextual Header, this mod allows you to choose custom images too and I think that module should be easier to fix.

**Comment by Androdiver** [comment]
I know about zeus contextual,the module only changes header image not whole qs background otherwise i think there's no way left except using zeus contextual.

**Comment by Androdiver** [comment]
you suggest me to use zeus contextual now take a look at screenshot below it large the header and overlap first notification.

**Comment by Androdiver** [comment]
Any way this is not your moddule or problem but in latest buibuild version tile working correctly axcept ripple effect but it doesn't matter i am happy.
