### ISSUE TITLE
Tapping DND mini tile leads to blank panel

### ISSUE THREAD

**Issue by TheDorkKnightRises** [wasdennnoch/AndroidN-ify#399]
When I tap the mini DND tile
![Blank panel](http://i.imgur.com/vSEKYjO.png)

Which when collapsed leads to this:

![No mini tiles](http://i.imgur.com/Fut5CNKh.jpg)

Pulling down once more makes the icons appear, but the bug is 100% reproducible.

Device: OnePlus One
ROM: Cyanogen OS 13 (Android 6.0.1)

**Comment by AdrianVovk** [comment]
Reproducible here on Moto X 2014 with CM13

**Comment by wasdennnoch** [comment]
Also happens with location tile (#679)

**Comment by Jerdle** [comment]
@wasdennnoch FYI also happens on Cast tile

**Comment by wasdennnoch** [comment]
This is fixed now.
