### ISSUE TITLE
More Settings crash

### ISSUE THREAD

**Issue by AdrianVovk** [wasdennnoch/AndroidN-ify#400]
In the edit screen tapping "More Settings" leads to a crash on CM13 on Moto X 2014

**Comment by wasdennnoch** [comment]
This should have nothing to do with the module  because it only modifies the dashboard. On the other hand the settings shouldn't crash when you are using the stock ROM. You can post a logcat just to be sure.

**Comment by AdrianVovk** [comment]
I'll post the logcat. I think you misinterpreted the issue. When you are in quick settings and tap edit, then "more settings", system is crashes

**Comment by wasdennnoch** [comment]
Ah ok. Still need a log :P

**Comment by wasdennnoch** [comment]
No response, so -

**Comment by AdrianVovk** [comment]
Actually this was fixed already when the done button as removed from the edit screen. Should have closed the issue. Sorry
