### ISSUE TITLE
Pulldown bug

### ISSUE THREAD

**Issue by justinkruit** [wasdennnoch/AndroidN-ify#403]
It seems like the animation isn't really going well. They will jump to their needed places if I would pull down a little bit more.

OnePlus One with Euphoria rom.
![screenshot_2016-06-06-12-49-23](https://cloud.githubusercontent.com/assets/1642830/15821126/30c7254a-2bee-11e6-8d52-c92dd053ccf2.png)

**Comment by wasdennnoch** [comment]
Please see #355 for further details.
