### ISSUE TITLE
QS not always showing

### ISSUE THREAD

**Issue by Xeonars** [wasdennnoch/AndroidN-ify#407]
The quick settings are only showing when i dont expand the notifications completely and. 

Video and log attached.

Log: https://drive.google.com/open?id=0B5I7RH2L8dc9VWpScUxfdEZyLWM
Video: https://www.youtube.com/watch?v=hy_Xgw6smHg&feature=youtu.be&ab_channel=Zendom

**Comment by wasdennnoch** [comment]
I can's view the video as it is private; make it unlisted please.

**Comment by wasdennnoch** [comment]
And please disable debug log and post the full og again, directly after a restart.

**Comment by wasdennnoch** [comment]
No response, so -
