### ISSUE TITLE
Multiple QS pages

### ISSUE THREAD

**Issue by AniketDhoke** [wasdennnoch/AndroidN-ify#408]

**Comment by AniketDhoke** [comment]
https://www.google.co.in/search?q=android+n&prmd=nvi&source=lnms&tbm=isch&sa=X&ved=0ahUKEwiU06m18pPNAhXEuI8KHWxlC8YQ_AUICSgD&biw=360&bih=512#imgrc=rG5fIYPQPKRNOM%3A

**Comment by AniketDhoke** [comment]
How I send screenshot??

**Comment by AniketDhoke** [comment]
https://drive.google.com/file/d/0BwHLwsbBEb_0YVgxY1YxaW02YjA/view?usp=docslist_api

**Comment by wasdennnoch** [comment]
Oh wait, do you mean multiple pages to fit the Quick Settings in?

**Comment by paphonbth** [comment]
Implemented
