### ISSUE TITLE
New wallpaper dialog

### ISSUE THREAD

**Issue by AniketDhoke** [wasdennnoch/AndroidN-ify#409]
Can you add this Set Wallpaper feature??
And the edit button should be in grey color as in screenshot.

https://drive.google.com/file/d/0BwHLwsbBEb_0dHJXQmhLVktYWWc/view?usp=drivesdk

https://drive.google.com/file/d/0BwHLwsbBEb_0LWFyeFI3NGlMQWs/view?usp=drivesdk

**Comment by wasdennnoch** [comment]
I'm actually not sure if the new wallpaper chooser is new in N or in the Google Now launcher...

**Comment by AniketDhoke** [comment]
I search on Google and I found it is not android N feature it is Google Now launcher feature
![screenshot_20160712-110200](https://cloud.githubusercontent.com/assets/19507968/16756122/8f2c4842-4820-11e6-9d0f-97fb14ea9824.png)

**Comment by wasdennnoch** [comment]
Then I can't add it as the launcher is obfuscated and I don't want to spend weeks just to figure out how to add one dialog. 

In the other hand the same screen you open to select the wallpaper already exists on M (and maybe L) and tis chooser dialog pops up on confirmation, so I'm not sure if it's from the launcher.

**Comment by wasdennnoch** [comment]
I'll close all issues that I've planned to implement anyways now.
