### ISSUE TITLE
QS not working

### ISSUE THREAD

**Issue by Hatrix5555** [wasdennnoch/AndroidN-ify#412]
Hi. I have LG G Flex2 H955 International version with Android 5.1.1, v15e software. I don't have QS in status bar, only EDIT button, but system UI crashes when I click it. Here's video when I tried to extend QS and click EDIT button: https://youtu.be/oeiHUdpGPiQ
Here's my logcat for Android N-ify module when I click EDIT button (when I tried to expand there was no logs): http://www46.zippyshare.com/v/pDqddmJD/file.html
And there's full logcat for a little time: http://www46.zippyshare.com/v/ZgcuJkD5/file.html
And xposed log: http://www46.zippyshare.com/v/SfQWToCl/file.html

**Comment by wasdennnoch** [comment]
Can you please post your SystemUI?

**Comment by Hatrix5555** [comment]
Ok, there is it: http://www78.zippyshare.com/v/mtMjSDIV/file.html

**Comment by wasdennnoch** [comment]
It looks like on some LG ROMs they removed the setTiles method which the module depends on. They also heavily changed some notification stuff. The SystemUI is dexed (as expected), so I can't really cahnge anything. I'd have to search for a deodexed version first, and the only one I found so far is 1.5GB in size... I fixed the crash with the latest commit, but it won't do anything now as the setTiles method is missing.

**Comment by Hatrix5555** [comment]
So you can't do anything?

**Comment by wasdennnoch** [comment]
I fear not, sorry ._.

**Comment by wasdennnoch** [comment]
I had a look at the code and LG changed literally EVERYTHING in a way that makes everything incompatible. I'm sorry but there's really nothing I can do about that, you'll have to disable the new QS.
