### ISSUE TITLE
System ui always fc

### ISSUE THREAD

**Issue by aviraxp** [wasdennnoch/AndroidN-ify#420]
Systemui Frequently fc on oneplus 2 h2 os 1.4 which is based on android 6.0.1.

[log and systemui.zip](https://github.com/wasdennnoch/AndroidN-ify/files/309455/log.and.systemui.zip)

**Comment by wasdennnoch** [comment]
These are very weird errors and I have no Idea what could be causing them. There are many errors regarding notifications, but you need to post a logcat after a SystemUI crash for me to know what happened.

**Comment by aviraxp** [comment]
[2016-06-12-01-10-25.zip](https://github.com/wasdennnoch/AndroidN-ify/files/310414/2016-06-12-01-10-25.zip)
here

**Comment by wasdennnoch** [comment]
It crashes because of some internal stuff. OOS isn't open source and I can't find a deodexed SystemUI of that version which makes it basically impossible to fix. I guess your only way is to disable the notification tweaks for now.
