### ISSUE TITLE
Module not activated

### ISSUE THREAD

**Issue by Assassinss** [wasdennnoch/AndroidN-ify#427]
I compile source code,and reboot the system,I find module not activated.

**Comment by deletescape** [comment]
Did you activate the module in xposed installer?

**Comment by Assassinss** [comment]
yes

**Comment by wasdennnoch** [comment]
If the module shows that it isn't activated the problem is on your side. Did you properly flash the right Xposed zip for your device?

**Comment by Assassinss** [comment]
Of course yes, Sorry for my poor English,I hope you can understand what i said. I installed build # 297 version is no problem, but I installed the app_debug.apk is not work after I compile source code.Rom is cm13
