### ISSUE TITLE
Tiles on QS independent from system on LP 5.1.1

### ISSUE THREAD

**Issue by xpduyson** [wasdennnoch/AndroidN-ify#430]
After #429, Number of title on QS doesn't sync with system. CM 12.1

![device-2016-06-12-102308](https://cloud.githubusercontent.com/assets/6981890/15988796/c202eb5a-3087-11e6-87d8-1f38a17ee1e4.png)
![device-2016-06-12-102251](https://cloud.githubusercontent.com/assets/6981890/15988797/c22a2fa8-3087-11e6-9f85-ac437ec7433c.png)

**Comment by paphonbth** [comment]
This module overrides tiles positions. Press the edit button to customize it.
