### ISSUE TITLE
Overlapping exdending icon

### ISSUE THREAD

**Issue by RobbeDelarbre** [wasdennnoch/AndroidN-ify#434]
The extending icon overlaps with the airplain icon and if i press it the airplain icon works here is a picture of it:https://drive.google.com/file/d/0B2B39yPcTS1eNXlVOFhQNDBmdjQ/view?usp=drivesdk also a reboot didn't fix it

**Comment by wasdennnoch** [comment]
Reduce the amount of header tiles in the settings...

**Comment by haseoxth** [comment]
Or you can reduce dpi value a little to make more space for tiles.
