### ISSUE TITLE
Can't add some new title, CM 12.1

### ISSUE THREAD

**Issue by xpduyson** [wasdennnoch/AndroidN-ify#435]
SystemUI crash while add new title, commit #433, CM12.1

https://drive.google.com/open?id=0B7yWEj89s7W6a2pkY2dmbTNVb2M

Logcat: [QS_addTtile_crash_CM12.1.txt](https://github.com/wasdennnoch/AndroidN-ify/files/310718/QS_addTtile_crash_CM12.1.txt)

**Comment by paphonbth** [comment]
CM12.1 removed IntentTile which is required by LiveDisplay and battery tile. There's nothing I can do about it.

**Comment by xpduyson** [comment]
After #437, SystemUI doesn't crash anymore, but I still can't add some title in lower row

https://drive.google.com/open?id=0B7yWEj89s7W6VGFvZEJRbXpFQ3c

**Comment by wasdennnoch** [comment]
Try tapping them

**Comment by xpduyson** [comment]
@wasdennnoch thanks, I didn't know that!

**Comment by paphonbth** [comment]
Logs?
