### ISSUE TITLE
QuickQS tile animates when peeking

### ISSUE THREAD

**Issue by SlimShadys** [wasdennnoch/AndroidN-ify#440]
So, with Temasek v9.2 everything is great but there is only a problem with QS.
Look at the rotation tile here on the right: https://www.youtube.com/watch?v=R5MGkniGOE0&feature=youtu.be

**Comment by wasdennnoch** [comment]
Can you please post your Xposed log with debug log enabled? (Open/close the panel several times)? (I'm very fast with that response, I know ^^)

**Comment by wasdennnoch** [comment]
*knock knock*

**Comment by SlimShadys** [comment]
Who's there?
http://www.mediafire.com/download/0drwedaztuz9d68/logcat.txt

**Comment by wasdennnoch** [comment]
It's me! With bad news. I couldn't find anything useful in the Temasek source, so I added additional logging to the latest build (414 as soon as it has finished building), please install that one and post the log after a reboot *without* clicking the tiles, just open and close the panel as you did in the video.

**Comment by wasdennnoch** [comment]
*cough* :P

**Comment by SlimShadys** [comment]
Vacation, brother :P

**Comment by wasdennnoch** [comment]
Alright, have fun :)

**Comment by wasdennnoch** [comment]
Sooo as this got forgotten and it's not that big of an issue I'll close it ;)
