### ISSUE TITLE
Clipped Notifications on Lock Screen, broken Clear All button, Option to hide edit button

### ISSUE THREAD

**Issue by bumpaneer** [wasdennnoch/AndroidN-ify#443]
I have run across a few issues after enabling N-ify.

- I am unable to hide the edit button.  I have verified that the option is selected, but it still shows up on the tiles page.
- The Clear All button has no effect.
- The last option on the lock screen is mostly obscured by the option above it.

I have uploaded a debug log, logcat, SystemUI.apk and screenshots to a Google drive folder here:
https://drive.google.com/folderview?id=0B4Nxg3bQ8H5aVnp1eXEtSVVHRlk&usp=sharing

Any assistance you are able to provide would be greatly appreciated!

![screenshot_20160612-155144](https://cloud.githubusercontent.com/assets/3710084/15993551/6f4d2dfa-30b7-11e6-8977-cbdf0c51fd3e.png)
![screenshot_20160612-155215](https://cloud.githubusercontent.com/assets/3710084/15993552/71f0837c-30b7-11e6-90c9-afdfea05d7db.png)
![screenshot_20160612-155236](https://cloud.githubusercontent.com/assets/3710084/15993553/74162198-30b7-11e6-8d8c-3d0bd286e7e5.png)
![screenshot_20160612-155553](https://cloud.githubusercontent.com/assets/3710084/15993555/7aedba44-30b7-11e6-8b8d-707f6ad3965c.png)

**Comment by wasdennnoch** [comment]
The option only hides the stock edit button and the clear button is a known issue.

**Comment by bumpaneer** [comment]
Is there a way to hide the N-ify edit button without resorting to disabling the QS editor and losing the battery percentage?

**Comment by wasdennnoch** [comment]
Currently not

**Comment by wasdennnoch** [comment]
You are now able to set a maximum amount of lockscreen notifications to avoid overlap.
