### ISSUE TITLE
Xposed can't read permissions file

### ISSUE THREAD

**Issue by juangcardoso** [wasdennnoch/AndroidN-ify#445]
Hello, first thanks for the good module and sorry for my bad English ...

A couple versions after the snapshot the module was working fine but now it isn't, exposed can't read the permissions file so I have to use the stock settings of the module.

If it can help u, there is my xposed log and my systemui apk.

Info:

Device: Moto X 2014
Android Version: 6.0 Marshmallow 
ROM: Modified stock ROM by Junior Passos

[log_and_systemui-apk.zip](https://github.com/wasdennnoch/AndroidN-ify/files/311241/log_and_systemui-apk.zip)

**Comment by wasdennnoch** [comment]
... have you clicked on the warnig and followed the instructions shown?

**Comment by juangcardoso** [comment]
Yes, I tried all the instructions.

**Comment by juangcardoso** [comment]
I tried reboot the device, reinstall the module,  change the selinux mode to permissive but no luck

**Comment by wasdennnoch** [comment]
Did you try uninstall, reboot, install, open the modules UI once and rebootingg again?

**Comment by juangcardoso** [comment]
Yes, I did it. But without success.

**Comment by wasdennnoch** [comment]
If that's the case I can't help you anymore, sorry. The module itself already tries to make the pref file readable, and if even the suggested help doesn't work there's no other way. Weird though that it was working before.

**Comment by AryToNeX** [comment]
This happens also on Moto G 2015 with DU ROM and Xposed 85

**Comment by umcc05** [comment]
This is also an issue on OnePlus Two - CM13, and V85 xposed. Stinks. Tried all of that too.
