### ISSUE TITLE
sim tile missing

### ISSUE THREAD

**Issue by AniketDhoke** [wasdennnoch/AndroidN-ify#446]
when I enable tile editor one sim tile becomming invisible
and when I disable it shows both tiles
Why it happens?

**Comment by wasdennnoch** [comment]
The module overrides the system tiles in order to add the tile editor, there is no other way. We are however addin more and more tiles to support as many devices as possible.

**Comment by wasdennnoch** [comment]
Should be added with 9b1b5a1ae977fd6469f2c00024266ae72fa0d480
