### ISSUE TITLE
Resurrection ROM issues

### ISSUE THREAD

**Issue by silentvisitor** [wasdennnoch/AndroidN-ify#447]
Hi

Thanks for your exceptional work !

I have following issues on RR ROM 5.6.9 (10th June)  : 
1. No QS animation. Tiles just run to left.
2. Doesn't show all RR tiles most importantly Power Menu, Application picker tiles (would love to get all RR tiles if possible)
3. Tapping DONE crashes SystemUI
4. Tap to add tile was much more comfortable. Can't drag lowest tile to top.

Xposed log is attached.

Thank you once again !
[ResurrectionRemix_5.6.9_Errors.txt](https://github.com/wasdennnoch/AndroidN-ify/files/312094/ResurrectionRemix_5.6.9_Errors.txt)

**Comment by wasdennnoch** [comment]
You can still tap to add. I'm on RR too, I'll add some RR tiles in the future. Having the same animation issue. I don't have th crashing SystemUI, but I see that you are using the paphonb build. Can you please try the newest "noral" build? ( https://ci.paphonb.xyz/job/AndroidN-ify/317/ )
If the SystemUI still crashes please send a full logcat.

**Comment by silentvisitor** [comment]
Sure.
Will let you know and post full logcat after a clean flash.
Btw what is "noral" ?
Kindly add Power Menu tile.

Thank you !

**Comment by wasdennnoch** [comment]
Whoops, typo. Ment "normal".

**Comment by silentvisitor** [comment]
Any update on animation in RR?
Your module is really exciting :)

**Comment by wasdennnoch** [comment]
Not yet unfortunately, still have to compare CM and RR sources to find out what's causing the issues.

**Comment by silentvisitor** [comment]
Thank you !
Looking forward.
Btw they're not using CM panel.
Will try to find and provide you relevant info.

**Comment by silentvisitor** [comment]
Here it is.
Sorry I couldn't find any way to share link of this post so took a screenshot.
Hope it helps !
![screenshot_20160615-040215](https://cloud.githubusercontent.com/assets/19911574/16061971/0209e208-32ae-11e6-805e-a0a319892576.png)

**Comment by wasdennnoch** [comment]
The QS animations should be fixed now? Except for a little jump at the end, but that's another issue.

**Comment by silentvisitor** [comment]
Thank you so much !
Will try soon and report back.

Thanks once again !
