### ISSUE TITLE
Inversion cannot be turned off on Samsung Good Lock

### ISSUE THREAD

**Issue by WerWolv98** [wasdennnoch/AndroidN-ify#463]
#If you click on the 'Invert Color' quick settings toggle on the Samsung Good Lock SystemUI, the toggle won't turn on and you can't turn it off anymore.

**Comment by elnod** [comment]
Changing to negative colours in accessibility doesn't revert back to normal either. Turns into an odd blend.. Any idea why they're not the same? Seem to be stuck with this combination for now.

**Comment by wasdennnoch** [comment]
Have you tried it with the module disabled?

**Comment by elnod** [comment]
Yeah, even uninstalling good lock with the module enabled and disabled doesn't help unfortunately.

**Comment by wasdennnoch** [comment]
Was it working correctly before you installed the module?

**Comment by wasdennnoch** [comment]
I pused a commit with an option to manually disable inversion ( 14d98a6468f475ce4a3fa4986cc579a716b0442e )

**Comment by paphonbth** [comment]
@letsflyak read the comment above yours
