### ISSUE TITLE
Emergency info on Lockscreen

### ISSUE THREAD

**Issue by silentvisitor** [wasdennnoch/AndroidN-ify#466]
Hi,
I'm posting this on behalf of Yudh, my XDA friend.

in emergency dialer page
1) We have to tap emergency info button twice to open the page 
2) Emergency info page can be enhanced by adding features like relatives contact no.
3) And an option to call specific people(user selects the no. Of people to choose) directly without opening the screenlock.(so that even if the mobile owner is unable to call others can contact the right person)
4) Error in Google play music notification because it cannot be expanded to control the music(for prev next play and pause functions.

Huge THANKS to MrWasdennnoch & paphonb !

**Comment by wasdennnoch** [comment]
Implemented.
