### ISSUE TITLE
Invalid battery percentage

### ISSUE THREAD

**Issue by AniketDhoke** [wasdennnoch/AndroidN-ify#468]
my battery is 92% and any % but when I click on edit and in edit mode it shows charging,81% but I am not charging my phone 

I think this can help you to implement multiwindow
https://developer.android.com/preview/features/multi-window.html

**Comment by wasdennnoch** [comment]
Ok, honestly this isn't that huge of an issue, it's only a preview of the tiles which would show a fixed value anyways, and you don't edit tiles that often, so it isn't something world breaking.
