### ISSUE TITLE
Tiles not working on my device

### ISSUE THREAD

**Issue by Androdiver** [wasdennnoch/AndroidN-ify#469]
In previous updates when i press edit button in qs,system UI always crashes in latest build nothing is happen overall issue is edit tile doesn't working
Logs
https://www.mediafire.com/download/1ajfzr6i9ps8jn5

**Comment by wasdennnoch** [comment]
There seem to be multiple problems on your ROM; I previously pushed a commit that fixed the crash - nothing happening is better than a crash. The main problem appears to be that an important class isn't found on your ROM. Which ROM are you using and can you please post your SystemUI? Deodexed if possible.

**Comment by paphonbth** [comment]
IntentTile doesn't exist in CM12.1. That's simply the reason.

[CM12.1](https://github.com/CyanogenMod/android_frameworks_base/tree/cm-12.1/packages/SystemUI/src/com/android/systemui/qs/tiles)
[Lollipop MR1](https://github.com/android/platform_frameworks_base/tree/lollipop-mr1-release/packages/SystemUI/src/com/android/systemui/qs/tiles)

**Comment by wasdennnoch** [comment]
Isn't there another tile that could solve the same purpose? Or is IntentTile required for creating multiple tiles of the same type? What does GB do for that?

**Comment by paphonbth** [comment]
GB also doesn't work.
There are many other tiles that can be used as well, but that requires some code change.

**Comment by Androdiver** [comment]
Sorry i have done a mistake in title i am on stock lollipop rom

**Comment by wasdennnoch** [comment]
As said in another issue, there's no help for your device.
