### ISSUE TITLE
Notification LED not working

### ISSUE THREAD

**Issue by CrisBarreiro** [wasdennnoch/AndroidN-ify#494]
Notification LED not working on my Xiaomi Mi 4S using CM13

**Comment by wasdennnoch** [comment]
This should have nothing to do with the module, it only chanhes the layout, not some light related things.

**Comment by wasdennnoch** [comment]
As I can't imagine any way the module could break the LED I'll close this now. When I first rooted my pphone I've had the same issue, the LED suddenly wasn't working anymore, and i got back to life after I flashed a new ROM, so it's probably a kernel issue. Try flashing a new one.
