### ISSUE TITLE
Fancy QS Transition

### ISSUE THREAD

**Issue by juangcardoso** [wasdennnoch/AndroidN-ify#495]
Hey man, remember me? I had a trouble with the xposed preference files!

I got the module to read xposed preference file flashing the rom again! Haha!

Now, another thing!

The Fancy QS Transition isn't working like in stock Android N! :s

I recorded a video showing it, see it: [Vídeo showing the problem](https://youtu.be/os0a8OXAQeE)

I catch logcats and xposed logs for you too, see if they can help you: [Logcat and Xposed Log](https://drive.google.com/open?id=0By0DFp_16N0pc05jZHFlUTl0eU0)

I uploaded the logs to Google Drive because Github doesn't support xposed log format!

Thank you for the attention and sorry for my bad english!

Device: Moto X 2014 (XT1097);
Android Version: 6.0 Marshmallow (Stock Motorola Software).

**Comment by wasdennnoch** [comment]
This has already been reported multiple times, please refer to #355 ;)
