### ISSUE TITLE
Three icons in first row of Qs are missing on cm 13 and......

### ISSUE THREAD

**Issue by AniketDhoke** [wasdennnoch/AndroidN-ify#502]
A few weeks ago I jumped from stock to cm 13 and install N-ify it shows 1st row in old style like in marshmallow but it behaves like in N tile and but it also shows that old horizontal line
also I tried enabling alternate Qs loading method and enlarge first row but no luck

Screenshot
https://drive.google.com/file/d/0BwHLwsbBEb_0N2dfdjFuLWNFZms/view

**Comment by wasdennnoch** [comment]
If yoh want to disable the large row on CM you have to open the CM tile editor (disable the N one foe that and click the edit tiles tile) and swipe left to find more options.

**Comment by paphonbth** [comment]
You can also hold the Settings button until it starts to spin and then release it. That will open CM tile editor.

**Comment by AniketDhoke** [comment]
Thanks for helping
