### ISSUE TITLE
Tile name and icons overlap when using VPN

### ISSUE THREAD

**Issue by AniketDhoke** [wasdennnoch/AndroidN-ify#505]
When I connected to VPN it causes overlapping of Name and tiles
And when I not connected it animates properly

Screenshot

**Comment by AniketDhoke** [comment]
https://drive.google.com/file/d/0BwHLwsbBEb_0M2plZFFRSWhBc28/view

**Comment by wasdennnoch** [comment]
I still need permission to open that file

**Comment by wasdennnoch** [comment]
Does this still occur?

**Comment by AniketDhoke** [comment]
fixed!!!
