### ISSUE TITLE
Slightly "off" positioning and other minor issues with fancy QS animation on stock

### ISSUE THREAD

**Issue by vemacs** [wasdennnoch/AndroidN-ify#510]
At the end of the animation on stock 6.0, the QS icons jump a bit. 

Here is an screenshot from somewhere close to the last frame of the animation (also note the scrunched LTE icon): http://i.imgur.com/uL9sWoq.png

Here is a screenshot of the expanded QS panel: http://i.imgur.com/hvEwsBQ.png

Open them in separate tabs and switch between the tabs to see what I mean by "jumping". The vertical height seems to be off by around 4dp (visually, it seems close to the height of the text...)

Another thing is that the animation fails to show up at all after opening and closing the tiles editor.

**Comment by Unpublished** [comment]
Please compile from this branch https://github.com/Unpublished/AndroidN-ify/tree/debug510 and post your xposed log (debug log enabled). Then I might be able to fix the "jump".

**Comment by vemacs** [comment]
https://gist.github.com/vemacs/e67f0c3a74db03af8027527dedf7351d

**Comment by Unpublished** [comment]
Yeah but 937 is valid. On my device gridheight changes from 11** too 10** too.
If you would use 10** on your device as gridheight the animation would be more broken than the little jump now.

I assume the calculation of the tile coordinates needs to be adjusted for aosp somehow.

**Comment by vemacs** [comment]
Are you on CM?

**Comment by Unpublished** [comment]
Yeah I'm on CM, please try this https://github.com/Unpublished/AndroidN-ify/tree/fix510

**Comment by vemacs** [comment]
"Jump" still occurs with that commit, unfortunately. Same with the scrunched up icons.

**Comment by vemacs** [comment]
Could the offset be related to the brightness bar? 

![](https://i.imgur.com/JNaLBMs.png)

**Comment by vemacs** [comment]
This commit "fixes" it: https://github.com/vemacs/AndroidN-ify/commit/4aff10a9147d8e40e6fc43d515158c581521b78b

**Comment by vemacs** [comment]
See above PR ^

**Comment by wasdennnoch** [comment]
Fixed with 486d9e05a2a51932a24757fe3f43453e1f73fc60
