### ISSUE TITLE
Replace Google search bar with clear all button in recents, increase window preview height

### ISSUE THREAD

**Issue by vemacs** [wasdennnoch/AndroidN-ify#518]
(Or add the clear all button if the Google search bar is disabled)

![](https://i.imgur.com/PTlZtUD.png)

Hidden when scrolled to the top:

![](https://i.imgur.com/B7nPEMH.png)

**Comment by wasdennnoch** [comment]
> Or add the clear all button if the Google search bar is disabled
Well, that's the problem, we haven't found a way to do so yet, same for the tall recents. And replacing the search bar would only show a static button instead of a scrolling one.
