### ISSUE TITLE
qs header tile disappear in latest build 

### ISSUE THREAD

**Issue by Androdiver** [wasdennnoch/AndroidN-ify#520]
![img_20160707_230553_684](https://cloud.githubusercontent.com/assets/19375581/16662892/64577f74-4497-11e6-9f17-8c4986d587d9.JPG)

Here is log
[logcat.txt](https://github.com/wasdennnoch/AndroidN-ify/files/352733/logcat.txt)

**Comment by wasdennnoch** [comment]
You're on CM12.1, right? 

(no QSPanel.getGridHeight())

**Comment by Androdiver** [comment]
No no iam on pure stock rom

**Comment by wasdennnoch** [comment]
Oh. You entitled an issue with CM12.1. Which ROM and manufacturer?

**Comment by Androdiver** [comment]
Stock rom lollipop 5.0.2 
Manufacturer XOLO

**Comment by wasdennnoch** [comment]
Please install this version, reboot and post the Xposed log: http://www.mediafire.com/download/vunmrg3i1dqhcdm/Android_N-ify_debug_qspanel_log.apk

**Comment by Androdiver** [comment]
I intalled apk and produce the log

[logcat.txt](https://github.com/wasdennnoch/AndroidN-ify/files/354397/logcat.txt)

**Comment by wasdennnoch** [comment]
I only see some other erors in the logcat, please post your **Xposed** log.

**Comment by Androdiver** [comment]
I can't😫 because my xposed is not showing any logs😞

**Comment by wasdennnoch** [comment]
Hm. Bad. But because of the other errors I don't know if I can do anything for you, some important classes can't be found. In other words, the tile editor won't work anyways. The only thing you can do is to disable the QS editor and the fancy QS transition.

Fun fact: In your screenshot there's the word "Mist", which is German for "crap" :P

**Comment by Androdiver** [comment]
That mist is showing because i have using a wheatber widget and it is broadcasting my area weather

**Comment by Androdiver** [comment]
I am very uppset that transition effect i really want that but the truth is qs transition is not working from the beginning when you add the option 😭

**Comment by wasdennnoch** [comment]
Well, your ROM is missing important classes, without them the editor won't work and there is no way to replace them. The only thing you can to is to install a custom ROM, but that's your decision.
