### ISSUE TITLE
Problems in Android 5.0

### ISSUE THREAD

**Issue by hrithikb** [wasdennnoch/AndroidN-ify#527]
Can't add or edit tiles from edit button, clear all button in notification panel is not working and fancy animation is not working!

**Comment by hrithikb** [comment]
https://drive.google.com/file/d/0B0NJb0mKnh5QOEtmWkQ2bjY3c2c/view?usp=drivesdk 
Its the logcat file.

**Comment by wasdennnoch** [comment]
Again a method (QSPanel.getGridHeight()) is missing. Can you please install this version and post your Xposed log: http://www.mediafire.com/download/rbecbl1kkwapeek/Android_N-ify_debug_qspanel_log.apk

**Comment by hrithikb** [comment]
Sir I'm not able to send xposed log because the log is empty in xposed!

**Comment by wasdennnoch** [comment]
The logcat should do too, but immediately after a reboot please.

**Comment by hrithikb** [comment]
https://drive.google.com/file/d/0B0NJb0mKnh5QazZNVl8xemhQUTA/view?usp=drivesdk
See, no log found!

**Comment by hrithikb** [comment]
https://drive.google.com/file/d/0B0NJb0mKnh5QVnBQNUxEZlJlLW8/view?usp=drivesdk
Here is the logcat.

**Comment by wasdennnoch** [comment]
Are you sure that you captured it immediately after a reboot? Also, to fix the empty log, try setting `ro.build.type` to `userdebug` in the `/system/build.prop` file.

**Comment by hrithikb** [comment]
I'm on Android 5.1 now

**Comment by wasdennnoch** [comment]
You opened another issue for this so I'll close this here.
