### ISSUE TITLE
Android M/N style volume panel in lollipop

### ISSUE THREAD

**Issue by hrithikb** [wasdennnoch/AndroidN-ify#528]
Can you add android M/N style volume panel in lollipop phones because it is so awesome and the expandable panel is the favorite part.

**Comment by wasdennnoch** [comment]
I already forgot how the panel behaves on LP; are all three bars visible by default?

**Comment by hrithikb** [comment]
No not in lollipop stock rom but in cm12.1 it's there but the expansion button is not nice looking. And also there is none, all and priority button in bottom please atleast remove it sir! Thank you.

**Comment by hrithikb** [comment]
https://drive.google.com/file/d/0B0NJb0mKnh5QZVN3djZIXzFMWVk/view?usp=drivesdk
See this is screenshot of 5.0 and the expandable panel button is enabled by gravitybox

**Comment by wasdennnoch** [comment]
I'm not that sure if I will add this, mainly because the codebase for the volume panel is huge and they changes many things; also it's not really "new" in N but in M. GravityBox already has some option to tweak it to behave like M.

**Comment by hrithikb** [comment]
Ok thanks for the reply.
