### ISSUE TITLE
Two ripple effects on clock

### ISSUE THREAD

**Issue by AniketDhoke** [wasdennnoch/AndroidN-ify#529]
https://drive.google.com/file/d/0BwHLwsbBEb_0T1dNUnNSYUhKT00/view

https://drive.google.com/file/d/0BwHLwsbBEb_0QkVmU19JZVhTZ28/view

**Comment by paphonbth** [comment]
Please upload the screenshot as public.

**Comment by AniketDhoke** [comment]
that is downloadable file not google drive link

**Comment by paphonbth** [comment]
No. It's not.
![image](https://cloud.githubusercontent.com/assets/8080853/16706694/2b4a70e8-45e0-11e6-877f-29bde7a19dd6.png)

**Comment by AniketDhoke** [comment]
https://drive.google.com/file/d/0BwHLwsbBEb_0T1dNUnNSYUhKT00/view



https://drive.google.com/file/d/0BwHLwsbBEb_0QkVmU19JZVhTZ28/view

**Comment by wasdennnoch** [comment]
The first one is for the alarm, the second one for the clock. No problem.

**Comment by AniketDhoke** [comment]
But that small ripple not opening anything but that big one can open alarm

**Comment by wasdennnoch** [comment]
Had a look a the source; normally the clock should open, but it doesn't because we replace the stored clock instance by a fake one to avoid some other issues. Will fix that soon.

**Comment by wasdennnoch** [comment]
Fixed with f62a4dd35a6641e25fa6ffe6094867648f4c34bf
