### ISSUE TITLE
Clear all recent behavior like N

### ISSUE THREAD

**Issue by AniketDhoke** [wasdennnoch/AndroidN-ify#537]
In cm 13 after clicking on clear all button of recents the all recents go to the right side in fade animation and one after the other.
But in N they all go simultaneously to right without fade animation and (without one after the other)

**Comment by wasdennnoch** [comment]
You're really going into detail here... We'll see if this is possible as the recents are very complicated.

**Comment by wasdennnoch** [comment]
I had a look at the animation and the tiles actually animate one after each other, just as in CM, only a little bit faster.

**Comment by AniketDhoke** [comment]
Yes, But that in Nougat, recents not become light in color as they go but in CM they go and they become light(fade) .

**Comment by paphonbth** [comment]
The light color in recents is so annoying. Will try to remove it.

**Comment by AniketDhoke** [comment]
Ok thanks
