### ISSUE TITLE
Force close on Quick settings in Paranoid Android on One plus two

### ISSUE THREAD

**Issue by vpeace** [wasdennnoch/AndroidN-ify#539]
There is also one blank space in the quick settings and the plus sign also should be relocated
![screenshot_20160710-181226](https://cloud.githubusercontent.com/assets/16059464/16713576/e72120b6-46c9-11e6-8c81-5561fd82b0f3.png)
![screenshot_20160710-181152](https://cloud.githubusercontent.com/assets/16059464/16713577/e81531a6-46c9-11e6-8465-c2ddc1301ce4.png)

**Comment by vpeace** [comment]
[logcat.txt](https://github.com/wasdennnoch/AndroidN-ify/files/359882/logcat.txt)
Logcat

**Comment by wasdennnoch** [comment]
You can hide the button in the module settings. Also there are many crashes in the log (until your system crashed...), but none of them seem module relates, so please explain when exactly it crashes and capture a (shorter) logcat immediately after the crash. (220k lines are way oo much :P)

**Comment by vpeace** [comment]
IT crashes when I click anything in the quick settings menu
And sorry for the previous long logcat😅
[logcat.txt](https://github.com/wasdennnoch/AndroidN-ify/files/363763/logcat.txt)

**Comment by wasdennnoch** [comment]
Fixed with f05e52aaf5399ec5d4a05ef3e4ef0a40cad872c1
