### ISSUE TITLE
Notification are half cut and clear all button is not changed 

### ISSUE THREAD

**Issue by Androdiver** [wasdennnoch/AndroidN-ify#541]
Notifications are half cut in notification panel and in heads up
See picture below 
![img_20160713_224243_541](https://cloud.githubusercontent.com/assets/19375581/16739611/a83cb55a-47b8-11e6-8a5b-99779dd2ca29.jpg)
Here is log 
[logcat.txt](https://github.com/wasdennnoch/AndroidN-ify/files/357634/logcat.txt)

**Comment by wasdennnoch** [comment]
Fixed with c256a352496ff7d89d58ff8624b0500fa1813c6a
