### ISSUE TITLE
Navigation bar like Android Nougat (Request)

### ISSUE THREAD

**Issue by andresxd98** [wasdennnoch/AndroidN-ify#542]
![android-n-nexus](https://cloud.githubusercontent.com/assets/19764635/16742745/aaee5ba4-476e-11e6-9f3a-8550a0a8f30e.png)

**Comment by wasdennnoch** [comment]
I decided not to implement it because this module already dies it: http://repo.xposed.info/module/reverb.com.nougatnavigationbar
