### ISSUE TITLE
Bottom notification action background seems a bit too dark

### ISSUE THREAD

**Issue by vemacs** [wasdennnoch/AndroidN-ify#548]
I swear the color was lighter a few weeks ago. It's not consistently dark either, sometimes there's no background on the bottom notification actions (often in heads-up notifications).

Screenshot:

![](http://i.imgur.com/3XbX8zu.png)

![](http://i.imgur.com/GBUHVv5.png)

It was more consistent and the color was more reasonable a while ago. Not sure what commit caused this.

**Comment by wasdennnoch** [comment]
It indeed was; I added an automatic calculation for the actions background color so that you don't have to set it manually, but it still requires some tweaking. If you want to play around with it, here's the code:

**Comment by vemacs** [comment]
Would it be possible to cache the first successful default color?

**Comment by wasdennnoch** [comment]
That's what I was planning to do.

**Comment by vemacs** [comment]
For reference, here's the color on the emulator:

![](https://i.imgur.com/lHjUZP5.png)

**Comment by vemacs** [comment]
Changing 0.8 to 0.95 seems to give a color very close to that in the emulator (ececec vs eeeeee).

**Comment by vemacs** [comment]
Changing 0.8 to 0.95 matches the color on AOSP. In addition, there's a thin, 1dp #dedede line under the notification which shouldn't be thete.

**Comment by wasdennnoch** [comment]
That's the divider. Also, Github is broken again, so it will take some time until I can merge the PR (it just disappears...)
