### ISSUE TITLE
QS animation not working (BUG)

### ISSUE THREAD

**Issue by VRT19** [wasdennnoch/AndroidN-ify#555]
@wasdennnoch I'm currently running version Build #414 and the quick settings animation is not working. I tried installing older versions but same problem persisted. I'm running CM13 on a Moto E 2nd Gen. 

I'm able to fix this issue by clicking the edit button, after that the animation works, but the quicksettings pannel becomes longer, way longer and if I reboot my device or restart systemUI The pannel becomes normal again but the animation disappears.

Here's a video:  https://youtu.be/9IBK4yVkiwk

**Comment by wasdennnoch** [comment]
The video is private, make it unlisted. Also a log would be nice.

**Comment by VRT19** [comment]
Sorry my bad fixed link to video

Here's the logcat: 
[logcat[1].txt](https://github.com/wasdennnoch/AndroidN-ify/files/362299/logcat.1.txt)

**Comment by wasdennnoch** [comment]
Can you please include your Xposed log too? There are no errors in the logcat. Also  make sure to fetch the log immediately after a restart, otherwise important information gets overwritten due to limited logcat size.

**Comment by VRT19** [comment]
@wasdennnoch Here's the xposed log: https://mega.nz/#!qQZFyRbR!-R6Q-nkXOjN-9eNqntWLgBUlYdea3BUM1sIwuZdvhOQ

**Comment by VRT19** [comment]
Thought you mayor want yo know. I fixed the issue by installing Build #387, and disabled QS editor.
