### ISSUE TITLE
Weather dont work in statusbar with CM13

### ISSUE THREAD

**Issue by ThiagoBezzy** [wasdennnoch/AndroidN-ify#556]
This feature was disable for n-ify module

**Comment by wasdennnoch** [comment]
What do you mean with "not working"? The module only changes the position and it is working perfectly fine for everybody else.

**Comment by ThiagoBezzy** [comment]
Like this image (Under user icon)
i.imgur.com/PAuhs7a.png

**Comment by ThiagoBezzy** [comment]
I'm sorry
Now this feature is show.

I don't know what happened.

So sorry.
