### ISSUE TITLE
Large icons in Header toggle 

### ISSUE THREAD

**Issue by hrithikb** [wasdennnoch/AndroidN-ify#559]
I'm on latest build 417 and the toggle icons in header is so big than the previous versions and when i press the wifi icon or any other icon in qs the
Qs panel collapse immediately! I'm on 5.1.1 exodus os based on cm12.1 and good news is animation is working good now!

**Comment by hrithikb** [comment]
Its the xposed log
https://drive.google.com/file/d/0B0NJb0mKnh5QQlJRODhWeDRIa0U/view?usp=docslist_api

**Comment by hrithikb** [comment]
https://drive.google.com/file/d/0B0NJb0mKnh5QLUI1UGw1SC1XUU0/view?usp=docslist_api
Its the screenshot of what I'm talking about!

**Comment by hrithikb** [comment]
https://drive.google.com/file/d/0B0NJb0mKnh5Qbk5RM0syM1FIUFE/view?usp=drivesdk
Its the logcat

**Comment by KamranMackey** [comment]
@wasdennnoch I'm having this same issue as well. Please fix it...

**Comment by hrithikb** [comment]
Icons are still big in header
