### ISSUE TITLE
Animate 6th QS icon from side

### ISSUE THREAD

**Issue by andresxd98** [wasdennnoch/AndroidN-ify#561]
![screenshot_20160714-160224](https://cloud.githubusercontent.com/assets/19764635/16856102/0875ce6c-49de-11e6-80f5-aac88c58a9fe.png)

**Comment by wasdennnoch** [comment]
Have you tried the snapshot builds? They  already contain an almost perfect animation.

**Comment by andresxd98** [comment]
Yes, I have installed the latest build , and you're right , you knew almost perfectly emulate the original animation, and I love that .
but I mean that the third quick setting in the image ( autorotation ) comes from the right side of the screen when the animation progresses, while the build last where the animation is improved, this quick setting comes up , sorry if I am very demanding

**Comment by wasdennnoch** [comment]
Ah yes, have to add that too. And please make the title a bit shorter next  time, there is a description filed for long stories ;)

**Comment by andresxd98** [comment]
Sorry , I'm new at this :l

**Comment by wasdennnoch** [comment]
Implemented with 5655c997ddfa32295691f71155adbf7af0799afc
