### ISSUE TITLE
QuickQS tile not  animate when device turn to landscape mod

### ISSUE THREAD

**Issue by dimuthu3** [wasdennnoch/AndroidN-ify#562]
when turn to landscape mod qs tile note getting animate pls fix it other things are working great
screen shot  on below 
![screenshot_20160715-094734](https://cloud.githubusercontent.com/assets/9978447/16863604/18170db0-4a72-11e6-934f-3e09c3a272dc.png)

**Comment by dimuthu3** [comment]
Sorry here on https://www.dropbox.com/s/46cw7xxb4q5wbbc/error.log?dl=0

**Comment by wasdennnoch** [comment]
Are you sure that this is the full log? It is very short. Also please enable debug log, reboot, rotate the device to break the animation and then post the log please.

**Comment by dimuthu3** [comment]
its now working good on latest build but not prefect som times animations are broken (still unable log find full error log with landscape on n-ify)

**Comment by dimuthu3** [comment]
i think i got it here is log cat.[https://www.dropbox.com/s/4df9qfq90uxofnp/2016-07-27-12-29-24.txt?dl=0](url)

**Comment by wasdennnoch** [comment]
With broken do you mean that the tiles jump left/right at the end? This is a known issue.

**Comment by dimuthu3** [comment]
no buddy can you watch this [https://vimeo.com/174948226](url)

**Comment by wasdennnoch** [comment]
Please install the latest version ant post your **Xposed** log.

**Comment by dimuthu3** [comment]
today installed latest N-ify 478 but bug stay on.when i see xposed log its have not much information than  build version/rom type remote build version and no error line.
but here is cat log-[https://www.dropbox.com/s/h8eiadrzyh01f2m/2016-07-28-09-33-10.txt?dl=0](url)

**Comment by wasdennnoch** [comment]
Which ROM are you on?

**Comment by dimuthu3** [comment]
i am on beanstalk 6.19 android 6.0.1 latest build

**Comment by dimuthu3** [comment]
issue had been now solved with latest build so i will close my request
