### ISSUE TITLE
When will we get battery tile in cm12.1??

### ISSUE THREAD

**Issue by hrithikb** [wasdennnoch/AndroidN-ify#564]

**Comment by wasdennnoch** [comment]
CM12.1 removed the IntentTile which the module uses to add those custom tiles. I can have a look if there's another tile that we can hijack for that, but that will be more complicated.

**Comment by hrithikb** [comment]
Please do something sir

**Comment by wasdennnoch** [comment]
It was easier than expected - implemented with b56f23618c3c66fbb9de584a0995390b75d30b40

**Comment by hrithikb** [comment]
Can we get this for blisspop also??

**Comment by wasdennnoch** [comment]
Bliss is based on CM, so it should be working.

**Comment by hrithikb** [comment]
No it's not can you tell me how to add?

**Comment by wasdennnoch** [comment]
You should be able to add if when you open the QS editor (after you enabled it of course) and select the battery tile. If you first enable the editor the tile should already be in the panel. Note that you need to install one of the latest snapshots. If the tile isn't there please post your Xposed log.

**Comment by hrithikb** [comment]
https://drive.google.com/file/d/0B0NJb0mKnh5QbG5ramstbkJPbWs/view?usp=drivesdk
Xposed log because tile is not coming

**Comment by hrithikb** [comment]
Sir, have you seen the xposed logs that i posted??

**Comment by wasdennnoch** [comment]
I've seen the post, I'm just not developing every day, give me some time ;)

**Comment by hrithikb** [comment]
Oh, sorry for bothering you sir take your time please!

**Comment by wasdennnoch** [comment]
Hm, there are no related errors in the log (You can disable debug log now btw). Bliss added a QS bar, make sure to disable that and to use the normal panel. Apart from that I don't see anything else I can do here. btw why are you still on LP? You should be able to upgrade to MM with Bliss.

**Comment by hrithikb** [comment]
Sir my phone's kernal is different and there's no MM rom supported for my phone
