### ISSUE TITLE
Huge problems in blisspop cm12.1 based

### ISSUE THREAD

**Issue by hrithikb** [wasdennnoch/AndroidN-ify#566]
Clock position is not goid as uou can see in screenshot and also settings gear icon is not showing and edit button overlaps and not working
https://drive.google.com/file/d/0B0NJb0mKnh5QWGV4Q1ZkV3M5aXM/view?usp=docslist_api

**Comment by hrithikb** [comment]
https://drive.google.com/file/d/0B0NJb0mKnh5Qc2ROSFJjaTF0clk/view?usp=docslist_api
Another ss for description

**Comment by hrithikb** [comment]
Xposed log
https://drive.google.com/file/d/0B0NJb0mKnh5QZ29EVUpsNUJmMFE/view?usp=docslist_api

**Comment by hrithikb** [comment]
Logcat
https://drive.google.com/file/d/0B0NJb0mKnh5Qd1lTZlZrMVV3UU0/view?usp=drivesdk

**Comment by wasdennnoch** [comment]
Fixed with 0c52afcfd76d3c3959008ae055e50f957e94876f
