### ISSUE TITLE
Fancy QS Transition now working anymore since build #419

### ISSUE THREAD

**Issue by juangcardoso** [wasdennnoch/AndroidN-ify#570]
Hello! It's me again!

Since build #419 the Fancy QS transition weren't working like in previous builds!

In a few builds after the transitions were working perfectly, just now it get troubles!

Device: Moto X 2014
ROM: Motorola's stock marshmallow

[xposed_error_20160715_221520.zip](https://github.com/wasdennnoch/AndroidN-ify/files/367044/xposed_error_20160715_221520.zip)

Thanks for the attention

**Comment by wasdennnoch** [comment]
Can you please post screenshots / video describing your issue?

**Comment by wasdennnoch** [comment]
No response, so -
