### ISSUE TITLE
Notifications panel shadow line comes in cast and DND

### ISSUE THREAD

**Issue by AniketDhoke** [wasdennnoch/AndroidN-ify#574]
#429 build

![screenshot_20160716-191358](https://cloud.githubusercontent.com/assets/19507968/16895162/fd1b7b72-4b89-11e6-9c43-9ca2e52d352f.png)
![screenshot_20160716-191342](https://cloud.githubusercontent.com/assets/19507968/16895164/0cc8843e-4b8a-11e6-9d98-9357ba127803.png)

**Comment by wasdennnoch** [comment]
Shadow got reworked, issue fixed.
