### ISSUE TITLE
Blank screen after enabling DNS in header-qs

### ISSUE THREAD

**Issue by Maik268** [wasdennnoch/AndroidN-ify#575]
After enabling DNS in header-qs, it just shows me a blank screen.
If I activate it in extended quick settings, it shows me the normal DNS settings.

HTC 10
Android 6.0.1
HTC Sense (8)

![screenshot_20160716-163211](https://cloud.githubusercontent.com/assets/13015934/16895327/65741de4-4b73-11e6-899f-3b85bc4d773c.png)

**Comment by AniketDhoke** [comment]
Its reported bug please search before post
