### ISSUE TITLE
Header divider shows up sometimes

### ISSUE THREAD

**Issue by hrithikb** [wasdennnoch/AndroidN-ify#577]
https://drive.google.com/file/d/0B0NJb0mKnh5QcHZibU9lZDVaMEE/view?usp=drivesdk
Screenshot

**Comment by hrithikb** [comment]
Also clear all button in notification doesn't change!!

**Comment by ja-som** [comment]
The divider is worst on wide screens, here are screenshots from my Nexus 7 II

https://drive.google.com/open?id=0B0bWVvdcNSQlQkM4YmhGNkRvb28

(  
https://drive.google.com/open?id=0B0bWVvdcNSQlV3hFYXY4UzlpeUk  )

**Comment by paphonbth** [comment]
That's bad. I'll remove it tomorrow and find a way to add shadow directly over the panel.

**Comment by wasdennnoch** [comment]
The main problem is that the shadow doesnt move over a specific point: http://imgur.com/1DstZZs

**Comment by wasdennnoch** [comment]
Removed
