### ISSUE TITLE
Phonograph and possibly other music players’ incompatibility

### ISSUE THREAD

**Issue by mahendra3** [wasdennnoch/AndroidN-ify#583]
It doesn't scale properly when it is not expanded
(https://cloud.githubusercontent.com/assets/20501070/16900513/0ae579ac-4c51-11e6-8d03-6458fb8ccd5a.png)

**Comment by wasdennnoch** [comment]
It's a general problem with custom notifications; we're waitig for the N source to get public to fix this. This is already an old issue btw.
