### ISSUE TITLE
SystemUI FC on CM 12.1

### ISSUE THREAD

**Issue by bgiesing** [wasdennnoch/AndroidN-ify#584]
System UI crashes when Style header is enabled. 

Sorry for no log but I cant get a logcat on device when System UI crashes and I'm away from my computer for a few days. If there's anything I can help with otherwise (like maybe provide the systemUI apk?) or if there's still a way to get the log, just let me know!

**Comment by wasdennnoch** [comment]
You can use apps like MatLog to get the logcat on your phone.

**Comment by bgiesing** [comment]
Yes but the crash happens the second after the device turns on after enabling the Style header setting so you can't Start the log if you can't even get past the lockscreen.

**Comment by wasdennnoch** [comment]
Oh. Well, then you need a pc :P

**Comment by bgiesing** [comment]
Well since I'm away from a computer, I can't do that at the moment but would at least having the ROM or the SystemUI APK help? Here's the ROM if so https://www.androidfilehost.com/?fid=24566459652898980

Also forgot to mention, the current stable version works fine but not any of the staging builds.

**Comment by wasdennnoch** [comment]
I can't do anything with a flashable system image. It looks like this is stock CM though, am I right? Looks like nobody else has this issue. I'm going to need a logcat to fix this, otherwise I don't know what crashes why, we'll have to wait the few days for a fix.

**Comment by aviraxp** [comment]
Ha ha, actually many reported this issue in China, but they don't want to send logcat........

**Comment by wasdennnoch** [comment]
Then they have to wait :P

**Comment by wasdennnoch** [comment]
I think a few days are over? ^^

**Comment by wasdennnoch** [comment]
I can't fix anything without a log, so I'll close this.

**Comment by ttimz1313** [comment]
Oook
