### ISSUE TITLE
Lockscreen notifications icons

### ISSUE THREAD

**Issue by ja-som** [wasdennnoch/AndroidN-ify#586]
Hi, some icons in lockscreen notifications looks weird...
Some, e.g. Gmail, are OK.

![screenshot_20160717-131600](https://cloud.githubusercontent.com/assets/5942380/16901371/e7b552c2-4c41-11e6-9228-07fe42d88340.png)

**Comment by paphonbth** [comment]
This and animated icons has been a problem for a long time. I still can't find a way to fix it. But animated icons are just fixed a few days ago.

**Comment by wasdennnoch** [comment]
Still an issue?

**Comment by ja-som** [comment]
Sorry, I don't use your module anymore, because I have N on my devices, but I will continue with my translation, because it is a great module ;)

**Comment by wasdennnoch** [comment]
Alright xD
