### ISSUE TITLE
Is it possible to have extended notification like in Android N??

### ISSUE THREAD

**Issue by hrithikb** [wasdennnoch/AndroidN-ify#588]
I'm just curious to know if you can add the expand notifications feature like in Android N??

**Comment by paphonbth** [comment]
Screenshot of what you are talking about please.

**Comment by hrithikb** [comment]
https://goo.gl/images/yNn8QZ see the Gmail notification when we swipe the notification it expands, we can see the whole message without opening it!

**Comment by wasdennnoch** [comment]
You can expand notifications since they got introduced which was somewhere around Android 4.

**Comment by hrithikb** [comment]
No sir I'm talking about the new feature of Android nougat, in this feature the notification combines to make a bundle of notifications from same app when we swipe it splits and stretches!

**Comment by wasdennnoch** [comment]
That's notification grouping and that already got requested in another issue.
