### ISSUE TITLE
N notifications scrolling behavior (experimental)

### ISSUE THREAD

**Issue by ja-som** [wasdennnoch/AndroidN-ify#593]
When I enable this option, I know is experimental :) , I have big space between header and QS, and the shadow is always in the middle...

Nexus 7 2013, stock Android 6.0.1

![screenshot_20160718-193116](https://cloud.githubusercontent.com/assets/5942380/16924934/02fbe9de-4d22-11e6-86ab-fbb4e4be4ccf.png)
![screenshot_20160718-193103](https://cloud.githubusercontent.com/assets/5942380/16924935/030c90b8-4d22-11e6-866c-9538164f44ae.png)

**Comment by paphonbth** [comment]
Shadow in the center is fixed by #595

**Comment by ja-som** [comment]
I see in changelog, that fix is in build 439, but unfortunately I still have shadow in the middle with build 450.

**Comment by wasdennnoch** [comment]
Still an issue?
