### ISSUE TITLE
lockscreen problem in latest build

### ISSUE THREAD

**Issue by hrithikb** [wasdennnoch/AndroidN-ify#594]
https://drive.google.com/file/d/0B0NJb0mKnh5QSmJ2TmlVYnQtWU0/view?usp=drivesdk
Here's the screenshot, when more than 3 notifications come then the +1 at the last shows fully white and the divider line is not coming and the icon of next notifications are not coming!

**Comment by wasdennnoch** [comment]
You swapped to AICP, does the issue still persist?

**Comment by hrithikb** [comment]
No sir it's fixed in aicp but please help me for another issue i reported(can't activate the module)

**Comment by wasdennnoch** [comment]
The only thing I can say is that you have to try to reinstall the module.

**Comment by hrithikb** [comment]
I tried sir too many times!
