### ISSUE TITLE
Error in log in the latest build when booting

### ISSUE THREAD

**Issue by aviraxp** [wasdennnoch/AndroidN-ify#602]
CM13.

Though when using nothing appears wrong, I want to report it as well.

[2016-07-19-22-22-35[1].txt](https://github.com/wasdennnoch/AndroidN-ify/files/371664/2016-07-19-22-22-35.1.txt)

**Comment by aviraxp** [comment]
Seems related to recent?

**Comment by wasdennnoch** [comment]
Yep, those are from the experimental features.

**Comment by aviraxp** [comment]
fixed.
