### ISSUE TITLE
Crash in settings

### ISSUE THREAD

**Issue by justinkruit** [wasdennnoch/AndroidN-ify#608]
Hello,

Whenever I press any of the 5 settings on top, the app does crash. I don't really know how to get a good log, so I hope this is alright. Android 5.1, Euphoria ROM.
![img-20160720-wa0007](https://cloud.githubusercontent.com/assets/1642830/16982450/22d7a87a-4e70-11e6-899c-6e720bcdc9c6.jpg)

**Comment by wasdennnoch** [comment]
Please post the full logcat, I can't fix it with just two lines of stack trace.

**Comment by justinkruit** [comment]
Sorry, again, nog often making a logcat. Hoping this is better. Cleared the log, let it crash, and saved the log.
[2016-07-20-13-55-57.txt](https://github.com/wasdennnoch/AndroidN-ify/files/373618/2016-07-20-13-55-57.txt)

**Comment by wasdennnoch** [comment]
Fixed with 2f59fe83881ee2f32be34abe98ccd0ec120f9f0c
