### ISSUE TITLE
crash when "search for updates" is active

### ISSUE THREAD

**Issue by ranielcsar** [wasdennnoch/AndroidN-ify#611]
log: [2016-07-20-10-07-09.txt](https://github.com/wasdennnoch/AndroidN-ify/files/373740/2016-07-20-10-07-09.txt)

**Comment by wasdennnoch** [comment]
Please post a full logcat and don't apply a search filter.

**Comment by ranielcsar** [comment]
[2016-07-20-13-50-19.txt](https://github.com/wasdennnoch/AndroidN-ify/files/374384/2016-07-20-13-50-19.txt)

**Comment by wasdennnoch** [comment]
This is an error caused by the SystemUI, for some reason it couldn't find the app icon. This should only be a temporary error, e.g. when you just updated the app. Please test again. If it still crashes It's  you ROMs fault an sobody else has issues with the updater.

**Comment by ranielcsar** [comment]
it's because of themes...when stock, they not crash
