### ISSUE TITLE
QS panel collapses when opening detail view

### ISSUE THREAD

**Issue by ranielcsar** [wasdennnoch/AndroidN-ify#614]
and the battery % dont show on expanded panel (using cm12.1 rom on GSIII mini)

Log: [2016-07-20-21-17-14.txt](https://github.com/wasdennnoch/AndroidN-ify/files/374934/2016-07-20-21-17-14.txt)

**Comment by wasdennnoch** [comment]
The battery percentage inside the battery doesn't show in the expanded panel as it already shows the percentage underneath it. Please give sone more details about the other bug.

**Comment by ranielcsar** [comment]
(i'm brazilian sorry for bad english) when I click on the edit button, the expanded bar back to normal... when not expanded. same when click on wifi to show N behavior. and dont show the options

**Comment by ranielcsar** [comment]
A made a little video to show you: https://drive.google.com/open?id=0B62olFeBaHvjbGgxNF9yaXoxWkk

**Comment by ranielcsar** [comment]
I still have this issue and now when I click on "edit" button or battery tile the SystemUI crash.
[log.txt](https://github.com/wasdennnoch/AndroidN-ify/files/445468/log.txt)

**Comment by paphonbth** [comment]
That log is from an older version.

**Comment by ranielcsar** [comment]
SystemUI crash on edit is resolved, only on battery tile now. And still collapses.

**Comment by wasdennnoch** [comment]
Collapsing is a duplicate of #418 and the battery percentage won't show inside the battery when expanded. Also not in the header.
