### ISSUE TITLE
system ui forced stopped on cm12.1

### ISSUE THREAD

**Issue by hrithikb** [wasdennnoch/AndroidN-ify#615]
After installing cm12.1 I installed n ify and when I ticked nify in xposed then I rebooted and system ui forced stop and stuck!!

**Comment by wasdennnoch** [comment]
So you swapped to pure CM? I need a logcat that you can fetch via a computer.

**Comment by hrithikb** [comment]
Yes i was on pure cm but My PC is not working that's why I moved to aicp 10 sir

**Comment by wasdennnoch** [comment]
Hm, without a PC you can't fetch a logcat which I would need to fix it. Bad situation.

**Comment by hrithikb** [comment]
But battery tile still not coming in aicp also

**Comment by wasdennnoch** [comment]
Whelp, the alternative tiles were working in my device. Do you have an Xposed log for the tiles? ^^

**Comment by hrithikb** [comment]
You have cm12.1 based ROM???

**Comment by hrithikb** [comment]
I'll provide you the xposed logs just wait

**Comment by hrithikb** [comment]
https://drive.google.com/file/d/0B0NJb0mKnh5QZXRHNGpvN0pOc0k/view?usp=docslist_api
The closed log for battery tile

**Comment by hrithikb** [comment]
Sory xposed* log

**Comment by wasdennnoch** [comment]
Please don't say that you are on CM12.1 when you are on AICP.
I forgot to unlock the tile for CM12.1 ROMs, fixed that with 91257e360a1707913479cf3152c3c7817ba9b2e1. Still can't do anything about the fc without a log.

**Comment by hrithikb** [comment]
Sir I'm asking to you that you have tested in cm12.1 or not!

**Comment by hrithikb** [comment]
Sorry if i said something wrong sir

**Comment by wasdennnoch** [comment]
I tested it on my GT-I9305 running ResurrectionRemix 5.7.1 based on CM13, so no. But it should work now.

**Comment by hrithikb** [comment]
I'm on aicp and still got no success with battery tile😞😞😞

**Comment by hrithikb** [comment]
No battery tile

**Comment by wasdennnoch** [comment]
The build with the unlock failed, hold on a second...

**Comment by hrithikb** [comment]
Ooh

**Comment by wasdennnoch** [comment]
build 463 should fix it

**Comment by hrithikb** [comment]
Woah, its fixed thanks sir!
But one thing, when i click to battery tile it won't open battery status screen

**Comment by wasdennnoch** [comment]
Again need a locgat for that...

**Comment by hrithikb** [comment]
How to get logcat without pc?.

**Comment by wasdennnoch** [comment]
MatLog. (App)

**Comment by hrithikb** [comment]
Ok, thanks

**Comment by hrithikb** [comment]
https://drive.google.com/file/d/0B0NJb0mKnh5QZ3B5N0FKYngwY3c/view?usp=drivesdk

**Comment by hrithikb** [comment]
Logcat

**Comment by wasdennnoch** [comment]
I only found that the method name is changed on Bliss, but according to the logcat you are on AICP and according to their source everything should work fine, the method is cleary there. I pushed a fix for thie bliss method, if that doesn't fix it I can't do anything.

**Comment by hrithikb** [comment]
It worked sir thanks!
