### ISSUE TITLE
Request for redesigning volume panel for LP

### ISSUE THREAD

**Issue by hrithikb** [wasdennnoch/AndroidN-ify#621]
Is it possible to hide these three buttons from volume panel (shown in ss)
https://drive.google.com/file/d/0B0NJb0mKnh5QNEtxOFd2Q3RUZUU/view?usp=drivesdk

**Comment by wasdennnoch** [comment]
I guess I can add an option to make that invisible, bot not more.

**Comment by hrithikb** [comment]
Yeah, invisible will be cool !

**Comment by hrithikb** [comment]
I'llbe glad if you make it soon!😅😅
