### ISSUE TITLE
SystemUI Crash QS Viper10

### ISSUE THREAD

**Issue by PwnArt1st** [wasdennnoch/AndroidN-ify#623]
SystenUI crashes when tapping QS tiles with the N_ify setting enabled. Logs attached. 
https://docs.google.com/uc?id=0BwVv75qLhDPwYW0waTFJRVJHTzA&export=download

**Comment by wasdennnoch** [comment]
Please post a full unfiltered logcat after the crash.

**Comment by PwnArt1st** [comment]
https://docs.google.com/uc?id=0BwVv75qLhDPwUTl2a3NjRExNdkk&export=download

**Comment by wasdennnoch** [comment]
Fixed with e67d75911accf133eb8505e0ef0a54890a1827c8

**Comment by PwnArt1st** [comment]
Latest version causes infinite SystemUI crashes, had to remove through recovery. https://docs.google.com/uc?id=0BwVv75qLhDPwcTh2a3F2NEpkazQ&export=download

**Comment by wasdennnoch** [comment]
If it crashes constantly you have to fetch the logcat via a computer during the crashes as it gets cleared every reboot.
