### ISSUE TITLE
SystemUI Crash Viper10

### ISSUE THREAD

**Issue by ibrokemypie** [wasdennnoch/AndroidN-ify#624]
Latest version causes infinite SystemUI crashes, had to remove through recovery. https://docs.google.com/uc?id=0BwVv75qLhDPwcTh2a3F2NEpkazQ&export=download

**Comment by wasdennnoch** [comment]
Again, you'll need to fetch the logcat from a computer now.

**Comment by PwnArt1st** [comment]
What was the problem with that one? I removed Nify so have access to device again

**Comment by wasdennnoch** [comment]
Yes, but the logcat gets cleared on every reboot, so I don't know what crashed before you removed it.

**Comment by PwnArt1st** [comment]
I dont know when I will be abke to test this then, perhaps someone else can. For now sticking with broken QS
