### ISSUE TITLE
Cannot click notification when status bar is expanded

### ISSUE THREAD

**Issue by aviraxp** [wasdennnoch/AndroidN-ify#626]
CM13.

![screenshot_20160725-125849 1](https://cloud.githubusercontent.com/assets/18079988/17090944/41880480-5268-11e6-8f0f-98d0c36dec9e.png)

**Comment by aviraxp** [comment]
[2016-07-25-13-05-04[1].txt](https://github.com/wasdennnoch/AndroidN-ify/files/380787/2016-07-25-13-05-04.1.txt)

**Comment by wasdennnoch** [comment]
Disabling the experimental hooks fixes this.

**Comment by aviraxp** [comment]
Fixed♥
