### ISSUE TITLE
Incorrect header background with themes

### ISSUE THREAD

**Issue by ranielcsar** [wasdennnoch/AndroidN-ify#627]
is that a bug? 
cm12 theme "Notes UI" before: ![screenshot_2016-07-25-13-40-04](https://cloud.githubusercontent.com/assets/20558676/17109302/d1fc4bac-526d-11e6-9940-c724d9809276.png)

after: 
![screenshot_2016-07-25-13-40-41](https://cloud.githubusercontent.com/assets/20558676/17109325/f2fa4e76-526d-11e6-9ae1-f3bc499a80c9.png)

**Comment by ranielcsar** [comment]
"Unaltered QS bg" is active

**Comment by wasdennnoch** [comment]
Loos like the themes modify the header background directly instead of the color, so I'll change the way the color gets applied.

**Comment by ranielcsar** [comment]
Thanks for the att. Good work! (:

**Comment by wasdennnoch** [comment]
Option added with 97021f216a2ab7f1365c0b75a36df0c787fdcb26
