### ISSUE TITLE
Brightness slider with extra button in aicp10

### ISSUE THREAD

**Issue by hrithikb** [wasdennnoch/AndroidN-ify#629]
https://drive.google.com/file/d/0B0NJb0mKnh5QakN3SEJkQXJFbzg/view?usp=drivesdk
Is it possible to hide this auto brightness button from here? It's only in aicp 10, i know I'm asking you for different thing but i just need the stock experience!

**Comment by hrithikb** [comment]
https://drive.google.com/file/d/0B0NJb0mKnh5QWGY2ajFyTUdObE0/view?usp=drivesdk 
It's the xposed log

**Comment by hrithikb** [comment]
Is it possible sir?

**Comment by wasdennnoch** [comment]
Of course.

**Comment by wasdennnoch** [comment]
Added with 15606db50a978a206e2da907d8379269ac47923c

**Comment by hrithikb** [comment]
Build failed?

**Comment by wasdennnoch** [comment]
Indeed, but it's not my fault, Jenkins seems to have a bad day :P

**Comment by paphonbth** [comment]
That's because it runs on a crappy server with 1GB(i can only afford that) so it won't be reliable. lol :)

**Comment by hrithikb** [comment]
Oh, Jenkins's bad.

**Comment by hrithikb** [comment]
The auto brightness icon still coming!

**Comment by wasdennnoch** [comment]
I had to remove the code again because for some reason it completely broke another hook for me which made the QS tweaks unusable, I'm looking into another way to hide the icon.

**Comment by hrithikb** [comment]
Ok sir

**Comment by wasdennnoch** [comment]
Reimplemented with 56d8c444212e237e57a1a71524de10cf85260a1d

**Comment by hrithikb** [comment]
Still it's showing!😞😞

**Comment by hrithikb** [comment]
The icon is annoying but i think i have to live with it. thanks for trying sir!

**Comment by hrithikb** [comment]
Sorry sir its a mistake its fixed now!
