### ISSUE TITLE
Battery detail view

### ISSUE THREAD

**Issue by dimuthu3** [wasdennnoch/AndroidN-ify#631]
can add android 7.0 battery usage on qs toggle feature to N-ify planned feature list or next snapshots
![androidn_betternotifications-100663900-large idge](https://cloud.githubusercontent.com/assets/9978447/17165182/40ebbac8-53ec-11e6-8638-076129307159.jpg)

**Comment by haseoxth** [comment]
+1 on this, it will bring much convenience..

**Comment by hrithikb** [comment]
+1 from me too, it'll be so awesome!

**Comment by wasdennnoch** [comment]
I will add it in the next version, I want to release a new version as soon as possible and not implement something else that takes a long time to be made compatible for everyone ^^

**Comment by wasdennnoch** [comment]
Implemented.
