### ISSUE TITLE
QS row do not show the correct status

### ISSUE THREAD

**Issue by ja-som** [wasdennnoch/AndroidN-ify#638]
Hi, I'm on build #478, and QS in row do not show the correct status, only Off, and battery is wrong in QS tile...
![screenshot_20160728-183926](https://cloud.githubusercontent.com/assets/5942380/17221499/591a4886-54f4-11e6-8f79-14eced704d60.png)
![screenshot_20160728-183932](https://cloud.githubusercontent.com/assets/5942380/17221506/612a2136-54f4-11e6-80f9-d591bb6464ee.png)

And the Xposed log
[xposed_error_20160728_183957.txt](https://github.com/wasdennnoch/AndroidN-ify/files/388920/xposed_error_20160728_183957.txt)

**Comment by paphonbth** [comment]
Wrong battery in QSPanel is a known issue. GravityBox's battery tile doesn't support showing on more than one place.

**Comment by wasdennnoch** [comment]
I think it's related to another crash caused by the N click behaviour, I'll add a workaround tomorrow (handleLongClick in some tiles is only implemented in CM)

**Comment by ja-som** [comment]
@paphonbth battery was OK in previous builds for me

Thank you both for the replies...

**Comment by wasdennnoch** [comment]
Fixed with b2e217d32aaa74ca8645247ebf0f8d03c7be1b3b, but the builds fail, so you'll have to roll back to 477. @paphonbth Why is gradle running low on memory suddenly? Did the module grow too big? ^^
