### ISSUE TITLE
Strange behaviour with build #478

### ISSUE THREAD

**Issue by juangcardoso** [wasdennnoch/AndroidN-ify#639]
Hello, man! Good evening!

In last build of your module I'm facing some issues:

- I can't organize QS Tiles as in older versions, the first line just show wifi and Bluetooth Tiles;

- When I hit edit button and return my quick setting panel disappear;

- Sometimes the transition doesn't works;

- Mobile Data tile doesn't open expanded tile when I click on it. It redirects me directly to settings;

- QS Editor on SystemUI tuner gives me FC on SystemUI (I don't use it but I told because I thinks it can be related to the strange behaviour related before).

I made videos to show you these strange behaviour!

About mobile data tile: https://youtu.be/-0HG_vBt0SA

Other issues: https://youtu.be/qjicWSm2Ls4

**Device: Moto X 2014
**System: Stock Motorola's Marshmallow Software

Xposed LOGS: https://drive.google.com/folderview?id=0B8oeUhpF28-2cGhlWno2cFVoNUk

If you need another thing, ask how many times you need and sorry for the trouble! :)

And thanks for your awesome work!

**Comment by juangcardoso** [comment]
PS: I have catch logs before and after recording the video! The two logs are on the folder I linked to you!

**Comment by wasdennnoch** [comment]
Well that's a good bug report!
I already fixed most of it, but the builds fail, so you'll have to stay on 477 until the build thing got fixed too :P
The SystemUI tuner also is known, but you shouldn't need it with the new editor. When you edit the tiles the animation breaks for a short time, known too.
