### ISSUE TITLE
Please add an option to keep battery percentage on expanded notifications panel header

### ISSUE THREAD

**Issue by jahirfiquitiva** [wasdennnoch/AndroidN-ify#640]
Without this module, when one expands the notification panel, the battery percentage appears in the header.

Can you add an option to keep that thing?

Thanks in advance.

**Comment by paphonbth** [comment]
Simply "no". This module provides battery tile instead, which looks like N.

**Comment by jahirfiquitiva** [comment]
@paphonbth 
Is just another option, why so restrictive?

Btw, I can't find the battery tile in the app or quick settings... how to add it?

**Comment by wasdennnoch** [comment]
The tile is available in snapshot builds. "No" because it isn't there in N anymore and got replaced by the battery tile.

**Comment by jahirfiquitiva** [comment]
Are snapshot builds "safe enough" to install?
Are they available via Xposed Installer?
If not, can you link me to them?

Thanks

**Comment by wasdennnoch** [comment]
They are linked in the second post in the XDA thread. The current version crashes on non-CM devices though, but I'm going to fix that in a few minutes.

**Comment by jahirfiquitiva** [comment]
Thanks. Would you mind leaving a comment here when the crash is fixed? Because I use AICP in my device.
Thanks in advance.

**Comment by wasdennnoch** [comment]
Yup. But speaking of AICP, the new QS transition is broken for that too, you'll have to disable the "fancy qs transition" in the settings, working on a fix too. Apart from that everything should be working.

**Comment by jahirfiquitiva** [comment]
Thanks

I think transition is something minor, so I don't mind waiting a bit.

Btw, I have a doubt: should I uninstall the current stable version from Xposed Installer, before installing snapshots?

Thanks

**Comment by paphonbth** [comment]
Yes. If you don't uninstall the version from Xposed Installer, you won't be able to install snapshot versoin because different certificate is used to sign.

**Comment by jahirfiquitiva** [comment]
Ok.
Thanks for the info.
Waiting for the fix to start using the snapshots.
🙂

Thanks for this great module, keep it up.

**Comment by wasdennnoch** [comment]
A push is fixed, but the builds fail, so you'll have to go with version 477 as 478 crashes.
