### ISSUE TITLE
Fix lockscreen notifications layout

### ISSUE THREAD

**Issue by jahirfiquitiva** [wasdennnoch/AndroidN-ify#641]
Some apps notifications end being ugly in lockscreen, because of the layout change.

To be honest, I've seen this in Spotify and Phonograph notifications, take a look at this screenshot:

![screenshot_20160728-195506](https://cloud.githubusercontent.com/assets/10360816/17236854/f6aae0d4-5511-11e6-950f-89b57e65a1c6.png)

Look at all that blank wasted space...

Please do something about it, because is bugging me. Thanks in advance.

**Comment by haseoxth** [comment]
Actually developers already answered this issue before, unfortunately it can't be fixed until final N source hit.

**Comment by wasdennnoch** [comment]
Already discussed in #142
