### ISSUE TITLE
Experimental features cutting Notifications in Landscape mode

### ISSUE THREAD

**Issue by AniketDhoke** [wasdennnoch/AndroidN-ify#642]
![screenshot_20160729-172507](https://cloud.githubusercontent.com/assets/19507968/17247608/36486f40-5549-11e6-9660-13245fb2192a.png)

**Comment by wasdennnoch** [comment]
The shadow seems to stretch across the whole screen, are you on the newest version?

**Comment by AniketDhoke** [comment]
on #478 build

**Comment by juangcardoso** [comment]
Same problem here! Build #497

**Comment by juangcardoso** [comment]
When we pull down QS and activate rotation and put the device in landscape mode, the notification are cut!
