### ISSUE TITLE
Please add a bit more space between first row and second row quick setting tiles.

### ISSUE THREAD

**Issue by jahirfiquitiva** [wasdennnoch/AndroidN-ify#643]
Hi

With the module activated, second row tiles are a bit too near the first row ones, and sometimes, when I want to press the first row ones, I end up pressing the second row ones.

Here you have some screenshots:

**Current look**
![current quicksettings](https://cloud.githubusercontent.com/assets/10360816/17263244/a8d24fe8-55a5-11e6-81da-dc51a01bc73a.png)

**Expected/desired look**
![betterlooking quicksettings](https://cloud.githubusercontent.com/assets/10360816/17263243/a8d090d6-55a5-11e6-8d7f-9d8304636080.png)

Thanks in advance.

**Comment by jahirfiquitiva** [comment]
I have it enabled for sure.

**Comment by jahirfiquitiva** [comment]
Sorry for this, I just checked and enabling it fixed the issue.

Btw, I saw version 492 is available, is it crashing? does it have new stuff? Is it safe to install it?

**Comment by wasdennnoch** [comment]
It doesn't crash anymore. It has improved tile click behavior, but some users reported it working incorrectly, but nothing world breaking ;)

**Comment by jahirfiquitiva** [comment]
Thanks for the info, seems to work fine, except for the tiles transition that is still broken in AICP.
Sometimes it works, sometimes doesn't.

Actually I think it's in a loop: works once, doesn't once, and repeat.

Can't wait for it to be fully fixed too because when it works it's just 😍
