### ISSUE TITLE
Blacklist does not work

### ISSUE THREAD

**Issue by jahirfiquitiva** [wasdennnoch/AndroidN-ify#644]
Hi

As I reported some hours ago, music players that have custom layouts for notifications, end having ugly notifications in lockscreen when this module is enabled.

I just realized that inside the app, there's an option to add apps to blacklist so their notifications don't change.

I have added the music player I use, but its notifications are still being themed or changed by the module.

Please fix this in a future release. Thank you so much.

**Comment by wasdennnoch** [comment]
See #142 ;)

**Comment by jahirfiquitiva** [comment]
I saw that issue some time ago, but it's related to wrong notification size, not the fact that blacklist doesn't work

**Comment by wasdennnoch** [comment]
True, but the height still gets applied with the  blacklist enabled because we can't change it dynamically yet.

**Comment by jahirfiquitiva** [comment]
Now it makes sense. I hope you find a fix soon.
Thanks.
