### ISSUE TITLE
Recent Apps bug

### ISSUE THREAD

**Issue by dom1201** [wasdennnoch/AndroidN-ify#646]
I have a Problem with it.. Every time i click on my recent apps button my Oneplus 3 turns black for a second and then sends me to lockscreen. (Version 2.0)

Logfiles: 
[alogcat.2016-07-30-17-02-52+0200.txt](https://github.com/wasdennnoch/AndroidN-ify/files/391934/alogcat.2016-07-30-17-02-52.0200.txt)

Latest OxygenOS installed.

**Comment by wasdennnoch** [comment]
Known issue, disable the new "No Recents" image to fix that. The code behind that is more complex than I thought, so it will take longer to be fixed (if possible).

**Comment by dom1201** [comment]
Ok danke ;)
