### ISSUE TITLE
Preference file isn't readable by xposed

### ISSUE THREAD

**Issue by hrithikb** [wasdennnoch/AndroidN-ify#647]
I tried every method reinstalling the module rebooting bt nothing helped!

**Comment by wasdennnoch** [comment]
Try the latest snapshot if it built successful, it should fix it (install, open, reboot). I can't help if the issue persists.

**Comment by hrithikb** [comment]
Ok, u knw the layout of your website for download is changed

**Comment by wasdennnoch** [comment]
You mean from the build server? This isn't my site, it's from @paphonbth

**Comment by hrithikb** [comment]
Oh yes and the website is showing an error it's not loading the page

**Comment by hrithikb** [comment]
Now it's working

**Comment by hrithikb** [comment]
Preference problem fixed but, when pressing the wifi, data, Bluetooth and any other toggle icon which shows the detail view are not working

**Comment by wasdennnoch** [comment]
So they don't show the detail view when the panel is expanded? Logs or it didn't happen :P

**Comment by hrithikb** [comment]
They don't show detail view and not even activating the toggle on single press in header toggle

**Comment by hrithikb** [comment]
https://drive.google.com/file/d/0B0NJb0mKnh5QaE5wSVo2c1o0T2c/view?usp=drivesdk
Xposed log

**Comment by wasdennnoch** [comment]
We'll mobe the discussion over to #649

**Comment by martirutllant** [comment]
What web are you talking about?

**Comment by wasdennnoch** [comment]
wat

**Comment by martirutllant** [comment]
Yeah, sorry, I have this problem and you say that in the last build this bug has been fixed; but I can't find the "build server", so may you give me the link please?

**Comment by wasdennnoch** [comment]
https://ci.paphonb.xyz/jenkins/job/AndroidN-ify/
I don't know what exactly you are talking about, but the empty QS fix isn't included yet as I need to fix a build failure.

**Comment by martirutllant** [comment]
Thank you! That was the web, but I am not getting the empty QS error, I just have the "Preference file isn't readable by xposed" error, now I have download the build but the error is still there, at least, the animation of the QS is the original android N animation
