### ISSUE TITLE
Music player notifications style

### ISSUE THREAD

**Issue by hrithikb** [wasdennnoch/AndroidN-ify#650]
https://drive.google.com/file/d/0B0NJb0mKnh5QeFlHaGVOejZra2c/view?usp=drivesdk
Is it possible to have this type of music notification? It is the headsup notification of music and the notification in panel looks like this:https://drive.google.com/file/d/0B0NJb0mKnh5QS1ZQS0d4dUdYcFE/view?usp=drivesdk

**Comment by wasdennnoch** [comment]
This depends on the music player, your player uses a custom notification layout whereas the other one uses a standard notification with actions. I can't change that.

**Comment by hrithikb** [comment]
I have google play music also but it also shows the notification like this

**Comment by hrithikb** [comment]
If the player srry the different layout then why headsup are like this

**Comment by hrithikb** [comment]
https://drive.google.com/file/d/0B0NJb0mKnh5QdXY5Zm1XdHpMTEk/view?usp=drivesdk
https://drive.google.com/file/d/0B0NJb0mKnh5QWVdKckwxS1BGeHc/view?usp=drivesdk
This is google play music

**Comment by wasdennnoch** [comment]
Play music uses the Media Notification style so it looks different too.

**Comment by hrithikb** [comment]
So will you suggest me the player which looks like Android n's

**Comment by wasdennnoch** [comment]
I don't suggest anything, I'm just saying that the three screenshots show players which post different notifications. If you have the same player as in the notification my guess is that they only use this style in N where the notifications officially look like that and use the custom layout in earlier versions.
