### ISSUE TITLE
QS tiles are gone occasionally

### ISSUE THREAD

**Issue by SlimShadys** [wasdennnoch/AndroidN-ify#652]
So, randomly a weird bug happens. While I'm on my phone scrolling etc the header disappears. The only things still visibile are the brightness and the edit button. No QS & User Icon etc 
Log: http://hastebin.com/omokulanez.vbs
(I'll give u the Temasek one very soon, just got back from vacation :P)

**Comment by aviraxp** [comment]
yes, I noticed that too.

**Comment by TheDorkKnightRises** [comment]
Can confirm.
On CandySix and Zephyr ROMs (both Substratum based, maybe that's the link?)
Device: OnePlus One (bacon)

**Comment by LPW00** [comment]
Same Problem here. 
Device: Bacon
ROM: RR-CAF (with CMTE so substratum can't be the Problem)

**Comment by MSF-Jarvis** [comment]
I can reproduce this partially, with only the text labels disappearing on DirtyUnicorns 10.5

**Comment by wasdennnoch** [comment]
Fixed with 9855d5d001e394f67e6472237507ddbfcbabee35
