### ISSUE TITLE
QS tiles doesn't show

### ISSUE THREAD

**Issue by LKc1949** [wasdennnoch/AndroidN-ify#653]
As the screenshots,QS tiles sometimes not show.
To solve this,just edit-add a new tile-back,and all the tiles will back again.
ROM: Resurrection Remix 5.7.2,Android 6.0.1_r52
![screenshot_20160801-185520](https://cloud.githubusercontent.com/assets/17155723/17292419/7dee6238-57af-11e6-9c85-d64e9d83eea1.png)
![screenshot_20160801-185529](https://cloud.githubusercontent.com/assets/17155723/17292423/86e9bf4a-57af-11e6-827c-ab59302e2c5c.png)

**Comment by wasdennnoch** [comment]
I'll update my RR to the same version too now, let's see if I'll face the same problem ^^

**Comment by wasdennnoch** [comment]
Actually I'll move this into #652
