### ISSUE TITLE
Dual Sim tiles don't toggle data

### ISSUE THREAD

**Issue by cbdreinulldrei** [wasdennnoch/AndroidN-ify#657]
Dual Sim devices have two tiles for signal ("cell1", "cell2"). QS editor can't cope with these. When leaving untouched (=only edit using System UI Tuner), two tiles show up. 

On earlier builds (473 and before) these e.g. sent the use to the cellular data settinngs. Builds > 496 don't do anything now.

**Comment by wasdennnoch** [comment]
The second sim tile was added in build 499 (although the fist sim might show up twice). Are there any errors in the logs?

**Comment by cbdreinulldrei** [comment]
Correct. When using the QS editor, I can chose from three tiles. The regular one and cell1+2. When using these, I notice that when looking at QS (without pulling down), both sims look correct. When pulling down, only sim1 has correct signal, sim2 is empty (like "no reception"). Clicking has no effect. Turned on logs and will check.

Xposed log showed one line: QSTileHostHooks: Brute forcing tile specs.

**Comment by wasdennnoch** [comment]
That's a normal log, I'll remove it when change the way tiles are loaded a bit. Apart from that there's nothing else in the log?

**Comment by cbdreinulldrei** [comment]
In 503 long pressing them opens the detailed WiFi settings.

Logs:
08-02 19:22:25.265 I/Xposed  ( 4244): [Android N-ify] [DEBUG] StatusBarHeaderHooks: Animating QuickQS icon: true; type: AirplaneModeTile
08-02 19:22:25.269 I/Xposed  ( 4244): [Android N-ify] [DEBUG] StatusBarHeaderHooks: Animating QuickQS icon: true; type: DndTile
08-02 19:22:25.989 I/Xposed  ( 4244): [Android N-ify] [DEBUG] StatusBarHeaderHooks: onMeasureHook: Grid height changed to 1070
08-02 19:22:26.812 I/Xposed  ( 4244): [Android N-ify] [DEBUG] StatusBarHeaderHooks: onMeasureHook: Grid height unchanged
08-02 19:22:27.997 I/Xposed  ( 4244): [Android N-ify] [DEBUG] StatusBarHeaderHooks: onMeasureHook: Grid height unchanged
08-02 19:22:28.550 I/Xposed  ( 4244): [Android N-ify] [DEBUG] NotificationPanelHooks: setBarStateHook: Setting state to 1
08-02 19:22:28.887 I/Xposed  ( 4244): [Android N-ify] [DEBUG] StatusBarHeaderHooks: onMeasureHook: Grid height unchanged
08-02 19:22:28.924 I/Xposed  ( 4244): [Android N-ify] [DEBUG] StatusBarHeaderHooks: onMeasureHook: Grid height unchanged
08-02 19:22:28.963 I/Xposed  ( 4244): [Android N-ify] [DEBUG] StatusBarHeaderHooks: onMeasureHook: Grid height unchanged
08-02 19:22:28.964 I/Xposed  ( 4244): [Android N-ify] [DEBUG] StatusBarHeaderHooks: onMeasureHook: Grid height unchanged
08-02 19:22:29.001 I/Xposed  ( 4244): [Android N-ify] [DEBUG] StatusBarHeaderHooks: onMeasureHook: Grid height unchanged
08-02 19:22:29.001 I/Xposed  ( 4244): [Android N-ify] [DEBUG] StatusBarHeaderHooks: onMeasureHook: Unhook and setup with grid height 1070
08-02 19:22:29.001 I/Xposed  ( 4244): [Android N-ify] [DEBUG] QuickQSPanel: setupAnimators called
08-02 19:22:37.052 I/Xposed  ( 4244): [Android N-ify] [DEBUG] NotificationPanelHooks: setBarStateHook: Setting state to 1
08-02 19:22:37.206 I/Xposed  ( 4244): [Android N-ify] [DEBUG] NotificationPanelHooks: setBarStateHook: Setting state to 1
08-02 19:22:41.660 I/Xposed  ( 4244): [Android N-ify] [DEBUG] NotificationPanelHooks: setBarStateHook: Setting state to 1
08-02 19:23:23.894 I/Xposed  ( 8760): YouTube: com.google.android.youtube 11.27.53 loaded!
08-02 19:23:23.895 I/Xposed  ( 8760): YouTube AdAway 3.2.4: Trying brute force way...
08-02 19:23:24.282 I/Xposed  ( 8760): YouTube AdAway: Successfully hooked nlh constructor!
08-02 19:23:29.527 I/Xposed  ( 8760): YouTube AdAway: Successfully hooked sequence: class =kiw params=lti, lws, kjt, kio
08-02 19:23:53.746 I/Xposed  ( 4244): [Android N-ify] [DEBUG] NotificationPanelHooks: setBarStateHook: Setting state to 0
08-02 19:24:48.600 I/Xposed  ( 4244): [Android N-ify] [DEBUG] StatusBarHeaderHooks: handleShowingDetail: showing detail; expanding: false
08-02 19:24:50.941 I/Xposed  ( 4244): [Android N-ify] [DEBUG] StatusBarHeaderHooks: handleShowingDetail: hiding detail; collapsing: false

**Comment by cbdreinulldrei** [comment]
Sorry that's build 504.

**Comment by wasdennnoch** [comment]
So no error. I'm going to have a deeper look at this later, going on vacation soon, so it might take some days ^^

**Comment by cbdreinulldrei** [comment]
Noticed that when not using the built-in editor, a long press opens bluetooth settings... instead of wifi (which open when using the built-in editor).

**Comment by cbdreinulldrei** [comment]
#522 still present if Android N click tile behaviour is active.

**Comment by rgshah3** [comment]
Bug still present on #573

**Comment by cbdreinulldrei** [comment]
Works here when I turn off N-style click behaviour. Assume a system call handles this in this case.

**Comment by rgshah3** [comment]
https://github.com/wasdennnoch/AndroidN-ify/files/445736/alogcat.2016-08-31-00-10-48.0530.txt

Log cat. 

This issue has been present since more than a month.

**Comment by wasdennnoch** [comment]
I'll merge this into #1029 because that one has more detailed information and gifs ;)
