### ISSUE TITLE
Ghost Touch between setting and user photo opens 5th qs

### ISSUE THREAD

**Issue by AniketDhoke** [wasdennnoch/AndroidN-ify#662]
![screenshot_20160804-093750](https://cloud.githubusercontent.com/assets/19507968/17390144/2867731a-59bf-11e6-9ec9-4d7d5cc7110a.png)

**Comment by wasdennnoch** [comment]
Does this still happen? I've seen nobody else having this issue.

**Comment by ItzLevvie** [comment]
Cannot reproduce on my end

**Comment by AniketDhoke** [comment]
after clicking user photo tiles open even after they are not there

https://drive.google.com/open?id=0BwHLwsbBEb_0a0dRcVpMYVpOaGs

**Comment by AniketDhoke** [comment]
Fixed
