### ISSUE TITLE
After clicking on editor and back causing duplicate tiles on header

### ISSUE THREAD

**Issue by AniketDhoke** [wasdennnoch/AndroidN-ify#663]
![screenshot_20160804-093809](https://cloud.githubusercontent.com/assets/19507968/17390187/7c466b80-59bf-11e6-97cf-aec3926c1689.png)

**Comment by AniketDhoke** [comment]
And enjoy your vacations

**Comment by wasdennnoch** [comment]
Fixed with the latest builds.

**Comment by ItzLevvie** [comment]
https://youtu.be/db4mt8ERZGw (skip to 0:25)

@wasdennnoch

**Comment by ItzLevvie** [comment]
^^ nevermind. It's fixed on #531

**Comment by ItzLevvie** [comment]
Can this be fixed? @wasdennnoch 

I don't know if this is fixed in #53
