### ISSUE TITLE
Animation partially broken on Quantum Go stock ROM

### ISSUE THREAD

**Issue by KaMyKaSii** [wasdennnoch/AndroidN-ify#666]

**Comment by KaMyKaSii** [comment]
Animation not working in Marshmallow AOSP (not Nexus)
Log: https://drive.google.com/file/d/0B1uvONk-jlRiREFORHM4aG1ZckE/view?usp=drivesdk
Video: https://drive.google.com/file/d/0B1uvONk-jlRiaUFneE5RbFBfVFU/view?usp=drivesdk

**Comment by wasdennnoch** [comment]
Still an issue?

**Comment by wasdennnoch** [comment]
No response
