### ISSUE TITLE
Wrong visualization in Heads Up notification on COS 13.1 (OnePlus One)

### ISSUE THREAD

**Issue by PaulSchulx** [wasdennnoch/AndroidN-ify#667]
![screenshot_20160805-130011](https://cloud.githubusercontent.com/assets/20858061/17434763/a90a7eb0-5b0c-11e6-923d-f9071757cf5f.png)

[xposed_error_20160805_130032.log.zip](https://github.com/wasdennnoch/AndroidN-ify/files/403617/xposed_error_20160805_130032.log.zip)

**Comment by wasdennnoch** [comment]
There is no module error in the log; make sure to post a log _after_ a broken heads up notification.

**Comment by ttimz1313** [comment]
Hummmmm.............OK...........tiesqure.....................vurooooom...............k........check................
