### ISSUE TITLE
Aospa status bar incompatibility

### ISSUE THREAD

**Issue by LPW00** [wasdennnoch/AndroidN-ify#670]
qs tiles from header aren't synchronized with the ones from the panel.
System UI force closes if u try to use the n-ify qs tiles editor and changes don't apply.
Battery qs tile isn't shown correctly. And the ^ button isn't where it should be.

logcat: http://s000.tinyupload.com/index.php?file_id=46523322216695546603
System UI folder: http://s000.tinyupload.com/index.php?file_id=00480094081586165945
Xposed log: http://s000.tinyupload.com/index.php?file_id=36133424667040231259

**Comment by wasdennnoch** [comment]
The crashes in the log got fixed with ac64c5575b43a18b4887831aa33efd2f36479917, are there any other issues?

**Comment by aviraxp** [comment]
There are also some issues.

i turned on Android N click behavior, but I can't change them in the top bar, they behave just like click the QS tile.

**Comment by wasdennnoch** [comment]
That should also be fixed, something else? ^^

**Comment by aviraxp** [comment]
I have changed to Exodus, so I can't test:D

**Comment by wasdennnoch** [comment]
Then I'll consider it as fixed :P

**Comment by LPW00** [comment]
I received the email to late, it's still buggy....
But I don't use aospa anymore...
