### ISSUE TITLE
Unsupported Toggles

### ISSUE THREAD

**Issue by Kroxzz** [wasdennnoch/AndroidN-ify#672]
![screenshot_20160807-043636](https://cloud.githubusercontent.com/assets/20885465/17461619/9c1eb53e-5c58-11e6-8286-6140668d5de5.png)
![screenshot_20160807-043630](https://cloud.githubusercontent.com/assets/20885465/17461622/a43ac622-5c58-11e6-8bc3-ce44a5858312.png)

**Comment by wasdennnoch** [comment]
They are indeed unsupported; HTC modified them heavily which makes it impossible for me to support them. You'll have to disable the header tweaks or live without header tiles.
