### ISSUE TITLE
Open calendar from Status Bar date

### ISSUE THREAD

**Issue by CaptInsano** [wasdennnoch/AndroidN-ify#674]
In my stock ROM Oxegen OS 3.2.2 on OnePlus Three when I tap the date in the status bar my calendar opens,  since installing N-ify (latest snapshot) clicking the status bar date does nothing. 

Is it possible to return this feature? 

Thanks you your work!

**Comment by cbdreinulldrei** [comment]
Confirmed to cause trouble on Moto X Play 2015 with 6.0.1. Clock does not open up.

08-16 23:30:38.744 E/Xposed  ( 4263): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
08-16 23:30:42.427 E/Xposed  ( 4263): java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.startsWith(java.lang.String)' on a null object reference
08-16 23:30:42.427 E/Xposed  ( 4263): 	at android.content.Intent.parseUri(Intent.java:4606)
08-16 23:30:42.427 E/Xposed  ( 4263): 	at com.ceco.marshmallow.gravitybox.ModStatusBar.launchClockAction(ModStatusBar.java:1315)
08-16 23:30:42.427 E/Xposed  ( 4263): 	at com.ceco.marshmallow.gravitybox.ModStatusBar.access$23(ModStatusBar.java:1311)
08-16 23:30:42.427 E/Xposed  ( 4263): 	at com.ceco.marshmallow.gravitybox.ModStatusBar$3.onClick(ModStatusBar.java:344)
08-16 23:30:42.427 E/Xposed  ( 4263): 	at android.view.View.performClick(View.java:5207)
08-16 23:30:42.427 E/Xposed  ( 4263): 	at android.view.View$PerformClick.run(View.java:21168)
08-16 23:30:42.427 E/Xposed  ( 4263): 	at android.os.Handler.handleCallback(Handler.java:746)
08-16 23:30:42.427 E/Xposed  ( 4263): 	at android.os.Handler.dispatchMessage(Handler.java:95)
08-16 23:30:42.427 E/Xposed  ( 4263): 	at android.os.Looper.loop(Looper.java:148)
08-16 23:30:42.427 E/Xposed  ( 4263): 	at android.app.ActivityThread.main(ActivityThread.java:5443)
08-16 23:30:42.427 E/Xposed  ( 4263): 	at java.lang.reflect.Method.invoke(Native Method)
08-16 23:30:42.427 E/Xposed  ( 4263): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
08-16 23:30:42.427 E/Xposed  ( 4263): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
08-16 23:30:42.427 E/Xposed  ( 4263): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)

**Comment by cbdreinulldrei** [comment]
I know the error message belongs to Gravity Box, but does not come up without N-ify.

**Comment by wasdennnoch** [comment]
Implemented with 64e1446d933c7518f586613de154d315f80d1fd9

**Comment by CaptInsano** [comment]
Confirmed working.

Many thanks for this fix and all your work!!
