### ISSUE TITLE
Location toggle missing options

### ISSUE THREAD

**Issue by Jerdle** [wasdennnoch/AndroidN-ify#679]
When tapping the location toggle on the quick pulldown, it doesn't show the options to select Battery Saving, High Accuracy, etc. When the tray is fully expanded it works as expected. See logs and screenshot.

[xposed.txt](https://github.com/wasdennnoch/AndroidN-ify/files/418298/xposed.txt)
[logcat_and_device_info (1).zip](https://github.com/wasdennnoch/AndroidN-ify/files/418299/logcat_and_device_info.1.zip)
![screenshot_20160815-100740](https://cloud.githubusercontent.com/assets/10408060/17668844/33b8f9aa-62d9-11e6-8bd6-df358d46a1bd.png)
![screenshot_20160815-111310](https://cloud.githubusercontent.com/assets/10408060/17668875/4a7d5758-62d9-11e6-8d7e-71e0fc999e84.png)

**Comment by wasdennnoch** [comment]
Looks similar to #399, I'll move them together.
