### ISSUE TITLE
QS completely "dead" in #515

### ISSUE THREAD

**Issue by cbdreinulldrei** [wasdennnoch/AndroidN-ify#681]
Was working in #512 or #513 ("Fix N tile click behaviour"). Now tiles show, but WiFi appears to be off, no mobile reception etc.

**Comment by cbdreinulldrei** [comment]
Works is QS editor is enabled. Seems to be related to system QS bar hooking.

**Comment by cbdreinulldrei** [comment]
Here's a log, but with QS enabled:

08-16 23:05:33.920 I/Xposed  (17912): [Android N-ify] [ERROR] StatusBarHeaderHooks: Error in hook
08-16 23:05:33.921 E/Xposed  (17912): java.lang.NoSuchMethodError: com.android.systemui.qs.tiles.WifiTile#handleDetailClick()#exact
08-16 23:05:33.921 E/Xposed  (17912): 	at de.robv.android.xposed.XposedHelpers.findMethodExact(XposedHelpers.java:337)
08-16 23:05:33.921 E/Xposed  (17912): 	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:178)
08-16 23:05:33.921 E/Xposed  (17912): 	at tk.wasdennnoch.androidn_ify.systemui.qs.tiles.hooks.QSTileHook.<init>(QSTileHook.java:38)
08-16 23:05:33.921 E/Xposed  (17912): 	at tk.wasdennnoch.androidn_ify.systemui.qs.tiles.hooks.WifiTileHook.<init>(WifiTileHook.java:20)
08-16 23:05:33.921 E/Xposed  (17912): 	at tk.wasdennnoch.androidn_ify.systemui.notifications.StatusBarHeaderHooks.hook(StatusBarHeaderHooks.java:982)
08-16 23:05:33.921 E/Xposed  (17912): 	at tk.wasdennnoch.androidn_ify.XposedHook.handleLoadPackage(XposedHook.java:109)
08-16 23:05:33.921 E/Xposed  (17912): 	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:34)
08-16 23:05:33.921 E/Xposed  (17912): 	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:61)
08-16 23:05:33.921 E/Xposed  (17912): 	at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:106)
08-16 23:05:33.921 E/Xposed  (17912): 	at de.robv.android.xposed.XposedInit$1.beforeHookedMethod(XposedInit.java:93)
08-16 23:05:33.921 E/Xposed  (17912): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:314)
08-16 23:05:33.921 E/Xposed  (17912): 	at android.app.ActivityThread.handleBindApplication(<Xposed>)
08-16 23:05:33.921 E/Xposed  (17912): 	at android.app.ActivityThread.-wrap1(ActivityThread.java)
08-16 23:05:33.921 E/Xposed  (17912): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1415)
08-16 23:05:33.921 E/Xposed  (17912): 	at android.os.Handler.dispatchMessage(Handler.java:102)
08-16 23:05:33.921 E/Xposed  (17912): 	at android.os.Looper.loop(Looper.java:148)
08-16 23:05:33.921 E/Xposed  (17912): 	at android.app.ActivityThread.main(ActivityThread.java:5443)
08-16 23:05:33.921 E/Xposed  (17912): 	at java.lang.reflect.Method.invoke(Native Method)
08-16 23:05:33.921 E/Xposed  (17912): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
08-16 23:05:33.921 E/Xposed  (17912): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
08-16 23:05:33.921 E/Xposed  (17912): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)

**Comment by cbdreinulldrei** [comment]
Result is that WiFi tile is dead in QS, but works when pulled down.

**Comment by wasdennnoch** [comment]
Which ROM are you on?

**Comment by cbdreinulldrei** [comment]
QS were looking OK in #515 with QS editor enabled, totally "dead" in #516...

**Comment by cbdreinulldrei** [comment]
ROM is near stock 6.0.1 by Motorola. Has some Moto stuff added, but not much.

**Comment by cbdreinulldrei** [comment]
MPD24.107-70 is the build number. It's an official intl ROM for the Moto X Play Dual Sim (XT 1562). 

Have Gravity Box installed. But was working before.

**Comment by ttimz1313** [comment]
Hmmmm..........h............set..............tiesqure...............not.............

**Comment by wasdennnoch** [comment]
It should be fixed now?

**Comment by cbdreinulldrei** [comment]
Yes, this very bug seems squashed. Clicking "cell1" and "cell2" tiles still produces nothing. Except for long press, which always opens data usage in settings for sim 2.
