### ISSUE TITLE
Hotspot does not appear

### ISSUE THREAD

**Issue by hakan5816** [wasdennnoch/AndroidN-ify#682]
Hotspot does not appear, although the speed setting section

**Comment by wasdennnoch** [comment]
Which ROM are you using?

**Comment by hakan5816** [comment]
Xperia Z3 Compact Slimm Rom v2.5

**Comment by wasdennnoch** [comment]
Where is the tile missing? In the header? Panel? Editor?

**Comment by hakan5816** [comment]
I add hotspots Edit place. It does not appear on the panel. In the title to appear on the panel it does not appear. (I tried Xperia Z2, it does not appear in the phone)

**Comment by wasdennnoch** [comment]
Anything changed with the latest build?

**Comment by hakan5816** [comment]
Yes,fixed. Thanx
