### ISSUE TITLE
Clicking clock does not do anything

### ISSUE THREAD

**Issue by cbdreinulldrei** [wasdennnoch/AndroidN-ify#683]
But generates error in log:

08-17 15:36:03.838 E/Xposed  ( 4293): java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.startsWith(java.lang.String)' on a null object reference
08-17 15:36:03.838 E/Xposed  ( 4293): 	at android.content.Intent.parseUri(Intent.java:4606)
08-17 15:36:03.838 E/Xposed  ( 4293): 	at com.ceco.marshmallow.gravitybox.ModStatusBar.launchClockAction(ModStatusBar.java:1315)
08-17 15:36:03.838 E/Xposed  ( 4293): 	at com.ceco.marshmallow.gravitybox.ModStatusBar.access$23(ModStatusBar.java:1311)
08-17 15:36:03.838 E/Xposed  ( 4293): 	at com.ceco.marshmallow.gravitybox.ModStatusBar$3.onClick(ModStatusBar.java:344)
08-17 15:36:03.838 E/Xposed  ( 4293): 	at android.view.View.performClick(View.java:5207)
08-17 15:36:03.838 E/Xposed  ( 4293): 	at android.view.View$PerformClick.run(View.java:21168)
08-17 15:36:03.838 E/Xposed  ( 4293): 	at android.os.Handler.handleCallback(Handler.java:746)
08-17 15:36:03.838 E/Xposed  ( 4293): 	at android.os.Handler.dispatchMessage(Handler.java:95)
08-17 15:36:03.838 E/Xposed  ( 4293): 	at android.os.Looper.loop(Looper.java:148)
08-17 15:36:03.838 E/Xposed  ( 4293): 	at android.app.ActivityThread.main(ActivityThread.java:5443)
08-17 15:36:03.838 E/Xposed  ( 4293): 	at java.lang.reflect.Method.invoke(Native Method)
08-17 15:36:03.838 E/Xposed  ( 4293): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
08-17 15:36:03.838 E/Xposed  ( 4293): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
08-17 15:36:03.838 E/Xposed  ( 4293): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)

**Comment by wasdennnoch** [comment]
This issue is caused by GravityBox and not my module and I even had a look at the GB source to confirm that. It seems that is is caused because you didn't specify an app that gets launched on clock click.

**Comment by cbdreinulldrei** [comment]
Stimmt, mein Fehler. Ich schulde dir ein Bier. :)

**Comment by ItzLevvie** [comment]
^ Translated version: "Right, my mistake . I owe you a beer. :)"

**Comment by cbdreinulldrei** [comment]
Hah, did not know it'd go live here as well... Sorry. :) Indeed my fault and I proposed a beer.
