### ISSUE TITLE
Wrong timestamp alignment LG stock rom

### ISSUE THREAD

**Issue by dil3mm4** [wasdennnoch/AndroidN-ify#687]
As shown in pic 
https://drive.google.com/file/d/0B_oTazq9BMw8ZUtWWktZZ0pKTmc/view?usp=drivesdk
This happens on each OS reboot but solves itself doing a SystemUI reboot.

Lg Stock 5.0.2 rom

**Comment by wasdennnoch** [comment]
It's a known issue with LG, but as your SystemUI looks close to AOSP it might be easier to fix. I'd need your deodexed SystemUI for that. If you know how to do deodex (or want to try it), it would help everyone with this issue. If not, I can try to search for another LG SystemUI. Just let me know :)

**Comment by dil3mm4** [comment]
Looks like AOSP because of xPosed tweaks over it.
I've tried also to disable all the modules except N-ify but the issue it's
still there.
If you want I can pull the systemUI for you.

Il 20/ago/2016 21:36, "MrWasdennnoch" <notifications@github.com> ha scritto:

**Comment by wasdennnoch** [comment]
I can't find a LG SystemUI because the XDA search seems to be broken for me, so if you want to you can upload the deodexed version. Not the odexed one, I can't do anything with it.

**Comment by paphonbth** [comment]
https://ci.paphonb.xyz/ppb/LGSystemUI.apk

**Comment by wasdennnoch** [comment]
If you enable 12h mode in the settings, does the am/pm label shift down too or only the time?

**Comment by dil3mm4** [comment]
Both

**Comment by dil3mm4** [comment]
Solved in unstable build
