### ISSUE TITLE
Quick settings header overlapping first notification

### ISSUE THREAD

**Issue by jemedejuex** [wasdennnoch/AndroidN-ify#688]
I have a strong feeling that a poorly-modified SystemUI.apk might be the cause of my problem, but most of the time, the quick settings header overlaps the first notification. I don't know if this is the right place to do this, but can I request for a feature to set a custom value for this?

**Comment by jemedejuex** [comment]
Running Android 5.1 on a Spreadtrum SoC. I had to mention this 'cause most devices with the same SoC have the same problem too.

**Comment by wasdennnoch** [comment]
The chipset won't have any influence on the module's behavior, but the ROM has, so please psot what ROM you use, attach a screenshot and just to be sure also post your Xposed log.

**Comment by jemedejuex** [comment]
Yeah... I mentioned the chipset 'cause near-AOSP ROMs on Spreadtrum have this wierd extra padding on the header. Yes, I use the stock ROM. Xposed logs coming right up
