### ISSUE TITLE
Qs issues with Cm 12.1

### ISSUE THREAD

**Issue by hrithikb** [wasdennnoch/AndroidN-ify#691]
Quick toggles are not working in header, detail view always collapse the qs panel!
But when i disabled the edit button then detail view appears but can't edit tiles then😖😖

**Comment by hrithikb** [comment]
Xposed logs
https://drive.google.com/file/d/0B0NJb0mKnh5QNloyeWxpOVNJUUk/view?usp=drivesdk

**Comment by xpduyson** [comment]
already reported at #418
