### ISSUE TITLE
SystemUI Crash since last update

### ISSUE THREAD

**Issue by Happyfeet01** [wasdennnoch/AndroidN-ify#697]
SystemUI Crashing when Android N-fy is enabled.

Here is an Crash report:

`--------- beginning of crash
08-25 13:44:55.747  5346  5346 E AndroidRuntime: FATAL EXCEPTION: main
08-25 13:44:55.747  5346  5346 E AndroidRuntime: Process: com.android.systemui, PID: 5346
08-25 13:44:55.747  5346  5346 E AndroidRuntime: java.lang.ClassCastException: android.widget.TextView cannot be cast to android.widget.ImageView
08-25 13:44:55.747  5346  5346 E AndroidRuntime:        at tk.wasdennnoch.androidn_ify.systemui.notifications.NotificationHooks$17.replaceHookedMethod(NotificationHooks.java:646)
08-25 13:44:55.747  5346  5346 E AndroidRuntime:        at de.robv.android.xposed.XC_MethodReplacement.beforeHookedMethod(XC_MethodReplacement.java:29)
08-25 13:44:55.747  5346  5346 E AndroidRuntime:        at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:314)
08-25 13:44:55.747  5346  5346 E AndroidRuntime:        at com.android.systemui.statusbar.ExpandableNotificationRow.setIconAnimationRunningForChild(<Xposed>)
08-25 13:44:55.747  5346  5346 E AndroidRuntime:        at com.android.systemui.statusbar.ExpandableNotificationRow.setIconAnimationRunning(ExpandableNotificationRow.java)
08-25 13:44:55.747  5346  5346 E AndroidRuntime:        at com.android.systemui.statusbar.ExpandableNotificationRow.setIconAnimationRunning(ExpandableNotificationRow.java)
08-25 13:44:55.747  5346  5346 E AndroidRuntime:        at com.android.systemui.statusbar.stack.NotificationStackScrollLayout.updateAnimationState(NotificationStackScrollLayout.java)
08-25 13:44:55.747  5346  5346 E AndroidRuntime:        at com.android.systemui.statusbar.stack.NotificationStackScrollLayout.updateAnimationState(NotificationStackScrollLayout.java)
08-25 13:44:55.747  5346  5346 E AndroidRuntime:        at com.android.systemui.statusbar.stack.NotificationStackScrollLayout.onViewAddedInternal(NotificationStackScrollLayout.java)
08-25 13:44:55.747  5346  5346 E AndroidRuntime:        at com.android.systemui.statusbar.stack.NotificationStackScrollLayout.onViewAdded(NotificationStackScrollLayout.java)
08-25 13:44:55.747  5346  5346 E AndroidRuntime:        at android.view.ViewGroup.dispatchViewAdded(ViewGroup.java:4203)
08-25 13:44:55.747  5346  5346 E AndroidRuntime:        at android.view.ViewGroup.addViewInner(ViewGroup.java:4360)
08-25 13:44:55.747  5346  5346 E AndroidRuntime:        at android.view.ViewGroup.addView(ViewGroup.java:4146)
08-25 13:44:55.747  5346  5346 E AndroidRuntime:        at android.view.ViewGroup.addView(ViewGroup.java:4087)
08-25 13:44:55.747  5346  5346 E AndroidRuntime:        at android.view.ViewGroup.addView(ViewGroup.java:4060)
08-25 13:44:55.747  5346  5346 E AndroidRuntime:        at com.android.systemui.statusbar.phone.PhoneStatusBar.updateNotificationShade(PhoneStatusBar.java)
08-25 13:44:55.747  5346  5346 E AndroidRuntime:        at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
08-25 13:44:55.747  5346  5346 E AndroidRuntime:        at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:334)
08-25 13:44:55.747  5346  5346 E AndroidRuntime:        at com.android.systemui.statusbar.phone.PhoneStatusBar.updateNotificationShade(<Xposed>)
08-25 13:44:55.747  5346  5346 E AndroidRuntime:        at com.android.systemui.statusbar.phone.PhoneStatusBar.updateNotifications(PhoneStatusBar.java)
08-25 13:44:55.747  5346  5346 E AndroidRuntime:        at com.android.systemui.statusbar.BaseStatusBar.addNotificationViews(BaseStatusBar.java)
08-25 13:44:55.747  5346  5346 E AndroidRuntime:        at com.android.systemui.statusbar.phone.PhoneStatusBar.addNotification(PhoneStatusBar.java)
08-25 13:44:55.747  5346  5346 E AndroidRuntime:        at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
08-25 13:44:55.747  5346  5346 E AndroidRuntime:        at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:334)
08-25 13:44:55.747  5346  5346 E AndroidRuntime:        at com.android.systemui.statusbar.phone.PhoneStatusBar.addNotification(<Xposed>)
08-25 13:44:55.747  5346  5346 E AndroidRuntime:        at com.android.systemui.statusbar.BaseStatusBar$6$1.run(BaseStatusBar.java)
08-25 13:44:55.747  5346  5346 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:739)
08-25 13:44:55.747  5346  5346 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:95)
08-25 13:44:55.747  5346  5346 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:234)
08-25 13:44:55.747  5346  5346 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:5526)
08-25 13:44:55.747  5346  5346 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
08-25 13:44:55.747  5346  5346 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
08-25 13:44:55.747  5346  5346 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
08-25 13:44:55.747  5346  5346 E AndroidRuntime:        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
read: unexpected EOF!`

**Comment by wasdennnoch** [comment]
Does it still crash?
