### ISSUE TITLE
alighment issue on qs tiles.too much goes to right side

### ISSUE THREAD

**Issue by dimuthu3** [wasdennnoch/AndroidN-ify#703]
Rom beanstalk 6.0
Build 534
Qs tile alighment not correct.qs tiles almost in right side and more space on left side.
Log and pic below
https://www.dropbox.com/m/browse?path=%2Fxda#

https://www.dropbox.com/pri/get/xda/2016-08-27-00-40-42.txt?_subject_uid=269000962&w=AAAzJuqNpar68-F62GQijZQtC0l52BpeHqdAdYq9nDkTIw

**Comment by wasdennnoch** [comment]
I have to log in to dropbox to see these files? I don't have a dropbox account and don't want to create one for viewing two files. Normally I should be able to view them without a login.

**Comment by dimuthu3** [comment]
ha ha this issue now solved by you with latest update so you can close this request as named solved.thanks you and next time i will use google drive or one else.
