### ISSUE TITLE
Data setting on the quick menu 

### ISSUE THREAD

**Issue by francgs** [wasdennnoch/AndroidN-ify#712]
can't open the quick menu of the data ussage, for on/off  i only need to go to the settings for put on

**Comment by rgshah3** [comment]
https://drive.google.com/file/d/0Byu333mD4mcSdlRuZ2FqSDRDUmM/view?usp=drivesdk

**Comment by rgshah3** [comment]
[alogcat.2016-08-31-00-10-48+0530.txt](https://github.com/wasdennnoch/AndroidN-ify/files/445736/alogcat.2016-08-31-00-10-48.0530.txt)

**Comment by rgshah3** [comment]
@wasdennnoch any progress with this?

**Comment by rgshah3** [comment]
Nothing?

**Comment by francgs** [comment]
Its ok. thank you

**Comment by rgshah3** [comment]
I still have the issue

**Comment by wasdennnoch** [comment]
If you are on Motorola strock it should be fixed with 823e6c55137a71e9f3c26be7474ae3c298a6df7e.
