### ISSUE TITLE
In latest builds volume panel is not in full width

### ISSUE THREAD

**Issue by Androdiver** [wasdennnoch/AndroidN-ify#729]
In your previous build volume panel comes in full width but in latest build its not in full width
Here is xposed log and screenshot.
![1472460336755](https://cloud.githubusercontent.com/assets/19375581/18046237/a2e6d538-6df4-11e6-90ec-37208f31fe53.jpg)
[xposed_error_20160829_002924.log.txt](https://github.com/wasdennnoch/AndroidN-ify/files/442070/xposed_error_20160829_002924.log.txt)

**Comment by wasdennnoch** [comment]
Any chance to grab a deodexed SystemUI?

**Comment by Androdiver** [comment]
Sorry i don't have deodexed system ui

**Comment by wasdennnoch** [comment]
Then please install this version and post your Xposed log after a reboot (Or logcat if the Xposed one is empty, but IMMEDIATELY after the boot finished): http://www.mediafire.com/download/2dnl97rfhs9y5zm/Android_N-ify_debug_log_ExpandableNotificationRow.apk

**Comment by Androdiver** [comment]
Here is xposed log of debug apk
[xposed_error_20160830_145308.log.txt](https://github.com/wasdennnoch/AndroidN-ify/files/444475/xposed_error_20160830_145308.log.txt)

**Comment by wasdennnoch** [comment]
Fixed with c17726d016dce122dde395e95f8811a576bac25f
