### ISSUE TITLE
Media Style notifications have a tiny icon

### ISSUE THREAD

**Issue by ninelore** [wasdennnoch/AndroidN-ify#744]
The Album Cover from the Play Music Apps Notification ist very tiny. I dont think that's right

To reproduce hear your favorite title via Google Play Musik App

**Comment by JaredTheWolf** [comment]
Same issue here. Screenshot provided. 
![screenshot_20160830-145032](https://cloud.githubusercontent.com/assets/21344934/18102624/2f2de0d2-6ec1-11e6-8f99-4a6359607ee5.png)

**Comment by SilverElf123** [comment]
It's not just google play music....even nexmusic player and some other (I don't member the name of ) have this same problem xD
Also is problem is not there in stable 2.0 buildi hope the developer looks in to it

**Comment by paphonbth** [comment]
A known issue. This happens on all media player that uses Notification.MediaStyle

**Comment by boswelja** [comment]
That looks like the thumbnail is about where the expand button should be.. Maybe an id clash?

**Comment by hakan5816** [comment]
Sony music (Walkman) have the same problem. Build 673 and earlier ..
![_20160924_001952](https://cloud.githubusercontent.com/assets/18596203/18801667/e8c2ae72-81ec-11e6-8716-e3ffe953fb3e.JPG)

**Comment by SilverElf123** [comment]
Is to possible to make these Media Style notifications the way it used to be till build 530 until you find a fix?
