### ISSUE TITLE
Graphical glitch in headers and lists

### ISSUE THREAD

**Issue by JaredTheWolf** [wasdennnoch/AndroidN-ify#746]
White blurred line in headers (WiFi, Bluetooth, battery expanded tiles), and also in lists (WiFi, Bluetooth). 

Device: Moto G3 osprey
ROM: Tesla by Ground Zero ROMs. Android 6.0.1, AOSP
Xposed: latest version as of August 30th
![screenshot_20160830-143516](https://cloud.githubusercontent.com/assets/21344934/18102517/c8d6abb6-6ec0-11e6-8f06-9e223e0a883b.png)

**Comment by wasdennnoch** [comment]
Nice song :p
Do you have any theme activated?

**Comment by JaredTheWolf** [comment]
Only a navbar Substratum layer (which is also currently hidden by an Xposed tweak)

**Comment by wasdennnoch** [comment]
Does this also happen without the module?

**Comment by JaredTheWolf** [comment]
Nevermind— I've found the issue. This is because of the other tweak, NogatNavBar, and doesn't have anything to do with Android N-ify. My bad. 😅

**Comment by wasdennnoch** [comment]
:P
