### ISSUE TITLE
Battery tile doesn't expand completely from quick toggles

### ISSUE THREAD

**Issue by JaredTheWolf** [wasdennnoch/AndroidN-ify#747]
https://gfycat.com/KaleidoscopicFinishedDalmatian

Device: Moto G3 osprey
ROM: Tesla by Ground Zero ROMs. AOSP 6.0.1
Xposed: latest as of this post

**Comment by wasdennnoch** [comment]
Hey, I have the same background. And the same issue, we're working on it ;)

**Comment by wasdennnoch** [comment]
Duplicate of #781.
