### ISSUE TITLE
QS background too high (bug? see screenshots)

### ISSUE THREAD

**Issue by valeriopastore20** [wasdennnoch/AndroidN-ify#749]
![photo_2016-08-31_11-27-16](https://cloud.githubusercontent.com/assets/21358535/18124086/fea46d68-6f70-11e6-89a7-bb54e135d716.jpg)
![photo_2016-08-31_11-27-23](https://cloud.githubusercontent.com/assets/21358535/18124085/fe9ead38-6f70-11e6-8f3e-0a19b2019ad4.jpg)

**Comment by paphonbth** [comment]
https://www.google.co.th/search?q=nougat+quick+settings&prmd=ivn&source=lnms&tbm=isch&sa=X&ved=0ahUKEwimif2qvevOAhWLNo8KHVF7CnMQ_AUIBygB&biw=412&bih=604&dpr=3.5
