### ISSUE TITLE
Gradle update

### ISSUE THREAD

**Issue by vlw** [wasdennnoch/AndroidN-ify#75]
![screenshot_4](https://cloud.githubusercontent.com/assets/6003820/15074463/d51c7f78-13a7-11e6-82c1-70482342ded0.jpg)

Please make a update Gradle
because Android Studio updated (2.0 -> 2.1)

**Comment by wasdennnoch** [comment]
I'm using the newest AS version and newest Gradle version... (AS 2.1 RC, Gradle 2.1.0-rc1)

**Comment by wasdennnoch** [comment]
Does it fix the problem when you remove the "-rc1" in the top-level build.gradle?

**Comment by vlw** [comment]
![screenshot_5](https://cloud.githubusercontent.com/assets/6003820/15074687/f7760552-13a8-11e6-9aa9-8b0c7f155a02.jpg)

**Comment by wasdennnoch** [comment]
Noticed that just now, it's updating.

**Comment by vlw** [comment]
It's fix a problem

>  when you remove the "-rc1"

**Comment by vlw** [comment]
but on stable channel no AS rc-1

**Comment by wasdennnoch** [comment]
Fixed with http://github.com/wasdennnoch/AndroidN-ify/commit/0b37989a1f563a6c4f1f2994a8aabf8a91dda673

**Comment by DVDAndroid** [comment]
I think that Gradle 2.1.0 breaks the module. 

See this [bug](https://github.com/rovo89/XposedBridge/issues/95)

**Comment by wasdennnoch** [comment]
Interesting, I don't have any issues with Gradle, everything is working flawlessly here.

**Comment by DVDAndroid** [comment]
The compilation is ok, but the execution has problems. I tested it on Genymotion emulator (API 21), and it gives the same error.

**Comment by wasdennnoch** [comment]
So it doesn't run on your device and the emulator?

**Comment by DVDAndroid** [comment]
Yes. In the log there are errors. [Complete log](http://pastebin.com/rHinsjZx)

**Comment by DVDAndroid** [comment]
Recompiled project and now works. I'm sorry for the trouble
