### ISSUE TITLE
Battery tile crashes everytime and shows red exclamation mark

### ISSUE THREAD

**Issue by hrithikb** [wasdennnoch/AndroidN-ify#754]
https://drive.google.com/file/d/0B0NJb0mKnh5QT1d4MF9MS2VnLU0/view?usp=drivesdk
Here is the logcat, system ui crashes on battery tile click in cm12.1 and shows an exclamation mark on battery tile

**Comment by hrithikb** [comment]
Also the notification icon in Notification header is very close to the notification text in some apps like g drive and also no notification expander icon is showing

**Comment by hrithikb** [comment]
https://drive.google.com/file/d/0B0NJb0mKnh5QMTd6eHYtNEpQblE/view?usp=drivesdk
Xposed log

**Comment by hrithikb** [comment]
https://drive.google.com/file/d/0B0NJb0mKnh5QNi1JcWtLWmtPeWM/view?usp=drivesdk
Ss for the notification icon

**Comment by paphonbth** [comment]
Notification header close to notification text is a known issue. Will fix it when crashes are fixed.

**Comment by hrithikb** [comment]
Sir what about the exclamation mark, will the logs help you in that?

**Comment by wasdennnoch** [comment]
The SystemUI doesn't have the battery permission for some reason, thus the crash.

```
08-31 20:45:46.068 E/AndroidRuntime(717): Caused by: java.lang.SecurityException: uid 10021 does not have android.permission.BATTERY_STATS.
08-31 20:45:46.068 E/AndroidRuntime(717): 	at android.os.Parcel.readException(Parcel.java:1546)
08-31 20:45:46.068 E/AndroidRuntime(717): 	at android.os.Parcel.readException(Parcel.java:1499)
08-31 20:45:46.068 E/AndroidRuntime(717): 	at com.android.internal.app.IBatteryStats$Stub$Proxy.getStatisticsStream(IBatteryStats.java:1063)
08-31 20:45:46.068 E/AndroidRuntime(717): 	at com.android.internal.os.BatteryStatsHelper.getStats(BatteryStatsHelper.java:1034)
08-31 20:45:46.068 E/AndroidRuntime(717): 	at com.android.internal.os.BatteryStatsHelper.loadStats(BatteryStatsHelper.java:1005)
08-31 20:45:46.068 E/AndroidRuntime(717): 	at com.android.internal.os.BatteryStatsHelper.getStats(BatteryStatsHelper.java:237)
08-31 20:45:46.068 E/AndroidRuntime(717): 	at tk.wasdennnoch.androidn_ify.extracted.settingslib.BatteryInfo$2.doInBackground(BatteryInfo.java:112)
```

**Comment by hrithikb** [comment]
So, will it be fixed or not sir?

**Comment by hrithikb** [comment]
One thing also sir system ui crashes when pressing the expander icon in Notification

**Comment by paphonbth** [comment]
Can you test if battery tile works now?

**Comment by hrithikb** [comment]
No sir still not working.

**Comment by wasdennnoch** [comment]
SO you said that it's still crashing, logcat again please.

**Comment by hrithikb** [comment]
https://drive.google.com/file/d/0B0NJb0mKnh5QYmlqRk1DSl9mUXM/view?usp=drivesdk
Logcat

**Comment by wasdennnoch** [comment]
Got fixed by not showing battery detail until we find a way to grant the permission on LP.
