### ISSUE TITLE
Incorrectly placed edit icon

### ISSUE THREAD

**Issue by IsaiahvH** [wasdennnoch/AndroidN-ify#757]
Hi, 

Firstly, I'd like to thank you for this awesome module, I absolutely love it. There is no support for Android N on my OnePlus 2, but this mod still provides the look and feel. 

However, there is a design flaw with the tile edit icon in OnePlus 2 running OxygenOs 3.
You can see the screenshot here, https://goo.gl/photos/37pHYDdYVbH3qJNu6. 

I hope this can be improved, 

Kind regards, 

Isaiah van Hunen

**Comment by IsaiahvH** [comment]
Also, changing the hide tile edit button (See https://goo.gl/photos/y3kGToqJSPqrCEVm9)  such have no effect.

**Comment by wasdennnoch** [comment]
Are you on 0.2.0? If so please install a snapshot build from the link in the second post in the XDA thread and report back.

**Comment by IsaiahvH** [comment]
Newest build works fine, thank you!
