### ISSUE TITLE
emergency  info crashing on cm 13

### ISSUE THREAD

**Issue by dimuthu3** [wasdennnoch/AndroidN-ify#762]
Dear Dev
rom beanstalk 6.20 android 6.0.1 cm 13 base
i am on latest build #576 
when i click emergency info on lock screen its getting crashing.here on screen shot and log file
https://drive.google.com/folderview?id=0B6NzzhtK6j4QYTlGVFNlYzRDaUk&usp=sharing

**Comment by JaredTheWolf** [comment]
Give Android N-ify calling and contacts permissions either through the "Edit Emergency Info" in the app itself or through permissions settings.

**Comment by paphonbth** [comment]
No error information in the log.
Please make sure you captured the moment it crashed too.

**Comment by dimuthu3** [comment]
Jaredthewolf you are right i gave permissions manualy and now its run awsomely.paphonbth i dont know what happen but i get the log when it put to record  as a log file.anuway pls close this issuse now.
