### ISSUE TITLE
First 5 QS invisible in landscape expanded panel

### ISSUE THREAD

**Issue by SilverElf123** [wasdennnoch/AndroidN-ify#772]
When I pull down quick settings panel in horizontal mode there is lots of empty space
![screenshot_20160903-155704](https://cloud.githubusercontent.com/assets/21692923/18224761/d6f3097a-71fd-11e6-9e93-50103ac887b5.png)

**Comment by wasdennnoch** [comment]
Are you sure it's a gap or just your first 3 QS invisible? And how many QS do you have set in the header?

**Comment by SilverElf123** [comment]
Oh yes I didn't noticed that before... Those 5 QS that I have in header are missing

**Comment by LumpBloom7** [comment]
This only happens when fancy QS animations are enabled in the settings, disabling it will bypass the problem.

**Comment by boswelja** [comment]
On build 606, I can see the 5 tiles, but there arent any animations only in landscape :/

**Comment by paphonbth** [comment]
Animation is disabled in landscape until we implement paged tile layout.

**Comment by LumpBloom7** [comment]
Fixed in the latest build.
