### ISSUE TITLE
No tiles to add from edit button and the black stripe is coming in tile editor

### ISSUE THREAD

**Issue by hrithikb** [wasdennnoch/AndroidN-ify#778]
https://drive.google.com/file/d/0B0NJb0mKnh5QMEVVc3lvOGZ1OWM/view?usp=drivesdk

Also see the exclamation mark on battery tile please!

**Comment by wasdennnoch** [comment]
(The black stripe is known, no tiles is new)

**Comment by hrithikb** [comment]
https://drive.google.com/file/d/0B0NJb0mKnh5QZGREeDNhNzd2aWs/view?usp=drivesdk
It's the logcat

**Comment by hrithikb** [comment]
https://drive.google.com/file/d/0B0NJb0mKnh5QY2RpY0Q0T3kxN2c/view?usp=drivesdk
Xposed logs

**Comment by wasdennnoch** [comment]
Does that still happen?

**Comment by hrithikb** [comment]
Sir can't tell that my phone was stolen so i have new phone with cm13😊
