### ISSUE TITLE
Battery detail cut off when opening from QuickQS

### ISSUE THREAD

**Issue by tushar260** [wasdennnoch/AndroidN-ify#781]
![screenshot_20160904-102520](https://cloud.githubusercontent.com/assets/21682756/18229136/2d75622a-728a-11e6-9613-baf5af48f38e.png)

**Comment by wasdennnoch** [comment]
It's actually the same on N, but on N every detail view is wrapped in a ScrollView so you can scroll up.

**Comment by wasdennnoch** [comment]
It's expanding fully on my end by now, can cou confirm?

**Comment by tushar260** [comment]
Sorry, I'm on cm14 now. 😅

**Comment by wasdennnoch** [comment]
Well then, enjoy your bug-free phone ;)

**Comment by tushar260** [comment]
xD
