### ISSUE TITLE
QS editor stays open when locking phone

### ISSUE THREAD

**Issue by nampud** [wasdennnoch/AndroidN-ify#789]
If the phone is locked while QS editor is open, after waking the phone up the QS editor will be displayed over the lockscreen. Even after unlocking, instead of opening the notification bar, the editor will appear without any animations. It is fixed after clicking Add broadcast tile. Not a serious bug but I was confused for a while when it happened.

**Comment by wasdennnoch** [comment]
It looks kinda cool, but yes, it shouldn't be that way.

**Comment by boswelja** [comment]
We could have a broadcastreceiver that checks for SCREEN_OFF and closes the editor

**Comment by paphonbth** [comment]
We already have a hook for setBarState that will close the editor when statusbar state is changed to keyguard.

**Comment by boswelja** [comment]
@paphonbth since when? It doesn't appear to be working on the latest build

**Comment by paphonbth** [comment]
Hmm... Maybe some crash that prevented it from closing. I remember that it worked first time when I implemented it. But it's not working anymore. Will try to fix it.

**Comment by wasdennnoch** [comment]
Fixed.
