### ISSUE TITLE
Not able to pull down QS from notifications with "No notifications" in the way.

### ISSUE THREAD

**Issue by geoff0616** [wasdennnoch/AndroidN-ify#790]
I've always found something really annoying when using N-ify but I never really understood how it happened, but I realized what it was. 

When trying to pull down the QS from the notification shade while there are no notifications, the text that says "No notifications" when initially dragging from that area, doesn't allow the QS to be opened. The "No notifications" area extends horizontally across the entire notification screen. This also happens in landscape but only the area directly below the QS tiles. This problem has existed for as long I could remember. 

[Here's a demonstration.](https://streamable.com/o9b5)

Quick edit: The same issue could be said for when there **ARE** notifications with the **CLEAR ALL** area not allowing the QS to be pulled down as well.

Hope this gets fixed, thank you for your dedication to N-ify!

**Comment by tushar260** [comment]
It IS a major bug!
Great digging :D

**Comment by wasdennnoch** [comment]
This is a big in Android itself, it still persists with the module disabled.

**Comment by geoff0616** [comment]
Strange, well that's sucks. Also, for some reason now I'm able to pull down the QS, though I did have a notification and cleared it. Apparently this only happens when I restart my phone so if anyone is trying to reproduce it, there you go.

**Comment by tushar260** [comment]
Btw eagerly waiting for you to completely implement direct reply.
Any ETA? 😅😌

**Comment by wasdennnoch** [comment]
Well, it's currently activated ;)

**Comment by wasdennnoch** [comment]
Only if an app supoorts and activates it below N which almost none does. That's the main problem.

**Comment by tushar260** [comment]
😂
