### ISSUE TITLE
Direct Reply autocorrect and punctuation issue.

### ISSUE THREAD

**Issue by LittleSnevil** [wasdennnoch/AndroidN-ify#792]
There's a problem with the autocorrect and the punctuation at the moment you want to write a direct reply. The autocorrect isn't working. And the punctuation (like auto mayus at the beginning and the acute accents [i'm spanish-speaking]) aren't working automatically. It's like the direct reply is acting like when you will write an email. I do not know how to explain better.

Hope you understand. 
Regards.

**Comment by nplezka** [comment]
I'm experiencing this too; it opens the numbers row like when typing passwords. No autocorrect, no emojis.

**Comment by wasdennnoch** [comment]
@Maxr1998 You implemented it; the XML tags are the same, so some part of the official used View code may be the solution.

**Comment by sunny1234590** [comment]
Also, many a times when I quick on Reply to xyz ( for WA), the keyboard doesn't pop up! Sometimes it pops up, sometimes it doesn't. Wonder what is wrong.

**Comment by tushar260** [comment]
How are you able to use this direct reply feature on WhatsApp? 😵

**Comment by wasdennnoch** [comment]
The paphonb builds have the quick reply backport enabled and an option to spoof the SDK int, which means that WA thinks that it's on N so that it uses Quick Reply. It has many unwanted side-effects like crashes though.

**Comment by Maxr1998** [comment]
I reworked much of the code now, and auto correct works for me, although I didn't even change the inputType in the xml. Seems it got ingored previously.

**Comment by Maxr1998** [comment]
Confirmed to be fixed, please close.
