### ISSUE TITLE
Latest commit breaks Double Tap

### ISSUE THREAD

**Issue by JaredTheWolf** [wasdennnoch/AndroidN-ify#793]
https://gfycat.com/RashAngelicDorking.

Tried all possible settings, System UI restarting each time.

Device: osprey
Xposed: Latest
ROM: Tesla by GZR, AOSP 6.0.1

**Comment by paphonbth** [comment]
Are you talking about #788 ? If yes, then it's impossible. The only changed file is QSCustomizer.

Did you update your ROM or other modules?

**Comment by wasdennnoch** [comment]
It doesn't look like a SystemUI crash, you would get a crash dialog then and would see the lock screen. Does this also happen with more than 2 recent items?

**Comment by paphonbth** [comment]
Multi window is the problem. Please disable it.
https://www.youtube.com/watch?v=099_3IZnJ0c
