### ISSUE TITLE
After every reboot, I need to restart system ui to fix this

### ISSUE THREAD

**Issue by tushar260** [wasdennnoch/AndroidN-ify#796]
![screenshot_20160906-190852](https://cloud.githubusercontent.com/assets/21682756/18275957/b4b8db44-7466-11e6-9b81-2c7005867858.png)

**Comment by wasdennnoch** [comment]
Nice wifi name. So the callular and battery tile animate to the position of the wifi and orientation tiles?

**Comment by tushar260** [comment]
Fixed
