### ISSUE TITLE
First 2 tiles don't correctly represent enlargement settings

### ISSUE THREAD

**Issue by jahirfiquitiva** [wasdennnoch/AndroidN-ify#797]
Hi

This module just keeps getting better, anyways, with last alpha/beta build, the first 2 tiles are moved from center to the left, and they don't even align with the tiles below.

Please fix it soon. Thanks.

Preview:
https://drive.google.com/file/d/0Bw52d3_ZiSb9Znp2RzM3bXo5MDQ/view?usp=drivesdk

**Comment by jahirfiquitiva** [comment]
Also, texts in settings are not translated (at least not to Spanish)

**Comment by wasdennnoch** [comment]
You are on CM. You have to toggle the first row enlargement in the CM settings too. Long click the settings icon and swipe right.

**Comment by jahirfiquitiva** [comment]
I am on AICP, and can't seem to find the setting.
It was working in previous builds too

**Comment by wasdennnoch** [comment]
When you long press the settings icon in the expanded header, you should be able to edit the tiles. Then you have to swipe right in the tiles list. At least I think AICP has that editor.

**Comment by jahirfiquitiva** [comment]
Thanks. I just checked and that option is properly enabled in the rom settings too.

Issue is still present.

I tried enabling and disabling other settings in module app, but nothing seems to work. After reboot it keeps looking the same.

**Comment by wasdennnoch** [comment]
The switch in the module and in the CM settings should be the same state, either both enabled to have 2 large tiles in the first row or both disabled to have 3 small ones.

**Comment by jahirfiquitiva** [comment]
I want 2 large tiles, and I have both switches enabled. It still doesn't works properly.

**Comment by sunny1234590** [comment]
Yup. I have the same issue! Everything is properly ticked still it persists.

**Comment by paphonbth** [comment]
Fixed with #819.
