### ISSUE TITLE
Save tile specs in System config instead of new prefs

### ISSUE THREAD

**Issue by LumpBloom7** [wasdennnoch/AndroidN-ify#800]
I'm using resurrection remix 5.7.3. When QS editor is enabled, the whole QS is rearranged and is not the same as the QS tiles set in rr settings. Some icons are missing, and changing any tiles does not change system configurations. It would be better if the QS editor actually edits the system configurations instead of using its own configurations.

**Comment by wasdennnoch** [comment]
I don't know where they are stored, I only know that they are stored and retrieved via System.Settings.

**Comment by wasdennnoch** [comment]
Implemented with b61018a481ce5513cc397ffb04cbc564933c5b0b
