### ISSUE TITLE
Invisible settings icon in quick settings header

### ISSUE THREAD

**Issue by Maik268** [wasdennnoch/AndroidN-ify#801]
As you can see on the following picture, there is an invisible settings icon at the top of the quick settings header (top/right next to the mobile data tile).

![screenshot_20160907-172630](https://cloud.githubusercontent.com/assets/13015934/18318270/5f5e33ea-7521-11e6-8080-5d53dc0a9c1a.png)

**Comment by wasdennnoch** [comment]
Should be fixed with 56e7282160ae878367a27a44eadf325c552a2564
