### ISSUE TITLE
Live display toggle turns to automatic after every reboot.

### ISSUE THREAD

**Issue by tushar260** [wasdennnoch/AndroidN-ify#802]
Also, the toggle should go 
Auto->Night->Off

But this goes like
Auto->Night->Auto->Off

This exists only after rebooting and toggling for the first time, after that it follows the correct toggling behavior.

**Comment by wasdennnoch** [comment]
I'll probably remove the custom LiveDisplay tile and instead use the existing one, the custom one is only there for an old workaround.

**Comment by boswelja** [comment]
The above commit wont work :(

**Comment by wasdennnoch** [comment]
What if you add the livedisplay spec manually to the spec list if it isn't in there yet?

**Comment by boswelja** [comment]
@wasdennnoch how would the tile manager respond to that though.. Would it be capable of reading a dynamic tile?

**Comment by boswelja** [comment]
And also @wasdennnoch why was the isCmBased code in AvailableTileAdapter commented out?

**Comment by wasdennnoch** [comment]
The tile manager is able to create this tile, and if not there won't be any problems, he'd just ignore it. I commented out the check for dynamic tiles, and I haven't heared of any issues, so I'll completely renove it.

**Comment by wasdennnoch** [comment]
There's no an option for alternative loading which includes the native tile.
