### ISSUE TITLE
Google Messenger crashes

### ISSUE THREAD

**Issue by Stephenking247** [wasdennnoch/AndroidN-ify#803]
Google Messenger will crash with either 122 build with spoofing API on or build 606.

**Comment by wasdennnoch** [comment]
This isn't really an issue but a logical consequence. Tricking the app into thinking it's in a N device will make it try to use N APIs which - well, don't exist prior to M. API spoofing is a very  hacky and risky way and ends up in more trouble than relief. There probably will be a module which explicitly enables quick reply for those apps, but until then there's no other way.
