### ISSUE TITLE
Battery Tiles Crash my system ui at build #606

### ISSUE THREAD

**Issue by jerryshaw12** [wasdennnoch/AndroidN-ify#804]
When i clicked it, it wont show summary
Logcat
https://drive.google.com/file/d/0B3TzmNRa2nE6cHU4cDR6LTJUTlk/view?usp=drivesdk
Xposed Log
https://drive.google.com/file/d/0B3TzmNRa2nE6ZzFDbF9peDI4QjA/view?usp=drivesdk

**Comment by wasdennnoch** [comment]
Please post a full logcat without any filter; right now I can see that the SystemUI crashed, but not why.
