### ISSUE TITLE
Increase vertical distance between QS tiles

### ISSUE THREAD

**Issue by Rodav10** [wasdennnoch/AndroidN-ify#808]
Image 1 is official N, Image 2 is N-Ify. The padding/spacing between each qs icon vertically is too cramped on image 2, you can compare it with image 1
![theres-cute-cat-game-hidden-android-nougats-quick-settings w1456](https://cloud.githubusercontent.com/assets/1808145/18389710/810bd19e-76ea-11e6-8ac5-927c6ba49f25.jpg)
![screenshot_20160910-092442](https://cloud.githubusercontent.com/assets/1808145/18405804/bdbad0d8-7738-11e6-908f-47de6a32dea8.png)
W2

**Comment by numeprenume** [comment]
Are you sure both screenshots are taken using the same dpi in Android?

**Comment by Rodav10** [comment]
Updated 2nd screenshot, doing changed to match the 420dpi of the 5x

**Comment by paphonbth** [comment]
Implemented with #815.
