### ISSUE TITLE
Notification expand button doesn't work in heads-up.

### ISSUE THREAD

**Issue by tushar260** [wasdennnoch/AndroidN-ify#809]

**Comment by wasdennnoch** [comment]
Heads-up notifications are always extended, please explain further. Is the expand button visible? If yes, does it do something on click?

**Comment by tushar260** [comment]
Yes the button is there but doesn't do anything

**Comment by paphonbth** [comment]
It shouldn't do anything as heads-up is alwys extended.

**Comment by wasdennnoch** [comment]
The button is also there in N and it also doesn't do anything.
