### ISSUE TITLE
Ability to show all QS tiles on a single page

### ISSUE THREAD

**Issue by LumpBloom7** [wasdennnoch/AndroidN-ify#821]
So as the title says, the QS tiles are squeeze into another page even when there is clearly enough space to put more. On landscape view it is worse, where 9 tiles are displayed in a single row, needing 3 pages. It's not really convenient for people who set a low DPI in their settings. The app should arrange the tiles according to the user's DPI as well.

**Comment by paphonbth** [comment]
Implemented.
