### ISSUE TITLE
System UI Crash (Blisspop 5.1.1)

### ISSUE THREAD

**Issue by jerryshaw12** [wasdennnoch/AndroidN-ify#823]
[logcat.txt](https://github.com/wasdennnoch/AndroidN-ify/files/466012/logcat.txt)
[logca2.txt](https://github.com/wasdennnoch/AndroidN-ify/files/466013/logca2.txt)
here is the logcat (currently on build 626)

**Comment by wasdennnoch** [comment]
Fixed with eb658b0336de3a60a0ed255e9dd39b1c76b1de06 (at least this crash)
