### ISSUE TITLE
No action on notification expand arrow click. Xposed logs: https://drive.google.com/file/d/0B5_P4hsjIFYmdDhKcHB5NUxndTQ/view?usp=docslist_api

### ISSUE THREAD

**Issue by Freewander10** [wasdennnoch/AndroidN-ify#825]

**Comment by wasdennnoch** [comment]
PLease install this version and post your Xposed log again: http://www.mediafire.com/download/3m1vb3iucdxe50g/Android_N-ify_debug_log_ExpandableNotificationRow.apk

**Comment by Freewander10** [comment]
Here it is @wasdennnoch
https://drive.google.com/file/d/0B5_P4hsjIFYmSkE0QTZaMDNkb00/view?usp=drivesdk

**Comment by wasdennnoch** [comment]
Well, there was another error which prevented my test method from executing. That's fixed now, and again please install and post log :P http://www.mediafire.com/download/17b3czvdpmkc7bt/Android_N-ify_debug_log2_ExpandableNotificationRow.apk

`java.lang.NoSuchMethodError: com.android.systemui.statusbar.ExpandableNotificationRow#notifyHeightChanged(java.lang.Boolean)#bestmatch`

**Comment by Freewander10** [comment]
No problem :D
Here your go:
https://drive.google.com/file/d/0B5_P4hsjIFYmYU11dDVYeGsyclk/view?usp=drivesdk
Thanks man 👍

**Comment by wasdennnoch** [comment]
And now please post a log with this build: http://www.mediafire.com/download/8qhdji1tzggo4z1/Android_N-ify_debug_log_ExpandableView.apk
(Sorry for the many tests, but I have to inspect multiple classes)

**Comment by Freewander10** [comment]
That's cool man. I don't mind. 
Thank you for taking the timeout to make the debug builds 👍
Here are the logs:
https://docs.google.com/uc?id=0B5_P4hsjIFYmTGNoY0YzMHc0Umc&export=download

**Comment by wasdennnoch** [comment]
Thanks, the solution was easier than expected. But I don't know if it gets animated or not (because the boolean controlled the animation). a7ac88f2a2cbf4422f64544ccd2dcde8801c5ad5

**Comment by Freewander10** [comment]
It doesn't seem to animate. But at least it works now.
