### ISSUE TITLE
Change lightning icon inside battery tile icon

### ISSUE THREAD

**Issue by jahirfiquitiva** [wasdennnoch/AndroidN-ify#826]
Hi, this is not an issue but still...

The battery tile has an icon that shows a lightning inside of it, when device is charging.

To be honest, it doesn't look so good, so I was wondering if you could change it and use [the lightning icon from material design official iconset](https://design.google.com/icons/#ic_flash_on)

I think it would look a lot better.

Thanks

**Comment by paphonbth** [comment]
Battery icon in the module is actually from N. It won't be changed.

**Comment by jahirfiquitiva** [comment]
Well, at least make it consistent with android version.

The status bar battery icon lightning icon, is different from the one in the module.

At least make it consistent with status bar one.
