### ISSUE TITLE
Notifications panel header chevron icon ripple is drawn behind of it

### ISSUE THREAD

**Issue by jahirfiquitiva** [wasdennnoch/AndroidN-ify#827]
Hi...

as you can see in the screenshot, when pressing the chevron icon to expand or collapse the notification panel, its ripple is drawn behind, so just a really small part of the ripple is shown.

It's been like that for some versions already, and it's kinda bugging me.

Hope you fix it. Thanks

![screenshot 11 sept 2016 23-23-51](https://cloud.githubusercontent.com/assets/10360816/18424655/5940f5a2-7877-11e6-8b3d-238736b6b5fe.png)

**Comment by wasdennnoch** [comment]
Do you have any custom header background activated or are using an option to change the background color in your ROM settings? Also which ROM are you on?

**Comment by jahirfiquitiva** [comment]
None of them @wasdennnoch 

And this happens even without themes, or with default stock settings.

I'm on AICP

**Comment by wasdennnoch** [comment]
Does that still happen?

**Comment by jahirfiquitiva** [comment]
Fixed :) Thanks
