### ISSUE TITLE
SystemUI crash when changing to landscape

### ISSUE THREAD

**Issue by Raikem** [wasdennnoch/AndroidN-ify#830]
Log:
[Nuevo documento de texto.txt](https://github.com/wasdennnoch/AndroidN-ify/files/467835/Nuevo.documento.de.texto.txt)
To reproduce the error I have to pull down quick settings.

**Comment by paphonbth** [comment]
Please attach logcat, not Xposed logs.

**Comment by Raikem** [comment]
I got that log from Android Studio

**Comment by paphonbth** [comment]
I opened the wrong file. Sorry.

**Comment by Raikem** [comment]
Official marshmallow moto g2 ported to moto g. It's almost stock AOSP.

**Comment by wasdennnoch** [comment]
Please install this test version and post your Xposed log after a reboot: http://www.mediafire.com/download/ws650wyak8s80yc/Android_N-ify_debug_log_QSTile_WifiTile.apk

**Comment by Raikem** [comment]
[xposed_error_20160919_020053.txt](https://github.com/wasdennnoch/AndroidN-ify/files/479935/xposed_error_20160919_020053.txt)

**Comment by wasdennnoch** [comment]
Got fixed somewhere in 3b9fb9849435ef5cf01365fba870bf3404193773 ;)

**Comment by Raikem** [comment]
I still have the crash with latest version :/

**Comment by wasdennnoch** [comment]
Then I need a new log.

**Comment by Raikem** [comment]
It seem like I'm just stupid, it works fine now sorry.

**Comment by Raikem** [comment]
Actually a rebooted and got the crash again, although I have to rotate it twice to replicate. I added xposed and adb logs:

[error-adb.txt](https://github.com/wasdennnoch/AndroidN-ify/files/485438/error-adb.txt)

[error-xposed.txt](https://github.com/wasdennnoch/AndroidN-ify/files/485440/error-xposed.txt)

**Comment by nampud** [comment]
Same problem on Z3C 6.0.1. It only happens with quick settings enlarge first row turned on.

**Comment by hakan5816** [comment]
@nampud exactly

**Comment by JaredTheWolf** [comment]
Been happening a lot for me, almost every time I enter landscape.

**Comment by cutiyar** [comment]
Same issue here

**Comment by Raikem** [comment]
Disable enlarge first row to temporarily fix this
@paphonbth @wasdennnoch

**Comment by Maxr1998** [comment]
Thanks, I will merge this issue into #1057.
