### ISSUE TITLE
system UI stopped when the camera is turned on Phone

### ISSUE THREAD

**Issue by hakan5816** [wasdennnoch/AndroidN-ify#831]
Phone I get the error system UI stopped when the camera is turned on.
#627
Xperia Z3C 6.0.1 Rom

**Comment by hakan5816** [comment]
I do not know how? Where's Logan?

**Comment by nampud** [comment]
I have this problem with the same phone, looks the same as #830 , logcat is the same, camera switches to landscape

**Comment by wasdennnoch** [comment]
Just google "How to logcat" and you'll find enough answers.

**Comment by hakan5816** [comment]
https://1drv.ms/t/s!ApqyWr9kZ7Clg_x9q9eQYStOnC98jw (Try the log for the first time) @wasdennnoch

**Comment by wasdennnoch** [comment]
This is your Xposed log, but we need a logcat.

**Comment by hakan5816** [comment]
I do not know. I tried for the first time. Using CatLog application. How Logcat there?

**Comment by ItzLevvie** [comment]
Search "How to logcat" on Google
