### ISSUE TITLE
not working normal on CM12.1

### ISSUE THREAD

**Issue by ranielcsar** [wasdennnoch/AndroidN-ify#832]
![screenshot_2016-09-12-17-09-29](https://cloud.githubusercontent.com/assets/20558676/18452429/2ef586d8-7911-11e6-8ddb-9143729d6e17.png)
![screenshot_2016-09-12-17-09-45](https://cloud.githubusercontent.com/assets/20558676/18452430/2f1d7a58-7911-11e6-95b8-62e13cd75674.png)
![screenshot_2016-09-12-17-10-01](https://cloud.githubusercontent.com/assets/20558676/18452431/2f246386-7911-11e6-8a3a-d727d68abe66.png)

**Comment by ranielcsar** [comment]
Xposed log: 
[xposed_error_20160912_201800.txt](https://github.com/wasdennnoch/AndroidN-ify/files/468539/xposed_error_20160912_201800.txt)

Adb log: 
[logcat.txt](https://github.com/wasdennnoch/AndroidN-ify/files/468544/logcat.txt)

**Comment by wasdennnoch** [comment]
Already fixed.
