### ISSUE TITLE
System UI crash 

### ISSUE THREAD

**Issue by Vality9** [wasdennnoch/AndroidN-ify#833]
The system UI crashes every 2-3 seconds on Canvas Spark Q380
[alogcat.2016-09-12-23-24-54+0530.txt](https://github.com/wasdennnoch/AndroidN-ify/files/469086/alogcat.2016-09-12-23-24-54.0530.txt)
![screenshot_2016-09-11-17-53-07](https://cloud.githubusercontent.com/assets/22166424/18464432/b9e4df12-79ae-11e6-9430-bdf752a2e603.png)

 that I cannot even use

**Comment by paphonbth** [comment]
Should be fixed with #843.
