### ISSUE TITLE
Use custom theme make Battery settings crash Settings 

### ISSUE THREAD

**Issue by xpduyson** [wasdennnoch/AndroidN-ify#834]
When apply Custom theme [Melior NUI ](https://play.google.com/store/apps/details?id=jahirfiquitiva.themes.meliornui), Battery settings completely not working. Both Battery settings (System Settings) and More Settings (on QS Battery summary titles) make Setting crash

https://gist.github.com/xpduyson/489e45d5f75f589665e9c96cf3c99817

**Comment by wasdennnoch** [comment]
Does it still crash without the theme?
