### ISSUE TITLE
WiFi drop down in QS gone

### ISSUE THREAD

**Issue by cbdreinulldrei** [wasdennnoch/AndroidN-ify#837]
Build #627 turns on some QS animation although it's off in settings. It also removes the drop down for WiFi in QS, so I can't chose a network. Also QS now have two pages...

**Comment by cbdreinulldrei** [comment]
After some research: this started in #619.

**Comment by cbdreinulldrei** [comment]
Hope this is it:

09-20 11:24:57.049 I/Xposed  ( 4265): [Android N-ify] [ERROR] StatusBarHeaderHooks: Error in onClickListener
09-20 11:24:57.063 E/Xposed  ( 4265): java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference
09-20 11:24:57.063 E/Xposed  ( 4265): 	at tk.wasdennnoch.androidn_ify.systemui.notifications.StatusBarHeaderHooks$14.onClickSafe(StatusBarHeaderHooks.java:877)
09-20 11:24:57.063 E/Xposed  ( 4265): 	at tk.wasdennnoch.androidn_ify.misc.SafeOnClickListener.onClick(SafeOnClickListener.java:44)
09-20 11:24:57.063 E/Xposed  ( 4265): 	at android.view.View.performClick(View.java:5207)
09-20 11:24:57.063 E/Xposed  ( 4265): 	at android.view.View$PerformClick.run(View.java:21168)
09-20 11:24:57.063 E/Xposed  ( 4265): 	at android.os.Handler.handleCallback(Handler.java:746)
09-20 11:24:57.063 E/Xposed  ( 4265): 	at android.os.Handler.dispatchMessage(Handler.java:95)
09-20 11:24:57.063 E/Xposed  ( 4265): 	at android.os.Looper.loop(Looper.java:148)
09-20 11:24:57.063 E/Xposed  ( 4265): 	at android.app.ActivityThread.main(ActivityThread.java:5443)
09-20 11:24:57.063 E/Xposed  ( 4265): 	at java.lang.reflect.Method.invoke(Native Method)
09-20 11:24:57.063 E/Xposed  ( 4265): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
09-20 11:24:57.063 E/Xposed  ( 4265): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
09-20 11:24:57.063 E/Xposed  ( 4265): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
09-20 11:24:59.072 I/Xposed  ( 4265): [Android N-ify] [ERROR] StatusBarHeaderHooks: Error in onClickListener
09-20 11:24:59.073 E/Xposed  ( 4265): java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference
09-20 11:24:59.073 E/Xposed  ( 4265): 	at tk.wasdennnoch.androidn_ify.systemui.notifications.StatusBarHeaderHooks$14.onClickSafe(StatusBarHeaderHooks.java:877)
09-20 11:24:59.073 E/Xposed  ( 4265): 	at tk.wasdennnoch.androidn_ify.misc.SafeOnClickListener.onClick(SafeOnClickListener.java:44)
09-20 11:24:59.073 E/Xposed  ( 4265): 	at android.view.View.performClick(View.java:5207)
09-20 11:24:59.073 E/Xposed  ( 4265): 	at android.view.View$PerformClick.run(View.java:21168)
09-20 11:24:59.073 E/Xposed  ( 4265): 	at android.os.Handler.handleCallback(Handler.java:746)
09-20 11:24:59.073 E/Xposed  ( 4265): 	at android.os.Handler.dispatchMessage(Handler.java:95)
09-20 11:24:59.073 E/Xposed  ( 4265): 	at android.os.Looper.loop(Looper.java:148)
09-20 11:24:59.073 E/Xposed  ( 4265): 	at android.app.ActivityThread.main(ActivityThread.java:5443)
09-20 11:24:59.073 E/Xposed  ( 4265): 	at java.lang.reflect.Method.invoke(Native Method)
09-20 11:24:59.073 E/Xposed  ( 4265): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
09-20 11:24:59.073 E/Xposed  ( 4265): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
09-20 11:24:59.073 E/Xposed  ( 4265): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
09-20 11:25:00.241 I/Xposed  ( 4265): [Android N-ify] [ERROR] StatusBarHeaderHooks: Error in onClickListener
09-20 11:25:00.241 E/Xposed  ( 4265): java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference
09-20 11:25:00.241 E/Xposed  ( 4265): 	at tk.wasdennnoch.androidn_ify.systemui.notifications.StatusBarHeaderHooks$14.onClickSafe(StatusBarHeaderHooks.java:877)
09-20 11:25:00.241 E/Xposed  ( 4265): 	at tk.wasdennnoch.androidn_ify.misc.SafeOnClickListener.onClick(SafeOnClickListener.java:44)
09-20 11:25:00.241 E/Xposed  ( 4265): 	at android.view.View.performClick(View.java:5207)
09-20 11:25:00.241 E/Xposed  ( 4265): 	at android.view.View$PerformClick.run(View.java:21168)
09-20 11:25:00.241 E/Xposed  ( 4265): 	at android.os.Handler.handleCallback(Handler.java:746)
09-20 11:25:00.241 E/Xposed  ( 4265): 	at android.os.Handler.dispatchMessage(Handler.java:95)
09-20 11:25:00.241 E/Xposed  ( 4265): 	at android.os.Looper.loop(Looper.java:148)
09-20 11:25:00.241 E/Xposed  ( 4265): 	at android.app.ActivityThread.main(ActivityThread.java:5443)
09-20 11:25:00.241 E/Xposed  ( 4265): 	at java.lang.reflect.Method.invoke(Native Method)
09-20 11:25:00.241 E/Xposed  ( 4265): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
09-20 11:25:00.241 E/Xposed  ( 4265): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
09-20 11:25:00.241 E/Xposed  ( 4265): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
09-20 11:25:00.478 I/Xposed  ( 4265): [Android N-ify] [ERROR] StatusBarHeaderHooks: Error in onClickListener
09-20 11:25:00.479 E/Xposed  ( 4265): java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference
09-20 11:25:00.479 E/Xposed  ( 4265): 	at tk.wasdennnoch.androidn_ify.systemui.notifications.StatusBarHeaderHooks$14.onClickSafe(StatusBarHeaderHooks.java:877)
09-20 11:25:00.479 E/Xposed  ( 4265): 	at tk.wasdennnoch.androidn_ify.misc.SafeOnClickListener.onClick(SafeOnClickListener.java:44)
09-20 11:25:00.479 E/Xposed  ( 4265): 	at android.view.View.performClick(View.java:5207)
09-20 11:25:00.479 E/Xposed  ( 4265): 	at android.view.View$PerformClick.run(View.java:21168)
09-20 11:25:00.479 E/Xposed  ( 4265): 	at android.os.Handler.handleCallback(Handler.java:746)
09-20 11:25:00.479 E/Xposed  ( 4265): 	at android.os.Handler.dispatchMessage(Handler.java:95)
09-20 11:25:00.479 E/Xposed  ( 4265): 	at android.os.Looper.loop(Looper.java:148)
09-20 11:25:00.479 E/Xposed  ( 4265): 	at android.app.ActivityThread.main(ActivityThread.java:5443)
09-20 11:25:00.479 E/Xposed  ( 4265): 	at java.lang.reflect.Method.invoke(Native Method)
09-20 11:25:00.479 E/Xposed  ( 4265): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
09-20 11:25:00.479 E/Xposed  ( 4265): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
09-20 11:25:00.479 E/Xposed  ( 4265): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
09-20 11:25:00.658 I/Xposed  ( 4265): [Android N-ify] [ERROR] StatusBarHeaderHooks: Error in onClickListener
09-20 11:25:00.659 E/Xposed  ( 4265): java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference
09-20 11:25:00.659 E/Xposed  ( 4265): 	at tk.wasdennnoch.androidn_ify.systemui.notifications.StatusBarHeaderHooks$14.onClickSafe(StatusBarHeaderHooks.java:877)
09-20 11:25:00.659 E/Xposed  ( 4265): 	at tk.wasdennnoch.androidn_ify.misc.SafeOnClickListener.onClick(SafeOnClickListener.java:44)
09-20 11:25:00.659 E/Xposed  ( 4265): 	at android.view.View.performClick(View.java:5207)
09-20 11:25:00.659 E/Xposed  ( 4265): 	at android.view.View$PerformClick.run(View.java:21168)
09-20 11:25:00.659 E/Xposed  ( 4265): 	at android.os.Handler.handleCallback(Handler.java:746)
09-20 11:25:00.659 E/Xposed  ( 4265): 	at android.os.Handler.dispatchMessage(Handler.java:95)
09-20 11:25:00.659 E/Xposed  ( 4265): 	at android.os.Looper.loop(Looper.java:148)
09-20 11:25:00.659 E/Xposed  ( 4265): 	at android.app.ActivityThread.main(ActivityThread.java:5443)
09-20 11:25:00.659 E/Xposed  ( 4265): 	at java.lang.reflect.Method.invoke(Native Method)
09-20 11:25:00.659 E/Xposed  ( 4265): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
09-20 11:25:00.659 E/Xposed  ( 4265): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
09-20 11:25:00.659 E/Xposed  ( 4265): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)

**Comment by cbdreinulldrei** [comment]
I think I found a workaround... works again if I make WiFi and Bluetooth my first two QS toggles.

**Comment by paphonbth** [comment]
It's because only wifi and bluetooth tile supports enlarge first row. If you put other tiles there it's not going to work. I'll add a check to prevent that from happening.

**Comment by cbdreinulldrei** [comment]
Yes, but since they can be shuffled with the built in UI tweaker, they can usually also be long pressed to access settings, but not with N-ify.

**Comment by paphonbth** [comment]
That's weird. I'll try to look into it after my exam.

**Comment by wasdennnoch** [comment]
Does that still happen with the latest builds? If so please describe precisely what happens because I haven't completely understood it yet.

**Comment by wasdennnoch** [comment]
No response
