### ISSUE TITLE
cm 13, system ui take too much memory

### ISSUE THREAD

**Issue by moonheart** [wasdennnoch/AndroidN-ify#840]
after two hours, system ui take up to 600mb memory, I have to force stop system ui to get more memory. 

cm 13, n-ify ver 627

**Comment by wasdennnoch** [comment]
Are there any crashes in the log? (Please post your Xposed log.) I'm on RR (which is based on CM) and paphon is on CM13 too and we both don't have any issues (mine only draws 91MB).

**Comment by paphonbth** [comment]
107 on mine. Never had any issue about memory leaks.

**Comment by moonheart** [comment]
sorry but I've updated my cm 13 and n-ify, thus  I can't provide  any logs ,sorry .
 Now system ui only take about 150MB memory .
shall I close this issue or keep it?
