### ISSUE TITLE
Kik app crashing with API Spoofing.

### ISSUE THREAD

**Issue by SlimShadys** [wasdennnoch/AndroidN-ify#842]
Using @paphonbth 's lastest build (experimental build 129) and enabled Kik on app spoofing window, it crashes.
Don't know if it related to Kik itself or to changes made in the module.
That's the log: http://hastebin.com/dihonejoxo.sql
Hope you can help me :)

**Comment by paphonbth** [comment]
As described before, API spoofing shouldn't be used and may make apps crash.
