### ISSUE TITLE
phone doesn't open

### ISSUE THREAD

**Issue by hakan5816** [wasdennnoch/AndroidN-ify#848]
build 631 (630) I have installed and rebooted the phone display does not come, but it does sound (messages, search)
6.0.1 Rom Xperia Z3C

**Comment by aviraxp** [comment]
I can confirm that. Black screen and systemui anr.

**Comment by ItzLevvie** [comment]
Confirmed on Xperia Z2

**Comment by Samsagax** [comment]
Got the same problem on my OnePlus 3 [logcat attached](https://github.com/wasdennnoch/AndroidN-ify/files/478426/logcat.txt)

Last version that worked: 618. Build 619+ doesn't work.
My system: OPLite 2.3 (OOS based (MM), debloated, modified DPI to 400), XPosed Framework v86 arm64.

**Comment by Samsagax** [comment]
Here is a hint in line 764 onward:

````
--------- beginning of crash
09-17 19:01:28.396  3520  3520 E AndroidRuntime: FATAL EXCEPTION: main
09-17 19:01:28.396  3520  3520 E AndroidRuntime: Process: com.android.systemui, PID: 3520
09-17 19:01:28.396  3520  3520 E AndroidRuntime: java.lang.NoSuchFieldError: com.android.systemui.qs.QSPanel#mGridHeight
09-17 19:01:28.396  3520  3520 E AndroidRuntime: 	at de.robv.android.xposed.XposedHelpers.findField(XposedHelpers.java:109)
09-17 19:01:28.396  3520  3520 E AndroidRuntime: 	at de.robv.android.xposed.XposedHelpers.setObjectField(XposedHelpers.java:726)
09-17 19:01:28.396  3520  3520 E AndroidRuntime: 	at tk.wasdennnoch.androidn_ify.systemui.qs.QuickSettingsHooks.onMeasure(QuickSettingsHooks.java:138)
09-17 19:01:28.396  3520  3520 E AndroidRuntime: 	at tk.wasdennnoch.androidn_ify.systemui.qs.QuickSettingsHooks$4.replaceHookedMethod(QuickSettingsHooks.java:109)
09-17 19:01:28.396  3520  3520 E AndroidRuntime: 	at de.robv.android.xposed.XC_MethodReplacement.beforeHookedMethod(XC_MethodReplacement.java:29)
09-17 19:01:28.396  3520  3520 E AndroidRuntime: 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:314)
09-17 19:01:28.396  3520  3520 E AndroidRuntime: 	at com.android.systemui.qs.QSPanel.onMeasure(<Xposed>)
09-17 19:01:28.396  3520  3520 E AndroidRuntime: 	at android.view.View.measure(View.java:18850)
````

**Comment by wasdennnoch** [comment]
Already fixed.

**Comment by hakan5816** [comment]
The problem did not improve. # 634 were tested. BLACK SCREEN.

**Comment by hakan5816** [comment]
Log @wasdennnoch https://1drv.ms/t/s!ApqyWr9kZ7Clg_0G2UVFAcJs-J4D8Q

**Comment by wasdennnoch** [comment]
No new snapshots are being built. I fixed the issue in code, but there is no version containf this fix right now. I'll link a version in the XDA thread soon.

**Comment by Samsagax** [comment]
Will test in a couple hours. Indeed the issue is not fixed in build 634. Maybe the cause is other. @wasdennoch, please reopen the issue until confirmed fix. Thanks for this awesome module

**Comment by Samsagax** [comment]
Tested can confirm that is fixed. Thanks @wasdennnoch

**Comment by hakan5816** [comment]
@Samsagax I'm the problem continues.

**Comment by Samsagax** [comment]
Yes, @hakan5816, you won't notice the fix until you build the app yourself or wait for a new post 634 build on Jenkins. The issue is fixed in the code tree but not built/released yet.

**Comment by hakan5816** [comment]
Build 634, There are already over Jenkins? @Samsagax

**Comment by Samsagax** [comment]
@hakan5816 you need to wait for a 635 release.

**Comment by hakan5816** [comment]
@Samsagax ok. Thanks

**Comment by wasdennnoch** [comment]
There won't be any new Jenkins builds, there is a new link to the newest build in the thread.

**Comment by hakan5816** [comment]
@wasdennnoch bad English. It will be a new building. A new link?

**Comment by hakan5816** [comment]
@wasdennnoch There won't be any new Jenkins builds. The new version, where new link?

**Comment by hakan5816** [comment]
Got it. Thanx
