### ISSUE TITLE
double tap on recents not working properly

### ISSUE THREAD

**Issue by V-Droid** [wasdennnoch/AndroidN-ify#849]
Hello, the double tap on recents is not working for me properly. I have it set for it to cycle through my recent apps however it only switches to my last used app. <br /><br />I've also enabled the other method to detect double tap on recents bit but still not working.<br /><br /> @wasdennnoch I don't know witch logs to post, so please tell me so you can fix this issue.<br /><br />I'm running CM13 on a Moto E 2015

**Comment by wasdennnoch** [comment]
Enable debug log and try to doulbe tap. Then post your Xposed log.
