### ISSUE TITLE
[SUGGESTION]Toggle to just enable notifications with N style.

### ISSUE THREAD

**Issue by wasd--** [wasdennnoch/AndroidN-ify#85]
Hi,
Just a suggestion, would be nice if you can add a toggle to just enable notification style and leave the rest by default.

Regards

**Comment by wasdennnoch** [comment]
I was planning to reorganize the settings and some "back end" code anyways and add toggles for every individual tweak.

**Comment by wasd--** [comment]
Perfect then, thanks ;)

**Comment by vlw** [comment]
Will make it now

**Comment by vlw** [comment]
Ready. Testing now.

**Comment by vlw** [comment]
Working. Will merge now

**Comment by vlw** [comment]
Merged. 931b5f2402b5d9d3750cf863d9496ab3d53afdc3
