### ISSUE TITLE
Crash after toggling airplane mode (and maybe another tiles)

### ISSUE THREAD

**Issue by jerryshaw12** [wasdennnoch/AndroidN-ify#855]
[logcat.txt](https://github.com/wasdennnoch/AndroidN-ify/files/478444/logcat.txt)

**Comment by jerryshaw12** [comment]
Rom: Mokee Android 5.1.1 (CM 12.1 Based)
Xposed: v86 API 22
Android N-ify: 634

**Comment by wasdennnoch** [comment]
Should be fixed with 21c11695e46dcda0a5c0596829f10bb1f1f3f1c6.
