### ISSUE TITLE
Doesnt seem to work AT ALL

### ISSUE THREAD

**Issue by ImReallyShiny** [wasdennnoch/AndroidN-ify#856]
![csl3jlew8aesz6t](https://cloud.githubusercontent.com/assets/17136956/18611550/b75787ca-7d34-11e6-899e-3d2943958d97.jpg)

**Comment by null-dev** [comment]
It was never designed to work on non-stock ROMs (Touchwiz, Samsung stuff)...

**Comment by ImReallyShiny** [comment]
Damn that sucks - Any workaround or another app to do it?

**Comment by ImReallyShiny** [comment]
![csmhsycweaapl7b](https://cloud.githubusercontent.com/assets/17136956/18611804/86905978-7d3e-11e6-8617-beff7a49c463.jpg)
Got it looking close :P
