### ISSUE TITLE
Text misplaced on Material Desing Xposed Installer

### ISSUE THREAD

**Issue by V-Droid** [wasdennnoch/AndroidN-ify#858]
Hello @paphonbth I noticed a peculiar bug for the 1xx builds. I use material design xposed installer by DVDAndroid and the title for the module looks misplaced. This doesn't happen on the 6xx builds and doesn't effect on the module's performance. I'm not sure what logs are necessary, so please tell me so you can fix this small bug. BTW fantastic job you all have done to this module! 

![screenshot_20160917-233137](https://cloud.githubusercontent.com/assets/20158071/18612984/cf9fb304-7d32-11e6-9b37-430f7ff4e2cf.png)

**Comment by wasdennnoch** [comment]
It's actually an issue of the installer, the version name TextView takes up so much width that the App name text needs several lines, but it's also so small that the name isn't visible. I'll create an issue in the installer repo.
