### ISSUE TITLE
Multiple Reply buttons possible when extracting from Android Wear or Auto

### ISSUE THREAD

**Issue by tushar260** [wasdennnoch/AndroidN-ify#862]
![screenshot_20160918-154750](https://cloud.githubusercontent.com/assets/21682756/18614972/52b02c9a-7db7-11e6-9bd9-fe1225e1642f.png)

**Comment by wasdennnoch** [comment]
One of them should open Quick Reply on the 13x builds. Currently the "compatible" button only gets added to the list while the others stay, this will be changed in the future.

**Comment by Maxr1998** [comment]
This is the oldest issue I found about this "bug", which is described [here on XDA](http://forum.xda-developers.com/showpost.php?p=69133065&postcount=11443), and seen as invalid.
