### ISSUE TITLE
System accent color not being applied to certain tiles.

### ISSUE THREAD

**Issue by geoff0616** [wasdennnoch/AndroidN-ify#868]
In conjunction with Android N-ify, I use Qs X Tiles per row module and like to change the look of my phone. I noticed that when changing the system accent color, it applies to the brightness slider, subtexts, and even the battery display graph made by N-ify. This is great, however it doesn't apply to every part of the quick settings tiles. 

[Here's a gif of what I'm talking about.](https://gfycat.com/AnyConsciousAlligator)

Can this be fixed? Thank you so much for this module. Appreciate your quick updates and dedication. 👍

**Comment by wasdennnoch** [comment]
Interesting, when I try to open the battery detail after changing the theme I'm stuck in an empty detail view and I have to lock the screen to make the animation work :P
Apart from that, the data usage view isn't being themed either and I'm not modifying that, so it could be a ROM issue. Does that happen with the module disabled too?

**Comment by geoff0616** [comment]
So it seems to not theme the data usage view even with N-ify disabled, I'm sure it's just an issue with Qs not applying the theme to the data usage view, the theme also isn't applied to the volume indicator so it's nothing on your end.

The battery however is where I'm just curious if that can be applied. By the way this is on a Nexus 5x Build MTC19T, the May 1st security patch. (I'm just too lazy to flash the updates). I haven't had any issues with anything not displaying correctly, in some of your earlier snapshots the battery graph didn't have a gradient rendered but it seemed to be fixed now.

**Comment by wasdennnoch** [comment]
>The battery however is where I'm just curious if that can be applied.
What do you mean?
