### ISSUE TITLE
No icons on notifications on 0.3.0

### ISSUE THREAD

**Issue by DavidMKD** [wasdennnoch/AndroidN-ify#869]
This is the issue that I've encountered with the latest build. I have all the files provided in this XDA post including the logs

> 09-18 23:39:53.661 I/Xposed  (  395): -----------------
09-18 23:39:53.661 I/Xposed  (  395): Starting Xposed version 86, compiled for SDK 22
09-18 23:39:53.661 I/Xposed  (  395): Device: XPERIA M2 (Sony), Android version 5.1.1 (SDK 22)
09-18 23:39:53.661 I/Xposed  (  395): ROM: EagleXperience-5.0b1-ota1-userdebug
09-18 23:39:53.661 I/Xposed  (  395): Build fingerprint: Sony/D2303/D2303:5.1.1/18.6.A.0.182/1807889774:user/release-keys
09-18 23:39:53.661 I/Xposed  (  395): Platform: armeabi-v7a, 32-bit binary, system server: yes
09-18 23:39:53.661 I/Xposed  (  395): SELinux enabled: yes, enforcing: yes
09-18 23:39:54.683 I/Xposed  (  395): -----------------
09-18 23:39:54.683 I/Xposed  (  395): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
09-18 23:39:55.226 I/Xposed  (  395): Detected ART runtime
09-18 23:39:55.245 I/Xposed  (  395): Found Xposed class 'de/robv/android/xposed/XposedBridge', now initializing
09-18 23:39:55.648 I/Xposed  (  395): Loading modules from /data/app/at.jclehner.appopsxposed-1/base.apk
09-18 23:39:55.905 I/Xposed  (  395):   Loading class at.jclehner.appopsxposed.AppOpsXposed
09-18 23:39:55.945 I/Xposed  (  395): Loading modules from /data/app/ma.wanam.youtubeadaway-1/base.apk
09-18 23:39:55.965 I/Xposed  (  395):   Loading class ma.wanam.youtubeadaway.Xposed
09-18 23:39:55.969 I/Xposed  (  395): Loading modules from /data/app/tk.wasdennnoch.androidn_ify-1/base.apk
09-18 23:39:56.185 I/Xposed  (  395):   Loading class tk.wasdennnoch.androidn_ify.XposedHook
09-18 23:39:56.214 I/Xposed  (  395): [Android N-ify] [INFO] XposedHook: Version 0.3.0-debug (6)
09-18 23:39:56.214 I/Xposed  (  395): [Android N-ify] [INFO] XposedHook: Official Build; Release: false (debug)
09-18 23:39:56.218 I/Xposed  (  395): [Android N-ify] [INFO] XposedHook: ROM type: aosp
09-18 23:39:56.218 I/Xposed  (  395): Loading modules from /data/app/net.jzhang.powernap-1/base.apk
09-18 23:39:56.310 I/Xposed  (  395):   Loading class net.jzhang.powernap.xposed.WakeLockManager
09-18 23:39:56.350 I/Xposed  (  395): Loading modules from /data/app/com.oasisfeng.greenify-1/base.apk
09-18 23:39:57.080 I/Xposed  (  395):   Loading class com.oasisfeng.greenify.pro.FrameworkPatch
09-18 23:39:57.114 I/Xposed  (  395):   Loading class com.oasisfeng.greenify.pro.SettingsPatch
09-18 23:39:57.115 I/Xposed  (  395): Loading modules from /data/app/com.pyler.mobileradioactivefix-1/base.apk
09-18 23:39:57.132 I/Xposed  (  395):   Loading class com.pyler.mobileradioactivefix.MobileRadioActiveFix
09-18 23:39:57.134 I/Xposed  (  395): Loading modules from /data/app/com.mohammadag.enablenotificationtickeronlollipop-1/base.apk
09-18 23:39:57.151 I/Xposed  (  395):   Loading class com.mohammadag.enablenotificationtickeronlollipop.XposedMod
09-18 23:40:13.538 E/Xposed  ( 1212): de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.android.systemui.statusbar.policy.NetworkControllerImpl$MobileSignalController
09-18 23:40:13.538 E/Xposed  ( 1212): 	at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:64)
09-18 23:40:13.538 E/Xposed  ( 1212): 	at tk.wasdennnoch.androidn_ify.systemui.statusbar.StatusBarHooks.<init>(StatusBarHooks.java:40)
09-18 23:40:13.538 E/Xposed  ( 1212): 	at tk.wasdennnoch.androidn_ify.systemui.statusbar.LollipopStatusBarHooks.<init>(LollipopStatusBarHooks.java:24)
09-18 23:40:13.538 E/Xposed  ( 1212): 	at tk.wasdennnoch.androidn_ify.systemui.statusbar.StatusBarHooks.create(StatusBarHooks.java:33)
09-18 23:40:13.538 E/Xposed  ( 1212): 	at tk.wasdennnoch.androidn_ify.systemui.SystemUIHooks.hookSystemUI(SystemUIHooks.java:45)
09-18 23:40:13.538 E/Xposed  ( 1212): 	at tk.wasdennnoch.androidn_ify.XposedHook.handleLoadPackage(XposedHook.java:122)
09-18 23:40:13.538 E/Xposed  ( 1212): 	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:34)
09-18 23:40:13.538 E/Xposed  ( 1212): 	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:61)
09-18 23:40:13.538 E/Xposed  ( 1212): 	at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:106)
09-18 23:40:13.538 E/Xposed  ( 1212): 	at de.robv.android.xposed.XposedInit$1.beforeHookedMethod(XposedInit.java:93)
09-18 23:40:13.538 E/Xposed  ( 1212): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:314)
09-18 23:40:13.538 E/Xposed  ( 1212): 	at android.app.ActivityThread.handleBindApplication(<Xposed>)
09-18 23:40:13.538 E/Xposed  ( 1212): 	at android.app.ActivityThread.access$1500(ActivityThread.java:156)
09-18 23:40:13.538 E/Xposed  ( 1212): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1412)
09-18 23:40:13.538 E/Xposed  ( 1212): 	at android.os.Handler.dispatchMessage(Handler.java:102)
09-18 23:40:13.538 E/Xposed  ( 1212): 	at android.os.Looper.loop(Looper.java:211)
09-18 23:40:13.538 E/Xposed  ( 1212): 	at android.app.ActivityThread.main(ActivityThread.java:5373)
09-18 23:40:13.538 E/Xposed  ( 1212): 	at java.lang.reflect.Method.invoke(Native Method)
09-18 23:40:13.538 E/Xposed  ( 1212): 	at java.lang.reflect.Method.invoke(Method.java:372)
09-18 23:40:13.538 E/Xposed  ( 1212): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020)
09-18 23:40:13.538 E/Xposed  ( 1212): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815)
09-18 23:40:13.538 E/Xposed  ( 1212): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
09-18 23:40:13.538 E/Xposed  ( 1212): Caused by: java.lang.ClassNotFoundException: com.android.systemui.statusbar.policy.NetworkControllerImpl$MobileSignalController
09-18 23:40:13.538 E/Xposed  ( 1212): 	at java.lang.Class.classForName(Native Method)
09-18 23:40:13.538 E/Xposed  ( 1212): 	at java.lang.Class.forName(Class.java:309)
09-18 23:40:13.538 E/Xposed  ( 1212): 	at external.org.apache.commons.lang3.ClassUtils.getClass(ClassUtils.java:823)
09-18 23:40:13.538 E/Xposed  ( 1212): 	at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:62)
09-18 23:40:13.538 E/Xposed  ( 1212): 	... 21 more
09-18 23:40:13.538 E/Xposed  ( 1212): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.android.systemui.statusbar.policy.NetworkControllerImpl$MobileSignalController" on path: DexPathList[[zip file "/system/priv-app/SystemUI/SystemUI.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
09-18 23:40:13.538 E/Xposed  ( 1212): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
09-18 23:40:13.538 E/Xposed  ( 1212): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
09-18 23:40:13.538 E/Xposed  ( 1212): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
09-18 23:40:13.538 E/Xposed  ( 1212): 	... 25 more
09-18 23:40:13.538 E/Xposed  ( 1212): 	Suppressed: java.lang.ClassNotFoundException: Didn't find class "com.android.systemui.statusbar.policy.NetworkControllerImpl$MobileSignalController" on path: DexPathList[[dex file "/data/dalvik-cache/xposed_XResourcesSuperClass.dex"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
09-18 23:40:13.538 E/Xposed  ( 1212): 		at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
09-18 23:40:13.538 E/Xposed  ( 1212): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
09-18 23:40:13.538 E/Xposed  ( 1212): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
09-18 23:40:13.538 E/Xposed  ( 1212): 		... 26 more
09-18 23:40:13.538 E/Xposed  ( 1212): 		Suppressed: java.lang.ClassNotFoundException: com.android.systemui.statusbar.policy.NetworkControllerImpl$MobileSignalController
09-18 23:40:13.538 E/Xposed  ( 1212): 			at java.lang.Class.classForName(Native Method)
09-18 23:40:13.538 E/Xposed  ( 1212): 			at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
09-18 23:40:13.538 E/Xposed  ( 1212): 			at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
09-18 23:40:13.538 E/Xposed  ( 1212): 			at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
09-18 23:40:13.538 E/Xposed  ( 1212): 			... 27 more
09-18 23:40:13.538 E/Xposed  ( 1212): 		Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
09-18 23:40:23.882 I/Xposed  ( 1212): [Android N-ify] [DEBUG] PagedTileLayout: Distributing tiles
09-18 23:40:23.884 I/Xposed  ( 1212): [Android N-ify] [DEBUG] PagedTileLayout: Adding WifiTile to 0
09-18 23:40:23.885 I/Xposed  ( 1212): [Android N-ify] [DEBUG] PagedTileLayout: Adding BluetoothTile to 0
09-18 23:40:23.885 I/Xposed  ( 1212): [Android N-ify] [DEBUG] PagedTileLayout: Adding FlashlightTile to 0
09-18 23:40:23.885 I/Xposed  ( 1212): [Android N-ify] [DEBUG] PagedTileLayout: Adding RotationLockTile to 0
09-18 23:40:23.886 I/Xposed  ( 1212): [Android N-ify] [DEBUG] PagedTileLayout: Adding DataTrafficTile to 0
09-18 23:40:23.886 I/Xposed  ( 1212): [Android N-ify] [DEBUG] PagedTileLayout: Adding LocationTile to 0
09-18 23:40:23.887 I/Xposed  ( 1212): [Android N-ify] [DEBUG] PagedTileLayout: Adding AutoSyncTile to 0
09-18 23:40:23.887 I/Xposed  ( 1212): [Android N-ify] [DEBUG] PagedTileLayout: Size: 1
09-18 23:40:24.294 I/Xposed  ( 1212): [Android N-ify] [DEBUG] PagedTileLayout: Instantiating 0
09-18 23:40:24.406 I/Xposed  ( 1212): [Android N-ify] [DEBUG] PageIndicator: Skipping animation false -1 0
09-18 23:40:27.915 I/Xposed  ( 2563):   KitKat: [OK]
09-18 23:41:43.420 I/XposedInstaller( 3947): Downloaded http://dl.xposed.info/repo/full.xml.gz with status 0 (error: null), size 1113365 bytes
09-18 23:41:48.786 I/XposedInstaller( 3947): Updated repository http://dl.xposed.info/repo/full.xml.gz to version 10188 (956 new / 0 removed modules)

[XDA post](http://forum.xda-developers.com/showpost.php?p=68753172&postcount=9292)

![screenshot_2016-09-18-23-46-43](https://cloud.githubusercontent.com/assets/13114412/18619819/49439c24-7e06-11e6-87cb-9ffdbdc4d074.png)

**Comment by wasdennnoch** [comment]
Should be fixed.
