### ISSUE TITLE
some times keyboard not poping or quick reply line not getting to write a sentence

### ISSUE THREAD

**Issue by dimuthu3** [wasdennnoch/AndroidN-ify#874]
When i click reply to whats app msg Keyboard not coming or quick reply line coming in also when i click quick reply on messenger some times its appearing and disappearing 
using experimental 135 build
android 6.0.1 beanstalk cm 13 base 
I9300
here is log https://drive.google.com/file/d/0B6NzzhtK6j4QY3VSNy1DNjVLUmM/view?usp=sharing

**Comment by wasdennnoch** [comment]
So only the keyboard doesn't appear? Or does it instantly disappear?

**Comment by dimuthu3** [comment]
on latest this have fix but when 2 or 3 messages from app cannot make quick reply and when click reply  its automaticaly turn open from the app

**Comment by wasdennnoch** [comment]
The app is responsible for providing the input action, if it doesn't do that N-ify can't add one.
