### ISSUE TITLE
Battery toggle in quick access

### ISSUE THREAD

**Issue by amitmittal117** [wasdennnoch/AndroidN-ify#878]
Can any body please help me finding way how to implement android nougat battery quick access in  n-ify.

**Comment by wasdennnoch** [comment]
There are snapshots linked in the second post in the XDA thread that contain the battery tile and much more.

**Comment by amitmittal117** [comment]
Can u plz give me the link??

**Comment by wasdennnoch** [comment]
http://forum.xda-developers.com/showpost.php?p=67725591&postcount=2
