### ISSUE TITLE
White stripe under notification when expanded from heads-up

### ISSUE THREAD

**Issue by xdddd23** [wasdennnoch/AndroidN-ify#881]
When Head up come and i expand it the notification over tap the down notification and in seconds go normal again. Cm13. I use experimental Android N notifications.

**Comment by xdddd23** [comment]
https://mega.nz/#!cNox3a5A!wi4fX8boNHvxm44OElacN9lUlDQ_WRCNsAypQRSrqJU screnshoot

**Comment by wasdennnoch** [comment]
Continue in #1020
