### ISSUE TITLE
Builds #639 and above: Unable to update the app. (App not installed error)

### ISSUE THREAD

**Issue by stevenx37** [wasdennnoch/AndroidN-ify#883]
Moto X 2013 XT1053 - On CM13 Unofficial 9/06 build.
I am on build #634 (works okay, notifications are a little bugged, otherwise fine). 
[Attached Screenshot](http://i.imgur.com/XUabwdk.png?1) (Imgur)

**Comment by jerryshaw12** [comment]
Uninstall first, they have different signature

**Comment by stevenx37** [comment]
Whoops, yeah that worked. Thank you.
