### ISSUE TITLE
No quick toggels

### ISSUE THREAD

**Issue by D-Slawotsky** [wasdennnoch/AndroidN-ify#892]
Instead of quick toggels they are empty and where I try pressing Edit it says mRecords==null;
[xposed_error_20160920_080652.zip](https://github.com/wasdennnoch/AndroidN-ify/files/481665/xposed_error_20160920_080652.zip)
Attached are logs that I changed the ending from .log to .zip. 
Thank you :)

**Comment by anuragdeshpande** [comment]
Facing the same issue

**Comment by anuragdeshpande** [comment]
please help fixing this, really missing them

**Comment by Freewander10** [comment]
Have you tried restarting the system UI? Or disable your theme if you're using one.

**Comment by D-Slawotsky** [comment]
Yes, the theme is on the Samsung Good Lock app, but it worked before.

**Comment by Freewander10** [comment]
My tiles used to disappear after applying a theme. A reboot usually fixes it though

**Comment by wasdennnoch** [comment]
Please post the log as a text file as changing the extension seems to corrupt it.

**Comment by D-Slawotsky** [comment]
09-21 11:46:41.990 I/Xposed  ( 5155): [Android N-ify] [ERROR] NotificationPanelHooks: Couldn't open edit view; mRecords == null
09-21 11:46:42.230 I/Xposed  ( 5155): fsbi >> simple_state_v23 >> data#0 vis: Some(true) lvl: Some(Some(75)) tpe: Some(None)
09-21 11:46:42.240 I/Xposed  ( 5155): fsbi >> simple_state_v23 >> PhoneState #0 >>
09-21 11:46:42.240 I/Xposed  ( 5155): mMobileStrengthId     : Some(id: 2130838675 name: stat_sys_signal_3_fully)
09-21 11:46:42.240 I/Xposed  ( 5155): mMobileTypeId         : Some((None,unknown id: 0))
09-21 11:46:42.240 I/Xposed  ( 5155): mMobileVisible        : Some(true)
09-21 11:46:42.240 I/Xposed  ( 5155): mSubId                : Some(unknown id: 1)
09-21 11:46:42.690 I/Xposed  ( 5155): [Android N-ify] [ERROR] NotificationPanelHooks: Couldn't open edit view; mRecords == null
09-21 11:46:43.240 I/Xposed  ( 5155): fsbi >> simple_state_v23 >> data#0 vis: Some(true) lvl: Some(Some(75)) tpe: Some(None)
09-21 11:46:43.250 I/Xposed  ( 5155): fsbi >> simple_state_v23 >> PhoneState #0 >>
09-21 11:46:43.250 I/Xposed  ( 5155): mMobileStrengthId     : Some(id: 2130838675 name: stat_sys_signal_3_fully)
09-21 11:46:43.250 I/Xposed  ( 5155): mMobileTypeId         : Some((None,unknown id: 0))
09-21 11:46:43.250 I/Xposed  ( 5155): mMobileVisible        : Some(true)
09-21 11:46:43.250 I/Xposed  ( 5155): mSubId                : Some(unknown id: 1)
09-21 11:46:44.250 I/Xposed  ( 5155): fsbi >> simple_state_v23 >> data#0 vis: Some(true) lvl: Some(Some(75)) tpe: Some(None)
09-21 11:46:44.270 I/Xposed  ( 5155): fsbi >> simple_state_v23 >> PhoneState #0 >>
09-21 11:46:44.270 I/Xposed  ( 5155): mMobileStrengthId     : Some(id: 2130838675 name: stat_sys_signal_3_fully)
09-21 11:46:44.270 I/Xposed  ( 5155): mMobileTypeId         : Some((None,unknown id: 0))
09-21 11:46:44.270 I/Xposed  ( 5155): mMobileVisible        : Some(true)
09-21 11:46:44.270 I/Xposed  ( 5155): mSubId                : Some(unknown id: 1)
09-21 11:46:46.270 I/Xposed  ( 5155): fsbi >> simple_state_v23 >> data#0 vis: Some(true) lvl: Some(Some(75)) tpe: Some(None)
09-21 11:46:46.280 I/Xposed  ( 5155): fsbi >> simple_state_v23 >> PhoneState #0 >>
09-21 11:46:46.280 I/Xposed  ( 5155): mMobileStrengthId     : Some(id: 2130838675 name: stat_sys_signal_3_fully)
09-21 11:46:46.280 I/Xposed  ( 5155): mMobileTypeId         : Some((None,unknown id: 0))
09-21 11:46:46.280 I/Xposed  ( 5155): mMobileVisible        : Some(true)
09-21 11:46:46.280 I/Xposed  ( 5155): mSubId                : Some(unknown id: 1)
09-21 11:46:47.570 I/Xposed  ( 5155): [Android N-ify] [ERROR] NotificationPanelHooks: Couldn't open edit view; mRecords == null
09-21 11:46:48.350 I/Xposed  ( 5155): fsbi >> simple_state_v23 >> data#0 vis: Some(true) lvl: Some(Some(75)) tpe: Some(None)
09-21 11:46:48.360 I/Xposed  ( 5155): fsbi >> simple_state_v23 >> PhoneState #0 >>
09-21 11:46:48.360 I/Xposed  ( 5155): mMobileStrengthId     : Some(id: 2130838675 name: stat_sys_signal_3_fully)
09-21 11:46:48.360 I/Xposed  ( 5155): mMobileTypeId         : Some((None,unknown id: 0))
09-21 11:46:48.360 I/Xposed  ( 5155): mMobileVisible        : Some(true)
09-21 11:46:48.360 I/Xposed  ( 5155): mSubId                : Some(unknown id: 1)
09-21 11:46:49.300 I/Xposed  ( 5155): fsbi >> simple_state_v23 >> data#0 vis: Some(true) lvl: Some(Some(75)) tpe: Some(None)
09-21 11:46:49.320 I/Xposed  ( 5155): fsbi >> simple_state_v23 >> PhoneState #0 >>
09-21 11:46:49.320 I/Xposed  ( 5155): mMobileStrengthId     : Some(id: 2130838675 name: stat_sys_signal_3_fully)
09-21 11:46:49.320 I/Xposed  ( 5155): mMobileTypeId         : Some((None,unknown id: 0))
09-21 11:46:49.320 I/Xposed  ( 5155): mMobileVisible        : Some(true)
09-21 11:46:49.320 I/Xposed  ( 5155): mSubId                : Some(unknown id: 1)
09-21 11:46:50.750 I/Xposed  ( 5155): fsbi >> simple_state_v23 >> data#0 vis: Some(true) lvl: Some(Some(75)) tpe: Some(None)
09-21 11:46:50.760 I/Xposed  ( 5155): fsbi >> simple_state_v23 >> PhoneState #0 >>
09-21 11:46:50.760 I/Xposed  ( 5155): mMobileStrengthId     : Some(id: 2130838675 name: stat_sys_signal_3_fully)
09-21 11:46:50.760 I/Xposed  ( 5155): mMobileTypeId         : Some((None,unknown id: 0))
09-21 11:46:50.760 I/Xposed  ( 5155): mMobileVisible        : Some(true)
09-21 11:46:50.760 I/Xposed  ( 5155): mSubId                : Some(unknown id: 1)
09-21 11:46:50.770 I/Xposed  ( 5155): fsbi >> nc >> onWifiStateChanged >> true >> rssi: -86dBm >> ssid: Partner LTE
09-21 11:46:53.320 I/Xposed  ( 5155): fsbi >> simple_state_v23 >> data#0 vis: Some(true) lvl: Some(Some(75)) tpe: Some(None)
09-21 11:46:53.340 I/Xposed  ( 5155): fsbi >> simple_state_v23 >> PhoneState #0 >>
09-21 11:46:53.340 I/Xposed  ( 5155): mMobileStrengthId     : Some(id: 2130838675 name: stat_sys_signal_3_fully)
09-21 11:46:53.340 I/Xposed  ( 5155): mMobileTypeId         : Some((None,unknown id: 0))
09-21 11:46:53.340 I/Xposed  ( 5155): mMobileVisible        : Some(true)
09-21 11:46:53.340 I/Xposed  ( 5155): mSubId                : Some(unknown id: 1)
09-21 11:46:53.800 I/Xposed  ( 5155): fsbi >> simple_state_v23 >> data#0 vis: Some(true) lvl: Some(Some(75)) tpe: Some(None)
09-21 11:46:53.800 I/Xposed  ( 5155): fsbi >> simple_state_v23 >> PhoneState #0 >>
09-21 11:46:53.800 I/Xposed  ( 5155): mMobileStrengthId     : Some(id: 2130838675 name: stat_sys_signal_3_fully)
09-21 11:46:53.800 I/Xposed  ( 5155): mMobileTypeId         : Some((None,unknown id: 0))
09-21 11:46:53.800 I/Xposed  ( 5155): mMobileVisible        : Some(true)
09-21 11:46:53.800 I/Xposed  ( 5155): mSubId                : Some(unknown id: 1)
09-21 11:46:53.830 I/Xposed  ( 5155): fsbi >> nc >> onWifiStateChanged >> true >> rssi: -78dBm >> ssid: Partner LTE
09-21 11:46:54.330 I/Xposed  ( 5155): fsbi >> simple_state_v23 >> data#0 vis: Some(true) lvl: Some(Some(75)) tpe: Some(None)
09-21 11:46:54.340 I/Xposed  ( 5155): fsbi >> simple_state_v23 >> PhoneState #0 >>
09-21 11:46:54.340 I/Xposed  ( 5155): mMobileStrengthId     : Some(id: 2130838675 name: stat_sys_signal_3_fully)
09-21 11:46:54.340 I/Xposed  ( 5155): mMobileTypeId         : Some((None,unknown id: 0))
09-21 11:46:54.340 I/Xposed  ( 5155): mMobileVisible        : Some(true)
09-21 11:46:54.340 I/Xposed  ( 5155): mSubId                : Some(unknown id: 1)
09-21 11:46:57.160 I/Xposed  ( 5155): fsbi >> simple_state_v23 >> carrier label: 012 Mobile
09-21 11:46:57.160 I/Xposed  ( 5155): fsbi >> simple_state_v23 >> data#0 vis: Some(true) lvl: Some(Some(50)) tpe: Some(None)
09-21 11:46:57.170 I/Xposed  ( 5155): fsbi >> simple_state_v23 >> PhoneState #0 >>
09-21 11:46:57.170 I/Xposed  ( 5155): mMobileStrengthId     : Some(id: 2130838673 name: stat_sys_signal_2_fully)
09-21 11:46:57.170 I/Xposed  ( 5155): mMobileTypeId         : Some((None,unknown id: 0))
09-21 11:46:57.170 I/Xposed  ( 5155): mMobileVisible        : Some(true)
09-21 11:46:57.170 I/Xposed  ( 5155): mSubId                : Some(unknown id: 1)
09-21 11:46:57.180 I/Xposed  ( 5155): fsbi >> nc >> onDataChanged >> 0 > true >  50 >  _ >> exists view: ArrayBuffer(true, true, true) >> max: ArrayBuffer(1, 1, 1)
09-21 11:47:02.030 I/XposedInstaller(12043): RepoLoader -> Downloaded http://dl.xposed.info/repo/partial/10202.xml.gz with status 1 (error: null), size 0 bytes
09-21 11:47:02.350 I/Xposed  ( 5155): fsbi >> simple_state_v23 >> data#0 vis: Some(true) lvl: Some(Some(50)) tpe: Some(None)
09-21 11:47:02.350 I/Xposed  ( 5155): fsbi >> simple_state_v23 >> PhoneState #0 >>
09-21 11:47:02.350 I/Xposed  ( 5155): mMobileStrengthId     : Some(id: 2130838673 name: stat_sys_signal_2_fully)
09-21 11:47:02.350 I/Xposed  ( 5155): mMobileTypeId         : Some((None,unknown id: 0))
09-21 11:47:02.350 I/Xposed  ( 5155): mMobileVisible        : Some(true)
09-21 11:47:02.350 I/Xposed  ( 5155): mSubId                : Some(unknown id: 1)
09-21 11:47:03.350 I/Xposed  ( 5155): fsbi >> simple_state_v23 >> data#0 vis: Some(true) lvl: Some(Some(50)) tpe: Some(None)
09-21 11:47:03.360 I/Xposed  ( 5155): fsbi >> simple_state_v23 >> PhoneState #0 >>
09-21 11:47:03.360 I/Xposed  ( 5155): mMobileStrengthId     : Some(id: 2130838673 name: stat_sys_signal_2_fully)
09-21 11:47:03.360 I/Xposed  ( 5155): mMobileTypeId         : Some((None,unknown id: 0))
09-21 11:47:03.360 I/Xposed  ( 5155): mMobileVisible        : Some(true)
09-21 11:47:03.360 I/Xposed  ( 5155): mSubId                : Some(unknown id: 1)
09-21 11:47:04.360 I/Xposed  ( 5155): fsbi >> simple_state_v23 >> data#0 vis: Some(true) lvl: Some(Some(50)) tpe: Some(None)
09-21 11:47:04.370 I/Xposed  ( 5155): fsbi >> simple_state_v23 >> PhoneState #0 >>
09-21 11:47:04.370 I/Xposed  ( 5155): mMobileStrengthId     : Some(id: 2130838673 name: stat_sys_signal_2_fully)
09-21 11:47:04.370 I/Xposed  ( 5155): mMobileTypeId         : Some((None,unknown id: 0))
09-21 11:47:04.370 I/Xposed  ( 5155): mMobileVisible        : Some(true)
09-21 11:47:04.370 I/Xposed  ( 5155): mSubId                : Some(unknown id: 1)
09-21 11:47:05.360 I/Xposed  ( 5155): fsbi >> simple_state_v23 >> data#0 vis: Some(true) lvl: Some(Some(50)) tpe: Some(None)
09-21 11:47:05.370 I/Xposed  ( 5155): fsbi >> simple_state_v23 >> PhoneState #0 >>
09-21 11:47:05.370 I/Xposed  ( 5155): mMobileStrengthId     : Some(id: 2130838673 name: stat_sys_signal_2_fully)
09-21 11:47:05.370 I/Xposed  ( 5155): mMobileTypeId         : Some((None,unknown id: 0))
09-21 11:47:05.370 I/Xposed  ( 5155): mMobileVisible        : Some(true)
09-21 11:47:05.370 I/Xposed  ( 5155): mSubId                : Some(unknown id: 1)
09-21 11:47:08.950 I/Xposed  ( 5155): fsbi >> nc >> onWifiStateChanged >> true >> rssi: -83dBm >> ssid: Partner LTE
09-21 11:47:08.960 I/Xposed  ( 5155): fsbi >> simple_state_v23 >> data#0 vis: Some(true) lvl: Some(Some(50)) tpe: Some(None)
09-21 11:47:08.970 I/Xposed  ( 5155): fsbi >> simple_state_v23 >> PhoneState #0 >>
09-21 11:47:08.970 I/Xposed  ( 5155): mMobileStrengthId     : Some(id: 2130838673 name: stat_sys_signal_2_fully)
09-21 11:47:08.970 I/Xposed  ( 5155): mMobileTypeId         : Some((None,unknown id: 0))
09-21 11:47:08.970 I/Xposed  ( 5155): mMobileVisible        : Some(true)
09-21 11:47:08.970 I/Xposed  ( 5155): mSubId                : Some(unknown id: 1)
09-21 11:47:12.380 I/Xposed  ( 5155): fsbi >> simple_state_v23 >> data#0 vis: Some(true) lvl: Some(Some(50)) tpe: Some(None)
09-21 11:47:12.390 I/Xposed  ( 5155): fsbi >> simple_state_v23 >> PhoneState #0 >>
09-21 11:47:12.390 I/Xposed  ( 5155): mMobileStrengthId     : Some(id: 2130838673 name: stat_sys_signal_2_fully)
09-21 11:47:12.390 I/Xposed  ( 5155): mMobileTypeId         : Some((None,unknown id: 0))
09-21 11:47:12.390 I/Xposed  ( 5155): mMobileVisible        : Some(true)
09-21 11:47:12.390 I/Xposed  ( 5155): mSubId                : Some(unknown id: 1)
09-21 11:47:13.380 I/Xposed  ( 5155): fsbi >> simple_state_v23 >> data#0 vis: Some(true) lvl: Some(Some(50)) tpe: Some(None)
09-21 11:47:13.380 I/Xposed  ( 5155): fsbi >> simple_state_v23 >> PhoneState #0 >>
09-21 11:47:13.380 I/Xposed  ( 5155): mMobileStrengthId     : Some(id: 2130838673 name: stat_sys_signal_2_fully)
09-21 11:47:13.380 I/Xposed  ( 5155): mMobileTypeId         : Some((None,unknown id: 0))
09-21 11:47:13.380 I/Xposed  ( 5155): mMobileVisible        : Some(true)
09-21 11:47:13.380 I/Xposed  ( 5155): mSubId                : Some(unknown id: 1)
09-21 11:47:15.000 I/Xposed  ( 5155): fsbi >> nc >> onWifiStateChanged >> true >> rssi: -82dBm >> ssid: Partner LTE
09-21 11:47:15.020 I/Xposed  ( 5155): fsbi >> simple_state_v23 >> data#0 vis: Some(true) lvl: Some(Some(50)) tpe: Some(None)
09-21 11:47:15.030 I/Xposed  ( 5155): fsbi >> simple_state_v23 >> PhoneState #0 >>
09-21 11:47:15.030 I/Xposed  ( 5155): mMobileStrengthId     : Some(id: 2130838673 name: stat_sys_signal_2_fully)
09-21 11:47:15.030 I/Xposed  ( 5155): mMobileTypeId         : Some((None,unknown id: 0))
09-21 11:47:15.030 I/Xposed  ( 5155): mMobileVisible        : Some(true)
09-21 11:47:15.030 I/Xposed  ( 5155): mSubId                : Some(unknown id: 1)
09-21 11:47:27.080 I/Xposed  ( 5155): fsbi >> nc >> onWifiStateChanged >> true >> rssi: -83dBm >> ssid: Partner LTE
09-21 11:47:27.100 I/Xposed  ( 5155): fsbi >> simple_state_v23 >> data#0 vis: Some(true) lvl: Some(Some(50)) tpe: Some(None)
09-21 11:47:27.110 I/Xposed  ( 5155): fsbi >> simple_state_v23 >> PhoneState #0 >>
09-21 11:47:27.110 I/Xposed  ( 5155): mMobileStrengthId     : Some(id: 2130838673 name: stat_sys_signal_2_fully)
09-21 11:47:27.110 I/Xposed  ( 5155): mMobileTypeId         : Some((None,unknown id: 0))
09-21 11:47:27.110 I/Xposed  ( 5155): mMobileVisible        : Some(true)
09-21 11:47:27.110 I/Xposed  ( 5155): mSubId                : Some(unknown id: 1)
09-21 11:47:33.150 I/Xposed  ( 5155): fsbi >> simple_state_v23 >> data#0 vis: Some(true) lvl: Some(Some(50)) tpe: Some(None)
09-21 11:47:33.160 I/Xposed  ( 5155): fsbi >> simple_state_v23 >> PhoneState #0 >>
09-21 11:47:33.160 I/Xposed  ( 5155): mMobileStrengthId     : Some(id: 2130838673 name: stat_sys_signal_2_fully)
09-21 11:47:33.160 I/Xposed  ( 5155): mMobileTypeId         : Some((None,unknown id: 0))
09-21 11:47:33.160 I/Xposed  ( 5155): mMobileVisible        : Some(true)
09-21 11:47:33.160 I/Xposed  ( 5155): mSubId                : Some(unknown id: 1)
09-21 11:47:33.190 I/Xposed  ( 5155): fsbi >> nc >> onWifiStateChanged >> true >> rssi: -81dBm >> ssid: Partner LTE
09-21 11:47:33.430 I/Xposed  ( 5155): fsbi >> simple_state_v23 >> data#0 vis: Some(true) lvl: Some(Some(50)) tpe: Some(None)
09-21 11:47:33.440 I/Xposed  ( 5155): fsbi >> simple_state_v23 >> PhoneState #0 >>
09-21 11:47:33.440 I/Xposed  ( 5155): mMobileStrengthId     : Some(id: 2130838673 name: stat_sys_signal_2_fully)
09-21 11:47:33.440 I/Xposed  ( 5155): mMobileTypeId         : Some((None,unknown id: 0))
09-21 11:47:33.440 I/Xposed  ( 5155): mMobileVisible        : Some(true)
09-21 11:47:33.440 I/Xposed  ( 5155): mSubId                : Some(unknown id: 1)
09-21 11:47:35.420 I/Xposed  ( 5155): fsbi >> simple_state_v23 >> data#0 vis: Some(true) lvl: Some(Some(50)) tpe: Some(None)
09-21 11:47:35.430 I/Xposed  ( 5155): fsbi >> simple_state_v23 >> PhoneState #0 >>
09-21 11:47:35.430 I/Xposed  ( 5155): mMobileStrengthId     : Some(id: 2130838673 name: stat_sys_signal_2_fully)
09-21 11:47:35.430 I/Xposed  ( 5155): mMobileTypeId         : Some((None,unknown id: 0))
09-21 11:47:35.430 I/Xposed  ( 5155): mMobileVisible        : Some(true)
09-21 11:47:35.430 I/Xposed  ( 5155): mSubId                : Some(unknown id: 1)
09-21 11:47:39.420 I/Xposed  ( 5155): fsbi >> simple_state_v23 >> data#0 vis: Some(true) lvl: Some(Some(50)) tpe: Some(None)
09-21 11:47:39.420 I/Xposed  ( 5155): fsbi >> simple_state_v23 >> PhoneState #0 >>
09-21 11:47:39.420 I/Xposed  ( 5155): mMobileStrengthId     : Some(id: 2130838673 name: stat_sys_signal_2_fully)
09-21 11:47:39.420 I/Xposed  ( 5155): mMobileTypeId         : Some((None,unknown id: 0))
09-21 11:47:39.420 I/Xposed  ( 5155): mMobileVisible        : Some(true)
09-21 11:47:39.420 I/Xposed  ( 5155): mSubId                : Some(unknown id: 1)
09-21 11:47:40.430 I/Xposed  ( 5155): fsbi >> simple_state_v23 >> data#0 vis: Some(true) lvl: Some(Some(50)) tpe: Some(None)
09-21 11:47:40.430 I/Xposed  ( 5155): fsbi >> simple_state_v23 >> PhoneState #0 >>
09-21 11:47:40.430 I/Xposed  ( 5155): mMobileStrengthId     : Some(id: 2130838673 name: stat_sys_signal_2_fully)
09-21 11:47:40.430 I/Xposed  ( 5155): mMobileTypeId         : Some((None,unknown id: 0))
09-21 11:47:40.430 I/Xposed  ( 5155): mMobileVisible        : Some(true)
09-21 11:47:40.430 I/Xposed  ( 5155): mSubId                : Some(unknown id: 1)

**Comment by D-Slawotsky** [comment]
Update: I found disabling editing fixes the problem. Now I can't edit the tiles but I do have Quick Toggles :)

**Comment by wasdennnoch** [comment]
This isn't the full log; are you sure you copied the while log from the Xposed installer from start to finish? You can also pack the log inside a zip after exporting or upload it anywhere else (or aste it on hastebin), just don't change the .log at the end.

**Comment by D-Slawotsky** [comment]
It was the whole thing. Now it is fixed. Since the Pixel look it works. Maybe the edit is now different so it works. Thanks you for your help and app.

**Comment by Freewander10** [comment]
You should probably close the issue then.
