### ISSUE TITLE
Clock off-axis vertical

### ISSUE THREAD

**Issue by Charaktor** [wasdennnoch/AndroidN-ify#895]
Build 146
OPO with Sultan xda Aug 8th
400 dpi

Clock in expanded and un-expanded qs ist shifted down. 
It is not alligned with little dot and date.
Same with theme and without.

![screenshot_20160920-081435](https://cloud.githubusercontent.com/assets/22313624/18659354/5510303a-7f0a-11e6-807e-b34bd2a90bc9.png)
![screenshot_20160920-081429](https://cloud.githubusercontent.com/assets/22313624/18659355/55243058-7f0a-11e6-91d5-3b1e93044fa1.png)

**Comment by wasdennnoch** [comment]
Is it this one? http://forum.xda-developers.com/oneplus-one/orig-development/rom-kernel-unofficial-cyanogenmod-13-0-t3242700
If it's CM then it should work correctly.

**Comment by Charaktor** [comment]
Yep that's the one. It is based on stable branch of cm.
Well then, its possibly due to other mods and changes I made to my phone.
Thanks anyway.
