### ISSUE TITLE
Cast tile not visibile on lockscreen

### ISSUE THREAD

**Issue by Maik268** [wasdennnoch/AndroidN-ify#898]
Cast tile is not selected in 'hide on lockscreen'. It's visible in normal panel AND lockscreen, but after a reboot it disappeared just on lockscreen.
I have to select and deselect it in nify-settings to hide it again temporary -> till next reboot.
[xposed_error_20160920_111711.txt](https://github.com/wasdennnoch/AndroidN-ify/files/482079/xposed_error_20160920_111711.txt)

**Comment by wasdennnoch** [comment]
Therr are no errors in the log; I added some debug lines, please install build 660 as soon as it's ready, enable debug log and post your Xposed log.

**Comment by Maik268** [comment]
Here is my log after a reboot.
I'm using latest 1xx build, but your debug lines are added there too, correct?
[xposed_error_20160921_122014.txt](https://github.com/wasdennnoch/AndroidN-ify/files/484706/xposed_error_20160921_122014.txt)

**Comment by wasdennnoch** [comment]
Does this still happen?

**Comment by Maik268** [comment]
Currently I'm not using N-ify (my device came back from repair a few days ago).
But before I sent it to repair it was still happening.

**Comment by wasdennnoch** [comment]
As there's nobody else with that issue (and you don't use it) I'll close this.
