### ISSUE TITLE
A Huge series of bugs since the 627th build.

### ISSUE THREAD

**Issue by sargijeh** [wasdennnoch/AndroidN-ify#903]
Since the build 627 till know there a lot of problems with this module (but I didn't experience any crashes)
the last stable build was 626 however the settings page won't themed in all of the versions.
I'm on Xperia Z Ultra 5.1.1 Stock Rom.
xposed logs are attached :)
---
[xposed_error_20160920_162403.log.txt](https://github.com/wasdennnoch/AndroidN-ify/files/482474/xposed_error_20160920_162403.log.txt)

![screenshot_2016-09-20-16-25-16](https://cloud.githubusercontent.com/assets/22320438/18669497/96f0ef8a-7f50-11e6-9612-54b24642cc70.png)
![screenshot_2016-09-20-16-25-26](https://cloud.githubusercontent.com/assets/22320438/18669517/ae93e0d4-7f50-11e6-9244-d0af06897a03.png)
![screenshot_2016-09-20-16-25-39](https://cloud.githubusercontent.com/assets/22320438/18669516/ae8faeba-7f50-11e6-9baf-e0573222b691.png)
![screenshot_2016-09-20-16-25-47](https://cloud.githubusercontent.com/assets/22320438/18669520/af91cd84-7f50-11e6-882c-302ba246993b.png)

**Comment by pwrusr** [comment]
@wasdennoch @paphonb... This is The common issue in Xperia lollipop.. Try to fix it

**Comment by sargijeh** [comment]
@pwrusr I hope they do something about it,
Are all of these happening for you too?

**Comment by pwrusr** [comment]
Yah.. I have it too.. From #627....I can't edit even... If I drag a tile to qs...it won't be placed there and on pressing back arrow of edit button.. It restarts system ui...qs animation also not smooth..it scatters after sometime.. Auto rotation with enlarge first row.. Restarts system ui.... Hope they will gonna fix..

**Comment by sargijeh** [comment]
@pwrusr they are not much an xperia fan, they are mainly focusing on cm13 :(

**Comment by pwrusr** [comment]
@sargijeh may be.. But most of the ppl r using cm builds...and most of the devices are on marshmallow... and few of us only on stock.. #Coz we.. Mostly me... Dont wanna unlock bootloader and mess with security and Sony signature builds and apps#.... Soo they may concentrate on them first.. Later they will gonna fix lollipop issues.. The thing which is worrying me is... Upto #626.. The issues r minor.. From #627.. What made it more buggy left me thinking..

**Comment by wasdennnoch** [comment]
We are trying to make it compatible on as many devices as possible, but many bugs can't be fixed instantly or easily. In this case a class isn't found which causes all hooks after it not to hook. The only Xperia SystemUI I have saved is from a M device and has the required class.
This means: I need a **deodexed** SystemUI from a LP Xperia ROM from you guys.

**Comment by sargijeh** [comment]
@pwrusr its true but there is no stable M for my xperia Z Ultra. Thus I'm stock with this :(

**Comment by sargijeh** [comment]
@wasdennnoch but until 626 the bugs ,as our friend mentioned, were minor,
I don't know about deodexed and odexed things, but I can attach the systemUI apk, is it enough?

**Comment by pwrusr** [comment]
Wer can I find that @wasdennoch.. Can u name it

**Comment by pwrusr** [comment]
I'm on deodexd mate @sargijeh.. Can u tell me the path.. Wer can I find it

**Comment by sargijeh** [comment]
@pwrusr I think it is located in "/system/priv-app/systemui"
Btw ,  are you on Z1?

**Comment by pwrusr** [comment]
I tried in my phone.. In System app section.. But i can't find systemui.apk

**Comment by sargijeh** [comment]
@pwrusr search systemui by a root explorer, I am using solid explorer and I searched in the root folder :)

**Comment by pwrusr** [comment]
I got it.. Should I open a new issue and upload? Or else.. Should I upload here @sargijeh.. If it's here.. And i can't see any attachment symbol here

**Comment by wasdennnoch** [comment]
You have to upload it externally (Google Drive, Dropbox, Mediafire, whatever)

**Comment by sargijeh** [comment]
I really don't know about it, I think @wasdennnoch can help you better,
I think you can upload it somewhere else and post the link here :)

**Comment by sargijeh** [comment]
@pwrusr as he said upload it. I really missed this module :(

**Comment by pwrusr** [comment]
@sargijeh Sorry mate.. Im on a shitty airtel network.. I'm trying from 20 mins.. Its still uploading

**Comment by sargijeh** [comment]
@pwrusr post here mate ;) thank in advance

**Comment by pwrusr** [comment]
I opened a new issue on this and for minor bugs too.. Uploaded full Xposed log.. I think they gonna fix by this log @sargijeh #919

**Comment by sargijeh** [comment]
@wasdennnoch 
the system UI that @pwrusr had uploaded it is added to this issue, it is for xperia lollipop and it is deodexed,
hope it help you:)
btw, the toggles and recents are fixed, but some minor flaws like the date alignment (which is really down) is being seen in all updates:
this is my issue and my xposed logs:
[xposed_error_20160921_114422.log.txt](https://github.com/wasdennnoch/AndroidN-ify/files/485892/xposed_error_20160921_114422.log.txt)
![screenshot_2016-09-21-12-41-26](https://cloud.githubusercontent.com/assets/22320438/18726322/c3946bb0-8050-11e6-8df7-a766114e7383.png)

this is @pwrusr xposed log:
[pwrusr-xposed_error_20160921_123210.log.txt](https://github.com/wasdennnoch/AndroidN-ify/files/485897/pwrusr-xposed_error_20160921_123210.log.txt)

**Comment by pwrusr** [comment]
@wasdennoch hers the system ui u asked @sargijeh let's hope for less bugs 

[SystemUI.apk.zip](https://github.com/wasdennnoch/AndroidN-ify/files/485965/SystemUI.apk.zip)

**Comment by wasdennnoch** [comment]
Should be fixed with 69990a52a80df8ff11f92c3f3f25e5fd7f589629

**Comment by pwrusr** [comment]
@wasdennnoch System ui crash with c9990a5 :( 
 pls fix this.. And #919 too

**Comment by licaon-kter** [comment]
Which part of this is fixed?

Xperia 5.1.1

After build 626:
* small quick tiles are not visible UNLESS Fancy animations are active
* when not visible, when quick settings is expanded clicking the Settings cog activates the 6-th small quick tile (as if it's still there)

**Comment by sargijeh** [comment]
Dou you have full width headsup notifications? @licaon-kter

**Comment by licaon-kter** [comment]
@sargijeh Nope.

@wasdennnoch Should I open a new issue?

**Comment by wasdennnoch** [comment]
Probably
