### ISSUE TITLE
Lp Xperia deodexd systemui 

### ISSUE THREAD

**Issue by pwrusr** [wasdennnoch/AndroidN-ify#910]
[Uploading SystemUI.apk.zip…]()

Here's the system ui of Xperia lp deodexd.. Hope this will gonna fix by @wasdennoch

**Comment by pwrusr** [comment]
@wasdennoch it's working great now.. Thank u for this beauty..minor issue.. Autorotation With enlarge first row enable causing system ui restart.. Then on edit tiles.. I can't place anything in qs 
It's not staying der.. Just reverted back..

**Comment by sargijeh** [comment]
Dear @wasdennnoch this is the file related to issue 903 :)

**Comment by sargijeh** [comment]
@pwrusr his name has 3 "n" s :D

**Comment by sargijeh** [comment]
quick toggles won't appear in build 662 and quickreplys results in crash. @wasdennnoch

**Comment by pwrusr** [comment]
My bad.. Sorry @wasdennnoch..thank u @sargijeh.... Ya u got the file? I mean in this post? I'm not so sure its uploaded or not coz my net is damn slow... 16kbps on 3g.. With this #660 gud thing is quick reply is working with read on both sides of Gmail

**Comment by pwrusr** [comment]
And on 662... Tiles behave weird...i touch owner tile.. It activates autorotation... Touch on taskmanager. It activates flight mode...funny ha ha 

Along with this the issues which I mentioned in first post r still present in #662

**Comment by sargijeh** [comment]
@pwrusr @wasdennnoch with fancy animations disabled tiles doesn't appear correctly,
and your file is still uploading :(
please upload it again here (by editing the post you can do that (I think))

**Comment by pwrusr** [comment]
I can.. But...I'm on a ridiculous network with 25 million customers.... providing me  amazing 16 kbps for 3g which claims to be the first in providing fastest ispeed 

..Soo I will try in morning.. @sargijeh

**Comment by wasdennnoch** [comment]
Upload it when you have good internet, no need to hurry. And please post it in #903 so I don't get confused what belongs where.
