### ISSUE TITLE
Old toggles don't show up on edit menu anymore

### ISSUE THREAD

**Issue by mranzy** [wasdennnoch/AndroidN-ify#914]
I'm on cm12.1 (lollipop)
The last build in which all my old toggles showed up in edit menu is #626
Here are xposed logs :
https://drive.google.com/file/d/0B2ceMNxEUb6eZnJKR1paM3lqQW8/view?usp=drivesdk

And here's a screenshot of how it shows up now:
https://drive.google.com/file/d/0B2ceMNxEUb6eRHFQd3dkS005Nmc/view?usp=drivesdk

**Comment by wasdennnoch** [comment]
If this is still an issue please poat a new Xposed log as you one got spammed with an error that is already fixed.

**Comment by mranzy** [comment]
Yeah it is, native stock tiles are still unavailable... So I went on xposed to get logs and the only log I found is this :


09-25 16:32:05.798 I/Xposed  ( 8595): [Android N-ify] [WARNING] MobileDataController: Failed to get data usage, no subscriber id



Don't know if there's something wrong with xposed or not, I'm still new to this... hope that helped.

**Comment by mranzy** [comment]
09-25 16:32:05.798 I/Xposed  ( 8595): [Android N-ify] [WARNING] MobileDataController: Failed to get data usage, no subscriber id

**Comment by wasdennnoch** [comment]
Fixed with 18d9290531ef52e3a5ac7e0e8ced5ee7b028336a
