### ISSUE TITLE
emergency information button doesn't show up in emergency screen

### ISSUE THREAD

**Issue by mranzy** [wasdennnoch/AndroidN-ify#915]
Xposed logs :
https://drive.google.com/file/d/0B2ceMNxEUb6eZnJKR1paM3lqQW8/view?usp=drivesdk

Screenshot : https://drive.google.com/file/d/0B2ceMNxEUb6eSmZ6ZFFRMHJRN1k/view?usp=drivesdk

PS : I'm using cm12.1 (lp)

**Comment by wasdennnoch** [comment]
#784
