### ISSUE TITLE
Lp Xperia deodexd systemui  +Xposed log... Issues with improper  tile touch functions..can't edit tiles  Enlarge first row ui restart on landscape autorotation ..scattered animation after sometime of.usage.. Many minor 

### ISSUE THREAD

**Issue by pwrusr** [wasdennnoch/AndroidN-ify#919]
[SystemUI.apk.zip](https://github.com/wasdennnoch/AndroidN-ify/files/484318/SystemUI.apk.zip)

Xposed log 
[xposed_error_20160921_123210.log.txt](https://github.com/wasdennnoch/AndroidN-ify/files/484322/xposed_error_20160921_123210.log.txt)
 
Full Xposed log 
[xposed_error_20160921_122739.log.txt](https://github.com/wasdennnoch/AndroidN-ify/files/484335/xposed_error_20160921_122739.log.txt)

**Comment by pwrusr** [comment]
@wasdennnoch.. I uploaded Xperia fully deodexd systemui.. Xposed log and full  Xposed log.. Which is if over 200 lines.. Please fix these issues in lollipop  devices 
@sargijeh finally network speed improved.. Uploaded.. Let's hope for fix

**Comment by sargijeh** [comment]
#903

**Comment by pwrusr** [comment]
#quick reply working only on native sms.. Double reply.. Lyk reply read reply.. On Gmail

**Comment by sargijeh** [comment]
What is your phone and which build of rom you are using? @pwrusr

**Comment by pwrusr** [comment]
Xperia z1 5.1 stock rom.....xzu.. Xz1 runs on Same software but differs in hardware

**Comment by sargijeh** [comment]
in build 667, most of the things work fine and the huge thing which doesn't work is the settings page.
btw, the date in the header is a little down, this is really annoying in months like "July" which is been shown as "Julv" because the down part of the texts are some kind of cropped!
btw, I had change the size of clock and it has no effect on the date,
my xposed log and the screenshot has been attached down below:

[xposed_error_20160921_114422.log.txt](https://github.com/wasdennnoch/AndroidN-ify/files/484589/xposed_error_20160921_114422.log.txt)
![screenshot_2016-09-21-12-41-26](https://cloud.githubusercontent.com/assets/22320438/18705366/e09a1058-7ffa-11e6-802c-c5de3a691743.png)

**Comment by pwrusr** [comment]
I will gonna check Nw
.and I will report

**Comment by pwrusr** [comment]
It's by @paphonb...let's wait for @wasdennnoch.. As logs and system ui posted here.. He will also take.a look... Did u tried landscape on anyapp by enabling enlarge first row... It restarts system ui.. And Nw the new bug is.. Screen blinks when I open any third party music and stock music app stutters.. I restart nify.. Then seems to be set.. Let's wait for the fix by @wasdennnoch and with date and time check #910

**Comment by sargijeh** [comment]
@pwrusr you don't have the datw problem :( I think it only happens on zultra,
Honestly I hadn't use enlarge first row option recently, it make the performance weird :D
Did you try the quick replys?
I had test it on plus messenger and after pressing send, nothing happens just "stock on sending" without any crashes :-S
Hope @wasdennnoch fix it too :)

**Comment by pwrusr** [comment]
![screenshot_2016-09-21-15-58-42](https://cloud.githubusercontent.com/assets/22295050/18707672/d34673f0-8014-11e6-8acc-9676246093cb.png)


Ya tried.. Working with no crash.. With double reply for Gmail.. One for onscreen reply and another for inapp reply or to compose or to read.. 

Performance wired? Hw? @ sargijeh..I'm pretty sure it will gonna restart ui on landscape if u enable it.. I think u should be on deodexd to get full benefits of anyapp or we call it customization.. Wats ur rom BTW?

**Comment by pwrusr** [comment]
Build #660 adapts notification background color according to theme.. #667 won't consider this too pls @wasdennnoch

**Comment by sargijeh** [comment]
Yep quick reply is working with sms flawlessly, I think the problem is plus messenger :D
I think you should attach a logcat for the crashes,
I'm on stock 5.1.1 (.236) @pwrusr
What is your music player?

**Comment by sargijeh** [comment]
@pwruser I think the issue #920 is related to the enlarge first row problem :)

**Comment by pwrusr** [comment]
Mm @sargijeh that's great it's working for u.. #667 also have the same issues I mentioned soo when @wasdennnoch took a look systemui and logs provided...it will get resolved I think.. Phonograph from playstore.. I lyk it coz of its adaption of color respective to album cover.. Highly customizable.. And it solved my tiny album cover bug in notification panel when expanded

**Comment by sargijeh** [comment]
@pwrusr wow, I used phonograph a year ago but I'd uninstalled it since then, I will try it again :)

**Comment by sargijeh** [comment]
@pwrusr I think as @wasdennnoch mentioned and closed that issue, you should upload your files on issue #903

**Comment by pwrusr** [comment]
I think author can only edit the post @sargijeh ... Can u download my attached Files and attach frm ur side..? Coz I'm having dead slow Internet here..

**Comment by sargijeh** [comment]
sure :) @pwrusr

**Comment by pwrusr** [comment]
Did u find any stable build so far frm #667? @sargijeh

**Comment by sargijeh** [comment]
build 669 is weird, double tap recents doesn't work and also I experienced some bootloops. I will revert to 667 :) @pwrusr

**Comment by pwrusr** [comment]
@sargijeh  Get on a deodexd rom.. U Wil get benefit of every mod and app out there... Im having same issues lyk I mentioned in #910.. No bootloops.. Doubletap recents works for me.. 

Search dstrikerz zu rom on xda.. It's the best deodexd rom so far.. No bugs..

**Comment by sargijeh** [comment]
actually I don't want to lose my apps, and apps data, I have more than 200 apps,
and also the doubletap feature bug happens rarely and it will be solved by 1 or 2 reboots, and I think the reason is Xperia Xposed module which I used to add useful tiles to quick settings and also other tweaks.
that module have a section for double tapping the recent button (which has 2 options, doing nothing and clearing all recent apps), I found that xperia xposed module is really more powerful than the N-ify in taking control of the recent button :D @pwrusr

**Comment by pwrusr** [comment]
Feels gud.. It solved ur issue... Actually u can do a backup on otg or to external card and give it a try..it hav latest Xperia X and Sony stock features..lyk. Dseehx.. Assertive display...supervivid.. S-force manymore.. Mainly it's totally deodexd... Ya I agree gravity box and xxm r powerful and they r powerful enuf to brick Xperia ;-) :-P kidding.. @sargijeh

**Comment by sargijeh** [comment]
wait a minute, I remembered something!
if your system UI is for this rom, so it is not actually stock xperia rom!
oh god, what might happen to this module and xperias? :O
@pwrusr

**Comment by pwrusr** [comment]
Ha ha ha easy mate.. Its STOCK...Remember.. Stock means.. The app which u gonna get by default frm Sony.. Nothing gonna happen to any Xperia and module..even it made easy to work on it.. Coz it's deodexd @sargijeh.. Dont worry mate.. It made one step closer to fix issues

**Comment by sargijeh** [comment]
but it has the xperia X UI, so, I'm kind of worried :))
btw, I think the developers are mad at us from this huge amount of commenting :)) @pwrusr

**Comment by pwrusr** [comment]
@sargijeh Mm ya Xperia X ui.. But its ported to lollipop as stock.. And As this module supports from lollipop thers no need to get worried for Xperias running on lollipop.. Mm  ya.. May be they must be watching us.. Great work devs.. :) pls take a lo_0k at xperians ;)

**Comment by sargijeh** [comment]
@pwrusr if your phone settings doesn't get N-ifyed as mine, so maybe it is the same :) because my settings page is not changing :D
Yep devs, you are awesome :))

**Comment by pwrusr** [comment]
@sargijeh yes... Mine also lyk stock.. Its not changing.. No nify ed settings.. Y it's happening.. But one of the xda members did a script file to get those settings on Resurrection remix rom...

**Comment by wasdennnoch** [comment]
If you have any other issues please open a new issue with clear description, 50 replys with information spread across doesn't help at all.
