### ISSUE TITLE
Enlarge first row vs. N-style click behaviour

### ISSUE THREAD

**Issue by cbdreinulldrei** [wasdennnoch/AndroidN-ify#920]
On my Moto X Play, when not selecting N-style click behavior, I can not long press WiFi or Bluetooth in QS. I also can not "pull down" because I can not select "enlarge first row" when "N-style click behaviour" is not selected.

When I use N-style click behaviour, clicking on a cellular tile (I have two, as it's a dual sim device) always brings up data settings for the second tile, never for the first one.

It's ok when I turn off "N-style click behaviour", but then I can't select WiFi or Bluetooth...

**Comment by wasdennnoch** [comment]
Fixed with f3f6e166853438be954de67dd5121986bb632b6b
