### ISSUE TITLE
wifi tiles won't expand ; 667 build ; cm12.1

### ISSUE THREAD

**Issue by jerryshaw12** [wasdennnoch/AndroidN-ify#921]
I have enabled enable tiles editor, but when I clicked wifi tiles, it won't expand.

logs https://drive.google.com/file/d/0B3TzmNRa2nE6M1Rhbm1ZVmdYSGc/view?usp=drivesdk

Xposed logs https://drive.google.com/file/d/0B3TzmNRa2nE6aUt2TElLcExuTDg/view?usp=drivesdk

**Comment by wasdennnoch** [comment]
Please post a new Xposed log, the current one is broken for some reason.

**Comment by jerryshaw12** [comment]
video
[URL]http://cloud.tapatalk.com/s/57e754bb1a7f0/2016_09_25_11_34_40.mp4[/URL]

xposed logs
[URL]https://drive.google.com/file/d/0B3TzmNRa2nE6TVVKLU92MTY2RVU/view?usp=sharing[/URL]

another xlog for cast tile also expand but get back to toggle grid
[URL]https://drive.google.com/file/d/0B3TzmNRa2nE6YjlPNmRoU1hoYzA/view?usp=sharing[/URL]

systemui
[url]https://drive.google.com/file/d/0B3TzmNRa2nE6UUdoTldfcTdodEU/view?usp=sharing[/url]

**Comment by wasdennnoch** [comment]
I don't know what you are doing, but the first 95% of the Xposed logs are just spaces. Are you exporting the logs from the installer properly?

**Comment by Freewander10** [comment]
I'm having this issue too.

**Comment by wasdennnoch** [comment]
Still need a proper log if that still happens.

**Comment by Freewander10** [comment]
Here are my closed logs. Hopefully they can help. 
[xposed_error_20161024_140337.txt](https://github.com/wasdennnoch/AndroidN-ify/files/548733/xposed_error_20161024_140337.txt)

**Comment by wasdennnoch** [comment]
Fixed with 5c66bbd0b6084fac2e2af8d9227f16164b8cfe73
