### ISSUE TITLE
Crashes on Lollipop 

### ISSUE THREAD

**Issue by jlobo912** [wasdennnoch/AndroidN-ify#923]
I'm facing SystemUI has crashed on Lollipop 5.0 Wiko Rainbow Up. Could you take a look at the logcat? http://pastebin.com/tVXgzBkx

**Comment by jlobo912** [comment]
Pastebin doesnt paste all the logcat. Sorry. I Uploaded to drive. Sorry if the logcat is a little bit big (6mb) but was my first time logcatting. https://drive.google.com/file/d/0B67s7C0DJ5nKbDRzSUxWTWl0YzA/view?usp=drivesdk

**Comment by jlobo912** [comment]
if you have any question, please send me a reply. I think I sent all the right stuff but it might be missing something

**Comment by wasdennnoch** [comment]
I guess this still happens; if so: If you are able to provide a **deodexed** SystemUI please do so, if not I'll try something else.

**Comment by wasdennnoch** [comment]
No response
