### ISSUE TITLE
'Overview' system UI crash

### ISSUE THREAD

**Issue by stagefright5** [wasdennnoch/AndroidN-ify#924]
The below link has the log of the crash in paphonb's "automatic" build (build number 667). The issue is, whenever 'Overview' button is pressed, system UI crashes and system UI will be restarted.

http://hastebin.com/osecogikan.scala

PS: This is my first whatever-this-is. Please let me know how may I help.

**Comment by stagefright5** [comment]
The version of android is 6.0.1

**Comment by wasdennnoch** [comment]
#680

**Comment by stagefright5** [comment]
How can I know if any issue has been reported earlier so that I don't open duplicate issues?

**Comment by wasdennnoch** [comment]
By looking through the issues list.
