### ISSUE TITLE
bug on lockscreen

### ISSUE THREAD

**Issue by tiagolinik** [wasdennnoch/AndroidN-ify#927]
![screenshot_20160921-143543](https://cloud.githubusercontent.com/assets/19411109/18722465/4579b9c8-800b-11e6-8961-bcaceaa5ad35.png)
![screenshot_20160921-143535](https://cloud.githubusercontent.com/assets/19411109/18722474/4c9e450c-800b-11e6-95ac-4d525aee6e06.png)

**Comment by wasdennnoch** [comment]
#816
