### ISSUE TITLE
Clock overlaps quick toggles

### ISSUE THREAD

**Issue by Filo90** [wasdennnoch/AndroidN-ify#928]
build #667 on nexus5 6.0.1 stock

When I pull down the notification bar, it briefly overlaps with quick toggles in the animation, the final shape is right.....

here's a picture of the overlapping in the animation:
![screenshot_20160921-195238](https://cloud.githubusercontent.com/assets/22352284/18722470/348628b6-8035-11e6-8806-66c472abe5d4.png)

**Comment by Filo90** [comment]
I never posted a log....is this ok?
[xposed_error_20160921_212747.txt](https://github.com/wasdennnoch/AndroidN-ify/files/485874/xposed_error_20160921_212747.txt)

**Comment by Filo90** [comment]
anyway I've just noticed that as soon as I try to modify the quicktoggles, the animation fix itself forever.....

**Comment by wasdennnoch** [comment]
Does this still happen?

**Comment by wasdennnoch** [comment]
No response
