### ISSUE TITLE
Time and date not aligned properly

### ISSUE THREAD

**Issue by shae23** [wasdennnoch/AndroidN-ify#930]
Below is a screen shot of what my pulldown looks like without the module enabled, the time and date are aligned.
![screenshot_20160921-202137](https://cloud.githubusercontent.com/assets/10815842/18734614/cece50fa-803b-11e6-9e52-f6cd1124f412.png)
The issue I am having is that with the module enabled, the time and date appear in one straight line instead of the time above and the date below, tested version 2.0 and experimental 163, same results.
![screenshot_20160921-183946](https://cloud.githubusercontent.com/assets/10815842/18734642/2df966c8-803c-11e6-8da2-11a002e34b03.png)
I'm a total noon and was advised to post the issue here, using an Alcatel Idol 3, running mm 6.0.1

**Comment by paphonbth** [comment]
It should be displayed in one line. It's like that on N.
For the overlapping issue, change the settings to make it smaller.

**Comment by wasdennnoch** [comment]
Actually the date format is way too long, it is something like "Wed, 22 Sept." on N. I already wanted to add a format toggle a long time ago.

**Comment by shae23** [comment]
Well that's good to know, lol, hopefully I'll see a toggle one day

**Comment by paphonbth** [comment]
Fixed with #960.
