### ISSUE TITLE
quick settings glitch

### ISSUE THREAD

**Issue by Filo90** [wasdennnoch/AndroidN-ify#933]
build #669 on Nexus5 6.0.1 stock

after opening and closing the battery graph in the notification panel, I had this glitch:

![screenshot_20160922-004606](https://cloud.githubusercontent.com/assets/22352284/18741897/d0ed3218-80b1-11e6-8f43-2dba19e80a34.png)

**Comment by Filo90** [comment]
here's the log, I could repeat the glitch every time....
[xposed_error_20160922_104801.txt](https://github.com/wasdennnoch/AndroidN-ify/files/486821/xposed_error_20160922_104801.txt)

**Comment by wasdennnoch** [comment]
Does that still happen? If so please post a new *full* Xposed log.

**Comment by wasdennnoch** [comment]
No response
