### ISSUE TITLE
Direct reply unfocuses and closes because of too high notification/keyboard

### ISSUE THREAD

**Issue by Filo90** [wasdennnoch/AndroidN-ify#934]
build #669 on Nexus5 6.0.1 stock
Whenever I receive  a mail, trying quick reply give this:
![screenshot_20160922-114948](https://cloud.githubusercontent.com/assets/22352284/18744107/be6447a2-80bc-11e6-97bd-761c915804de.png) 
or this:
![screenshot_20160922-114858](https://cloud.githubusercontent.com/assets/22352284/18744129/d8c0136a-80bc-11e6-9ef3-ccf422d52c10.png)

**Comment by Maxr1998** [comment]
This probably happens when keyboard and notification are to high.. Text input gets behind keyboard, unfocuses, closes. Or it just bugs. Will take a look at it.
