### ISSUE TITLE
No cross in mobile data tile

### ISSUE THREAD

**Issue by Silver-Fullbuster** [wasdennnoch/AndroidN-ify#936]
The mobile data tile does not show a cross when mobile data is off.

**Comment by dimuthu3** [comment]
@Silver-Fullbuster  did you check is it enable from app settings?last time i had this and enabled reboot its ok now

**Comment by Silver-Fullbuster** [comment]
It's on, and I've rebooted my phone multiple times. No change. It's a bug.. What should I provide though? Logs or deodexed system ui?

**Comment by wasdennnoch** [comment]
Xposed log and probably your deodexed SystemUI, yes.

**Comment by Silver-Fullbuster** [comment]
Xposed logs: http://pastebin.com/X9wW7mGs
Deodexed System UI: https://drive.google.com/open?id=0BzDyS5Y6vDYVaFpCMXZocXVqQ0E

**Comment by Silver-Fullbuster** [comment]
In the latest builds, the cross sign works, but only if I enable and disable mobile data at least once. Upon a fresh reboot, if the mobile data is disabled, no cross sign

**Comment by wasdennnoch** [comment]
Multi-sim is a bit hard to deal with; I added a proper check on boot, but it will probably only check thei first data-capable sim.
