### ISSUE TITLE
no service mark in signals 

### ISSUE THREAD

**Issue by tausifj15** [wasdennnoch/AndroidN-ify#940]
Sir when i use nify in sim indicator no network shows but  my network is full 
2 (6)
09-23 06:57:25.735 I/Xposed  (  260): [Android N-ify] [INFO] XposedHook: Automated Build; Version: 672
09-23 06:57:25.735 I/Xposed  (  260): [Android N-ify] [INFO] XposedHook: Build Time: 2016-09-22T20:23Z
09-23 06:57:25.735 I/Xposed  (  260): [Android N-ify] [INFO] XposedHook: Git SHA: 21a846b485124c5ce53d0cd1a67498ed866699f1
09-23 06:57:25.735 I/Xposed  (  260): [Android N-ify] [INFO] XposedHook: ROM type: undefined
09-23 06:57:25.735 I/Xposed  (  260): [Android N-ify] [WARNING] XposedHook: Can't read prefs file, default values will be applied in hooks!
09-23 06:57:25.736 I/Xposed  (  260): Loading modules from /data/app/com.zst.xposed.screenoffanimation-1/base.apk
09-23 06:57:25.779 I/Xposed  (  260):   Loading class com.zst.xposed.screenoffanimation.MainXposed
09-23 06:57:25.795 I/Xposed  (  260): Loading modules from /data/app/com.pyler.xinternalsd-1/base.apk
09-23 06:57:25.827 I/Xposed  (  260):   Loading class com.pyler.xinternalsd.XInternalSD
09-23 06:57:25.838 I/Xposed  (  260): Loading modules from /data/app/com.bocharov.xposed.fskeyboard-1/base.apk
09-23 06:57:25.901 I/Xposed  (  260):   Loading class com.bocharov.xposed.fskeyboard.Module
09-23 06:57:28.458 E/Xposed  ( 1309): de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.android.server.PowerManagerService
09-23 06:57:28.458 E/Xposed  ( 1309): 	at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:64)
09-23 06:57:28.458 E/Xposed  ( 1309): 	at com.zst.xposed.screenoffanimation.MainXposed.handleLoadPackage(MainXposed.java:75)
09-23 06:57:28.458 E/Xposed  ( 1309): 	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:34)
09-23 06:57:28.458 E/Xposed  ( 1309): 	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:61)
09-23 06:57:28.458 E/Xposed  ( 1309): 	at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:106)
09-23 06:57:28.458 E/Xposed  ( 1309): 	at de.robv.android.xposed.XposedInit$3$1.beforeHookedMethod(XposedInit.java:135)
09-23 06:57:28.458 E/Xposed  ( 1309): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:314)
09-23 06:57:28.458 E/Xposed  ( 1309): 	at com.android.server.SystemServer.startBootstrapServices(<Xposed>)
09-23 06:57:28.458 E/Xposed  ( 1309): 	at com.android.server.SystemServer.run(SystemServer.java:289)
09-23 06:57:28.458 E/Xposed  ( 1309): 	at com.android.server.SystemServer.main(SystemServer.java:176)
09-23 06:57:28.458 E/Xposed  ( 1309): 	at java.lang.reflect.Method.invoke(Native Method)
09-23 06:57:28.458 E/Xposed  ( 1309): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
09-23 06:57:28.458 E/Xposed  ( 1309): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
09-23 06:57:28.458 E/Xposed  ( 1309): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
09-23 06:57:28.458 E/Xposed  ( 1309): Caused by: java.lang.ClassNotFoundException: com.android.server.PowerManagerService
09-23 06:57:28.458 E/Xposed  ( 1309): 	at java.lang.Class.classForName(Native Method)
09-23 06:57:28.458 E/Xposed  ( 1309): 	at java.lang.Class.forName(Class.java:324)
09-23 06:57:28.458 E/Xposed  ( 1309): 	at external.org.apache.commons.lang3.ClassUtils.getClass(ClassUtils.java:823)
09-23 06:57:28.458 E/Xposed  ( 1309): 	at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:62)
09-23 06:57:28.458 E/Xposed  ( 1309): 	... 13 more
09-23 06:57:28.458 E/Xposed  ( 1309): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.android.server.PowerManagerService" on path: DexPathList[[zip file "/system/framework/org.cyanogenmod.platform.jar", zip file "/system/framework/org.cyanogenmod.hardware.jar", zip file "/system/framework/services.jar", zip file "/system/framework/ethernet-service.jar", zip file "/system/framework/wifi-service.jar"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
09-23 06:57:28.458 E/Xposed

**Comment by paphonbth** [comment]
Not an issue. See 706a751.
