### ISSUE TITLE
Notifications actions or buttons pressing area is too big

### ISSUE THREAD

**Issue by jahirfiquitiva** [wasdennnoch/AndroidN-ify#941]
As you can see in screenshot, the area that can be pressed for second button is basically all available space. And it's ripple is shown in that space too.

Please, make it button only.

Thanks

![screenshot_20160922-165822](https://cloud.githubusercontent.com/assets/10360816/18774228/b8b6cf04-811c-11e6-9023-b580fa24e883.png)

**Comment by tushar260** [comment]
It is the way it is in Nougat.

**Comment by wasdennnoch** [comment]
It's like that on N, the last (or only) action button covers the whole width. Weird, indeed, but Nougat.

**Comment by jahirfiquitiva** [comment]
A little bit disappointing how you want this module to match Android N that much, you even keep its issues.

Everything else is great, btw. Keep up the good work.

**Comment by wasdennnoch** [comment]
It's not really an issue, they intended it to be that. But yes, we aim to mimic N as much as possible. It depends on you whether you like it or not ;)
