### ISSUE TITLE
SystemUI fc on Lollipop 5.0

### ISSUE THREAD

**Issue by sapthesh** [wasdennnoch/AndroidN-ify#942]
Please find the attached log of SystemUI fc when n-ify is enabled. 
Please take a look at it. 
I can only use stable version 0.2
Thanks. 
[systemui-fc-nify.txt](https://github.com/wasdennnoch/AndroidN-ify/files/489419/systemui-fc-nify.txt)

**Comment by wasdennnoch** [comment]
Same crash as #1063
