### ISSUE TITLE
Bug on Music and Spotify notification tile (672/166)

### ISSUE THREAD

**Issue by DavidMKD** [wasdennnoch/AndroidN-ify#943]
Xposed Log: https://drive.google.com/open?id=0BxOx6OK5fXEnYlRybTVlcGYwUEk

Walkman Music (the album art and music info are misplaced):
http://imgur.com/a/wi0Ne

Spotify(the music info is a bit misaligned aligned to the album art):
http://imgur.com/RmI9yWW

**Comment by wasdennnoch** [comment]
#744
