### ISSUE TITLE
I answer seems to be still sms notification

### ISSUE THREAD

**Issue by hakan5816** [wasdennnoch/AndroidN-ify#945]
Reply using (1 message base) comes when I answer the SMS message as notifications again
Build 673 
Android 6.0.1 Rom

**Comment by wasdennnoch** [comment]
Explain precisely and/or attach screenshots please.

**Comment by hakan5816** [comment]
The same message comes again. As you see..
https://1drv.ms/v/s!ApqyWr9kZ7Clg_1JCDnAbaeYXQW84A

**Comment by wasdennnoch** [comment]
It's the apps fault, it shows a new notification after the message is sent. No module issue.

**Comment by hakan5816** [comment]
Build 670, There was no such problem.

**Comment by wasdennnoch** [comment]
Probably because you used API spoofing to force the app to use directly reply then?

**Comment by hakan5816** [comment]
English is not good. Some details? Xperia Z3C and Xperia Z2 tested. The two phones have the same problem. No API feature. I'm having this problem by using the n-ify module answer feature.

**Comment by wasdennnoch** [comment]
On build 670 you were probably using API spoofing to add Direct Reply. The app probably behaved correctly then, hiding zhe notification after sending. I removed that option to spoof now so the app may behave differently.

**Comment by hakan5816** [comment]
Okay. Thanks
