### ISSUE TITLE
Quick Reply problems.

### ISSUE THREAD

**Issue by Simi3000** [wasdennnoch/AndroidN-ify#946]
There are some problems with this feature (at least on WhatsApp)
1. When you receive 2 message from different contacts you can't reply.
2. When you receive 2 messages from the same contact you can't reply.

**Comment by wasdennnoch** [comment]
This is no issue of the module. It's the apps fault.

**Comment by Simi3000** [comment]
Not totally, Android N has the option/API or something, that separate message notifications.
