### ISSUE TITLE
Settings app crashes on build 168

### ISSUE THREAD

**Issue by Freewander10** [wasdennnoch/AndroidN-ify#951]
ROM: Exodus 5.1
Xposed Logs: https://docs.google.com/uc?id=0B5_P4hsjIFYmWEtVYUpfcmRnUFE&export=download
System Logs: https://docs.google.com/uc?id=0B5_P4hsjIFYmUzRfVE95ZDNzTEE&export=download

**Comment by jerryshaw12** [comment]
here is mine
Mokee 5.1.1 
https://drive.google.com/file/d/0B3TzmNRa2nE6ZTI4LWRlaUZOMDQ/view?usp=drivesdk

**Comment by paphonbth** [comment]
Fixed with #958.
