### ISSUE TITLE
WiFi quick tile isn't working

### ISSUE THREAD

**Issue by DavidMKD** [wasdennnoch/AndroidN-ify#952]
When I press the tile it doesn't do anything, it just shows the signal and the SSID nothing more than that, it doesn't shut off the WiFi or expands, nothing

Xposed Log: https://drive.google.com/open?id=0BxOx6OK5fXEnQ0FuNHhnSkUwdVk

**Comment by wasdennnoch** [comment]
The collapsed icon only toggles it while the expanded one shows detail if you have the N click behavior enabled. Is this is still a problem please post a new log as I can't access this one anymore.

**Comment by wasdennnoch** [comment]
No response
