### ISSUE TITLE
N-settings drawer and statusbar overlap

### ISSUE THREAD

**Issue by Maik268** [wasdennnoch/AndroidN-ify#953]
With the new n-setting drawer my settings overlap with statusbar and looks like this.
-> Settings crashes in some submenus and in some menus the header with some extra information and settings is missing.
All in all my settings app looks really weird.
HTC 10 with Android 6.0.1
N-ify 171

![screenshot_20160924-142059](https://cloud.githubusercontent.com/assets/13015934/18808428/cd887de6-8262-11e6-88d5-7a207de3552b.png)
[xposed_error_20160924_142411.txt](https://github.com/wasdennnoch/AndroidN-ify/files/491101/xposed_error_20160924_142411.txt)
[xposed_error_20160924_223646.txt](https://github.com/wasdennnoch/AndroidN-ify/files/491620/xposed_error_20160924_223646.txt)

**Comment by Freewander10** [comment]
Sorry. Didn't see this. I'll close mine. I think they'll need more than your xposed logs though. So I'll provide a logcat:
https://docs.google.com/uc?id=0B5_P4hsjIFYmNTZacEtlNmxISUE&export=download

**Comment by wasdennnoch** [comment]
Of course HTC changed something so that two important things are missing. Would it be possible to post a **deodexed** SystemUI?

`java.lang.NoSuchMethodError: com.android.settings.dashboard.DashboardSummary#rebuildUI(android.content.Context)#exact`
`java.lang.ClassNotFoundException: com.android.settings.Utils`

**Comment by Maik268** [comment]
[SystemUI.zip](https://github.com/wasdennnoch/AndroidN-ify/files/496560/SystemUI.zip)

**Comment by Maik268** [comment]
Yes, HTC removes to much in my opinion.
I don't have system ui tuner either, because HTC removed it. So it's not possible for me to get stock quick settings look/tiles back without dirty flashing my ROM.

**Comment by wasdennnoch** [comment]
Oops, I'm a dummy, I need your deodexed Settings and not the SystemUI of course, sorry :)

**Comment by Maik268** [comment]
[Settings.zip](https://github.com/wasdennnoch/AndroidN-ify/files/548500/Settings.zip)

**Comment by wasdennnoch** [comment]
Drawer should be fixed with 80a75b8f0751f26421c18f408470a26dc680cb13, tell me if there are other issues with the latest build.
