### ISSUE TITLE
No "x" if mobile data is disabled

### ISSUE THREAD

**Issue by Maik268** [wasdennnoch/AndroidN-ify#954]
On my HTC 10 (Android 6.0.1) there is no "x" if Mobile data is disabled.
As you can see on the screenshot, everything is disabled, but there is no "x".

![screenshot_20160924-142059](https://cloud.githubusercontent.com/assets/13015934/18808437/05328746-8263-11e6-9e24-2c58bb6fbe94.png)
[xposed_error_20160924_142411.txt](https://github.com/wasdennnoch/AndroidN-ify/files/491102/xposed_error_20160924_142411.txt)

**Comment by wasdennnoch** [comment]
I'll just post the link to your SystemUI here: https://github.com/wasdennnoch/AndroidN-ify/files/496560/SystemUI.zip

**Comment by wasdennnoch** [comment]
#1084
