### ISSUE TITLE
App-specific "hide sensitive notifications content"

### ISSUE THREAD

**Issue by tushar260** [wasdennnoch/AndroidN-ify#963]

**Comment by tushar260** [comment]
*protected lockscreen (be it pin or pattern or password..) 😅

**Comment by tushar260** [comment]
I just want to display my text messages and mails on lockscreen and hide contents of WhatsApp.

I'm pretty sure many us would've wished this was present 🤤

**Comment by tushar260** [comment]
I wish you understood that right.
I just wanted to explain that once again 😅
The thing is google just allow to select 'hide sensitive notifications' and doesn't allow to mark which apps are sensitive. I want to make only WhatsApp as sensitive and want all other notifications to be displayed with contents on lockscreen and only WA to show 'contents hidden'.

Just a check list for everyone's convenience to customise this and use this feature to the fullest.

**Comment by tushar260** [comment]
Thanks btw for considering it ;)

**Comment by paphonbth** [comment]
Implemented with 8715cca.

**Comment by tushar260** [comment]
Where to check? I'm on v685, couldn't find that option listed anywhere 🙄

**Comment by tushar260** [comment]
Hello? 🙄🤓

**Comment by paphonbth** [comment]
Long click a notification and you'll see a new button.

**Comment by tushar260** [comment]
One is mute and the other is app specific notification controls button. What's new?

**Comment by paphonbth** [comment]
Did you enable experimental features and are you on MM?

**Comment by tushar260** [comment]
I was searching for the experimental features toggle only. But couldn't find that. 😅

And yes I'm on mm (cm13).

**Comment by paphonbth** [comment]
It should work on CM13. At least on my phone. Please make sure that you have it enabled in experimental features. (It defaults to disabled)

**Comment by tushar260** [comment]
But where is it bro? How to enable experimental features? 😅

**Comment by wasdennnoch** [comment]
Tap the N icon.

**Comment by tushar260** [comment]
Not working 😅
I've posted a screenshot for your reference.

**Comment by wasdennnoch** [comment]
There's no screenshot :P
Tap the N icon in the apps about screen 8 times. A toast should appear saying that you have experimental features enabled. Then reboot.

**Comment by tushar260** [comment]
I posted it as a new issue. Done with that thing button now toggles are not visible when swiping down notifications on lockscreen.
