### ISSUE TITLE
SystemUI doesn't start on the new builds >672

### ISSUE THREAD

**Issue by DavidMKD** [wasdennnoch/AndroidN-ify#964]
Seems like it's only problem on Xperia LP firmwares:

[logcat.txt](https://github.com/wasdennnoch/AndroidN-ify/files/491223/logcat.txt)

**Comment by sargijeh** [comment]
@davidmkd same here :) what phone do you got? :)

**Comment by wasdennnoch** [comment]
Fixed with 4395335184467bf11d8c438fa8ad6da957d86857.
