### ISSUE TITLE
n drawer no availabel and settings dashboad also not in

### ISSUE THREAD

**Issue by dimuthu3** [wasdennnoch/AndroidN-ify#965]
I am uaing beanstalk  6.0.1 for my i9300 and using latest #681 build.already i have enabel experimental features by tapping n logo on n-ify app and rebooted twice.still not settings drawer and no settings dashboad if this is a bug pls help to fix 
Here is log https://drive.google.com/file/d/0B6NzzhtK6j4QNV9WbFY5QVAtams/view?usp=drivesdk

**Comment by hrithikb** [comment]
Same problem here!

**Comment by dimuthu3** [comment]
Update to #683 but still no settings  drawer  or dashboard.ita worked befor with experimental  build #168 can you pls help

**Comment by paphonbth** [comment]
![](http://i.imgur.com/YLM3zdj.png)

**Comment by Silver-Fullbuster** [comment]
I'm having this problem.. updated to the latest builds, turned on experimental features, and then rebooted twice..


http://pastebin.com/PFaaagrb

**Comment by dimuthu3** [comment]
Why it say i am using #576.ok i will try again with uninstall module reboot and install latest and reboot and will send log

**Comment by dimuthu3** [comment]
Sorry bad txt files here is correct one and still same https://drive.google.com/file/d/0B6NzzhtK6j4QckhjckVTSHlLeWM/view?usp=drivesdk

**Comment by dimuthu3** [comment]
hi dev this is not bug i think i have set my selinux permission to permissive now and app drawer and dashboard working.coooool.can i close this issue

**Comment by paphonbth** [comment]
Maybe the settings app can't read prefs?

**Comment by dimuthu3** [comment]
Ya it can be.you can close this

**Comment by Silver-Fullbuster** [comment]
I haven't tried shifting my selinux to permissive.. let me try that

**Comment by Silver-Fullbuster** [comment]
Didn't get fixed. Don't close this issue because I still have it.

**Comment by wasdennnoch** [comment]
The general problem with the settings settings (yep) is here: #987
To keep it clean I'll close this one.
