### ISSUE TITLE
SystemUI FC on boot

### ISSUE THREAD

**Issue by KaMyKaSii** [wasdennnoch/AndroidN-ify#967]
[logcatonbootsystemuifc.txt](https://github.com/wasdennnoch/AndroidN-ify/files/491275/logcatonbootsystemuifc.txt)
Logcat:
https://drive.google.com/file/d/0B1uvONk-jlRicmlMS2NoX05TNlU/view?usp=drivesdk

Android 6.0 Mediatek

**Comment by paphonbth** [comment]
Caused by MinMinGuard.
http://i.imgur.com/6CTaqsp.png

**Comment by Cris--** [comment]
Also SystemUI fc since #680-684 or so. #674 works perfectly on Resurrection Remix 5.7.4_r66.
No time for log, sry!

**Comment by wasdennnoch** [comment]
I need your deodexed SystemUI for this one if possible, it's a different issue than the others.

**Comment by Cris--** [comment]
Ok, working now without SystemUI fc. #695-696 on RR 5.7.4_r66.
Next time i open an own issue thread!

**Comment by KaMyKaSii** [comment]
This means that my rom is odexed, right? I'm looking for a tutorial to deodex
![screenshot_20160929-070338](https://cloud.githubusercontent.com/assets/17092335/18949778/28e94edc-8613-11e6-91b0-f2a14d1e1adb.png)

**Comment by wasdennnoch** [comment]
Yep, it's odexed (thus the odex file).

**Comment by wasdennnoch** [comment]
Please install this version and post your Xposed log: http://www.mediafire.com/file/nzb2u1q1huqzupt/Android_N-ify_debug_log_setMobileDataIndicators.apk

**Comment by wasdennnoch** [comment]
No response
