### ISSUE TITLE
Settings app crash 

### ISSUE THREAD

**Issue by Freewander10** [wasdennnoch/AndroidN-ify#968]
When trying to enter certain sub menus in settings, the app crashes. For example:
Settings>privacy>privacy guard>crash.
I'm using Exodus 5.1. 
Logs:
https://docs.google.com/uc?id=0B5_P4hsjIFYmNTZacEtlNmxISUE&export=download

**Comment by Maik268** [comment]
Same problem here on Android 6.0.1 - HTC 10

[xposed_error_20160924_223646.txt](https://github.com/wasdennnoch/AndroidN-ify/files/491324/xposed_error_20160924_223646.txt)

**Comment by wasdennnoch** [comment]
@Maik268 there are many errors in your log, HTC seems to have changed many things.
@Freewander10 I guess the crash still occurs?

```
09-24 14:26:31.090 15121 15121 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setLayoutParams(android.view.ViewGroup$LayoutParams)' on a null object reference
09-24 14:26:31.090 15121 15121 E AndroidRuntime: 	at com.android.internal.app.ToolbarActionBar.setCustomView(ToolbarActionBar.java)
09-24 14:26:31.090 15121 15121 E AndroidRuntime: 	at com.android.internal.app.ToolbarActionBar.setCustomView(ToolbarActionBar.java)
09-24 14:26:31.090 15121 15121 E AndroidRuntime: 	at com.android.exodussettings.exodus.navbar.NavbarSettingsFragment.onStop(NavbarSettingsFragment.java:195)
09-24 14:26:31.090 15121 15121 E AndroidRuntime: 	at android.app.Fragment.performStop(Fragment.java)
```

**Comment by Maik268** [comment]
@wasdennnoch As always...

**Comment by Freewander10** [comment]
@wasdennoch yes it does.

**Comment by wasdennnoch** [comment]
@Maik268 Probably fixed with the latest build.
@Freewander10 I can't find the source of the Exodus Settings (there is a repo, but there are only 3 classes in there, not the one involved in thus crash), so I have no idea what causes it; you can try to deodex your ExodusSettings if you don't know where I can find the source too.
