### ISSUE TITLE
There is a bug of status bar data connection toggle

### ISSUE THREAD

**Issue by codexss** [wasdennnoch/AndroidN-ify#97]
here is a video to see
https://goo.gl/photos/dbhyHFd5aHZNNb119

**Comment by codexss** [comment]
and if notify is blank
the time is too close to the edge
![screenshot_20160508-103138](https://cloud.githubusercontent.com/assets/5959201/15095703/5adf7d5c-1508-11e6-8141-4686f7020f47.png)

**Comment by codexss** [comment]
My phone is Nexus5 Factory ROM Android 6.0.1 MOB30H

**Comment by wasdennnoch** [comment]
I know, it's the detail view that expands, you can see it when you pull down the panel.

**Comment by haseoxth** [comment]
All fixed in today's build.
