### ISSUE TITLE
In Nougat, date is placed above time in qs. Btw the previous one was better in which both were in the same line separated by dot

### ISSUE THREAD

**Issue by tushar260** [wasdennnoch/AndroidN-ify#974]

**Comment by wasdennnoch** [comment]
It depends on the screen size. If your screen width exceeds a certain size the date will be displayed on the right side, otherwise below.

**Comment by wasdennnoch** [comment]
Also date is not placed above but below.

**Comment by tushar260** [comment]
My phone's screen size is 5.5" 😂😂
Also, it is displayed as it is in landscape too.

Date and time, side-by-side is far better

**Comment by wasdennnoch** [comment]
Blame Google :P

**Comment by tushar260** [comment]
You can correct this bro if you want, and this is would be better than google's implementation :D

**Comment by tushar260** [comment]
*and think it would be better

**Comment by tushar260** [comment]
It has happened in the last update only. Before that, the date came alongside time.

**Comment by paphonbth** [comment]
Real screen size doesn't matter. Just pixel amount and density is used.

**Comment by tushar260** [comment]
But it worked perfectly until I updated it yesterday😞

**Comment by paphonbth** [comment]
It's a feature. Not a bug.
