### ISSUE TITLE
Problem with the date

### ISSUE THREAD

**Issue by Simi3000** [wasdennnoch/AndroidN-ify#977]
Date is not showed properly.

**Comment by Simi3000** [comment]
https://mega.nz/#!ilxUGKLL

**Comment by Simi3000** [comment]
https://mega.nz/#!u8RFwAob

**Comment by Simi3000** [comment]
#865 on Moto G 1st Gen with cm13

**Comment by paphonbth** [comment]
Not a bug. Please see 78ab22c.

**Comment by Simi3000** [comment]
But I didn't have it until I update to the 684 version, and I think 4" is not a small screen

**Comment by Simi3000** [comment]
But, what can I do?

**Comment by wasdennnoch** [comment]
If you really want that other date format buy a bigger phone.

**Comment by Simi3000** [comment]
:/
