### ISSUE TITLE
Graphical issue (white lines)

### ISSUE THREAD

**Issue by NeFeroN** [wasdennnoch/AndroidN-ify#978]
Hi , I have problems with white lines between notifications and when I'm deleting any notification , background is white to.
![screenshot_20160926-073231](https://cloud.githubusercontent.com/assets/19422440/18822836/9ca859ac-83bc-11e6-9951-7a920024f021.png)

I made screenshot , so u can see what I'm saying about.

**Comment by paphonbth** [comment]
It's a feature, not a bug. Also there's an option to disable this.
