### ISSUE TITLE
[BUG] incorrect position of statusbar header

### ISSUE THREAD

**Issue by vlw** [wasdennnoch/AndroidN-ify#98]
When no notifications, statusbar header is higher than necessary
![screenshot_20160508-083823](https://cloud.githubusercontent.com/assets/6003820/15096302/36f7c1ae-14fb-11e6-8d18-0c4ba6b8806b.png)
![screenshot_20160508-083829](https://cloud.githubusercontent.com/assets/6003820/15096307/3fea892c-14fb-11e6-94ec-32c8f8c1d178.png)

**Comment by vlw** [comment]
CyanogenMod 13 (6.0.1)

**Comment by vlw** [comment]
Latest build from sources

**Comment by vlw** [comment]
And no icons on closed header :(

**Comment by vlw** [comment]
[xposed_error_20160508_090652.txt](https://github.com/wasdennnoch/AndroidN-ify/files/253775/xposed_error_20160508_090652.txt)

**Comment by LKc1949** [comment]
![screenshot_20160508-144906](https://cloud.githubusercontent.com/assets/17155723/15096478/1c59e85e-14bf-11e6-8216-4770aedcf2aa.png)
Same here with Resurrection Remix MM

**Comment by vemacs** [comment]
Same with stock MM:

![](http://i.imgur.com/mTS5kzL.png)

**Comment by paphonbth** [comment]
Please try [this build](https://ci.paphonb.xyz/job/AndroidN-ify_Experimental/32/).

**Comment by vemacs** [comment]
Looks like that fixed it, thanks. It would be great if you could look into the "No notifications" font size and margins as well.

**Comment by LKc1949** [comment]
Seems it has been fixed, thks dev.
![screenshot_20160509-122945](https://cloud.githubusercontent.com/assets/17155723/15103773/0738cc86-1575-11e6-8a43-7196fbf1aaf5.png)

**Comment by wasdennnoch** [comment]
Fixed with b2b93ea03bf213cbe4400a024632016268c144a3
