### ISSUE TITLE
System UI doesn't shows up even with Permissive mode

### ISSUE THREAD

**Issue by sargijeh** [wasdennnoch/AndroidN-ify#980]
Xperia LP build 686

**Comment by wasdennnoch** [comment]
Log at least. Open a new one if it isn't fixed with the latest build.

**Comment by sargijeh** [comment]
Why did you close this issue?
You told on xda there is no need for logs,
I really appreciate your efforts, but that's not fare to close this @wasdennnoch

**Comment by wasdennnoch** [comment]
Sorry, but I can't keep track of every username and who has which issue. Please link to which issue you are referring. Also please test the latest build as I fixed a bunch of crashes.
