### ISSUE TITLE
Systemui has stopped

### ISSUE THREAD

**Issue by c4lb0r0** [wasdennnoch/AndroidN-ify#981]
Hello sir, I've installed the latest preview build and after i reboot i am encountering a "systemui has stopped" i can't give a log because i am stack at that thing. I am using resurrection remix 5.7.3, hope you can help me. thanks in advance

**Comment by c4lb0r0** [comment]
This build is working but if i use a latest preview build #686 I've encounter a "systemui has stopped"

**Comment by wasdennnoch** [comment]
1. without a log I can't do anything and 2. this already got reported multiple times.
