### ISSUE TITLE
CM13 Redmi Note 4G

### ISSUE THREAD

**Issue by tushar260** [wasdennnoch/AndroidN-ify#983]
![screenshot_20160927-103236](https://cloud.githubusercontent.com/assets/21682756/18860789/d186ea4e-849d-11e6-9c24-fd0a35c77a34.png)

**Comment by tushar260** [comment]
Using system default theme, works fine after restarting system ui.

I'm using N-theme by pashapuma but when I switched to systen theme, I got this :p

**Comment by paphonbth** [comment]
Switching themes will cause this bug. Please restart SystemUI
