### ISSUE TITLE
This ripple on the top right collapses the notification panel. No use.

### ISSUE THREAD

**Issue by tushar260** [wasdennnoch/AndroidN-ify#985]
![screenshot_20160927-143944](https://cloud.githubusercontent.com/assets/21682756/18867063/5443a946-84c0-11e6-808e-b7481722e00d.png)

**Comment by wasdennnoch** [comment]
Do you have the header weather enabled in the CM settings? Because of the position it's the only thing I can imagine there.

**Comment by tushar260** [comment]
Oh ya! But it is not displayed after installing many many apps. None of the apps show up in the weather section in settings.

**Comment by wasdennnoch** [comment]
(I guess) All commertial apps don't implement the necessary APIs to provide the weather info to CM. But CM already has one built in (cLock). You should be able to hide the weather by searching for "weather" in the settings, it should be titled something like "Show weather" in the notification header section (I don't know how the settings are stuctured on CM).
