### ISSUE TITLE
Settings have no access to SharedPrefs / default values get used

### ISSUE THREAD

**Issue by wasdennnoch** [wasdennnoch/AndroidN-ify#987]
And thus disabling / enabling features doesn't work.

**Comment by Silver-Fullbuster** [comment]
The issue is still present in the latest build.. It's enabled in N-ify Settings (Experimental > Settings Drawer) and I've rebooted after updating the module, but there is no change..

**Comment by wasdennnoch** [comment]
I know, I closed it because there's already another nicer issue for that ;)

**Comment by Silver-Fullbuster** [comment]
Oh, didn't notice. ;P
