### ISSUE TITLE
Update on Build 688 # still Sys ui crashes on lollipop xperia 

### ISSUE THREAD

**Issue by pwrusr** [wasdennnoch/AndroidN-ify#988]
Frm 675.. Sys ui crashes and logs submitted by someusers using xperia issue #964  Those issues haven't been closed too.. Pls fix this issue @wasdennnoch and devs. thanks for ur efforts (:

**Comment by hakan5816** [comment]
6.0.1 xperia problem persists. UI stopped when switching to fullscreen
