### ISSUE TITLE
Absent toggles.

### ISSUE THREAD

**Issue by tushar260** [wasdennnoch/AndroidN-ify#989]
![screenshot_20160928-004414](https://cloud.githubusercontent.com/assets/21682756/18888152/c49c0536-8514-11e6-88ec-e3ad6f4fde4e.png)

**Comment by nicolo01** [comment]
Happens to me too.
When you are in lock screen and expand a notification

**Comment by ch3mn3y** [comment]
Turn on Fancy QS transition. hey will show.

**Comment by wasdennnoch** [comment]
If it still happens Xposed log.

**Comment by ch3mn3y** [comment]
Doesn't happen anymore on newest 721 and 725 builds.
