### ISSUE TITLE
WiFi quick tile isn't working on expanded QS and edit tile doesn't save the config and battery icon isn't shown

### ISSUE THREAD

**Issue by DavidMKD** [wasdennnoch/AndroidN-ify#990]
It doesn't turn off Wi Fi but it turns it on. 

image: http://imgur.com/Hbz47iq

Logcat: https://drive.google.com/open?id=0BxOx6OK5fXEncWhDbW1OYVh2ZEE

Xposed Log: https://drive.google.com/open?id=0BxOx6OK5fXEnc3EycTE4aUVGOVE

**Comment by licaon-kter** [comment]
Seeing at least the "WiFi quick tile isn't working on expanded QS" part on Xperia 5.1.1 build 732

**Comment by licaon-kter** [comment]
Looks fixed in build 738. Thanks

**Comment by wasdennnoch** [comment]
@DavidMKD Fixed?

**Comment by DavidMKD** [comment]
@wasdennnoch Sorry was busy these days and I've just checked mail. Yeah, i've installed the latest build and it's fixed.
