### ISSUE TITLE
latest build, the settings changed to a weird one :|

### ISSUE THREAD

**Issue by sargijeh** [wasdennnoch/AndroidN-ify#991]
and also there is a red bar above which is my theme's accent color, but it shouldn't been there!
[xposed_error_20160927_224627.log.txt](https://github.com/wasdennnoch/AndroidN-ify/files/496499/xposed_error_20160927_224627.log.txt)

![screenshot_2016-09-27-22-56-21](https://cloud.githubusercontent.com/assets/22320438/18888914/439eb058-8507-11e6-915f-0cb623b91c29.png)

**Comment by JaredTheWolf** [comment]
I'm not getting that. Try disabling the module and seeing if it persists maybe?

**Comment by niaboc79** [comment]
I have the same issue on my Xperia Z2
