### ISSUE TITLE
QS panel swiping bug

### ISSUE THREAD

**Issue by Uszkix** [wasdennnoch/AndroidN-ify#998]
I have bad bug when i swipe back qs panel. It happen when i tap and swipe on qs panel, when i tap and swipe out of this is correct. Text below icons "jump". Here is video of this bug and my logs..
https://drive.google.com/folderview?...EVPa0ljOXhqMm8

**Comment by erorcun** [comment]
Video is unreachable atm, but I want to explain this to the dev.
This is my post from XDA but I don't know has he seen it:

If I push up panel from space in landscape, instantly qs shrink animation starts. But if I do it from notifications, it thinks there is a portion needs to be scrolled first and shrink animation starts after that, but animation doesn't calculate the scrolled height so all the qs icons' y position jumps to unscrolled state and shrink animation starts from there.

I'm using CM 13 - 1920x1080 400 dpi.

**Comment by wasdennnoch** [comment]
#995
