### ISSUE TITLE
System ui crash on data toggle

### ISSUE THREAD

**Issue by Freewander10** [wasdennnoch/AndroidN-ify#999]
https://docs.google.com/uc?id=0B5_P4hsjIFYmTGRJbTN6eGZMZFk&export=download

**Comment by Freewander10** [comment]
The system ui crashes continuously whenever I toggle data. The link to the logcat is above.

**Comment by wasdennnoch** [comment]
Does it still crash with the latest build? If so, which ROM and Android version are you on?

**Comment by Freewander10** [comment]
No. It no longer crashes. Thanks.
